<style type="text/css">

	#history {
		border: 1px solid #666666;
        width: 100%;
        padding: 5px 15px 0 15px;
	}

	#history tbody tr td {
		font-family: "lucida grande", verdana, sans-serif;
		font-size: 8pt;
		padding: 3px 8px;
        text-align: center;
	}

    #history tbody tr th {
		font-family: "lucida grande", verdana, sans-serif;
		font-size: 8pt;
		padding: 3px 8px;
        background-color: #3d80df;
        color: #fff;
        text-align: center;
	}

	#history tbody tr.selected td {
		background-color: #3d80df;
		color: #ffffff;
		font-weight: bold;
		border-left: 1px solid #346DBE;
		border-bottom: 1px solid #7DAAEA;
	}
</style>
        
<table id="history">
<tr>
    <th>No.</th>
    <th>Trano</th>
    <th>Project</th>
    <th>PO No.</th>
    <th>Submit Date</th>
    <th>Approval Date</th>
    <th>Next Person</th>
    <th>Status</th>
    <th>Comment</th>
</tr>
<?php
        $i = $this->current;
        foreach ($this->result as $key => $val)
        {
            if ($i % 2 == 0)
                $style = "background-color:#eee;";
            else
                $style = "background-color:#fff;";
?>
<tr style="<?=$style?>">
    <td><?=$i?></td>
    <td><a href="#" onclick="showHistoryDocs('<?=$val['item_id']?>');"><?=$val['item_id']?><a/></td>
    <td><?=$val['prj_kode']?></td>
    <td><?=$val['po_no']?></td>
    <td><?=$val['date_submit']?></td>
    <td><?=$val['date']?></td>
    <td><?=$val['next_person']?></td>
    <td><?=$val['msg']?></td>
    <td><?=$val['comment']?></td>
</tr>
    <?php $i++;} ?>
<?php

        
?>
</table>
<div id="paging-teks"><?=$this->current?> of <?=$this->totalResult?> Result</div>
<div id="paging2">
	<ul>
		<?php if ($this->currentPage > 1) {?>
		<li><a href="#" onclick="gotoPage(1);">First</a></li>
		<li><a href="#" onclick="gotoPage(<?=($this->currentPage-1)?>);">&lt; Previous</a></li>
		<?php }
			  if ($this->currentPage > 2)
			  {
			  	for($i=$this->currentPage-2;$i<=($this->currentPage-1);$i++)
			  	{
		?>
		<li><a href="#" onclick="gotoPage(<?=$i?>);"><?=$i?></a></li>
		<?php
			  	}
			  }
			  elseif ($this->currentPage > 1)
			  {
		?>
		<li><a href="#" onclick="gotoPage(1);">1</a></li>
		<?php
			  }
		?>
		<li><a href="#" class="current"><?=$this->currentPage?></a></li>
		<?php
			  if ($this->totalPage >= ($this->currentPage + 2 ))
			  {
			  	for($i=$this->currentPage+1;$i<=($this->currentPage+2);$i++)
			  	{
		?>
				<li><a href="#" onclick="gotoPage(<?=$i?>);"><?=$i?></a></li>
		<?php
			  	}
			  }
			  elseif ($this->totalPage >= ($this->currentPage + 1 ))
			  {
		?>
				<li><a href="#" onclick="gotoPage(<?=$this->totalPage?>);"><?=$this->totalPage?></a></li>
		<?php
			  }
			  if ($this->currentPage < $this->totalPage)
			  {
		?>
		<li><a href="#" onclick="gotoPage(<?=($this->currentPage+1)?>);">Next &gt;</a></li>
		<li><a href="#" onclick="gotoPage(<?=$this->totalPage?>);">Last</a></li>
		<?php
			  }
		?>
	</ul>
</div>
<script type="text/javascript">
function showHistoryDocs(trano)
{

    myPanel = Ext.getCmp('result-panel');
    myPanel.body.load({
        url: '/default/home/showcheckdocument',
        scripts : true,
        params: {trano: trano}
    });
}


function showHistoryDocsGeneric(trano)
{

    myPanel = Ext.getCmp('result-panel');
    myPanel.body.load({
        url: '/default/home/show-check-document-generic',
        scripts : true,
        params: {trano: trano}
    });
}

function gotoPage(pageNum)
{
	var limit = <?=$this->limit?>;
	var currentPage = <?=$this->currentPage?>;

    var orders = Ext.getCmp('order_by');
    if (orders != undefined)
        var order = orders.getValue(); 
	var currents = 1 + ((pageNum - 1) * limit);

    var params = <?=$this->encoded_params?>;

    params.currentPage =  pageNum;
    params.current = currents;
    params.encoded_params = '<?=$this->encoded_params?>';

	 myPanel = Ext.getCmp('result-panel');
	    myPanel.body.load({
		        url: '/default/report/show-my-approved-document',
	                scripts: true,
	                params: params

		});
}

function printdoc (trano)
{
    type = 'pdf';
    urlLoad =  '/jasper/podetail/trano/' + trano + '/type/' + type;
    params = {trano:trano};
    Ext.Ajax.request({
        url: '/default/home/cekprint',
        method:'POST',
        success: function(resp){
            var returnData = Ext.util.JSON.decode(resp.responseText);
            if (returnData.success)
            {
                window.open(urlLoad,'mywin',
                'left=20, top=20, width=100, height=20, toolbar=0, resizable=0');
            }
            else
            {
                Ext.Msg.alert('Error', returnData.msg);
            }
        },
        failure:function( action){
        if(action.failureType == 'server'){
          obj = Ext.util.JSON.decode(action.responseText);
          Ext.Msg.alert('Error!', obj.errors.reason);
        }else{
          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
        }
        },
        params: params
    });
}
</script>