<style type="text/css">
        .tooltip {
            border-bottom: 1px dotted #000000; color: #000000; outline: none;
            cursor: help; text-decoration: none;
            position: relative;
        }
        .tooltip span {
            margin-left: -999em;
            position: absolute;
        }
        .tooltip:hover span {
            border-radius: 5px 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px;
            box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1); -webkit-box-shadow: 5px 5px rgba(0, 0, 0, 0.1); -moz-box-shadow: 5px 5px rgba(0, 0, 0, 0.1);
            font-family: Calibri, Tahoma, Geneva, sans-serif;
            position: absolute; left: 1em; top: 2em; z-index: 99;
            margin-left: 0;
        }
        .tooltip:hover img {
            border: 0; margin: -10px 0 0 -55px;
            float: left; position: absolute;
        }
        .tooltip:hover em {
            font-family: Candara, Tahoma, Geneva, sans-serif; font-size: 1.2em; font-weight: bold;
            display: block; padding: 0.2em 0 0.6em 0;
        }
        .info { padding: 0.8em 1em;background: #FFFFAA; border: 1px solid #FFAD33;width:370px; }
        .custom { padding: 0.5em 0.8em 0.8em 2em; }
        * html a:hover { background: transparent;}

</style> 

<style>

.files{
    margin-top: 30px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#E0ECEE;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}


.last-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.all-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#F6CBCA;
    color:#222222;
    padding:4px;
    text-align:left;
}
.all-approve{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    /*background:#CEE6C3;*/
    color:#222222;
    padding:4px;
    text-align:left;
    height: 200px;
    overflow: auto;
}    
.body {
	/*width: 720px;*/
    /*overflow: auto;*/
}
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
    margin-bottom: 10px;
}
.title2 {
	width: 100%;
    float: left;
	text-align: center;
	font-size: 14px;
	font-weight: bold;
    margin-top: 10px;
	margin-bottom: 10px;
}
.etc {
	width: 100%;
	height: 50px;
}
.kanan-etc {
	float: right;
	width: 48%;
}
.kiri-etc {
	float: left;
	width: 48%;
}
.blok {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
}
.blokoverhead {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
    color: #ff0000;
}
.budgetTable {
	width: 100%;
	font-size: 12px;
	font-weight: normal;
}

/*css for afe &boq3 table*/
table.afe
{ width: 700px;
background-color: #fafafa;
border: 1px #000000 solid;
border-collapse: collapse;
border-spacing: 0px; }


td.afeheader
{ background-color: #99CCCC;
border: 1px #000000 solid;
font-weight: bold;
font-size: 14px;
text-align: center;
color: #404040; }


td.afeisi
{ border-bottom: 1px #6699CC dotted;
font-weight: normal;
font-size: .7em;
color: #404040;
background-color: #fafafa;
padding-top: 4px;
padding-bottom: 4px;
padding-left: 8px;
padding-right: 8px; }

#afe_info {
    margin-bottom: 30px;
}

td.total
{
    font-weight: bold;
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    border-bottom: 1px #000000 solid;
    border-top: 1px #000000 solid;
}

td.margin
{
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    font-weight: bold;
    color: red;
}

td.movement
{
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    font-weight: bold;
    color: red;
    background-color: #ffff00;
}

/*end here*/
    
</style>

<style type="text/css">
    .x-grid3-td-name b {
            font-family:tahoma, verdana;
            display:block;
            color:#333;
    }
    .x-grid3-td-name b i {
        font-weight:normal;
        font-style: normal;
        color:#000;
    }
    .x-grid3-td-name .personicon {
        padding-left:20px;
        background:transparent url(/images/engineer-icon.png) no-repeat 0 2px;
    }
    .x-grid3-td-name .x-grid3-cell-inner {
        white-space:normal;
    }

    .x-grid3-row-body p {
        margin:5px 20px 10px 25px !important;
        color:#555;
    }

    .rolename {
        color:#333;
    }

</style>



<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">

<div class="title">APPROVAL FOR EXPENDITURE</div>

<?php if ($this->reject) { ?>
<div class="last-reject">
        This Document was Rejected by <?php echo $this->lastReject[0]['name']; ?> at <?php echo date('d-m-Y H:i:s',strtotime($this->lastReject[0]['date'])); ?>
        <br />
        Comment : <?php echo $this->lastReject[0]['comment']; ?>
</div>
<?php } ?>

<div class="etc">
	<div class="kiri-etc">
        <div class="blok">Submitted Date : <?=date("d M Y",strtotime($this->tglAfe));?></div>
        <div class="blok">Final Approved Date : <?=date("d M Y",strtotime($this->finalDate));?></div>
		<?php if ($this->edit || $this->approve) {?><div class="blok">AFE Number : <?=$this->etc[0]['trano']?></div><?php } ?>
        <?php if ($this->edit || $this->approve) {?><div class="blok">PIC : <?=$this->etc[0]['user']?></div><?php } ?>
        <div class="blok">Project : <?=$this->etc[0]['prj_kode']?> - <?=$this->etc[0]['prj_nama']?></div>
	</div>

    <div class="kanan-etc">

         <div class="blok">Currency : <?=$this->etc[0]['val_kode']?></div>
         <div class="blok">Exchange Rate : <?=number_format($this->etc[0]['rateidr'],2)?></div>
	    <div class="blok">Site : <?=$this->etc[0]['sit_kode']?> - <?=$this->etc[0]['sit_nama']?></div>
             <div class="blok">Reason  : <?=$this->etc[0]['ket']?></div>
    </div>

   
</div>

<?php if ($this->file != '') { ?>
    <br>
<div class="files">
    <div class="blok">Attachment Files For Additional Revenue :</div>
    <ul>
    <?php foreach ($this->file as $key => $val) { ?>
    <li>- <a href="#" onclick="window.open('/default/file/download/path/files/filename/<?php echo $val['savename']; ?>','mywin','left=20,top=20,width=100,height=20,toolbar=0,resizable=0');"><?php echo $val['filename']; ?></a></li>
    <?php } ?>
    </ul>
</div><br />
<?php } ?>

<?php
    $boq2_oriTotal = $this->etc[0]['boq2_oriIDR'] + ($this->etc[0]['boq2_oriUSDinIDR']);
    $boq2_currentTotal = $this->etc[0]['boq2_currentIDR']+($this->etc[0]['boq2_currentUSD']*$this->etc[0]['rateidr']);

?>

<div id = 'afe_info'>

    <center>

        <?php
            $afeValIDR = floatval($this->etc[0]['afeValIDR']);
            $afeValUSD = floatval($this->etc[0]['afeValUSD']);
            
            $val = $this->etc[0]['val_kode'];
            if ($val == 'IDR')
            {
                $add_rev_idr = $this->etc[0]['add_rev'];
                $add_rev_usd = 0;
                $total_rev = $add_rev_idr+($add_rev_usd*$this->etc[0]['rateidr']);
                $afeValTotal = $afeValIDR+($afeValUSD*$this->etc[0]['rateidr']);

                $addRevIDR = floatval($this->etc[0]['add_rev']);
                $addRevUSD = 0;
                $addRevTotal = $addRevIDR;

            }else
            {
                $add_rev_idr = 0;
                $add_rev_usd = $this->etc[0]['add_rev'];
                $total_rev = $add_rev_idr+($add_rev_usd*$this->etc[0]['rateidr']);
                $afeValTotal = $afeValIDR+($afeValUSD*$this->etc[0]['rateidr']);
               
                $addRevUSD = floatval($this->etc[0]['add_rev']);
                $addRevIDR = 0;
                $addRevTotal = $addRevUSD*$this->etc[0]['rateidr'];
            }
            
            $mip = $this->etc[0]['mip'];
            $mipIDR = $mip['mip_currentIDR'];
            $mipUSD = $mip['mip_currentHargaUSD'];
            $mipUSDRate = $mip['mip_currentHargaUSDRate'];
            $mip_total_IDR = $mip['mip_currentIDR'] + $mip['mip_currentHargaUSDRate'];
            
//            $salary_IDR = $mip['salary_IDR'];
//            $salary_USD = $mip['salary_USD'];
//            $rpi_approved_IDR = $mip['rpi_approved_IDR'];
//            $rpi_approved_USD = $mip['rpi_approved_USD'];
//            $asf_IDR = $mip['asf_IDR'];
//            $asf_USD = $mip['asf_USD'];
//            $pmeal_IDR = $mip['pmeal_IDR'];
//            $pmeal_USD = $mip['pmeal_USD'];
//            $fdopoIDR = $mip['fdopoIDR'];
//            $fdopoUSD = $mip['fdopoUSD'];
//            $material_return_IDR = $mip['material_return_IDR'];
//            $material_return_USD = $mip['material_return_USD'];

            //Balance Budget dalam IDR
            $balance_budget = floatval((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD))*$this->etc[0]['rateidr']);

            //Balance Budget dalam USD
            $balance_budget_in_USD = (floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD));
           

            $boq3_oriInIDR = floatval($this->etc[0]['boq3_oriUSD'])*$this->etc[0]['rateidr'];
//            $boq3_currentInIDR = floatval($this->etc[0]['boq3_currentUSD'])*$this->etc[0]['rateidr'];
            $boq3_currentInIDR = floatval($mip['mip_currentUSD'])+ $balance_budget;

            $boq3_oriTotal = $this->etc[0]['boq3_oriIDR']+$this->etc[0]['boq3_oriUSDRate'];//($this->etc[0]['boq3_oriUSD']*$this->etc[0]['rateidr']);
            $boq3_currentTotal = $this->etc[0]['current_budget'];//$this->etc[0]['boq3_currentIDR']+$mipUSDRate+($this->etc[0]['boq3_currentUSD']-$mipUSD)*$this->etc[0]['rateidr'];

            $totalCurrentBoq3 = $afeValTotal + $boq3_currentTotal;

            $percentage = $totalCurrentBoq3==0 ? 0 : ($afeValTotal/$totalCurrentBoq3)*100;
            

            $total_co_idr = (floatval($this->etc[0]['boq2_currentIDR']) + floatval($add_rev_idr));
            $total_co_usd = (floatval($this->etc[0]['boq2_currentUSD']) + floatval($add_rev_usd));
            $total_current_co = $total_co_idr+($total_co_usd*$this->etc[0]['rateidr']);

            $total_add_cost_idr = (floatval($this->etc[0]['boq3_currentIDR']) + floatval($afeValIDR));
            $total_add_cost_usd = (floatval($this->etc[0]['boq3_currentUSD']) + floatval($afeValUSD));
//            $total_current_add_cost = $total_add_cost_idr + ($total_add_cost_usd * $this->etc[0]['rateidr']);
            $total_current_add_cost = $boq3_currentTotal+floatval($afeValIDR)+floatval($afeValUSD*$this->etc[0]['rateidr']);
                                      

            $val_grossmargin_origin_idr = $this->etc[0]['boq2_oriIDR']-$this->etc[0]['boq3_oriIDR'];
            $val_grossmargin_origin_usd = $this->etc[0]['boq2_oriUSD']-$this->etc[0]['boq3_oriUSD'];

            $val_grossmargin_prev_idr = $this->etc[0]['boq2_currentIDR']-$this->etc[0]['boq3_currentIDR'];
            $val_grossmargin_prev_usd = $this->etc[0]['boq2_currentUSD']-$this->etc[0]['boq3_currentUSD'];

            $val_grossmargin_addcost_idr = $add_rev_idr-$afeValIDR;
            $val_grossmargin_addcost_usd = $add_rev_usd-$afeValUSD;

            $val_grossmargin_totalcurr_idr = $total_co_idr-$total_add_cost_idr;
            $val_grossmargin_totalcurr_usd = $total_co_usd-$total_add_cost_usd;

            //$total_grossmargin_origin = $val_grossmargin_origin_idr+($val_grossmargin_origin_usd*$this->etc[0]['rateidr']);
            $total_grossmargin_origin = floatval($val_grossmargin_origin_idr) + floatval($val_grossmargin_origin_usd)*floatval($this->etc[0]['boq3_rateidr']);
//            $total_grossmargin_prev = floatval($val_grossmargin_prev_idr) + (floatval($val_grossmargin_prev_usd) * $this->etc[0]['rateidr']);
            $total_grossmargin_prev = $boq2_currentTotal-$boq3_currentTotal;
            //$total_grossmargin_add = $val_grossmargin_addcost_idr+($val_grossmargin_addcost_usd*$this->etc[0]['rateidr']);
            $total_grossmargin_add = floatval($total_rev)- floatval($afeValTotal);
//            $total_grossmargin_current = floatval($val_grossmargin_totalcurr_idr) + ($val_grossmargin_totalcurr_usd * $this->etc[0]['rateidr']);
            $total_grossmargin_current = $total_current_co-$total_current_add_cost;//$val_grossmargin_totalcurr_idr+($val_grossmargin_totalcurr_usd*$this->etc[0]['rateidr']);

            $percen_grossmargin_origin = $boq2_oriTotal==0 ? 0 : ($total_grossmargin_origin/$boq2_oriTotal)*100;
            $percen_grossmargin_prev = $boq2_currentTotal==0 ? 0 : ($total_grossmargin_prev/$boq2_currentTotal)*100;

            $percen_grossmargin_totalcurrent = $total_current_co==0 ? 0 : ($total_grossmargin_current/$total_current_co)*100;
           
            //$percen_grossmargin_actual_current = (1 - (floatval($mip_total_IDR)/floatval($total_current_co))) * 100;
            $percen_grossmargin_actual_current = $this->progress==0 ? 0: floatval((($total_current_co*$this->progress - $mip_total_IDR)/$total_current_co*$this->progress) * 100);
            $percen_grossmargin_add = $total_rev == 0 ? 'N/A' : ($total_grossmargin_add/$total_rev)*100;
           

            $gm_mov_origin = $percen_grossmargin_totalcurrent - $percen_grossmargin_origin;
            $gm_mov_prev = $percen_grossmargin_totalcurrent - $percen_grossmargin_prev;

        ?>

        <table class="afe" cellspacing="0">

            <tr>
                <td class="afeheader">Description</td>
                <td class="afeheader">Valuta</td>
                <td class="afeheader">Origin</td>
                <td class="afeheader">Previous</td>
                <td class="afeheader">Add(subt)</td>
                <td class="afeheader">Total Current</td>
            </tr>

            <tr>
                <td class="afeisi">Customer Order (CO)</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_oriIDR']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_currentIDR']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($add_rev_idr),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_co_idr),4)?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_oriUSD']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_currentUSD']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($add_rev_usd),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_co_usd),4)?></td>
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq2_oriTotal),4)?><span class="info" style="text-align:left">
                 Origin CO IDR + Origin CO USD <br>
                 Origin CO IDR : <?=number_format(floatval($this->etc[0]['boq2_oriIDR']),4);?><br>
                 Origin CO USD : <?=number_format(floatval($this->etc[0]['boq2_oriUSD']),4);?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq2_rateidr']));?>)<br>
                </span></a></td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq2_currentTotal),4)?><span class="info" style="text-align:left">
                 Previous CO IDR + Previous CO USD <br>
                 Previous CO IDR : <?=number_format(floatval($this->etc[0]['boq2_currentIDR']),4);?><br>
                 Previous CO USD : <?=number_format(floatval($this->etc[0]['boq2_currentUSD']),4);?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>         
                </span></a></td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_rev),4)?><span class="info" style="text-align:left">
                  Add(subt) CO IDR + Add(subt) CO USD <br>
                  Add(subt) CO IDR : <?=number_format(floatval($add_rev_idr),4);?><br>
                  Add(subt) CO  USD : <?=number_format(floatval($add_rev_usd),4);?> * <?=number_format(floatval($this->etc[0]['rateidr']),4);?><br>           
                </span></a></td>

                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_current_co),4)?><span class="info" style="text-align:left">
                   Total Current CO IDR + Total Current CO USD <br>
                   Total Current CO IDR : <?=number_format(floatval($total_co_idr),4);?><br>
                   Total Current CO USD : <?=number_format(floatval($total_co_usd),4);?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>         
                </span></a></td> 

            </tr>

            <tr>
                <td class="afeisi">Add(Subt) Cost</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_oriIDR']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_currentIDR']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($afeValIDR),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_add_cost_idr),4)?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_oriUSD']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_currentUSD']),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($afeValUSD),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_add_cost_usd),4)?></td>
            </tr>
            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">&nbsp;</td>
                <td class="afeisi" align="right"><a class="tooltip" href="#" >Recorded Cost<span class="info" style="text-align:left">ASF Claim + BSF Claim + Piecemeal + OCA + RPI(to site) + DO - (Material Return + Material Cancel) - Cancel RPI</span></a></td></td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipUSD),4)?></td>
                    
                <td class="afeisi" align="right">&nbsp;</td>
                <td class="afeisi" align="right">&nbsp;</td>
            </tr>
            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">&nbsp;</td>
                <td class="afeisi" align="right">Balance Budget</td>
                <td class="afeisi" align="right"><?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)),4)?></td>
                 <td class="afeisi" align="right">&nbsp;</td>
                <td class="afeisi" align="right">&nbsp;</td>
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq3_oriTotal),4)?><span class="info" style="text-align:left">
                Origin Add(Subt) Cost IDR + Origin Add(Subt) Cost USD <br>
                Origin Add(Subt) Cost IDR : <?=number_format(floatval($this->etc[0]['boq3_oriIDR']),4)?><br>
                Origin Add(Subt) Cost USD : <?=number_format(floatval($this->etc[0]['boq3_oriUSD']),4)?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq3_rateidr']),2);?>)
                </span></a></td>     
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq3_currentTotal),4)?><span class="info" style="text-align:left">
                Previous Add(Subt) Cost IDR + Recorded Cost USD + Balance Budget USD <br>
                Previous Add(Subt) Cost IDR : <?=number_format(floatval($this->etc[0]['boq3_currentIDR']),4)?><br>
                Recorded Cost USD : <?=number_format(floatval($mipUSDRate),4)?> (<?=number_format(floatval($mipUSD),4)?> * Transaction's exchange rate) <br>
               
                Balance Budget USD : <?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)),4)?> * <?=number_format(floatval($this->etc[0]['rateidr']),4);?><br>
                </span></a></td>     
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format($afeValTotal,4)?><span class="info" style="text-align:left">
                Add(Subt) Cost IDR + Add(Subt) Cost USD <br>
                Add(Subt) Cost IDR : <?=number_format(floatval($afeValIDR),4);?><br>
                Add(Subt) Cost USD : <?=number_format(floatval($afeValUSD),4)?> * <?=number_format(floatval($this->etc[0]['rateidr']),4)?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format($total_current_add_cost,4)?><span class="info" style="text-align:left">
                Total Current Add(Subt) Cost IDR  + Recorded Cost USD + Balance Budget USD + Add(Subt) Cost USD <br>
                Total Current Add(Subt) Cost IDR : <?=number_format(floatval($total_add_cost_idr),4);?><br>
                Recorded Cost USD : <?=number_format(floatval($mipUSDRate),4)?> (<?=number_format(floatval($mipUSD),4)?> * Transaction's exchange rate) <br>
                
                Balance Budget USD : <?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)),4)?> * <?=number_format(floatval($this->etc[0]['rateidr']),4);?><br>
                Add(Subt) Cost USD : <?=number_format(floatval($afeValUSD),4)?> * <?=number_format(floatval($this->etc[0]['rateidr']),4)?>
                </span></a></td> 
           
            </tr>

            <tr>
                <td class="afeisi">Gross Margin</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_origin_idr),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_prev_idr),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_addcost_idr),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_totalcurr_idr),4)?></td>
              
            </tr>

             <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_origin_usd),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_prev_usd),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_addcost_usd),4)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_totalcurr_usd),4)?></td>
          
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_origin),4)?><span class="info" style="text-align:left">
                Origin Gross Margin IDR + Origin Gross Margin USD<br>
                Origin Gross Margin IDR : <?=number_format(floatval($val_grossmargin_origin_idr),4)?> <br>
                Origin Gross Margin USD : <?=number_format(floatval($val_grossmargin_origin_usd),4)?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq3_rateidr']))?>)
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_prev),4)?><span class="info" style="text-align:left">
                Previous CO Total - Previous Add(Subt) Cost Total<br>
                Previous CO Total : <?=number_format(floatval($boq2_currentTotal),4)?><br>
                Previous Add(Subt) Cost Total : <?=number_format(floatval($boq3_currentTotal),4)?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_add),4)?><span class="info" style="text-align:left">
                Add(Subt) CO Total - Add(Subt) Add(Subt) Cost Total <br>
                Add(Subt) CO Total : <?=number_format(floatval($total_rev),4)?><br>
                Add(Subt) Add(Subt) Cost Total : <?=number_format($afeValTotal,4)?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_current),4)?><span class="info" style="text-align:left">
                Total Current CO Total - Total Current Add(Subt) Cost Total <br>
                Total Current CO Total : <?=number_format(floatval($total_current_co),4)?><br> 
                Total Current Add(Subt) Cost Total : <?=number_format($total_current_add_cost,4)?>
                </span></a></td> 
               
            </tr>

            <tr>
                <td class="margin">Gross Margin</td>
                <td class="margin" align="center">%</td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_origin),4)?> % <span class="info" style="text-align:left">
                (Origin Gross Margin Total / Origin CO Total) * 100% <br>
                Origin Gross Margin Total : <?=number_format(floatval($total_grossmargin_origin),4)?><br>
                Origin CO Total : <?=number_format(floatval($boq2_oriTotal),4)?> 
                </span></a></td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_prev),4)?> % <span class="info" style="text-align:left">
                (Previous Gross Margin Total / Previous CO Total) * 100% <br>
                Previous Gross Margin Total : <?=number_format(floatval($total_grossmargin_prev),4)?><br>
                Previous CO Total : <?=number_format(floatval($boq2_currentTotal),4)?>
                </span></a></td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_add),4)?> % <span class="info" style="text-align:left">
                (Add(Subt) Gross Margin Total / Add(Subt) CO Total) * 100% <br>
                Add(Subt) Gross Margin Total : <?=number_format(floatval($total_grossmargin_add),4)?><br>
                Add(Subt) CO Total : <?=number_format(floatval($total_rev),4)?>
                </span></a></td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_totalcurrent),4)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin Total / Total Current CO Total) * 100%<br>
                Total Current Gross Margin Total : <?=number_format(floatval($total_grossmargin_current),4)?><br>
                Total Current CO Total : <?=number_format(floatval($total_current_co),4)?>
                </span></a></td>

            </tr>

            <tr>
                <td class="movement">Gross Margin Movement</td>
                <td class="movement" align="center">%</td> <?php if($gm_mov_origin<0) $red='style="color:red"'; ?>
                <td class="movement" align="right"><a class="tooltip" href="#" <?=$red?> ><?=number_format(floatval($gm_mov_origin),4)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin % - Origin Gross Margin %)<br>
                Total Current Gross Margin % : <?=number_format(floatval($percen_grossmargin_totalcurrent),4)?> %  <br>
                Origin Gross Margin % : <?=number_format(floatval($percen_grossmargin_origin),4)?> % 
                </span></a></td>
                <?php if($gm_mov_prev<0) $red2='style="color:red"'; ?>
                <td class="movement" align="right"><a class="tooltip" href="#" <?=$red2?> ><?=number_format(floatval($gm_mov_prev),4)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin % - Previous Gross Margin %)  <br>
                Total Current Gross Margin % : <?=number_format(floatval($percen_grossmargin_totalcurrent),4)?> %  <br>
                Previous Gross Margin % : <?=number_format(floatval($percen_grossmargin_prev),4)?> % 
                </span></a></td>
                <td class="movement">&nbsp;</td>
                <td class="movement">&nbsp;</td>
            </tr>


            <tr  style="border-top: 1px #000000 solid;">
                <td class="afeisi"><a class="tooltip" href="#" >Recorded Cost<span class="info" style="text-align:left">ASF Claim + BSF Claim + Piecemeal + OCA + RPI(to site) + DO - (Material Return + Material Cancel) - Cancel RPI</span></a></td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipIDR),4)?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipUSD),4)?></td>
            </tr>
            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total">&nbsp;</td>
                <td class="total">&nbsp;</td>
                <td class="total">&nbsp;</td>
                <td class="total" align="right"><a class="tooltip" href="#" align="left" ><?=number_format(floatval($mip_total_IDR),4)?><span class="info" style="text-align:left">
                 Recorded Cost IDR + Recorded Cost USD <br>
                 Recorded Cost IDR : <?=number_format(floatval($mipIDR),4)?><br>   
                 Recorded Cost USD : <?=number_format(floatval($mipUSDRate),4)?> (<?=number_format(floatval($mipUSD),4)?> * Transaction's exchange rate) <br>
                 
                </span></a></td>
            </tr>

            <tr>
                <td class="margin">Actual Gross Margin</td>
                <td class="margin" align="center">%</td>
                <td class="margin" align="right">&nbsp;</td>
                <td class="margin" align="right">&nbsp;</td>
                <td class="margin" align="right">&nbsp;</td><?php if($percen_grossmargin_actual_current<0) $red3='style="color:red"'; ?>
                <td class="margin" align="right"><a class="tooltip" href="#" <?=$red3 ?>><?=number_format(floatval($percen_grossmargin_actual_current),4)?> %<span class="info" style="text-align:left">
                 ([Total Current CO * % Progress - Total Recorded Cost]/Total Current CO * % Progress)*100%   
                 Total Current CO : <?=number_format(floatval($total_current_co),4)?><br>
                 % Progress : <?=number_format(floatval($this->progress*100),4)?> %<br>
                 Total Recorded Cost : <?=number_format(floatval($mip_total_IDR),4)?><br>
                 
                   
                </span></a></td>
            </tr>

        </table>

    </center>

</div>


<?php   $rateidr = $this->etc[0]['rateidr'];
        if ($this->result) { ?>

<div class="title2">AFE Additional Table</div>

<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Name Material</center></th>
             <th scope="col"><center>UoM</center></th>
             <th scope="col"><center>Qty (BOQ3)</center></th>
            <th scope="col"><center>Unit Price (BOQ3)</center></th>
            <th scope="col"><center>Total (BOQ3)</center></th>
            <th scope="col"><center>Qty (Request)</center></th>
            <th scope="col"><center>Unit Price (Request)</center></th>
            <th scope="col"><center>Total (Request)</center></th>
        </tr>
    	<?php

    		$totals = 0;
            $totals2 = 0;
        
       		for ($i=0;$i<(count($this->result));$i++)
    		{
    			$total = floatval($this->result[$i]['qty']) * floatval($this->result[$i]['price']);
                $total2 = floatval($this->result[$i]['qtyori']) * floatval($this->result[$i]['priceori']);


   				foreach ($this->result[$i] as $key => $val)
    			{
    				if ($val === '')
    					$this->result[$i][$key] = "&nbsp;";
    			}
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
            <td ><?=$this->result[$i]['cfs_kode']?></td>
            <td ><?=$this->result[$i]['workid']?></td>
            <td><?=$this->result[$i]['kode_brg']?> - <?=$this->result[$i]['nama_brg']?></td>
    		<td ><?=$this->result[$i]['uom']?></td>
    		<td align="right"><?=number_format(floatval($this->result[$i]['qtyori']),4)?></td>

            <td align="right"><?=number_format(floatval($this->result[$i]['priceori']),4)?></td>

    		<td align="right"><?=number_format($total2,4)?></td>
            <td align="right"><?=number_format(floatval($this->result[$i]['qty']),4)?></td>

             <td align="right"><?=number_format(floatval($this->result[$i]['price']),4)?></td>

    		<td align="right"><?=number_format(floatval($total),4)?></td>
    		</tr>

        <?php
            if ($this->result[$i]['invalid'] === true)
            {
        ?>
            <tr bgcolor="#C15119">
                <td colspan="10"><b><?=$this->result[$i]['invalid_msg']?></b></td>
            </tr>

        <?php } ?>
    	<?php
    		$totals += $total;
            $totals2 += $total2;

    		}

            $totalAdd = $totals - $totals2;

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="7">Total</th>
    		<td align="right"><?=number_format($totals2,4)?></td>
            <td colspan="2">&nbsp;</td>
            <td align="right"><?=number_format($totals,4)?></td>
    		</tr>
        <tr>
    		<th scope="row" class="spec" colspan="10">Total Additional Costs</th>
    		<td align="right"><?=number_format($totalAdd,4)?></td>
        </tr>

</table>
<?php }

        if($this->result2) {?>

<div class="title2">AFE Saving Table</div>

<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Name Material</center></th>
             <th scope="col"><center>UoM</center></th>
             <th scope="col"><center>Qty (BOQ3)</center></th>
            <th scope="col"><center>Unit Price (BOQ3)</center></th>
            <th scope="col"><center>Total (BOQ3)</center></th>
            <th scope="col"><center>Qty (Request)</center></th>
            <th scope="col"><center>Unit Price (Request)</center></th>
            <th scope="col"><center>Total (Request)</center></th>
        </tr>
    	<?php

    		$totals3 = 0;
            $totals4 = 0;

       		for ($i=0;$i<(count($this->result2));$i++)
    		{
                $total3 = floatval($this->result2[$i]['qty']) * floatval($this->result2[$i]['price']);

                $total4 = floatval($this->result2[$i]['qtyori']) * floatval($this->result2[$i]['priceori']);

   				foreach ($this->result2[$i] as $key => $val)
    			{
    				if ($val == '')
    					$this->result2[$i][$key] = "&nbsp;";
    			}

    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
            <td ><?=$this->result2[$i]['cfs_kode']?></td>
            <td ><?=$this->result2[$i]['workid']?></td>
    		<td><?=$this->result2[$i]['kode_brg']?> - <?=$this->result2[$i]['nama_brg']?></td>
    		<td ><?=$this->result2[$i]['uom']?></td>
            <td align="right"><?=number_format(floatval($this->result2[$i]['qtyori']),4)?></td>

                <td align="right"><?=number_format(floatval($this->result2[$i]['priceori']),4)?></td>

    		<td align="right"><?=number_format(floatval($total4),4)?></td>
    		<td align="right"><?=number_format(floatval($this->result2[$i]['qty']),4)?></td>

                <td align="right"><?=number_format(floatval($this->result2[$i]['price']),4)?></td>

    		<td align="right"><?=number_format(floatval($total3),4)?></td>
    		</tr>

        <?php
            if ($this->result2[$i]['invalid'] === true)
            {
        ?>
            <tr>
                <th style="background-color: #ffff00; color: red; font-size: 10px;" colspan="10" class="spec"><?=$this->result2[$i]['invalid_msg']?></th>
            </tr>

        <?php } ?>
    	<?php
    		$totals3 += $total3;
            $totals4 += $total4;

    		}
            $totalSaving = $totals4 - $totals3;

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="7">Total</th>
    		<td align="right"><?=number_format($totals4,4)?></td>
            <td colspan="2">&nbsp;</td>
            <td align="right"><?=number_format($totals3,4)?></td>
    		</tr>
        <tr>
    		<th scope="row" class="spec" colspan="10">Total Saving to Compensate</th>
    		<td align="right"><?=number_format($totalSaving,4)?></td>

    		</tr>

</table>
<?php } ?>

<?php

    if($this->etc[0]['val_kode'] == IDR)
    {
      $afeValIDR = floatval($totalAdd) - floatval($totalSaving);
      $afeValUSD = 0;
      $afeValTotal = $afeValIDR;

      $addRevIDR = floatval($this->etc[0]['add_rev']);
      $addRevUSD = 0;
      $addRevTotal = $addRevIDR;

    }
    else
    {
      $afeValUSD = floatval($totalAdd) - floatval($totalSaving);
      $afeValIDR = 0;
      $afeValTotal = $afeValUSD*$this->etc[0]['rateidr'];

      $addRevUSD = floatval($this->etc[0]['add_rev']);
      $addRevIDR = 0;
      $addRevTotal = $addRevUSD*$this->etc[0]['rateidr'];
      
    }

    $boq3_oriInIDR = floatval($this->etc[0]['boq3_oriUSD'])*$this->etc[0]['rateidr'];
    $boq3_currentInIDR = floatval($this->etc[0]['boq3_currentUSD'])*$this->etc[0]['rateidr'];

    $boq3_oriTotal = $boq3_oriInIDR + $this->etc[0]['boq3_oriIDR'];
    $boq3_currentTotal = $boq3_currentInIDR + $this->etc[0]['boq3_currentIDR'];

    $totalCurrentBoq3 = $afeValTotal + $boq3_currentTotal;
            
    $percentage = $afeValTotal/$totalCurrentBoq3*100;

    if(floatval($boq2_oriTotal) == 0)
    {
        $mbpohOri = 0;
    }
    else
    {
        $mbpohOri = (1- floatval($boq3_oriTotal)/floatval($boq2_oriTotal))*100;
    }

    if(floatval($boq2_currentTotal) == 0)
    {
        $lastMbpoh = 0;
    }
    else
    {
        $lastMbpoh = (1- floatval($boq3_currentTotal)/floatval($boq2_currentTotal))*100;
    }


    if(floatval($boq2_currentTotal)+floatval($addRevTotal) == 0)
    {
        $mbpohCurrent = 0;
    }
    else
    {
        $mbpohCurrent = (1- ($totalCurrentBoq3)/(floatval($boq2_currentTotal)+floatval($addRevTotal)))*100;
    }
    $mbpohMoved = $mbpohCurrent- $mbpohOri;
    $mbpohLastCurrent = $lastMbpoh - $mbpohCurrent;

    $marginAFEToOri = floatval($percen_grossmargin_totalcurrent) - floatval($percen_grossmargin_origin);
    $marginAFEToCurrent = floatval($percen_grossmargin_totalcurrent) - floatval($percen_grossmargin_prev);


?>



 <?php
    if ( $this->etc[0]['user_approval'] != '')
    {
    ?>
    <div class="all-approve">
    <b>Approval History</b></br>
    <ul>
    <?php
        foreach ($this->etc[0]['user_approval'] as $key => $val)
        {
    ?>
            <li><?php echo "<b>" . $val['approve'] . "</b> " . date('d-m-Y H:i:s',strtotime($val['date'])) . " : " . $val['displayname'] . " (" . $val['display_name'] . ")<br />Sign : " . $val['signature'] . "<br />Comment : " . $val['comment']; ?></li>
    <?php
        }
    ?>
    </ul>
    </div>
    <?php
    }
    ?>

<?php if (!$this->show) { ?>
	<div style="margin-top:15px;">
		<div id="back-button"  style="margin-left:5px;float: right;"></div>
		<div id="cancel-button"  style="margin-left:5px;float: right;"></div>
		<div id="ok-button"  style="float: right;"></div>
	</div>
<?php } ?>

</div>


<script type="text/javascript">

function submitData(params,dataArray)
{
    var addurl = '';

    if (params == "" || params == '')
        return false;
    if (dataArray != undefined)
        addurl = '/next/' + dataArray.data['next'] + '/uid_next/' + dataArray.data['uid_next'] + '/workflow_structure_id/' + dataArray.data['workflow_structure_id'] + '/workflow_id/' + dataArray.data['workflow_id'] + '/workflow_item_id/' + dataArray.data['workflow_item_id'];
    Ext.getBody().mask('Loading..','x-mask-loading',false);
    Ext.Ajax.request({
            url: '/projectmanagement/afe/insertafe' + addurl,
            method:'POST',
            success: function(resp){
                Ext.getBody().unmask();
                var returnData = Ext.util.JSON.decode(resp.responseText);
                if (returnData.success)
                {
                    if (returnData.user != undefined && returnData.number == undefined)
                    {
                        showNextPerson(returnData.user,params);
                        return false;
                    }
                    else
                    {
                        Ext.Msg.alert('Success', 'AFE has been saved and submitted to current Workflow!' + '<br><br>Your AFE number is <b><font color="#ff0000">' + returnData.number + '</font></b>');
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/projectmanagement/afe/addafe',        
                            scripts : true
                        });
                    }
                }
                else
                {
                    Ext.Msg.alert('Error', returnData.msg);
                }
            },
            failure:function( action){
              Ext.getBody().unmask();
              if(action.failureType == 'server'){
              obj = Ext.util.JSON.decode(action.responseText);
              Ext.Msg.alert('Error!', obj.errors.reason);
              }else{
              Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
              }
              },
            params: params
        });

}

function submitData2(params,dataArray)
{
    var addurl = '';

    if (params == "" || params == '')
        return false;
    if (dataArray != undefined)
        addurl = '/next/' + dataArray.data['next'] + '/uid_next/' + dataArray.data['uid_next'] + '/workflow_structure_id/' + dataArray.data['workflow_structure_id'] + '/workflow_id/' + dataArray.data['workflow_id'] + '/workflow_item_id/' + dataArray.data['workflow_item_id'];
    Ext.getBody().mask('Loading..','x-mask-loading',false);
    Ext.Ajax.request({
	        url: '/projectmanagement/afe/updateafe' + addurl,
	        method:'POST',
	        success: function(resp){
                    Ext.getBody().unmask();
				var returnData = Ext.util.JSON.decode(resp.responseText);
				if (returnData.success)
				{
                     if (returnData.user != undefined && returnData.number == undefined)
                    {
                        showNextPerson(returnData.user,params,true);
                        return false;
                    }
                    else
                    {
                        Ext.Msg.alert('Success', 'AFE has been saved and submitted to current Workflow!');
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/projectmanagement/afe/afe',
                            scripts : true
                        });
                    }
				}
                else
                {
                    Ext.Msg.alert('Error', returnData.msg);
                }
	        },
	    	failure:function( action){
                  Ext.getBody().unmask();
	      	if(action.failureType == 'server'){
	          obj = Ext.util.JSON.decode(action.response.responseText);
	          Ext.Msg.alert('Error!', obj.errors.reason);
	      	}else{
	          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
	      	}
	      	},
	        params: params
	    });

}

function showNextPerson(userArray,params,isEdit)
{

    var addlist = Ext.data.Record.create([
             {name: 'id', type: 'string'},
             {name: 'workflow_id', type: 'string'},
             {name: 'workflow_item_id', type: 'string'},
             {name: 'workflow_item_name', type: 'string'},
             {name: 'workflow_structure_id', type: 'string'},
             {name: 'next', type: 'string'},
             {name: 'uid_next', type: 'string'},
             {name: 'name', type: 'string'},
             {name: 'role_name', type: 'string'},
             {name: 'prj_kode', type: 'string'}
        ]);

     var storeUser = new Ext.data.Store({
        reader: new Ext.data.JsonReader({fields: addlist})
    });

    Ext.each(userArray, function (t, index){
        var d = new addlist({
            id: t.id,
            workflow_id: t.workflow_id,
            workflow_item_id: t.workflow_item_id,
            workflow_item_name: t.workflow_item_name,
            workflow_structure_id: t.workflow_structure_id,
            uid_next: t.uid_next,
            next: t.next,
            name: t.name,
            role_name: t.role_name,
            prj_kode: t.prj_kode
        });
        storeUser.add(d);
        d = undefined;
    });

    var userColumns =  [
        new Ext.grid.RowNumberer(),
        {header: "Receiver", dataIndex: 'name', width: 220, renderer: function (v,p,r) {
            return '<div class="personicon"><b>' + r.data.name + '</b>&nbsp;<span class="rolename">' + r.data.role_name + '<br>Transaction Type: ' + r.data.workflow_item_name + '<br>Project : ' + r.data.prj_kode + '</span></div>';
        }}
    ];

    var bForm = new Ext.Window ({
    id: 'choose-next',
    layout:'fit',
    width: 300,
    height: 250,
    modal: true,
    title: 'Choose Document Receiver',
    style: 'margin-top: 10px',
    labelAlign: 'right',
    stateful: false,
    items : [
            new Ext.form.FormPanel({
                frame: true,
                items: [


                    new Ext.grid.GridPanel({
//                        width: 380,
                        height: 230,
                        id: 'site-grids',
                        loadMask: true,
                        columns: userColumns,
                        store: storeUser,
                        sm: new Ext.grid.RowSelectionModel({
                            singleSelect:true
                        }),
                        viewConfig: {
                            forceFit: true,
                            enableRowBody:true,
                            showPreview:true,
                            getRowClass : function(record, rowIndex, p, ds) {
                                            return 'x-grid3-row-expanded';
//                                            return 'x-grid3-row-collapsed';
                                          }
                        },
                        listeners: {
                            'rowdblclick': function(g, rowIndex, e){
                                    var record = g.getStore().getAt(rowIndex);
                                    if (isEdit)
                                        submitData2(params,record);
                                    else
                                        submitData(params,record);
                                    bForm.close();
                            }
                        }
                    })
                ]
                })
            ],
             buttons: [
                      {
                         text: 'OK',
                         id: 'ok-next',
                         iconCls: 'silk-upd',
                         handler: function(btn, ev) {
                            var row = Ext.getCmp('site-grids').getSelectionModel().getSelections();
                            var record = row[0];
                            if (isEdit)
                                submitData2(params,record);
                            else
                                submitData(params,record);
                            bForm.close();
                          }

                      },
                      {
                         text: 'Cancel',
                         id: 'cancel',
                         handler: function(btn, ev) {
                             bForm.close();
                          }

                      }


                        ]
        });
        bForm.show();
};

<?php
if (!$this->show) {
if ($this->approve)
{
?>

var trano = '<?=$this->docsID?>';
var uid = '<?=$this->uid?>';
var user_id = '<?=$this->userID?>';

<?php if ($this->reject) { ?>

var cancelButton = new Ext.Button({
    text: 'Goto Edit AFE',
    iconCls: 'icon-go',
    scale: 'large',
    handler: function (){
		myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
            url: '/projectmanagement/afe/editafe/trano/<?php echo $this->docsID; ?>',
	        scripts : true
	    });
	},
	renderTo: 'cancel-button'
});

<?php } else { ?>

var okButton = new Ext.Button({
    text: 'Approve',
    iconCls: 'icon-add',
    scale: 'large',
    handler: function (){
         this.disable();
	Ext.MessageBox.show({
        title: 'Comment',
        msg: 'Please enter comment:',
        width:300,
        buttons: Ext.MessageBox.OKCANCEL,
        multiline: true,
        fn: showResultText2
    });

	function showResultText2(btn, text){
		var comment='';
		if (btn == 'ok')
        {
			comment = text;
        }
        else if (btn == 'cancel')
            return false;
		params = {trans:trano, user: uid, comment: comment, user_id:user_id};
                Ext.getBody().mask('Loading..','x-mask-loading',false);
		Ext.Ajax.request({
	        url: '/admin/workflow/approve',
	        method:'POST',
	        success: function(resp){
                                Ext.getBody().unmask();
				var returnData = Ext.util.JSON.decode(resp.responseText);
				if (returnData.success)
				{
//					Ext.Msg.alert('Success', 'Document has been approved!');
					getDocs();
					myPanel = Ext.getCmp('abs-budget-panel');
				    myPanel.body.load({
				        url: '/default/home/showprocessdocument',
				        scripts : true
			        });
				}
    			else
    			{
    				Ext.Msg.alert('Error', returnData.msg);
    			}
	        },
	    	failure:function( action){
                  Ext.getBody().unmask();
	      	if(action.failureType == 'server'){
	          obj = Ext.util.JSON.decode(action.responseText);
	          Ext.Msg.alert('Error!', obj.errors.reason);
	      	}else{
	          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
	      	}
	      	},
	        params: params
	    });
	}
	},
	renderTo: 'ok-button'
});

var cancelButton = new Ext.Button({
    text: 'Reject',
    iconCls: 'icon-cancel',
    scale: 'large',
    handler: function (){
	Ext.MessageBox.show({
        title: 'Comment',
        msg: 'Please enter comment:',
        width:300,
        buttons: Ext.MessageBox.OKCANCEL,
        multiline: true,
        fn: showResultText
    });

	function showResultText(btn, text){
		var comment='';
        if (btn == 'ok')
        {
			comment = text;
        }
        else if (btn == 'cancel')
            return false;
        params = {trans:trano, user: uid, comment: comment, user_id:user_id};
        Ext.getBody().mask('Loading..','x-mask-loading',false);
    	Ext.Ajax.request({
            url: '/admin/workflow/reject',
            method:'POST',
            success: function(resp){
                        Ext.getBody().unmask();
    			var returnData = Ext.util.JSON.decode(resp.responseText);
    			if (returnData.success)
    			{
//    				Ext.Msg.alert('Success', 'Document has been rejected!');
    				getDocs();
    				myPanel = Ext.getCmp('abs-budget-panel');
    			    myPanel.body.load({
    			        url: '/default/home/showprocessdocument',
    			        scripts : true
    		        });
    			}
    			else
    			{
    				Ext.Msg.alert('Error', returnData.msg);
    			}
            },
        	failure:function( action){
              Ext.getBody().unmask();
          	if(action.failureType == 'server'){
              obj = Ext.util.JSON.decode(action.responseText);
              Ext.Msg.alert('Error!', obj.errors.reason);
          	}else{
              Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
          	}
          	},
            params: params
        });
    };


	},
	renderTo: 'cancel-button'
});

var backButton = new Ext.Button({
    text: 'Cancel',
    scale: 'large',
    handler: function (){
		myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '<?php echo $this->urlBack; ?>',
	        scripts : true
	    });
	},
	renderTo: 'back-button'
});

<?php
	}
}
elseif (!$this->approve)
{
?>


var json = '<?php echo $this->jsonResult; ?>';
var json2 = '<?php echo $this->jsonResult2; ?>';
var jsonFile = '<?php echo $this->jsonFile; ?>';

var okButton = new Ext.Button({
            text: 'Submit',
            iconCls: 'icon-save',
            scale: 'large',
            handler: function (){
             this.disable();

			<?php
			if (!$this->edit)
			{
			?>

	//parameter = '[{"prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($mbpohMoved,4)?>", "margin2": "<?=number_format($mbpohLastCurrent,4)?>"}]';
	parameter = '[{"prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($marginAFEToOri,4)?>", "margin2": "<?=number_format($marginAFEToCurrent,4)?>"}]';

	params = {posts:json, etc:parameter, posts2:json2, file: jsonFile};
	submitData(params);
	 <?php } else { ?>


//	 parameter = '[{"prj_kode":"<?=$this->etc[0]['prj_kode']?> ","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"cus_kode":"<?=$this->etc[0]['cus_kode']?>", "trano":"<?=$this->etc[0]['trano']?>", "assigned": "<?=$this->etc[0]['assigned']?>", "rev": "<?=$this->etc[0]['rev']?>"}]';
	 //parameter = '[{"trano":"<?=$this->etc[0]['trano']?>","prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($mbpohMoved,4)?>", "margin2": "<?=number_format($mbpohLastCurrent,4)?>"}]';
	 parameter = '[{"trano":"<?=$this->etc[0]['trano']?>","prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($marginAFEToOri,4)?>", "margin2": "<?=number_format($marginAFEToCurrent,4)?>"}]';
		params = {posts:json, etc:parameter, posts2:json2, file: jsonFile};
		submitData2(params);
		 <?php } ?>
	},
	renderTo: 'ok-button'
});


var cancelButton = new Ext.Button({
    text: 'Cancel',
    iconCls: 'icon-cancel',
    scale: 'large',
    handler: function (){
        <?php
			if (!$this->edit)
			{
			?>
        parameter = '[{"prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?= $this->etc[0]['rateidr']?>"}]';
		params = {posts:json, posts2:json2, etc:parameter, file:jsonFile};
		myPanel = Ext.getCmp('abs-budget-panel'); //Load the panel
	    myPanel.body.load({
	        url: '/projectmanagement/afe/addafe/returnback/true', //the url
	        scripts : true,
	        params: params //our params goes here
	    });
        <?php } else {  $afe_no = $this->etc[0]['trano'] ?>
            var afe_number = '<?=$afe_no?>';
                parameter = '[{"trano":"<?=$this->etc[0]['trano']?>","prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?= $this->etc[0]['rateidr']?>"}]';
        params = {posts:json, posts2:json2, etc:parameter, file:jsonFile};
		myPanel = Ext.getCmp('abs-budget-panel'); //Load the panel
	    myPanel.body.load({
	        url: '/projectmanagement/afe/editafe/returnback/true/trano/'+afe_number, //the url
	        scripts : true,
	        params: params //our params goes here
	    });
           <?php } ?>
	},
	renderTo: 'cancel-button'
});

<?php
}
}
?>


</script>