<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>
<style>

.parentContainer { /* The parent container */
    margin: 5px;
    padding: 0px;
    border: none;
    width: 840px; /* Required to set */
    height: 420px; /* Required to set */
    overflow: auto; /* Required to set */
	font-size: 14px;
}

</style>
<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
    	<tr>
        	<th scope="col" rowspan="2">No</th>
            <th scope="col" rowspan="2">Product ID</th>
            <th scope="col" rowspan="2">Description</th>
            <th scope="col" colspan="2">Qty</th>
            <th scope="col" colspan="2">Unit Price (IDR)</th>
            <th scope="col" colspan="2">Unit Price (USD)</th>
            <th scope="col" colspan="2">Total Price (IDR)</th>
            <th scope="col" colspan="2">Total Price (USD)</th>
        </tr>
        <tr>
        	<th>Origin</th>
        	<th>Current</th>
        	<th>Origin</th>
        	<th>Current</th>
        	<th>Origin</th>
        	<th>Current</th>
        	<th>Origin</th>
        	<th>Current</th>
        	<th>Origin</th>
        	<th>Current</th>
        </tr>
    </thead>
    <tbody>
    	<?php 
    		$grandTotalIDR = 0;
    		$grandTotalUSD = 0;
    		$grandTotalIDRori = 0;
    		$grandTotalUSDori = 0;
    		$j=0;
    		foreach($this->result as $key => $val)
    		{
    			$totalIDR = 0;
    			$totalUSD = 0;
    			$totalIDRori = 0;
    			$totalUSDori = 0;
    			?>
    			<tr>
    				<!--<td colspan="2">Work ID : <?=$key?></td>
    				<td colspan="6"><?=$this->result[$key]['workname']?></td>-->
                    <td colspan="2">CFS Code : <?=$key?></td>
    				<td colspan="6"><?=$this->result[$key]['cfs_nama']?></td>
    			</tr>
    			<?php 
    			
    			for($i=0;$i<count($this->result[$key])-1;$i++)
    			{
    	?>
    	
    	<tr>
        	<td><?=$j+1;?></td>
            <td><?=$this->result[$key][$i]['kode_brg'];?></td>
            <td width="300" style="overflow:hidden"><?=$this->result[$key][$i]['nama_brg'];?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['qtyori'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['qty'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['hargaIDRori'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['hargaIDR'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['hargaUSDori'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['hargaUSD'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['totalIDRori'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['totalIDR'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['totalUSDori'],2);?></td>
            <td align="right"><?=number_format($this->result[$key][$i]['totalUSD'],2);?></td>
        </tr>
        <?php 		$j++;
        			$totalIDR += $this->result[$key][$i]['totalIDR'];
        			$totalUSD += $this->result[$key][$i]['totalUSD'];
        			$totalIDRori += $this->result[$key][$i]['totalIDRori'];
        			$totalUSDori += $this->result[$key][$i]['totalUSDori'];
    			}
    	?>
    			<tr style="background: #4C6891;">
    				<!--<td colspan="7" style="color:#FFFFFF;" align="right">Total Work ID : <?=$key?> <?=$this->result[$key]['workname']?></td>-->
    				<td colspan="7" style="color:#FFFFFF;" align="right">Total CFS Code : <?=$key?> <?=$this->result[$key]['cfs_kode']?></td>
                    <td colspan="2" style="color:#FFFFFF;">--------></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($totalIDRori,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($totalIDR,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($totalUSDori,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($totalUSD,2)?></td>
    			</tr>
    	
    	<?php
    		
        			$grandTotalIDR += $totalIDR;
        			$grandTotalUSD += $totalUSD;
        			$grandTotalIDRori += $totalIDRori;
        			$grandTotalUSDori += $totalUSDori;
    		} ?>
        		<tr style="background: #4C6891;">
    				<td colspan="7" style="color:#FFFFFF;" align="right">Grand Total Site :</td>
    				<td colspan="2" style="color:#FFFFFF;">--------></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($grandTotalIDRori,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($grandTotalIDR,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($grandTotalUSDori,2)?></td>
    				<td  align="right" style="color:#FFFFFF;"><?=number_format($grandTotalUSD,2)?></td>
    			</tr>
    </tbody>
</table>
</div>
<script type="text/javascript">
//<![CDATA[

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 2
	});
})();

//]]>
</script>