<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<style>

.parentContainer { 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 840px; 
    height: 430px; 
    overflow: hidden; 
	font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="newspaper" class="newspaper">
    <thead id="fixed">
        <tr bgcolor="#ffff456">
            <th scope="col" align="center"><b>No</b></th>
            <th scope="col" align="center"><b>MDI No</b></th>
            <th scope="col" align="center"><b>Date</b></th>
            <th scope="col" align="center"><b>Work Id</b></th>
            <th scope="col" align="center"><b>Work Name</b></th>
            <th scope="col" align="center"><b>Prod Id</b></th>
            <th scope="col" align="center"><b>Description</b></th>
            <th scope="col" align="center"><b>Qty</b></th>

        </tr>
    </thead>

    <tbody>
    	<?php

            for($i=0; $i<count($this->result); $i++)
            {
        ?>
    	<tr>
            <td><?=$i+1;?></td>
            <td><?=$this->result[$i]['trano'];?></td>
            <td><?=$this->result[$i]['tgl_return'];?></td>
            <td><?=$this->result[$i]['workid'];?></td>
            <td><?=$this->result[$i]['workname'];?></td>
            <td><?=$this->result[$i]['kode_brg'];?></td>
            <td><?=$this->result[$i]['nama_brg'];?></td>
            <td align="right"><?=$this->result[$i]['qty'];?></td>
        </tr>
        <?php
            }
        ?>
    </tbody>
</table>
</div>
<script type="text/javascript">

(function() {
	var mySt = new superTable("newspaper", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 1
	});
})();

</script>