<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 640px; 
    height: 420px; 
    overflow: auto; 
    font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
            <tr>
                  <th scope="col" ><center><b>No</b></center></th>
                  <th scope="col" > <center><b>Trans No</b></center></th>
                  <th scope="col" ><center><b>Product Id</b></center></th>
                  <th scope="col" ><center><b>Material Name</b></center></th>
                  <th scope="col" ><center><b>Qty MDO</b></center></th>
                  <th scope="col" ><center><b>Qty DO</b></center></th>
                  <th scope="col" ><center><b>Balance</b></center></th>
            </tr>
    </thead>
    <tbody>

        <?php        	
            $j = 1;
            foreach ($this->result as $i => $val)
            {
    	?>
        
    	<tr>
            <td><?=$j++;?></td>
            <td><?=$this->result[$i]['mdo_no'];?></td>
            <td align="left"><?=$this->result[$i]['kode_brg'];?></td>
            <td align="left"><?=$this->result[$i]['nama_brg'];?></td>
            <td align="right"><?=number_format($this->result[$i]['qty_mdo'],4);?></td>
            <td align="right"><?=number_format($this->result[$i]['qty_do'],4);?></td>
            <td align="right"><?=number_format($this->result[$i]['balance'],4);?></td>
        </tr>

        <?php
            }
        ?>

    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows :1
	});
})();

</script>