<?php 
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}

?>
<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 840px; 
    height: 420px; 
    overflow: auto; 
    font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Trans No</center></th>
            <th scope="col"><center>Date</center></th>
            <th scope="col"><center>Supplier</center></th>        
            <th scope="col" colspan="2"><center>Total IDR</center></th>
            <th scope="col" colspan="2"><center>Total USD</center></th>
            <th scope="col"><center>Buyer</center></th>
            <th scope="col"><center>Status</center></th>
        </tr>
        
        
        
    </thead>
    <tbody>
        <tr style="background:#CFDCEE;">
            <td scope="col" colspan="4"></td>     
            <td scope="col"><center>With PPN</center></td>
            <td scope="col"><center>Without PPN</center></td>
            <td scope="col"><center>With PPN</center></td>
            <td scope="col"><center>Without PPN</center></td>
            <td scope="col"></td> 
            <td scope="col"></td>
        </tr>
        
        <?php
        	$nomer = $this->current;
            for($i=0; $i<count($this->result); $i++)
            {
            	
            	if (($i >= ($this->current - 1)) && ($i < ($this->current + $this->limitPerPage - 1)))
            	{
                    $status='';
                    switch ($this->result[$i]['approve']) {
                        case 150:
                            $status='Resubmit';
                        break;
                        
                        case 200:
                            $status='Approved';
                        break;
                        
                        case 300:
                            $status='Rejected';
                        break;
                            
                        case 400:
                            $status='Final';
                        break; 
                   
                        case 500:
                            $status='Executed';
                        break;
                        
                        default:
                            $status='Submitted';
                    }
    	?>
    	<tr>
            <td><?=$nomer;?></td>
            <td><a href="#" onclick="gotoDetail('<?=$this->result[$i]['trano'];?>')"><?=$this->result[$i]['trano'];?></a></td>
            <td><?=$this->result[$i]['tgl'];?></td>
            <td><?=$this->result[$i]['sup_nama'];?></td>          
            <td align="right"><?=number_format($this->result[$i]['total_IDR'],2);?></td>
            <td align="right"><?=number_format($this->result[$i]['total_IDR_NonPPN'],2);?></td>
            <td align="right"><?=number_format($this->result[$i]['total_USD'],2);?></td>            
            <td align="right"><?=number_format($this->result[$i]['total_USD_NonPPN'],2);?></td>
            <td><?=$this->result[$i]['pc_nama'];?></td>
            <td><?=$status;?></td>
        </tr>

        <?php        
        			$nomer++;
            	}
            $total = $this->result[$i]['total_IDR'];
            $totalJumlah = $totalJumlah + $total;

            $total2 = $this->result[$i]['total_USD'];
            $totalJumlah2 = $totalJumlah2 + $total2;
            
            $total = $this->result[$i]['total_IDR_NonPPN'];
            $totalJumlah_NonPPN = $totalJumlah_NonPPN + $total;

            $total2 = $this->result[$i]['total_USD_NonPPN'];
            $totalJumlah2_NonPPN = $totalJumlah2_NonPPN + $total2;

            $total3 = $this->result[$i]['totalUSD_IDR'];
            $totalJumlah3 = $totalJumlah3 + $total3;

            $totalJumlah4 = $totalJumlah3 + $totalJumlah;

            }
        ?>
       
    			<tr style="background: #4C6891;">
                            <td colspan="4" style="color:#FFFFFF;" align="right">Total: -----></td>                         
                            <td style="color:#FFFFFF;" align="right"><?=number_format($totalJumlah,2)?></td>
                            <td style="color:#FFFFFF;" align="right"><?=number_format($totalJumlah_NonPPN,2)?></td>
                            <td style="color:#FFFFFF;" align="right"><?=number_format($totalJumlah2,2)?></td>
                            <td style="color:#FFFFFF;" align="right"><?=number_format($totalJumlah2_NonPPN,2)?></td>
                            <td style="color:#FFFFFF;" align="right"></td>
                            <td style="color:#FFFFFF;" align="right"></td>
                        </tr>
    </tbody>
</table>
</div>
<?=$this->paging($this->pageUrl,$this->totalResult,$this->limitPerPage,$this->current,$this->currentPage)?>
<script type="text/javascript">

function gotoDetail(trano)
    {
    myPanel = Ext.getCmp('abs-budget-panel');
    myPanel.body.load({
	        url: '/report/podetail/trano/' + trano,
                scripts: true

	});
    }


(function() {
	var mySt = new superTable("budgetTable", {
	    cssSkin : "sSky",
	    fixedCols : 2,
	    headerRows : 1
	});
})();

</script>