<?php 

    header("Content-type: application/vnd-ms-excel");

    header("Content-Disposition: attachment; filename=Invoice_Detail.xls"); 
 ?>


<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}

?>
<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 740px;
    height: 460px;
    overflow: auto; 
    font-size: 14px;
}

.parentContainer2{
    font-size: 12px;
}

</style>

<table class="parentContainer2">
        <tr>
            <td>Project</td><td>:</td>
            <td><?=$this->result[0]['prj_kode'];?></td>
            <td><?=$this->result[0]['prj_nama'];?></td>
        </tr>
        <tr>
            <td>Site</td><td>:</td>
            <td><?=$this->result[0]['sit_kode'];?></td>
            <td><?=$this->result[0]['sit_nama'];?></td>
        </tr>
        <tr>
            <td>Date</td><td>:</td>
            <td><?=date('d-m-Y',strtotime($this->start_date));?> -</td>
            <td><?=date('d-m-Y',strtotime($this->end_date));?></td>
        </tr>

</table>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable" border="1">
    <thead id="fixed">
        <tr><th colspan="8"><center>PAID COST DETAIL</center></th></tr>
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Date</center></th>
            <th scope="col"><center>Transaction No.</center></th>
            <th scope="col"><center>Currency</center></th>
            <th scope="col"><center>Amount</center></th>
            <th scope="col"><center>IDR Rate</center></th>
            <th scope="col"><center>IDR Total</center></th>
            <th scope="col"><center>Author</center></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->result AS $index => $data)
            {
    	?>
    	<tr>
            <td><?=$i+=1;?></td>
            <td><?=date('d-m-Y',strtotime($data['tgl']));?></td>
            <td><?=$data['trano'];?></td>
            <td><?=$data['val_kode'];?></td>
            <td align="right"><?=($data['val_kode'] !='IDR' ?number_format($data['totalUSD'],4):number_format($data['totalIDR'],2));?></td>
            <td><?=number_format($data['rateidr']);?></td>
            <td align="right"><?=($data['val_kode'] !='IDR' ? number_format($data['totalUSD']*$data['rateidr'],2) : number_format($data['totalIDR'],2) ) ;?></td>
            <td align="right"><?= ucfirst($data['uid']); ?></td>      
        </tr>

        <?php        
             $total +=floatval($data['val_kode'] !='IDR' ? floatval($data['totalUSD']*$data['rateidr']) : floatval($data['totalIDR']) )  ;
          

            }
        ?>
        <tr style="background: #4C6891;">
            <td colspan="5" style="color:#FFFFFF;" align="right">Grand Total: </td>
            <td style="color:#FFFFFF;"> --------> </td>
            <td style="color:#FFFFFF;"><?=number_format(floatval($total),2)?></td>
            <td>&nbsp;</td>
        </tr>
    </tbody>
</table>
</div>
