<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">

<br></br>
<table id="mytable" cellspacing="0">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Name</center></th>
            <th scope="col"><center>Project</center></th>
            <th scope="col"><center>Total Hour</center></th>
        </tr>
    	<?php
    		$totals = 0;
    		foreach($this->result as $key => $val)
            {
                $i = 1;
                foreach($val['project'] as $key2 => $val2)
                {
                    if($i == 1)
                    {
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($no+1)?></th>
    		<td><?=$val['name']?></td>
    		<td><?=$key2?></td>
    		<td align="right"><?=number_format(floatval($val2))?></td>
    		</tr>
    	<?php
                    }
                    else
                    {
        ?>
            <tr>
    		<th scope="row" class="spec">&nbsp;</th>
    		<td>&nbsp;</td>
    		<td><?=$key2?></td>
    		<td align="right"><?=number_format(floatval($val2))?></td>
    		</tr>
        <?php
                    }
                    $i++;
                    $totals += floatval($val2);
                }
                $no++;
    		}

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="3">Grand Total</th>
    		<td align="right"><?=number_format($totals)?></td>
    	</tr>
</table>

</div>