<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        <?php echo $this->action('index','textfield',null); ?>


        function create()
        {
            myPanel = Ext.getCmp('cfs-panel');
            myPanel.body.load({
                url: '/projectmanagement/cfs/create',
                scripts : true
            });
        }

        function edit()
        {
            myPanel = Ext.getCmp('cfs-panel');
            myPanel.body.load({
                url: '/projectmanagement/cfs/edit',
                scripts : true
            });
        }
        
        function view()
        {
            myPanel = Ext.getCmp('cfs-panel');
            myPanel.body.load({
                url: '/projectmanagement/cfs/view',
                scripts : true
            });
        }

        var windowForm = ({

            title:'Master Engineer Work',
            id:'cfs-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                    items: [
                            {
                                id: 'masterwork_add_button',
                                text: 'Create CFS Code',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/action_paste.gif",
                                handler:create
                            }
                            ,{
                                id: 'masterwork_edit_button',
                                text: 'Edit CFS Code',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler:edit
                            }
                            ,{
                                id: 'masterwork_view_button',
                                text: 'View CFS Code',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/grid.png",
                                handler:view
                            }
                            ]
                    }
                }
            ]

        })
        
//        function getExchangeRate()
//        {
//            Ext.Ajax.request({
//                url: '/default/valuta/getexchangerate/val_kode/USD',
//                method: 'POST',
//                success: function(result, request) {
//                    var returnData = Ext.util.JSON.decode(result.responseText);
//                    if (returnData.success) {
//                        if(returnData.rate == 0)
//                        {
//                            Ext.MessageBox.show({
//                                title: 'Error',
//                                msg: 'Please Call Accounting Staffs (Ext. 1101 - 1104). Ask Them to Input Current IDR Rate. Thank You.',
//                                buttons: Ext.MessageBox.OK,
//                                icon: Ext.MessageBox.ERROR,
//                                fn:function(){window.location='';}
//                            });
//                        }
//                    
//                        Ext.getCmp('rateidr').setValue(returnData.rate);
//                    }
//                },
//                failure: function(action) {
//                    if (action.failureType == 'server') {
//                        obj = Ext.util.JSON.decode(action.response.responseText);
//                        Ext.Msg.alert('Error!', obj.errors.reason);
//                    }
//                }
//            });
//        }
//        getExchangeRate();

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('cfs-panel');
        centerRegionTab.layout.setActiveItem('cfs-panel');
        panelBaru.body.load({
                url: '/projectmanagement/cfs/view',
                scripts: true
            });

        showSubmenu('cfs-panel');
    })

</script>
