<script type="text/javascript">

 function refreshData ()
        {
            cfsstore.clearFilter();
            Ext.getCmp('search').setValue('');
            Ext.getCmp('paging').doRefresh();
        }

        var datas = [
                ['CFS Code',1],
                ['CFS Name',2]
            ];

        var store = new Ext.data.ArrayStore({
            fields: ['a', 'b'],
            data : datas
        });

        var combo = new Ext.form.ComboBox({
            store: store,
            displayField:'a',
            valueField: 'b',
            typeAhead: true,
            mode: 'local',
            triggerAction: 'all',
            selectOnFocus:true,
            name:'option',
            width:100,
            style: 'margin-left: 5px',
            value:1,
            id:'option'
        });
        
       
        var cfsstore = new Ext.data.Store({

            url:'/projectmanagement/cfs/getviewcfs',
            autoLoad:true,
            reader: new Ext.data.JsonReader({
                root:'data',
                totalProperty:'total'
            },[
                {name:'cfs_kode',type:'String'},
                {name:'cfs_nama',type:'String'},
                {name:'id',type:'int'}
            ])

        });
        
    Ext.onReady(function(){

        Ext.QuickTips.init();

        var addcfs = new Ext.form.FormPanel ({

            id:'add-new-cfs',
            title:'Add New CFS',
            renderTo:'cfsform',
            frame:true,
            iconCls: 'silk-user',
            width:400,
            height:120,
            items:[
                
                {
                    xtype:'textfield',
                    fieldLabel:'CFS Code',
                    name:'cfs_kode',
                    msgTarget:'side',
                    width:100,
                    allowBlank:false
                },{
                    xtype:'textfield',
                    fieldLabel:'CFS Name',
                    name:'cfs_nama',
                    msgTarget:'side',
                    width:260,
                    allowBlank:false
                }
            ],
            buttons:[
                {
                    text:'Submit',
                    handler:function(btn,ev)
                    {
                        if (!Ext.getCmp('add-new-cfs').getForm().isValid())
                        {
                            Ext.Msg.alert('Error','Please fill in all required fields');
                            return false;
                        }else
                        {
                            Ext.MessageBox.confirm(
                                    'Confirm',
                                    'Are you sure you want to create a new CFS ?',
                                    function(btn)
                                    {
                                        if (btn == 'yes')
                                        {
                                            Ext.getBody().mask('Loading..','x-mask-loading',false);
                                            Ext.getCmp('add-new-cfs').getForm().submit({
                                                method:'POST',
                                                url:'/projectmanagement/cfs/getaddcfs',
                                                success:function(thisform,response){
                                                    Ext.getBody().unmask();
                                                    Ext.Msg.alert('success','New CFS has been saved');
                                                    Panel = Ext.getCmp('cfs-panel');
                                                    Panel.body.load ({
                                                        url:'/projectmanagement/cfs/create',
                                                        scripts:true
                                                    })
                                                },failure:function(thisfoem, response)
                                                {
                                                    Ext.getBody().unmask();
                                                    if (response.failureType == 'server')
                                                    {
                                                        var resp = Ext.util.JSON.decode(response.response.responseText);
                                                        Ext.Msg.alert('Error',resp.pesan);
                                                    }
                                                }
                                            })
                                        }
                                    });
                        }
                    }
                },{
                    text:'Reset',
                    handler:function (btn,ev)
                    {
                        addcfs.form.reset();
                    }
                }
            ]

        });
        
        var grid = new Ext.grid.GridPanel ({

            store:cfsstore,

            viewConfig:{
              forceFit:true
            },

            title:'View CFS List',
            renderTo:'viewcfs',
            width:440,
            height:400,
            frame:true,
            listeners:{
                'rowdblclick':function(grid,row,e){
                    isDblClick = true;

                    var row = grid.getStore().getAt(row);
                    Ext.getCmp('edit-new-cfs').getForm().loadRecord(row);
                    
                }
            },
            columns:[
                new Ext.grid.RowNumberer(),
                {
                    header:'CFS Code',
                    dataIndex:'cfs_kode',
                    align:'center',
                    width:60,
                    sortable:true
                },
                {
                    header:'CFS Name',
                    dataIndex:'cfs_nama',
                    align:'left',
                    width:200,
                    sortable:true
                }
            ],
            bbar: new Ext.PagingToolbar ({
                id:'paging',
                pagesize:20,
                store:cfsstore,
                displayInfo:true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),
            tbar:[
                {
                    xtype:'tbtext',
                    text:'Search',
                    style: 'margin-left: 5px'
                },'-',
                combo,
                {
                    xtype: 'textfield',
					id: 'search',
                    style: 'margin-left: 10px;margin-right:10px',
                    enableKeyEvents: true,
                    listeners:{
                        'keyup' : function (textfieldIni,event) {
                            var isiTeks = textfieldIni.getValue();
                            if (isiTeks != "" && isiTeks.toString().length >= 2)
                            {
                                var search = Ext.getCmp('search').getValue();
                                var option = Ext.getCmp('option').getValue();
                                cfsstore.proxy.setUrl('/projectmanagement/cfs/getviewcfs/search/' + search + '/option/' + option);
                                cfsstore.reload();
                                grid.getView().refresh();
                            }
                        }
                    }
                },'-',{
				    text: 'refresh',
				    iconCls: 'icon-refresh',
				    handler: refreshData,
				    scope: this
                }
            ]

        });


    })

</script>


<div id="cfsform" style="float:left"></div>
<div id="viewcfs" style="margin-left: 20px;float:left"></div>
 
