<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();


        var storebank = new Ext.data.Store ({

            autoLoad:true,
            url:'/finance/bank/getviewbanklist',
            reader:new Ext.data.JsonReader ({

                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'bnk_kode'
                },{
                    name:'bnk_nama'
                },{
                    name:'bnk_norek'
                },{
                    name:'bnk_noreknama'
                },{
                    name:'bnk_cabang'
                },{
                    name:'bnk_alamat'
                },{
                    name:'val_kode'
                },{
                    name:'cabang'
                },{
                    name:'bnk_kota'
                }]

            })

        })

        var gridbank = new Ext.grid.GridPanel ({

            id:'bank_list',
            renderTo:'bank-list',
            title:'Bank Account List',
            frame:true,
            store:storebank,
//            viewConfig:{
//                forceFit:true
//            },
            height:300,
            width:840,
            columns:[{
                header:'Bank Name',
                dataIndex:'bnk_nama',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Account Number',
                dataIndex:'bnk_norek',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Account Name',
                dataIndex:'bnk_noreknama',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Valuta',
                dataIndex:'val_kode',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Branch',
                dataIndex:'bnk_cabang',
                sortable:true,
                align:'center',
                width:140
            },{
                header:'Bank Address',
                dataIndex:'bnk_alamat',
                sortable:true,
                align:'center',
                width:180
            },{
                header:'Bank City Address',
                dataIndex:'bnk_kota',
                sortable:true,
                align:'center',
                width:120
            }],bbar: new Ext.PagingToolbar ({
                id: 'paging',
                pageSize: 10,
                store: storebank,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            })


        })


    })


</script>

    <div id="bank-list"></div>
 
