<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init ();

        var windowForm = ({

            title: 'Bank Account Menu',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                    items: [
                            {
                                id: 'insert_bank',
                                text: 'Insert Bank Account',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/action_paste.gif",
                                handler:function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/bank/forminsertbank',
                                        scripts : true
                                    });
                                }
                            }
                            ,{
                                id: 'edit_bank',
                                text: 'Edit Existing Bank Account',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler:function ()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/bank/formeditbank',
                                        scripts : true
                                    });
                                }
                            }
                            ]
                    }
                }

            ]

        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        panelBaru.body.load ({
            url:'/finance/bank/banklist',
            scripts:true
        })


    })


</script>
