<script type="text/javascript">

    Ext.apply(Ext.form.VTypes, {

    numericText: "Only numbers are allowed.",
    numericMask: /[0-9]/,
    numericRe: /(^-?dd*.d*$)|(^-?dd*$)|(^-?.dd*$)/,
    numeric: function(v) {
        return function() { return this.numericRe.test(v)} ;
        }

    });


    Ext.onReady(function(){

        Ext.QuickTips.init();

        function showbanklist ()
        {

            var storebank = new Ext.data.Store ({

            autoLoad:true,
            url:'/finance/bank/getviewbanklist',
            reader:new Ext.data.JsonReader ({

                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'id'
                },{
                    name:'bnk_nama'
                },{
                    name:'bnk_norek'
                },{
                    name:'bnk_noreknama'
                },{
                    name:'bnk_cabang'
                },{
                    name:'bnk_alamat'
                },{
                    name:'val_kode'
                },{
                    name:'cabang'
                },{
                    name:'bnk_kota'
                }]

            })

        })

            var gridbank = new Ext.grid.GridPanel ({

            id:'bank_list',
            title:'Bank Account List',
            store:storebank,
//            viewConfig:{
//                forceFit:true
//            },
            height:300,
            width:840,
            columns:[{
                header:'Bank Name',
                dataIndex:'bnk_nama',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Account Number',
                dataIndex:'bnk_norek',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Account Name',
                dataIndex:'bnk_noreknama',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Valuta',
                dataIndex:'val_kode',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Branch',
                dataIndex:'bnk_cabang',
                sortable:true,
                align:'center',
                width:140
            },{
                header:'Bank Address',
                dataIndex:'bnk_alamat',
                sortable:true,
                align:'center',
                width:180
            },{
                header:'Bank City Address',
                dataIndex:'bnk_kota',
                sortable:true,
                align:'center',
                width:120
            }],bbar: new Ext.PagingToolbar ({
                id: 'paging',
                pageSize: 10,
                store: storebank,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),listeners:
                {
                    'rowdblclick':function(gridaktif,rowindex,e)
                    {
                        isDbClick = true;
                        var bank = gridaktif.getStore().getAt(rowindex);
                        Ext.getCmp('edit-bank').getForm().loadRecord(bank);

                        bankwindow.close();

                    }
                }


        })


            var bankwindow = new Ext.Window ({

                title:'Choose Bank to Edit',
                id:'choose-bank',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 854,
                height: 330,
                loadMask:true,
                items:[gridbank]


            })

            bankwindow.show();
        }

        var editbank = new Ext.form.FormPanel ({

            title:'Edit Bank Account',
            id:'edit-bank',
            renderTo:'edit_bank',
            frame:true,
            width:360,
            labelWidth:160,
            defaults:{
                msgTarget:'side'
            },
            items:[{
                xtype:'trigger',
                fieldLabel:'Code Bank',
                triggerClass:'teropong',
                allowBlank:false,
                editable:false,
                id:'id',
                width:157,
                onTriggerClick:function()
                {
                    showbanklist();
                }
            },{
                xtype:'textfield',
                fieldLabel:'Bank Name',
                allowBlank:false,
                id:'bnk_nama'
            },{
                xtype:'textfield',
                fieldLabel:'Bank Account Number',
                allowBlank:false,
                vtype:'numeric',
                id:'bnk_norek'
            },{
                xtype:'textfield',
                fieldLabel:'Bank Account Name',
                allowBlank:false,
                id:'bnk_noreknama'

            },{
                xtype:'combo',
                allowBlank:false,
                store: new Ext.data.SimpleStore ({
                    fields: ['name', 'value'],
                    data:[['IDR','IDR'],['USD','USD']]
                }),
                fieldLabel:'Bank Valuta',
                displayField:'name',
                valueField:'value',
                mode: 'local',
                triggerAction: 'all',
                selectOnFocus:true,
                width:157,
                emptyText:'Select Bank Valuta ...',
                id:'val_kode',
                forceSelection: true,
                editable: false
            },{
                xtype:'textfield',
                fieldLabel:'Bank Branch',
                allowBlank:false,
                id:'bnk_cabang'
            },{
                xtype:'textarea',
                fieldLabel:'Bank Address',
                width:157,
                allowBlank:false,
                id:'bnk_alamat'
            },{
                xtype:'textfield',
                fieldLabel:'Bank City Address',
                allowBlank:false,
                id:'bnk_kota'
            }],
            buttons:[{
                text:'Edit',
                handler:function (btn,ev)
                {
                    if (!Ext.getCmp('edit-bank').getForm().isValid())
                    {
                        Ext.Msg.alert('Error','Please cek your field');
                        return false;
                    }

                    Ext.MessageBox.confirm('Confirm','Are you sure want this action ?',function(btn){

                        if (btn == 'yes')
                        {
                            Ext.getCmp('edit-bank').getForm().submit({

                                method:'POST',
                                url:'/finance/bank/editbank',
                                success:function (thisForm,response)
                                {
                                    Ext.Msg.alert('Message','Success, Bank Account has been Edit');
                                    panel = Ext.getCmp('abs-budget-panel');
                                    panel.body.load ({
                                        url: '/finance/bank/bankmenu',
                                        scripts: true
                                    })
                                },
                                failure:function(thisForm,response){
                                    if (response.failureType == 'server')
                                    {
                                        var resp = Ext.util.JSON.decode(response.response.responseText);
                                        Ext.Msg.alert('Error',resp.pesan);
                                    }
                                }


                            })
                        }

                    })



                }
            },{
                text:'Cancel',
                style:'marginRight:18px',
                handler:function(btn,ev)
                {
                    panel = Ext.getCmp('abs-budget-panel');
                    panel.body.load ({
                        url: '/finance/bank/bankmenu',
                        scripts: true
                    })
                }
            }]
        })



    })

</script>

   <div id="edit_bank"></div>

 
