<?php $this->doctype(); ?>
<html>
    <head>
        <?php
// add the CSS
        $this->headLink()->appendStylesheet('/css/960.css');
        $this->headLink()->appendStylesheet('/css/960text.css');
        $this->headLink()->appendStylesheet('/css/960web.css');

        echo $this->headLink();
        echo $this->headTitle();
        ?>
    </head>
    <body>
<?php echo $this->render('_webheader.phtml') ?>

        <div id="page-bg">
                <div id="hspace"></div>
                <div id="center">
<?php echo $this->layout()->content; ?>
                </div>
                <div id="hspace"></div>
        </div>
<?php echo $this->render('_webfooter.phtml') ?>
    </body>
</html>