<style>


    .last-reject{
        margin-top: 10px;
        margin-bottom: 10px;
        border:solid 1px #DEDEDE;
        background:#EFEFEF;
        /*color:#222222;*/
        color: #C15119;
        padding:4px;
        text-align:left;
    }
    .all-reject{
        margin-top: 10px;
        margin-bottom: 10px;
        border:solid 1px #DEDEDE;
        background:#F6CBCA;
        color:#222222;
        padding:4px;
        text-align:left;
    }
    .all-approve{
        margin-top: 10px;
        margin-bottom: 10px;
        border:solid 1px #DEDEDE;
        /*background:#CEE6C3;*/
        color:#222222;
        padding:4px;
        text-align:left;
        height: 200px;
        overflow: auto;
    }    

    .body {
        /*width: 720px;*/
        overflow: auto;
    }
    .title {
        width: 100%;
        text-align: center;
        font-size: 18px;
        font-weight: bold;
        margin-bottom: 10px;
    }
    .title2 {
        width: 100%;
        float: left;
        text-align: center;
        font-size: 12px;
        font-weight: bold;
        margin-top: 10px;
        margin-bottom: 10px;
    }
    .etc {
        width: 100%;
        height: 50px;
    }
    .kanan-etc {
        float: right;
        width: 48%;
    }
    .kiri-etc {
        float: left;
        width: 48%;
    }
    .blok {
        font-size: 12px;
        font-weight: bold;
        margin-bottom: 5px;
    }
    .budgetTable {
        width: 100%;
        font-size: 12px;
        font-weight: normal;
    }

</style>
<style type="text/css">
    .x-grid3-td-name b {
        font-family:tahoma, verdana;
        display:block;
        color:#333;
    }
    .x-grid3-td-name b i {
        font-weight:normal;
        font-style: normal;
        color:#000;
    }
    .x-grid3-td-name .personicon {
        padding-left:20px;
        background:transparent url(/images/engineer-icon.png) no-repeat 0 2px;
    }
    .x-grid3-td-name .x-grid3-cell-inner {
        white-space:normal;
    }

    .x-grid3-row-body p {
        margin:5px 20px 10px 25px !important;
        color:#555;
    }

    .rolename {
        color:#333;
    }
</style>

<script type="text/javascript">

    Ext.onReady(function() {
<?php if (!$this->preview && !$this->show) { ?>
    <?php if ($this->approve) { ?>
                //Variabel yg dikirim, approve / reject sama variabelna...
                var trano = '<?= $this->docsID ?>';
                var uid = '<?= $this->uid ?>';
                var user_id = '<?= $this->userID ?>';

        <?php if (!$this->reject) { ?>
                    var wButt = new Ext.ux.workflowButton({
                        renderTo: 'wButton',
                        showApproveButton: true,
                        showRejectButton: true,
                        showAskButton: true,
                        showCancelButton: true,
                        trano: '<?= $this->trano ?>',
                        itemType: 'ASF',
                        approveParams: {trans: trano, user: uid, user_id: user_id},
                        rejectParams: {trans: trano, user: uid, user_id: user_id},
                        beforeApproveCallback: function(theWButton) {
                            var cb = function(bypass) {
                                if (bypass == undefined)
                                    bypass = false;
                                theWButton.approveParams.bypass_next = bypass;
                                var cbcomment = function(comment) {
                                    theWButton.approveParams.comment = comment;
                                    theWButton.doApprove(theWButton.approveParams);
                                };
                                theWButton.showComment(cbcomment);
                            };
                            checkNominalWorkflow(uid, '<?= $this->docsID ?>', '<?= $this->trano ?>', cb);
                        },
                        approveSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts: true
                            });
                        },
                        rejectSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts: true
                            });
                        },
                        cancelSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts: true
                            });
                        }
                    });

                    wButt.on('beforeworkflowapprove', function(t) {

                    });
        <?php } else { ?>

                    var wButt = new Ext.ux.workflowButton({
                        renderTo: 'wButton',
                        showEditButton: true,
                        itemType: 'ASF',
                        editSuccessCallback: function() {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/procurement/procurement/editasf',
                                params: {
                                    trano: '<?php echo $this->trano; ?>'
                                },
                                scripts: true
                            });
                        }
                    });
        <?php } ?>
    <?php } else { ?>
                // variabel yg dikirim untuk submit ke workflow

                var json = '<?php echo $this->jsonResult; ?>';
                var json2 = '<?php echo $this->jsonResult2; ?>';
                var json3 = '<?php echo $this->jsonResult3; ?>';
                var parameter = '<?= Zend_Json::encode($this->etc) ?>';
                var jsonFile = '<?php echo $this->jsonFile; ?>';
                var jsonDeletedFile = '<?php echo $this->jsonDeletedFile; ?>';


                var params = {
                    posts: json,
                    posts2: json2,
                    posts3: json3,
                    etc: parameter,
                    file: jsonFile,
                    item_type: 'ASF'
                };

        <?php if (!$this->edit) { ?>
                    var url = '/procurement/procurement/insertasf',
                            urlCancel = '/procurement/procurement/addasf/returnback/true',
                            edit = false;
        <?php } else { ?>
                    var url = '/procurement/procurement/updateasf',
                            urlCancel = '/procurement/procurement/editasf/returnback/true/trano/'+'<?=$this->etc[0]['trano']?>',
                            edit = true;
        <?php } ?>

                var wButt = new Ext.ux.workflowButton({
                    renderTo: 'wButton',
                    itemType: 'ASF',
                    showSubmitButton: true,
                    showCancelButton: true,
                    urlSubmit: url,
                    isEdit: edit,
                    submitParams: params,
                    submitSuccessCallback: function() {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/procurement/procurement/asf',
                            scripts: true
                        });
                    },
                    cancelSuccessCallback: function() {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: urlCancel,
                            params: params,
                            scripts: true
                        });
                    }
                });
    <?php } ?>
<?php } ?>
    });

</script>


<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">
    <div align="right"><img src="/images/qdc.gif" alt= "logo qdc" /></div>
    <div class="title">ADVANCE SETTLEMENT FORM</div>

    <?php if ($this->reject) { ?>
        <div class="last-reject">
    This Document was Rejected by <?php echo $this->lastReject[0]['name']; ?> at <?php echo date('d-m-Y H:i:s',strtotime($this->lastReject[0]['date'])); ?>
    <br />
    Comment : <?php echo $this->lastReject[0]['comment']; ?>
        </div>
    <?php } ?>

    <?php if ($this->file != '') { ?>
        <div class="files">
            Attachment Files :<br />
            <ul>
                <?php foreach ($this->file as $key => $val) { ?>
                    <li>- <a href="#" onclick="window.open('/default/file/download/path/files/filename/<?php echo $val['savename']; ?>', 'mywin', 'left=20,top=20,width=100,height=20,toolbar=0,resizable=0');"><?php echo $val['filename']; ?></a></li>
                <?php } ?>
            </ul>
        </div>
        <br />
        <script>
            var uploaderButton = function()
            {
                var callback = function()
                {
                    var jsonFile = <?= $this->jsonFile ?>,
                            params = {
                                trano: '<?= $this->etc[0]['trano'] ?>'
                            };

                    var cb = function()
                    {
                        Ext.Msg.alert('Success', 'File has been uploaded, Please Approve or Reject this ASF');
                    };

                    showUploaderWindow('/procurement/procurement/update-asf-file', params, jsonFile, cb);
                };
                showAuthWindow('/admin/document/auth-upload/item_type/ASF', callback);
            };
            var reviseButton = function()
            {
                var callback = function()
                {
                    var json = '<?php echo $this->jsonRev; ?>';
                    var json2 = '<?php echo $this->jsonRev2; ?>';
                    var parameter = '<?= Zend_Json::encode($this->revetc) ?>';
                    var jsonFile = '<?php echo $this->jsonFile; ?>';

                    var params = {
                        posts: json,
                        posts2: json2,
                        etc: parameter,
                        file: jsonFile,
                        item_type: 'ASF'
                    };
                    
                    var cb = function()
                    {
                        Ext.Msg.alert('Success', 'ASF Value has been revised, Please Approve or Reject this ASF');
                        
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/procurement/procurement/appasf/approve/'+'<?= $this->approve;?>',
                            scripts: true
                        });
                    };

                    showReviseWindow('/procurement/procurement/updateasfvalue', params, jsonFile, cb);
                   
                };
                showAuthWindow('/admin/document/auth-upload/item_type/ASF', callback);
            }
        </script>
        <button onclick="uploaderButton();">Upload Revised ASF Document</button>
        <button onclick="reviseButton();">Revise ASF Value</button>
        <br /><br />
    <?php } ?>

    <div class="etc">
        <div class="kiri-etc">

            <?php if ($this->edit || $this->approve) { ?><div class="blok">ASF Number : <?= $this->etc[0]['trano'] ?></div><?php } ?>
                <!--<div class="blok">ARF Number : <?= $this->etc[0]['arf_no'] ?></div>-->
            <div class="blok">Requester Name : <?= $this->etc[0]['requester'] ?></div>
            <div class="blok">Manager Name : <?= $this->etc[0]['petugas'] ?></div>
            <div class="blok">PIC Name : <?= $this->etc[0]['pic'] ?></div>
            <div class="blok"><b>Remark : <?= $this->etc[0]['ket'] ?></b></div>
        </div>
        <div class="kanan-etc">
            <div class="blok">Project : <?= $this->etc[0]['prj_kode'] ?> - <?= $this->etc[0]['prj_nama'] ?></div>
            <div class="blok">Site : <?= $this->etc[0]['sit_kode'] ?> - <?= $this->etc[0]['sit_nama'] ?></div>

        </div>
    </div>

    <?php if ($this->result) { ?>

        <div class="title2">Expense Claim Table</div>

        <table id="mytable" cellspacing="0">
            <tr>
                <th scope="col"><center>No.</center></th>
            <th scope="col"><center>ARF Number</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Work Name</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Name Material</center></th>
            <th scope="col"><center>UoM</center></th>
            <th scope="col"><center>Qty</center></th>
            <th scope="col"><center>Unit Price</center></th>
            <th scope="col"><center>Total</center></th>
            </tr>
            <?php
            $totals = 0;

            for ($i = 0; $i < (count($this->result)); $i++) {
                if ($this->approve)
                    $total = $this->result[$i]['total'];
                else
                    $total = $this->result[$i]['totalPrice'];


                foreach ($this->result[$i] as $key => $val) {
                    if ($val == '')
                        $this->result[$i][$key] = "&nbsp;";
                }
                ?>
                <tr>
                    <th scope="row" class="spec"><?= ($i + 1) ?></th>
                    <td><a href="#" onclick="window.open('/default/report/arfdetail/popup/true/trano/<?= $this->result[$i]['arf_no'] ?>', 'mywin', 'toolbar=0');"><?= $this->result[$i]['arf_no'] ?></a></td>            
                    <td><?= $this->result[$i]['workid'] ?> </td>
                    <td><?= $this->result[$i]['workname'] ?> </td>
                    <td ><?php
                        if ($this->result[$i]['cfs_kode'] == '') {
                            echo "&nbsp;";
                        } else {
                            echo $this->result[$i]['cfs_kode'];
                        }
                        ?></td>
                    <td><?= $this->result[$i]['kode_brg'] ?> - <?= $this->result[$i]['nama_brg'] ?></td>
                    <td ><?= $this->result[$i]['uom'] ?></td>
                    <td align="right"><?= number_format($this->result[$i]['qty'],2) ?></td>

                    <td align="right"><?= $this->result[$i]['val_kode']== 'USD' ? number_format(floatval($this->result[$i]['price']),2) : number_format($this->result[$i]['price']) ?></td>

                    <td align="right"><?= $this->result[$i]['val_kode']== 'USD' ? number_format(floatval($total),2) : number_format($total) ?></td>
                </tr>

                <?php
                $totals += $total;
            }
            ?>
            <tr>
                <th scope="row" class="spec" colspan="8">Total</th>
                <td align="right"><?= $this->result[0]['val_kode']== 'USD' ? number_format(floatval($totals),2) : number_format($totals) ?></td>
            </tr>
        </table>
        <?php
    }

    if ($this->result2) {
        ?>

        <div class="title2">Amount Due To Company Table</div>

        <table id="mytable" cellspacing="0">
            <tr>
                <th scope="col"><center>No.</center></th>
            <th scope="col"><center>ARF Number</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Work Name</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Name Material</center></th>
            <th scope="col"><center>UoM</center></th>
            <th scope="col"><center>Qty</center></th>
            <th scope="col"><center>Unit Price</center></th>
            <th scope="col"><center>Total</center></th>
            </tr>
            <?php
            $totals2 = 0;

            for ($i = 0; $i < (count($this->result2)); $i++) {
                if ($this->approve)
                    $total2 = $this->result2[$i]['total'];
                else
                    $total2 = $this->result2[$i]['totalPrice'];


                foreach ($this->result2[$i] as $key => $val) {
                    if ($val == '')
                        $this->result2[$i][$key] = "&nbsp;";
                }
                ?>
                <tr>
                    <th scope="row" class="spec"><?= ($i + 1) ?></th>
                    <td><a href="#" onclick="window.open('/default/report/arfdetail/popup/true/trano/<?= $this->result2[$i]['arf_no'] ?>', 'mywin', 'toolbar=0');"><?= $this->result2[$i]['arf_no'] ?></a></td>
                    <td><?= $this->result2[$i]['workid'] ?> </td>
                    <td><?= $this->result2[$i]['workname'] ?> </td>
                    <td ><?php
                        if ($this->result[$i]['cfs_kode'] == '') {
                            echo "&nbsp;";
                        } else {
                            echo $this->result[$i]['cfs_kode'];
                        }
                        ?></td>
                    <td><?= $this->result2[$i]['kode_brg'] ?> - <?= $this->result2[$i]['nama_brg'] ?></td>
                    <td ><?= $this->result2[$i]['uom'] ?></td>
                    <td align="right"><?= number_format($this->result2[$i]['qty'],2) ?></td>

                    <td align="right"><?= $this->result2[$i]['val_kode']== 'USD' ? number_format(floatval($this->result2[$i]['price']),2) : number_format($this->result2[$i]['price']) ?></td>

                    <td align="right"><?= $this->result2[$i]['val_kode']== 'USD' ? number_format(floatval($total2),2) : number_format($total2) ?></td>
                </tr>

                <?php
                $totals2 += $total2;
            }
            ?>
            <tr>
                <th scope="row" class="spec" colspan="8">Total</th>
                <td align="right"><?= $this->result2[0]['val_kode']== 'USD' ? number_format(floatval($totals2),2) : number_format($totals2) ?></td>
            </tr>
        </table>
    <?php } ?>

    <?php
    if ($this->etc[0]['user_approval'] != '') {
        ?>
        <div class="all-approve">
            <b>Approval History</b></br>
            <ul>
                <?php
                foreach ($this->etc[0]['user_approval'] as $key => $val) {
                    ?>
                    <li><?php echo "<b>" . $val['approve'] . "</b> " . date('d-m-Y H:i:s', strtotime($val['date'])) . " : " . $val['displayname'] . " (" . $val['display_name'] . ")<br />Sign : " . $val['signature'] . "<br />Comment : " . $val['comment']; ?></li>
                    <?
                    }
                    ?>
                </ul>
            </div>
            <?php
        }
        ?>

    <div style="margin-top:15px; float:right;" id="wButton">

    </div>
