<link rel="stylesheet" type="text/css" href="/css/table.css"/>
<style type="text/css">
    .tooltip {
        border-bottom: 1px dotted #000000; color: #000000; outline: none;
        cursor: help; text-decoration: none;
        position: relative;
    }
    .tooltip span {
        margin-left: -999em;
        position: absolute;
    }
    .tooltip:hover span {
        border-radius: 5px 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px;
        box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1); -webkit-box-shadow: 5px 5px rgba(0, 0, 0, 0.1); -moz-box-shadow: 5px 5px rgba(0, 0, 0, 0.1);
        font-family: Calibri, Tahoma, Geneva, sans-serif;
        position: absolute; left: 1em; top: 2em; z-index: 99;
        margin-left: 0;
    }
    .tooltip:hover img {
        border: 0; margin: -10px 0 0 -55px;
        float: left; position: absolute;
    }
    .tooltip:hover em {
        font-family: Candara, Tahoma, Geneva, sans-serif; font-size: 1.2em; font-weight: bold;
        display: block; padding: 0.2em 0 0.6em 0;
    }
    .info { padding: 0.8em 1em; }
    .custom { padding: 0.5em 0.8em 0.8em 2em; }
    * html a:hover { background: transparent; }
    .info {background: #FFFFAA; border: 1px solid #FFAD33; }
</style>
<div class="body">

<br></br>
<table id="mytable" cellspacing="0">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Trano</center></th>
            <th scope="col"><center>NPK</center></th>
            <th scope="col"><center>Name</center></th>
            <th scope="col"><center>Project</center></th>
            <th scope="col"><center>Site</center></th>
            <th scope="col"><center>Start</center></th>
            <th scope="col"><center>End</center></th>
            <th scope="col"><center>Hour</center></th>
        </tr>
    	<?php
    		$totals = 0;
    		foreach($this->result as $key => $val)
            {
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($this->offset + ($no+1))?></th>
    		<td><?=$val['trano']?></td>
    		<td><?=$val['npk']?></td>
    		<td><?=$val['name']?></td>
    		<td><a class="tooltip" href="#"><?=$val['prj_kode']?><span class="info"><?=$val['prj_nama']?></span></a></td>
    		<td><a class="tooltip" href="#"><?=$val['sit_kode']?><span class="info"><?=$val['sit_nama']?></span></a></td>
    		<td><?=$val['start']?></td>
    		<td><?=$val['end']?></td>
    		<td align="right"><?=number_format(floatval($val['hour']))?></td>
    		</tr>
    	<?php
                $no++;
    		}

    	?>
</table>
<?=$this->paging($this->pageUrl,$this->totalResult,$this->limitPerPage,$this->current,$this->currentPage)?>

</div>