<link rel="stylesheet" type="text/css" href="/css/table.css"/>
<style>
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
	margin-bottom: 10px;
}
</style>

<div class="body">
<?php if ($this->name) { ?>
<div class="title">DETAIL TIMESHEET FOR <?=$this->name?></div>
<?php } ?>
<br></br>
<table id="mytable" cellspacing="0">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Trano</center></th>
            <th scope="col"><center>Project</center></th>
            <th scope="col"><center>Site</center></th>
            <th scope="col"><center>Start</center></th>
            <th scope="col"><center>End</center></th>
            <th scope="col"><center>Notes</center></th>
            <th scope="col"><center>On Behalf Of</center></th>
            <th scope="col"><center>Total Hour</center></th>
        </tr>
    	<?php
    		$totals = 0;
    		for ($i=0;$i<(count($this->result));$i++)
    		{
    			foreach ($this->result[$i] as $key => $val)
    			{
    				if ($val == '')
    					$this->result[$i][$key] = "&nbsp;";
    			}
                $totals += floatval($this->result[$i]['hour']);
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
    		<td><?=$this->result[$i]['trano']?></td>
    		<td><?=$this->result[$i]['prj_kode']?></td>
    		<td><?=$this->result[$i]['sit_kode']?></td>
    		<td><?=$this->result[$i]['start']?></td>
    		<td><?=$this->result[$i]['end']?></td>
            <td><?=$this->result[$i]['notes']?></td>
            <td><?=$this->result[$i]['behalfof']?></td>
    		<td align="right"><?=number_format(floatval($this->result[$i]['hour']))?></td>
    		</tr>
    	<?php

    		}

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="7">Grand Total</th>
    		<td align="right"><?=number_format($totals)?></td>
    	</tr>
</table>

</div>