<?php 
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}

?>
<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 740px;
    height: 460px;
    overflow: auto; 
    font-size: 14px;
}

.parentContainer2{
    font-size: 12px;
}

</style>

<table class="parentContainer2">
        <tr>
            <td>Project</td><td>:</td>
            <td><?=$this->result[0]['prj_kode'];?></td>
            <td><?=$this->result[0]['prj_nama'];?></td>
        </tr>
        <tr>
            <td>Site</td><td>:</td>
            <td><?=$this->result[0]['sit_kode'];?></td>
            <td><?=$this->result[0]['sit_nama'];?></td>
        </tr>
        <tr>
            <td>Trans No</td><td>:</td>
            <td><?=$this->result[0]['trano'];?></td>
        </tr>
        <tr>
            <td>Date</td><td>:</td>
            <td><?=$this->result[0]['tgl'];?></td>
        </tr>
</table>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
        <tr>
            <th scope="col"><center><b>No</b></center></th>
            <!--<th scope="col"><center><b>Trans No</b></center></th>
            <th scope="col"><center><b>Date</b></center></th>-->
            <th scope="col"><center><b>Work Id</b></center></th>
            <th scope="col"><center><b>Work Name</b></center></th>
            <th scope="col"><center><b>Product Id</b></center></th>
            <th scope="col"><center><b>Description</b></center></th>
            <th scope="col"><center><b>Qty</b></center></th>
            <th scope="col"><center><b>Transporter</b></center></th>
            <th scope="col"><center><b>Delivery From</b></center></th>
        </tr>
    </thead>
    <tbody>
        <?php
            for($i=0; $i<count($this->result); $i++)
            {
    	?>
    	<tr>
            <td><?=$i+1;?></td>
            <!--<td><?//=$this->result[$i]['trano'];?></td>
            <td><?//=$this->result[$i]['tgl'];?></td>-->
            <td><?=$this->result[$i]['workid'];?></td>
            <td><?=$this->result[$i]['workname'];?></td>
            <td><?=$this->result[$i]['kode_brg'];?></td>
            <td><?=$this->result[$i]['nama_brg'];?></td>
            <td align="right"><?=number_format($this->result[$i]['qty'],4);?></td>
            <td><?=$this->result[$i]['namatransporter'];?></td>
            <td><?=$this->result[$i]['deliveryfrom'];?></td>
        </tr>

        <?php        
            //$total = $this->result[$i]['total'];
            //$totalJumlah = $totalJumlah + $total;

            }
        ?>
       
    			<!--<tr style="background: #4C6891;">
                            <td colspan="8" style="color:#FFFFFF;" align="right">Total : </td>
                            <td colspan="1" style="color:#FFFFFF;"> --------> 
                         <!--   <td style="color:#FFFFFF;"><?//=number_format($totalJumlah,2)?></td>
                            <td style="color:#FFFFFF;"><?//=$this->result[0]['val_kode'];?></td>
    			</tr>-->
    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 1
	});
})();

</script>