<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<style>

.parentContainer { /* The parent container */
    margin: 6px;
    padding: 0px;
    border: none;
    width: 840px; /* Required to set */
    height: 420px; /* Required to set */
    overflow: auto; /* Required to set */
	font-size: 14px;
}

</style>
<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
    	<tr>
            <th scope="col" rowspan="2">No</th>
            <th scope="col" rowspan="2">No Trans PR</th>
            <th scope="col" rowspan="2">Work ID</th>
            <th scope="col" rowspan="2">Work Name</th>
            <th scope="col" rowspan="2">Product ID</th>
            <th scope="col" width="300" rowspan="2">Material Name</th>
            <th scope="col"   align="center">Qty PR</th>
            <th scope="col"   align="center">Qty PO</th>
            <th scope="col" align="center">Balance</th>
        </tr>

    </thead>
    <tbody>
    	<?php
    		foreach($this->result as $key => $val)
    		{
    	?>

    	<tr>
            <td><?=$j+1;?></td>
            <td><?=$this->result[$key]['trano'];?></td>
            <td><?=$this->result[$key]['workid'];?></td>
            <td><?=$this->result[$key]['workname'];?></td>
            <td><?=$this->result[$key]['kode_brg'];?></td>
            <td><?=$this->result[$key]['nama_brg'];?></td>
            <td align="right"><?=number_format($this->result[$key]['qtypr'],2);?></td>
            <td align="right"><?=number_format($this->result[$key]['qtypo'],2);?></td>
            <td align="right"><?=number_format($this->result[$key]['balance'],2);?></td>
        </tr>
        <?php 		$j++;

    		} ?>

    </tbody>
</table>
</div>
<script type="text/javascript">
//<![CDATA[

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 5,
		headerRows : 1
	});
})();

//]]>
</script>