<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 640px; 
    height: 420px; 
    overflow: auto; 
    font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
        <tr>
            <th scope="col" rowspan="2"><center><b>No</b></center></th>
            <th scope="col" rowspan="2"><center><b>Trans No</b></center></th>
            <th scope="col" colspan="2"><center><b>Total PO</b></center></th>
            <th scope="col" colspan="2"><center><b>Total RPI</b></center></th>
            <th scope="col" colspan="2"><center><b>Balance</b></center></th>
        </tr>
        <tr>
        	<th>IDR</th>
        	<th>USD</th>
        	<th>IDR</th>
        	<th>USD</th>
        	<th>IDR</th>
        	<th>USD</th>
        </tr>
    </thead>
    <tbody>
        <?php
        	$totalPOIDR = 0;
	        $totalPOUSD = 0;
	        $totalRPIIDR = 0;
	        $totalRPIUSD = 0;
	        $totalBalanceIDR = 0;
	        $totalBalanceUSD = 0;
        	$j = 0;
            foreach ($this->result as $i => $val)
            {
    	?>
    	<tr>
            <td><?=$j+1;?></td>
            <td><?=$this->result[$i]['po_no'];?></td>
            <td align="right"><?=number_format($this->result[$i]['totalPO_IDR']);?></td>
            <td align="right"><?=number_format($this->result[$i]['totalPO_USD']);?></td>
            <td align="right"><?=number_format($this->result[$i]['totalRPI_IDR']);?></td>
            <td align="right"><?=number_format($this->result[$i]['totalRPI_USD']);?></td>
            <td align="right"><?=number_format(($this->result[$i]['totalPO_IDR'] - $this->result[$i]['totalRPI_IDR']));?></td>
            <td align="right"><?=number_format(($this->result[$i]['totalPO_USD'] - $this->result[$i]['totalRPI_USD']));?></td>
            
        </tr>

        <?php
				$totalPOIDR += $this->result[$i]['totalPO_IDR'];
		        $totalPOUSD += $this->result[$i]['totalPO_USD'];
		        $totalRPIIDR += $this->result[$i]['totalRPI_IDR'];
		        $totalRPIUSD += $this->result[$i]['totalRPI_USD'];
		        $totalBalanceIDR += ($this->result[$i]['totalPO_IDR'] - $this->result[$i]['totalRPI_IDR']);
		        $totalBalanceUSD += ($this->result[$i]['totalPO_USD'] - $this->result[$i]['totalRPI_USD']);
		        $j++;
                }
        ?>       
    	<tr>
    	<td colspan="2"><b>Grand Total</b></td>
    	<td align="right"><b><?=number_format($totalPOIDR);?></b></td>
    	<td align="right"><b><?=number_format($totalPOUSD);?></b></td>
    	<td align="right"><b><?=number_format($totalRPIIDR);?></b></td>
    	<td align="right"><b><?=number_format($totalRPIUSD);?></b></td>
    	<td align="right"><b><?=number_format($totalBalanceIDR);?></b></td>
    	<td align="right"><b><?=number_format($totalBalanceUSD);?></b></td>
    	</tr>		
    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 2
	});
})();

</script>