<?php echo $this->printHeader(); ?>
<?php echo $this->webHeader(); ?>


<script type="text/javascript">

function showDrillDown(prjCode)
{
   var dForm =  new Ext.Window({
    id: 'drillChart' + prjCode,
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    width: 600,
    height: 500,
    items :
        [{
        xtype : 'fusion',
	mediaMask : {msg:'Loading Chart Object'},
	loadMask  : {msg:'Gathering Chart Data'},
	autoMask  : true,
	title: 'PieChart - Animate',
	chartURL: '/Charts/FCF_Bar2D.swf',
	dataURL: '/procurement/getChart/data/' + prjCode
        } ]
    });
    dForm.title = 'Drill Down Chart';
    dForm.show();
}

var windowForm2 = {
    xtype: 'tabpanel',
    id: 'charts-po-panel',
    activeTab: 0,
    region: 'center',
    items: [
        {
    title: 'Chart 1',
    layout: 'fit',
    id: 'risk1',

    items: [
        {
        xtype : 'fusion',
	mediaMask : {msg:'Loading Chart Object'},
	loadMask  : {msg:'Gathering Chart Data'},
	autoMask  : true,
	title: 'PO Chart',
	chartURL: '/Charts/FCF_Bar2D.swf',
	dataURL: '/procurement/getChart'
        }
//        new Ext.ux.Chart.Fusion.Panel({
//        id : 'chartpanel',
//        title : 'Chart',
//        collapsible : true,
//        renderTo : Ext.getBody(),
//
//        chartCfg :{ id : 'chart1'},
//        autoScroll : true,
//        mediaMask  : 'Loading Fusion Chart Object',
//       loadMask  : {msg:'Loading Chart Data...'},
//       autoMask  : true,
//       params    : { wmode       :'transparent' },
//
//        chartURL : '/Charts/FCF_Pie3D.swf',
//        dataURL : '/procurement/getChart',
//        width : 100,
//        height : 200,
//        listeners :{
//             chartload : function(p,obj){window.console && console.log('chart '+obj.id+' loaded.')},
//             chartrender : function(p,obj){window.console && console.log('chart '+obj.id+' rendered.')}
//        }
//     })
     ]} , {
     title: 'Chart 2',
    layout: 'fit',
    id: 'risk2',
    items: [
            {
        xtype : 'fusion',
	mediaMask : {msg:'Loading Chart Object'},
	loadMask  : {msg:'Gathering Chart Data'},
	autoMask  : true,
	title: 'PieChart - Animate',
	chartURL: '/Charts/FCF_Pie3D.swf',
	dataURL: '/procurement/getChart'
        } ] }

    ]

};

//var windowForm2 =  ({
//
//    title: 'Chart Procurement',
//    id: 'charts-po-panel',
//    layout: 'fit',
//    bodyStyle: 'padding:15px;',
//    minWidth: 300,
//    minHeight: 200,
//    loadMask: true,
//    items: [
//    	new Ext.ux.Chart.Fusion.Panel({
//        id : 'chartpanel',
//        title : 'Chart',
//        collapsible : true,
//        renderTo : Ext.getBody(),
//
//        chartCfg :{ id : 'chart1'},
//        autoScroll : true,
//        mediaMask  : 'Loading Fusion Chart Object',
//       loadMask  : {msg:'Loading Chart Data...'},
//       autoMask  : true,
//       params    : { wmode       :'transparent' },
//
//        chartURL : '/Charts/FCF_Pie3D.swf',
//        dataURL : '/procurement/getChart',
//        width : 100,
//        height : 200,
//        listeners :{
//             chartload : function(p,obj){window.console && console.log('chart '+obj.id+' loaded.')},
//             chartrender : function(p,obj){window.console && console.log('chart '+obj.id+' rendered.')}
//        }
//     }),
//     new Ext.ux.Chart.Fusion.Panel({
//        id : 'chartpanel2',
//        title : 'Chart',
//        collapsible : true,
//        renderTo : Ext.getBody(),
//
//        chartCfg :{ id : 'chart2'},
//        autoScroll : true,
//        mediaMask  : 'Loading Fusion Chart Object',
//       loadMask  : {msg:'Loading Chart Data...'},
//       autoMask  : true,
//       params    : { wmode       :'transparent' },
//
//        chartURL : '/Charts/FCF_Pie3D.swf',
//        dataURL : '/procurement/getChart',
//        width : 100,
//        height : 200,
//        listeners :{
//             chartload : function(p,obj){window.console && console.log('chart '+obj.id+' loaded.')},
//             chartrender : function(p,obj){window.console && console.log('chart '+obj.id+' rendered.')}
//        }
//     })
//
//            ]
//});

    </script>

<?php echo $this->specialHeader('procurement-chart'); ?>

<div style="display:none;">

 <div id="start-div">
            <div style="float:left; margin-right:5px;" ><img src="/images/qdc.gif" /></div>
            <div style="margin-left:100px;">
                <h2>Welcome!</h2>
                <p>This is QDC iPCC on web, current state : Development.</p>
            </div>
        </div>
    <!-- Form layouts -->

    <div id="charts-po-details">

    </div>
</div>
