<script type="text/javascript">
    Ext.onReady(function() {
        Ext.QuickTips.init();

        var showBSFTrano = function(){
            var win = new Ext.Window({
                title: 'Choose BSF Trano',
                height: 100,
                width: 300,
                modal: true,
                items: [
                    new Ext.form.FormPanel({
                        frame: true,
                        border: true,
                        items: [
                            {
                                xtype:'tranoselector',
                                fieldLabel:'BSF Number',
                                Tranotype: ['BSF'],
                                id:'trano_select',
                                Selectid: 'trano',
                                allowBlank:false,
                                width: 150,
                                callbackFunc: function(trano,itemType)
                                {
                                    Ext.Ajax.request({
                                        url: '/procurement/bt-request/cek-workflow',
                                        method:'POST',
                                        params: {
                                            trano: trano,
                                            item_type: itemType
                                        },
                                        success: function(result, request){
                                            var returnData = Ext.util.JSON.decode(result.responseText);
                                            if(returnData.success) {
                                                win.close();
                                                myPanel = Ext.getCmp('abs-budget-panel');
                                                myPanel.body.load({
                                                    url: '/procurement/bt-settlement/edit',
                                                    scripts : true,
                                                    params: {
                                                        trano: trano,
                                                        item_type: itemType
                                                    }
                                                });
                                            }
                                            else
                                            {
                                                Ext.Msg.alert("Error",returnData.msg);
                                                return false;
                                            }
                                        },
                                        failure:function( action){
                                            if(action.failureType == 'server'){
                                                obj = Ext.util.JSON.decode(action.response.responseText);
                                                Ext.Msg.alert('Error!', obj.errors.reason);
                                            }
                                        }
                                    });
                                }
                            }
                        ]
                    })
                ],
                buttons: [
                    {
                        text: 'Close',
                        handler: function()
                        {
                            win.close();
                        }
                    }
                ]
            },this);

            win.show();
        };

        var windowForm =  ({
            title: 'Bussiness Trip Settlement Form (BSF)',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                        items: [
                            {
                                id: 'erf_add_button',
                                text: 'Create BSF',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/action_paste.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/procurement/bt-settlement/add',
                                        scripts : true
                                    });
                                }
                            },
                            {
                                id: 'erf_edit_button',
                                text: 'Edit Existing BSF',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler: function()
                                {
                                   showBSFTrano();
                                }
                            },
                            {
                                id: 'brf_to_bsf_button',
                                text: 'BSF to BRF',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/procurement/bt-settlement/bsf-to-brf',
                                        scripts : true
                                    });
                                }
                            }

                        ]
                    }
                }
            ]
        });
        
//        function getExchangeRate()
//        {
//            Ext.Ajax.request({
//                url: '/default/valuta/getexchangerate/val_kode/USD',
//                method: 'POST',
//                success: function(result, request) {
//                    var returnData = Ext.util.JSON.decode(result.responseText);
//                    if (returnData.success) {
//                        if(returnData.rate == 0)
//                        {
//                            Ext.MessageBox.show({
//                                title: 'Error',
//                                msg: 'Please Call Accounting Staffs (Ext. 1101 - 1104). Ask Them to Input Current IDR Rate. Thank You.',
//                                buttons: Ext.MessageBox.OK,
//                                icon: Ext.MessageBox.ERROR,
//                                fn:function(){window.location='';}
//                            });
//                        }
//                    
//                        Ext.getCmp('rateidr').setValue(returnData.rate);
//                    }
//                }, 
//                failure: function(action) {
//                    if (action.failureType == 'server') {
//                        obj = Ext.util.JSON.decode(action.response.responseText);
//                        Ext.Msg.alert('Error!', obj.errors.reason);
//                    }
//                }
//            });
//        }
//        getExchangeRate();

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        showSubmenu('abs-budget-panel');
    });
</script>