<script type="text/javascript">

showCFS = function(){
    myPanel = Ext.getCmp('abs-budget-panel');
    userid = Ext.getCmp('userid').getValue();
    uid = Ext.getCmp('uid').getValue();

    if (userid == '')
    {
		Ext.MessageBox.show({
	           title: 'Error',
	           msg: 'Please Select User',
	           buttons: Ext.MessageBox.OK,
	           icon: Ext.MessageBox.ERROR
	       });
		 return false;
    }

    myPanel.body.load({
        url:'/admin/approval/showprocessdocument/userid/' + userid +'/uid/'+uid,
        scripts: true
    });
}

var windowForm =  ({

    title: 'Bypass Approval',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    minWidth: 300,
    minHeight: 200,
    loadMask: true,
    tbar:[
        {
            xtype: 'tbtext',
            text: 'User'
        }
        ,'-',
        {
            xtype: 'userselector',
            fieldLabel: 'Requester',
            ShowName: false,
            id: 'uid_requester',
            UserSelectid: 'requester',
            width: 200,
            projectCode: '',
            chainWithJob: true,
            jobTitleId: 'job_title',
        }
        ,'-',
        {
            xtype: 'textfield',
            fieldLabel: 'User ID',
            id: 'userid',
            name: 'userid',
            readOnly: true,
            hidden:true,
        },
        {
            xtype: 'textfield',
            fieldLabel: 'User Name',
            id: 'uid',
            name: 'uid',
            readOnly: true,
            hidden:true,
        }
        ,'-','-',
        {
            xtype: 'textfield',
            fieldLabel: 'Job Title',
            name: 'job_title',
            id: 'job_title',
            displayField: 'display_name',
            valueField: 'id_role',
            readOnly: true,
            hidden:true
        },
        {
            xtype: 'button',
            text: 'Show',
            width:70,
            id: 'show_budget',
            cls:"x-btn-text-icon" ,
            icon:"/images/icons/fam/control_rewind.png",
            handler:showCFS
        },
        
    ]
});

 viewPort = Ext.getCmp('viewport');
 centerRegionTab = viewPort.getComponent('content-panel');
 centerRegionTab.items.each(function(c){centerRegionTab.remove(c);})
 centerRegionTab.add(windowForm);
 panelBaru = Ext.getCmp('abs-budget-panel');
 centerRegionTab.layout.setActiveItem('abs-budget-panel');
</script>