<script type="text/javascript">

    function AppFormType(docsType, idDocs, params)
    {
        if (docsType == 'PR')
        {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apppr/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apppr/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
            });
        }

            if (docsType == 'PO')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apppo/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apppo/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'DOR')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/logistic/logistic/appdor/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                        url: '/logistic/logistic/appdor/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'ARF')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apparf/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apparf/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'ASF')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/appasf/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                        url: '/procurement/procurement/appasf/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'PMEAL')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apppmeal/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apppmeal/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'iLOV')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                    <?php if ($this->isType) { ?>
                        url: '/logistic/logistic/appilov/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                    <?php } else { ?>
                        url: '/logistic/logistic/appilov/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                    <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'iCAN')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/logistic/logistic/appican/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                        url: '/logistic/logistic/appican/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'iSUP')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/logistic/logistic/appisupp/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/logistic/logistic/appisupp/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'SUPP')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                    <?php if ($this->isType) { ?>
                        url: '/logistic/logistic/appsupp/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                    <?php } else { ?>
                        url: '/logistic/logistic/appsupp/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                    <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'AFE')
            {
                Ext.Ajax.request({
                    url: '/projectmanagement/afe/check-afe-switching',
                    method:'POST',
                    success: function(resp){
                    var returnData = Ext.util.JSON.decode(resp.responseText);
                    if (returnData.success)
                    {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            <?php if ($this->isType) { ?>
                                url: '/projectmanagement/afe/app-afe-idr-usd/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            <?php } else { ?>
                                    url: '/projectmanagement/afe/app-afe-idr-usd/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            <?php } ?>
                                scripts : true
                            });
                        }
                        else
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                            <?php if ($this->isType) { ?>
                                url: '/projectmanagement/afe/appafe/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            <?php } else { ?>
                                url: '/projectmanagement/afe/appafe/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            <?php } ?>
                                scripts : true
                            });
                        }
                    },
                    failure:function(action){
                    if (action.failureType == 'server'){
                    obj = Ext.util.JSON.decode(action.responseText);
                            Ext.Msg.alert('Error!', obj.errors.reason);
                    } else{
                    Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
                    }
                    },
                    params: {
                    workflow_id: idDocs
                    }
                });
            }
            else if (docsType == 'RPI')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apprpi/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apprpi/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'PBOQ3')
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                <?php if ($this->isType) { ?>
                    url: '/procurement/procurement/apppmeal/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } else { ?>
                    url: '/procurement/procurement/apppmeal/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                <?php } ?>
                    scripts : true
                });
            }
            else if (docsType == 'PRABOQ3')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/projectmanagement/budget/apppraboq/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/projectmanagement/budget/apppraboq/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'REM')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/appreimburs/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/appreimburs/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'PRO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/appprbudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/appprbudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ARFO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/apparfbudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/apparfbudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'POO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/apppobudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/apppobudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ASFO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/appasfbudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/appasfbudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'RPIO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/procurement/apprpibudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/procurement/apprpibudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'TSHEET')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/projectmanagement/timesheet/apptimesheet/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/projectmanagement/timesheet/apptimesheet/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'PRABOQ2')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/projectmanagement/budget/apppraco/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/projectmanagement/budget/apppraco/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'PRAOHP')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/humanresource/humanresource/appohp/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/humanresource/humanresource/appohp/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'PRABGO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/projectmanagement/budget/apptemporaryohbudget/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/projectmanagement/budget/apptemporaryohbudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ARF_REVISI')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/arfrevisi/apparfrevisi/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/arfrevisi/apparfrevisi/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ARF_REVISI_OH')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/arfrevisi/apparfrevisioh/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/arfrevisi/apparfrevisioh/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ARF_REVISI_S')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/arfrevisi/apparfrevisisales/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/arfrevisi/apparfrevisisales/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'RINV')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/finance/invoice/apprequestinvoice/type/<?php echo $this->type; ?>/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/finance/invoice/apprequestinvoice/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'PRACO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/sales/sales/appco/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/sales/sales/appco/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'APRACO')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/sales/sales/appaddco/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/sales/sales/appaddco/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'ARFP')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/arf-pulsa/type/<?php echo $this->type; ?>/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/arf-pulsa/app-arf-pulsa/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    params: {
                    params: params
                    },
                            scripts : true
                    });
            }
            else if (docsType == 'ASFP')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/asf-pulsa/type/<?php echo $this->type; ?>/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/asf-pulsa/app-asf-pulsa/approve/' + idDocs  + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    params: {
                    params: params
                    },
                            scripts : true
                    });
            }
            else if (docsType == 'BRF' || docsType == 'BRFP')
            {
            var myPanel = Ext.getCmp('abs-budget-panel'), payment = '';
                    if (docsType == 'BRFP')
                    payment = '/payment/true';
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/procurement/bt-request/app/type/<?php echo $this->type; ?>/approve/' + idDocs + payment + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/procurement/bt-request/app/approve/' + idDocs + payment + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'BSF')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/procurement/bt-settlement/app/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'IA')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/logistic/inventory/app-inventory-adjustment/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'PPNREM')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/finance/ppn/app-ppn-rem/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'PPNSET')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/finance/ppn/app-ppn-rem-settle/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'OCA')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/finance/charging/app-charging/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'CRPI')
            {
            myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
<?php if ($this->isType) { ?>
                        url: '/finance/cancelrpi/appcancelrpi/type/<?php echo $this->type; ?>/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } else { ?>
                        url: '/finance/cancelrpi/appcancelrpi/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
<?php } ?>
                    scripts : true
                    });
            }
            else if (docsType == 'UHB')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/logistic/logisticbarang/appupdatebarang/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }
            else if (docsType == 'TBOQ')
            {
            var myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/sales/sales/apptransferbudget/approve/' + idDocs + '/userid/'+<?php echo $this->userId; ?>,
                            scripts : true
                    });
            }

            }

    function gotoAppForm(idDocs, params)
            {
            if (idDocs == undefined)
                    return false;
                    Ext.Ajax.request({
                    results: 0,
                            url: '/default/home/getdocumenttype/id/' + idDocs,
                            method:'POST',
                            success: function(result, request){
                            var returnData = Ext.util.JSON.decode(result.responseText);
                                    if (returnData.success) {
                            AppFormType(returnData.docs.name, idDocs, params);
                            }
                            },
                            failure:function(action){
                            if (action.failureType == 'server'){
                            obj = Ext.util.JSON.decode(action.response.responseText);
                                    Ext.Msg.alert('Error!', obj.errors.reason);
                            }
                            }
                    });
                    }

    function gotoAppTsheet(uid)
            {
            if (uid == undefined)
                    return false;
                    myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/projectmanagement/timesheet/apptimesheetall/uid/' + uid,
                            scripts: true
                    });
                    }

    Ext.onReady(function(){

    var proxy = new Ext.data.HttpProxy({
    url : '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>'
    });
            var reader = new Ext.data.JsonReader({
            idProperty: 'id',
                    totalProperty: 'count',
                    root : 'posts'},
                    [
                    {name: 'id'},
                    {name: 'item_id'},
                    {name: 'caption_id'},
                    {name: 'type'},
                    {name: 'date', type: 'date', dateFormat: 'Y-m-d H:i:s'},
                    {name: 'username_prev'},
                    {name: 'user_next'},
                    {name: 'uid'},
                    {name: 'comment'},
                    {name: 'reject'},
                    {name: 'approve'},
                    {name: 'prj_kode'},
                    {name: 'is_bt'},
                    {name: 'params'},
                    {name: 'isPA'}
                    ]
                    );
            var store = new Ext.data.Store({
            reader: reader,
                    proxy: proxy
            });
            searchDocument2 = function(field, e){

//        var txttext = txttext.getValue();

            if (e.button == 12)
            {
            var docs = Ext.getCmp('document-text').getValue();
<?php if ($this - isType) { ?>
                var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/<?php echo $this->type; ?>/id/' + docs;
                        //store.proxy.setUrl(newUrl);
<?php } else { ?>
                var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/id/' + docs;
                        //store.proxy.setUrl(newUrl);
<?php } ?>
            //    	Ext.getCmp('user-grids').getStore().reload();
            Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            }



            };
            searchDocumentType2 = function(){
            var docs = Ext.getCmp('combo-type').getRawValue();
                    var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/' + docs;
//    	store.proxy.setUrl('/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/' + docs);
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            };
            searchDocument = function(){
            var docs = Ext.getCmp('document-text').getValue();
<?php if ($this - isType) { ?>
                var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/<?php echo $this->type; ?>/id/' + docs;
                        //store.proxy.setUrl(newUrl);
<?php } else { ?>
                var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/id/' + docs;
                        //store.proxy.setUrl(newUrl);
<?php } ?>
//    	Ext.getCmp('user-grids').getStore().reload();
            Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            };
            searchDocumentType = function(){
            var docs = Ext.getCmp('combo-type').getRawValue();
                    var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/' + docs;
//    	store.proxy.setUrl('/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/' + docs);
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            };
            searchDocumentProject = function(){
            var prj = Ext.getCmp('prj_kode').getValue();
                    var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/prj_kode/' + prj;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            };
            refreshAll = function(){
            Ext.getCmp('prj_kode').setValue('');
                    Ext.getCmp('combo-type').setValue('');
                    Ext.getCmp('combo-type').setRawValue('');
                    Ext.getCmp('document-text').setValue('');
                    var newUrl = '/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>';
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.api.read['url'] = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.url = newUrl;
                    Ext.getCmp('user-grids').getBottomToolbar().store.proxy.setUrl(newUrl);
                    Ext.getCmp('user-grids').getBottomToolbar().moveFirst();
                    Ext.getCmp('user-grids').getView().refresh();
            };
            var grid = new Ext.grid.GridPanel({
            store: store,
                    id: 'user-grids',
                    stateful: false,
                    loadMask: true,
<?php if ($this->isType) { ?>
                title: 'Verify & Approval',
<?php } else { ?>
                title: 'My Process Document',
<?php } ?>
            columns: [
                    new Ext.grid.RowNumberer(),
            {header: "", width: 70, dataIndex: 'item_id', renderer: function (v, p, r) {
            var bt = '';
                    var imageDocs = '<img src="/images/file_doc.png">';
                    if (r.data['isPA'] != true)
            {
            if (r.data['is_bt'])
            {
            p.attr = 'ext:qtip="This Document has Business Trip items."';
                    var bt = "&nbsp;<img src='/images/folder_public.png'>";
            }
            }

            return imageDocs + bt;
            }},
            {header: "Trano", width: 130, sortable: true, dataIndex: 'item_id', renderer: function(v, p, r){
            if (r.get("caption_id"))
            {
            return r.get("caption_id");
            }
            else
                    return v;
            }},
            {header: "Project", width: 80, sortable: true, dataIndex: 'prj_kode'},
            {header: "From", width: 170, sortable: true, dataIndex: 'username_prev'},
            {header: "Date", width: 120, sortable: true, dataIndex: 'date', renderer: Ext.util.Format.dateRenderer('d/m/Y H:i:s')},
            {header: "Status", width: 100, sortable: true, dataIndex: 'approve'},
            {header: "Comment", width: 300, sortable: true, dataIndex: 'comment'}
    ],
                    view: new Ext.grid.GridView({
                    enableRowBody:true
                            , getRowClass:function(record, rowIndex, p, store) {
                            var reject = record.get('reject');
                                    if (reject)
                                    return 'x-grid3-row-with-body3';
                            }

                    }),
                    frame:true,
                    height: 400,
                    layout: 'fit',
                    renderTo: 'grids',
                    loadMask: true,
                    bbar: new Ext.PagingToolbar({
                    id: 'paging',
                            pageSize: 100,
                            store: store,
                            displayInfo: true,
                            displayMsg: 'Displaying data {0} - {1} of {2}',
                            emptyMsg: "No data to display"
                    }),
                    tbar: [
                    {
                    text: 'Trano',
                            xtype:'label',
                            style: 'margin-right: 5px'
                    },
                    {
                    xtype: 'textfield',
                            id: 'document-text',
                            enableKeyEvents:true,
                            listeners:{
                            'keypress': function (field, e)
                            {searchDocument2(field, e)}
                            }
                    },
                    {
                    text: 'Search',
                            iconCls: 'search-icon',
                            handler: searchDocument,
                            scope: this
                    },
                            '-',
                    {
                    text: 'Document Type',
                            id: 'label-doc-type',
                            xtype:'label',
                            style: 'margin-right: 5px'
                    },
                    {
                    id: 'combo-type',
                            name: 'workflow_item_type_id',
                            hiddenName : 'workflow_item_type_id',
                            width: 100,
                            editable:false,
                            xtype: 'combo',
                            triggerAction: 'all',
                            mode: 'remote',
                            displayField: 'name',
                            valueField: 'workflow_item_type_id',
                            store: new Ext.data.JsonStore({
//		                 autoLoad: true,
                            url: '/admin/workflow/listworkflowitemtype/from/showprocessdocument',
                                    root: 'posts',
                                    fields:[
                                    { name: "name"}, { name: "workflow_item_type_id"}
                                    ]
                            }),
                            listeners:{
                            select:function ()
                            {
                            searchDocumentType2();
                            }
                            }
                    },
                    {
                    text: 'Search',
                            id: 'search-doc-type',
                            iconCls: 'search-icon',
                            handler: searchDocumentType,
                            scope: this
                    }, '-',
                    {
                    xtype: 'label',
                            text: 'Project',
                            style: 'margin-right:5px'
                    },
                    {
                    xtype: 'projectselector',
                            anchor: '100%',
                            id: 'project-select',
                            Selectid: 'prj_kode',
                            ShowName: false,
                            showAll: true
                    },
                            '-',
                    {
                    text: 'Search',
                            iconCls: 'search-icon',
                            handler: searchDocumentProject,
                            scope: this
                    }, '-',
                    {
                    text: 'Reset All',
                            iconCls: 'silk-table-refresh',
                            handler: refreshAll,
                            scope: this
                    }
                    ]
            });
            grid.on('rowclick', function(t, row, e){

            var r = grid.getStore().getAt(row);
                    if (r.data['isPA'] != true)
            {
            var params = r.data['params'];
                    if (params != undefined)
            {
            params = Ext.util.JSON.encode(params);
            }
            if (r.data['type'] != 'TSHEET')
            {
            gotoAppForm(r.data['id'], params);
            }
            else
            {
            if (r.data['approve'] != 'REJECTED')
                    gotoAppTsheet(r.data['uid']);
                    else
                    gotoAppForm(r.data['id'], params);
            }
            }
            });
<?php if ($this->isType) { ?>


        store.proxy.setUrl('/default/home/documenttoprocessnew/userid/<?php echo $this->userId; ?>/type/<?php echo $this->type; ?>');
                Ext.getCmp('user-grids').getStore().reload();
                Ext.getCmp('user-grids').getView().refresh();
                Ext.getCmp('combo-type').setVisible(false);
                Ext.getCmp('label-doc-type').setVisible(false);
                Ext.getCmp('search-doc-type').setVisible(false);
<?php } else { ?>

        store.load();
<?php } ?>

    });


</script>

<div id="grids"></div>