<script type="text/javascript">

Ext.onReady (function(){

    Ext.QuickTips.init();

    var windowForm = ({

        title:'Payment',
        id:'abs-budget-panel',
        layout: 'fit',
        bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
        bodyStyle: 'padding:15px;',
        loadMask: true,
        minWidth: 300,
        minHeight: 200,
        tbar:[{
            xtype:'tbbutton',
            text:'Select Action',
            iconCls:'menu-drop',
            menu:{
                items:[
                    {
                        text:'Payment RPI',
                        id:'finance-payment-rpi',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/paymentvoucherrpi',
                                scripts : true
                            });
                        }
                    },
//                    {
//                        text:'Edit Payment RPI',
//                        id:'finance-edit-payment-rpi',
//                        cls:"x-btn-text-icon" ,
//                        icon:"/images/icons/fam/action_paste.gif",
//                        handler:function ()
//                        {
//                            var bForm =  new Ext.Window({
//                                layout:'fit',
//                                width: 300,
//                                height: 100,
//                                style: 'margin-top: 10px',
//                                labelAlign: 'right',
//                                stateful: false,
//                                modal: true,
//                                resizable: false,
//                                items: [
//                                    new Ext.FormPanel({
//                                        frame: true,
//                                        items: [
//                                            {
//                                                xtype: 'bpvselector',
//                                                id: 'bpv_trano',
//                                                Selectid: 'bpv_trano_text',
//                                                bpvType: 'RPI',
//                                                fieldLabel: 'BPV Trano'
//                                            }
//                                        ]
//                                    })
//                                ],
//                                buttons: [
//                                    {
//                                        text: 'Edit',
//                                        handler: function(){
//                                            var trano = Ext.getCmp('bpv_trano_text').getValue();
//                                            if (trano == undefined || trano == '')
//                                            {
//                                                return false;
//                                            }
//                                            myPanel = Ext.getCmp('abs-budget-panel');
//                                            myPanel.body.load({
//                                                url: '/finance/payment/editpaymentvoucherrpi',
//                                                params: {
//                                                    trano: trano
//                                                },
//                                                scripts : true
//                                            });
//                                            bForm.close();
//                                        }
//                                    },
//                                    {
//                                        text: 'Cancel',
//                                        handler: function(){
//                                            bForm.close();
//                                        }
//                                    }
//                                ]
//                            });
//
//                            bForm.show();
//                        }
//                    },
                    '-',

                    {
                        text:'Payment ARF',
                        id:'finance-payment-arf',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/paymentvoucherarf',
                                scripts : true
                            });
                        }
                    },
                    '-',
                    {
                        text:'Payment REM',
                        id:'finance-payment-rem',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/paymentreimbursement/paymentvoucherrem',
                                scripts : true
                            });
                        }
                    },
                    '-',
                    {
                        text:'Payment PPN REM',
                        id:'finance-payment-ppnrem',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/payment-ppn-rem',
                                scripts : true
                            });
                        }
                    },
                    '-',
                    {
                        text:'Payment BRF',
                        id:'finance-payment-brf',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/paymentvoucherbrf',
                                scripts : true
                            });
                        }
                    },'-',
                    {
                        text:'Payment BRFP',
                        id:'finance-payment-brfp',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/paymentvoucherbrfp',
                                scripts : true
                            });
                        }
                    },'-',
                    {
                        text:'Payment PO',
                        id:'finance-payment-po',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function ()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/payment/paymentpo',
                                scripts : true
                            });
                        }
                    }
                ]
            }
        }]

    })
    
        function getExchangeRate()
        {
            Ext.Ajax.request({
                url: '/default/valuta/getexchangerate/val_kode/USD',
                method: 'POST',
                success: function(result, request) {
                    var returnData = Ext.util.JSON.decode(result.responseText);
                    if (returnData.success) {
                        if(returnData.rate == 0)
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Please Input Current IDR Rate. Thank You.',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR,
                                fn:function(){window.location='';}
                            });
                        }
                    
                        Ext.getCmp('rateidr').setValue(returnData.rate);
                    }
                },
                failure: function(action) {
                    if (action.failureType == 'server') {
                        obj = Ext.util.JSON.decode(action.response.responseText);
                        Ext.Msg.alert('Error!', obj.errors.reason);
                    }
                }
            });
        }
        getExchangeRate();

    viewPort = Ext.getCmp('viewport');

    centerRegionTab = viewPort.getComponent('content-panel');
    centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
    centerRegionTab.add(windowForm);
    panelBaru = Ext.getCmp('abs-budget-panel');
    centerRegionTab.layout.setActiveItem('abs-budget-panel');
    showSubmenu('abs-budget-panel');

})


</script>