<script type="text/javascript">

    var paymentType = '';
    var tempExchange, tempOri = 0;
    var payment_valuta = null;
    function getExchangeRate()
    {
        Ext.Ajax.request({
            url: '/default/valuta/getexchangerate',
            method: 'POST',
            success: function(result, request) {
                var returnData = Ext.util.JSON.decode(result.responseText);
                if (returnData.success) {
                    Ext.getCmp('val_rate_text').setValue(returnData.rate);
                    tempOri = returnData.rate;
                }
            }
            , failure: function(action) {
                if (action.failureType == 'server') {
                    obj = Ext.util.JSON.decode(action.response.responseText);
                    Ext.Msg.alert('Error!', obj.errors.reason);
                }
            }
        });
    }

    Ext.onReady(function() {

        Ext.QuickTips.init();
        Ext.apply(Ext.form.VTypes, {
            numericText: "Only numbers are allowed.",
            numericMask: /[0-9]/,
            numericRe: /(^-?dd*.d*$)|(^-?dd*$)|(^-?.dd*$)/,
            numeric: function(v) {
                return function() {
                    return this.numericRe.test(v)
                };
            }
        });
        var type = 'RPI',
                tempTotalpayment = 0,
                tempTotalequivalent = 0,
                paymentIDR = false
                ;
        /*Sembunyikan Dulu Karena Belum Final
         * var gridEbanking = new Ext.ux.grid.gridEbanking({
            height: 300,
            autoWidth: true,
            id: 'grid-ebanking',
            renderTo: 'gridEbanking',
            disableNewTrano: false
        });*/
        
        function cekCoaBank()
        {
            Ext.Ajax.request({
                url: '/finance/coa/getcoabanktype',
                method: 'POST',
                params: {
                    type: Ext.getCmp('trans').getValue()
                },
                success: function(result, request) {
                    var returnData = Ext.util.JSON.decode(result.responseText);
                    if (returnData.success) {
                        payment_valuta = returnData.data.valuta;
                    }
                },
                failure: function(action) {
                    if (action.failureType == 'server') {
                        obj = Ext.util.JSON.decode(action.response.responseText);
                        Ext.Msg.alert('Error!', obj.errors.reason);
                    }
                }
            });
        }

        function resetFormPayment() {
            Ext.getCmp('rpi_voucher_payment').getForm().reset();
            store_payment.removeAll();
            paymentIDR = false
            recordBPV = null;
            payment_valuta = null;
            if (tempExchange != tempOri)
                Ext.getCmp('val_rate_text').setValue(tempExchange);
        }

        function balancesum()
        {
            var totalval = parseFloat(Ext.getCmp('voc-val').getValue().toString().replace(/\$|\,/g, ''));
            var totalpaid = parseFloat(Ext.getCmp('voc-paid').getValue().toString().replace(/\$|\,/g, ''));
            var totalmaterai = parseFloat(Ext.getCmp('voc-materai').getValue().toString().replace(/\$|\,/g, ''));
            var balance = (totalval) - totalpaid;
            Ext.getCmp('voc-balan').setValue(balance);
            Ext.getCmp('pay-value').setValue(balance);
        }

        function hitungTotalKonversiGrid()
        {
            if (!payment_valuta)
                return false;
            if (Ext.getCmp('valuta-1').getValue() != payment_valuta) {
                newrate = Ext.getCmp('val_rate_text').getOriginalValue();
                store_payment.each(function(stores) {
                    stores.data['total_payment_konversi'] = parseFloat(stores.data['total_payment']) * parseFloat(newrate);
                });
                grid_payment.getView().refresh();
            }
        }

        function setpayment(trano)
        {
            Ext.Ajax.request({
                url: '/finance/payment/getpayment/trano/' + trano,
                method: 'POST',
                success: function(result, request)
                {
                    var returndata = Ext.util.JSON.decode(result.responseText);
                    Ext.getCmp('voc-val').setValue(returndata.gtotal);
                    Ext.getCmp('voc-paid').setValue(returndata.paid);
                    Ext.getCmp('valuta-1').setValue(returndata.voc_data[0].valuta);
                    Ext.getCmp('valuta-2').setValue(returndata.voc_data[0].valuta);
                    Ext.getCmp('valuta-3').setValue(returndata.voc_data[0].valuta);
                    Ext.getCmp('valuta-4').setValue(returndata.voc_data[0].valuta);
                    Ext.getCmp('val_kode_text').setValue(returndata.voc_data[0].valuta);
                    Ext.getCmp('currency-select').setRate(returndata.voc_data[0].valuta, hitungTotalKonversiGrid);
                    if (returndata.materai == true)
                        Ext.getCmp('voc-materai').setValue(returndata.total_materai);
                    else
                        Ext.getCmp('voc-materai').setValue(0);
                    if (returndata.voc_data[0].valuta != 'IDR')
                        Ext.getCmp('payment-idr').show();
                    balancesum();


                },
                failure: function(action)
                {
                    if (action.failureType == 'server')
                    {
                        obj = Ext.util.JSON.decode(action.response.responseText);
                        Ext.Msg.alert(('Error!'), obj.errors.reason);
                    }
                }
            })
        }

        function showpaymenthistory()
        {
            var storehistory = new Ext.data.Store({
                url: '/finance/payment/getpaymenthistory/trano/' + Ext.getCmp('voc-number').getValue(),
                autoLoad: true,
                reader: new Ext.data.JsonReader({
                    root: 'data',
                    totalProperty: 'total',
                    fields: [{
                            name: 'trano'
                        }, {
                            name: 'tgl',
                            type: 'date',
                            format: 'd M Y H:i:s'
                        }, {
                            name: 'val_kode'
                        }, {
                            name: 'total_bayar'
                        }, {
                            name: 'username'
                        }]
                })
            })

            var gridhistory = new Ext.grid.GridPanel({
                store: storehistory,
                height: 300,
                width: 600,
                viewConfig: {
                    forceFit: true
                },
                columns: [{
                        header: 'Payment Number',
                        dataIndex: 'trano',
                        sortable: true
                    }, {
                        header: 'Date',
                        dataIndex: 'tgl',
                        width: 120,
                        sortable: true
                    }, {
                        header: 'Total Payment',
                        dataIndex: 'total_bayar',
                        width: 150,
                        sortable: true,
                        renderer: function(v, p, r) {
                            return v ? r.data['val_kode'] + ' ' + Ext.util.Format.number(v, '0,0.00') : '';
                        },
                        align: 'right'
                    }, {
                        header: 'Username',
                        dataIndex: 'username',
                        width: 120,
                        sortable: true
                    }], bbar: new Ext.PagingToolbar({
                    id: 'paging-history',
                    pageSize: 20,
                    store: storehistory,
                    displayInfo: true,
                    displayMsg: 'Displaying data {0} - {1} of {2}',
                    emptyMsg: "No data to display"
                })
            })

            var windowhistory = new Ext.Window({
                title: 'Payment History for ' + Ext.getCmp('voc-number').getValue(),
                id: 'payment-history-window',
                layout: 'absolute',
                minHeight: 200,
                stateful: false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 612,
                height: 330,
                loadMask: true,
                items: [
                    gridhistory
                ],
                buttons: [
                    {
                        text: 'Close',
                        handler: function() {
                            windowhistory.close();
                        }
                    }
                ]
            })

            windowhistory.show();
        }

        var recordBPV = null;
        function showrpivoucherpayment()
        {
            var filterBPV = function(searchTxt) {
                var option = Ext.getCmp('option').getValue(),
                        option_type = Ext.getCmp('option_type').getValue(),
                        search = Ext.getCmp('search').getValue();
                var type = 'RPI';
                storevoucher.proxy.setUrl('/finance/payment/getvoucher/search/' + search + '/option/' + option + '/type/' + type + '/option_type/' + option_type);
                storevoucher.reload();
                gridvoucher.getView().refresh();
            };
            var storevoucher = new Ext.data.Store({
                url: '/finance/payment/getvoucher/type/<?= $this->type ?>',
                autoLoad: true,
                reader: new Ext.data.JsonReader({
                    root: 'data',
                    totalProperty: 'total',
                    fields: [{
                            name: 'trano'
                        }, {
                            name: 'tgl'
                        }, {
                            name: 'item_type'
                        }, {
                            name: 'prj_kode'
                        }, {
                            name: 'valuta'
                        }, {
                            name: 'bpv_type'
                        }, {
                            name: 'ref_number'
                        }]
                })
            })

            var gridvoucher = new Ext.grid.GridPanel({
                store: storevoucher,
                height: 300,
                width: 600,
                viewConfig: {
                    forceFit: true
                },
                columns: [{
                        header: 'Trano',
                        dataIndex: 'trano',
                        sortable: true
                    }, {
                        header: 'Date',
                        dataIndex: 'tgl',
                        width: 120,
                        sortable: true
                    }, {
                        header: 'Type',
                        dataIndex: 'item_type',
                        sortable: true
                    }, {
                        header: 'Project Code',
                        dataIndex: 'prj_kode',
                        sortable: true
                    }, {
                        header: 'Type',
                        dataIndex: 'bpv_type',
                        sortable: true
                    }], bbar: new Ext.PagingToolbar({
                    id: 'paging-rpi',
                    pageSize: 20,
                    store: storevoucher,
                    displayInfo: true,
                    displayMsg: 'Displaying data {0} - {1} of {2}',
                    emptyMsg: "No data to display"
                }), tbar: [
                    {
                        text: 'Type',
                        xtype: 'label',
                        style: 'margin-left:5px'
                    },
                    '-',
                    {
                        xtype: 'combo',
                        id: 'option_type',
                        width: 100,
                        store: new Ext.data.SimpleStore({
                            fields: ['nilai', 'name'],
                            data: [
                                ['ALL', 'ALL'],
                                ['RPI', 'RPI'],
                                ['PPN', 'PPN'],
                                ['WHT', 'With Holding Tax']
                            ]
                        }),
                        valueField: 'nilai',
                        displayField: 'name',
                        typeAhead: true,
                        forceSelection: true,
                        editable: false,
                        mode: 'local',
                        triggerAction: 'all',
                        selectOnFocus: true,
                        value: 'ALL',
                        listeners: {
                            'select': function() {
                                filterBPV();
                            }
                        }
                    }, '-',
                    {
                        text: 'Search By',
                        xtype: 'label',
                        style: 'margin-left:5px'
                    }, '-',
                    {
                        xtype: 'combo',
                        id: 'option',
                        width: 120,
                        store: new Ext.data.SimpleStore({
                            fields: ['nilai', 'name'],
                            data: [
                                ['trano', 'BPV Trano'],
                                ['ref_number', 'RPI Trano'],
                                ['prj_kode', 'Project Code']
                            ]
                        }),
                        valueField: 'nilai',
                        displayField: 'name',
                        typeAhead: true,
                        forceSelection: true,
                        editable: false,
                        mode: 'local',
                        triggerAction: 'all',
                        selectOnFocus: true,
                        value: 'trano',
                        listeners: {
                            'select': function() {
                                filterBPV();
                            }
                        }
                    }, '-', {
                        xtype: 'textfield',
                        id: 'search',
                        enableKeyEvents: true,
                        listeners: {
                            'keyup': function(txttext, event)
                            {
                                var txttext = txttext.getValue();
                                if (txttext != "" && txttext.toString().length >= 3)
                                {
                                    filterBPV();
                                }
                            }
                        }
                    }
                ],
                listeners: {
                    'rowclick': function(gridaktif, rowIndex, e)
                    {
                        isDbClick = true;
                        var voucher = gridaktif.getStore().getAt(rowIndex);
                        recordBPV = voucher;
                        var trano = voucher.get('trano');
                        Ext.getCmp('voc-number').setValue(trano);
                        store_payment.proxy.setUrl('/finance/payment/getvoucherlistdetail/type/<?= $this->type ?>/trano/' + trano);
                        store_payment.load();
                        Ext.getCmp('grid-payment').getView().refresh();
                        var gridstore = Ext.getCmp('grid-payment').getStore();
                        setpayment(trano);
                        windowvoucher.close();
                    }
                }

            })

            var windowvoucher = new Ext.Window({
                title: 'Choose Bank Payment Voucher',
                id: 'choose-bank-payment-voucher',
                layout: 'absolute',
                minHeight: 200,
                stateful: false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 612,
                height: 330,
                loadMask: true,
                items: [
                    gridvoucher
                ]
            })

            windowvoucher.show();
        }

        var proxy = new Ext.data.HttpProxy({
            url: 'what ever'
        });
        var record = new Ext.data.Record.create([
            {name: 'ref_number'},
            {name: 'prj_kode'},
            {name: 'sit_kode'},
            {name: 'coa_kode'},
            {name: 'total_bayar'},
            {name: 'total_payment'},
            {name: 'total_paid'},
            {name: 'total_bayar_konversi'},
            {name: 'total_payment_konversi'},
            {name: 'statusppn'},
            {name: 'holding_tax_status'},
            {name: 'holding_tax'},
            {name: 'total'},
            {name: 'valuta'},
            {name: 'valuta_konversi'},
            {name: 'kode_brg'},
            {name: 'workid'}
        ])

        var store_payment = new Ext.data.Store({
            proxy: proxy,
            id: 'store-payment',
            reader: new Ext.data.JsonReader({
                root: 'data',
                totalProperty: 'total',
                fields: record
            })
        })

        var editor = new Ext.ux.grid.RowEditor({
            saveText: 'Save',
            clicksToEdit: 1,
            listeners: {
                'canceledit': function(ed, close) {
                    ed.record.cancelEdit();
                },
                'afteredit': function(ed, obj, rec, index) {
                    var recs = store_payment.getAt(index);
                    var total = parseFloat(recs.data['total']);
                    var rateidr = parseFloat(Ext.getCmp('val_rate_text').getOriginalValue().toString().replace(/\$|\,/g, ''));
                    var totalPayment = parseFloat(recs.data['total_payment']);
                    var totalPaid = parseFloat(recs.data['total_paid']) + totalPayment;
                    var totalEquivalent = parseFloat(recs.data['total_payment_konversi']);
                    var totalPaymentKonversi = parseFloat(rateidr * totalPayment);
                    if (totalPaid > total)
                    {
                        Ext.Msg.alert('Error', 'Total Payment is greater than Total Voucher');
                        store_payment.rejectChanges();
                        return false;
                    }

                    if (recs.data['valuta'] == 'USD')
                    {
                        recs.data['total_payment_konversi'] = totalPaymentKonversi;
                        recs.data['total_payment_konversi'] = totalPaymentKonversi;
                        if (totalEquivalent == null) {
                            Ext.Msg.alert('Error', 'Total Equivalent field is required');
                            store_payment.rejectChanges();
                            return false;
                        }
                        if (totalEquivalent != 0) {
                            if (totalEquivalent.toFixed(2) != totalPaymentKonversi.toFixed(2)) {
                                Ext.Msg.alert('Error', 'Total Equivalent is greater than Total Voucher');
                                store_payment.rejectChanges();
                                return false;
                            }
                        }

                        if (totalEquivalent == 0) {
                            paymentIDR = false;
                        }

                    }



                    ed.record.commit(); //Commit changes into store

                    var tot = 0;
                    store_payment.each(function(stores) {
                        tot += parseFloat(stores.data['total_payment']);
                    });
                    var totalmaterai = parseFloat(Ext.getCmp('voc-materai').getValue().toString().replace(/\$|\,/g, ''));
                    Ext.getCmp('pay-value').setValue(tot + totalmaterai);
                }
            }
        });
        var grid_payment = new Ext.grid.GridPanel({
            store: store_payment,
            height: 200,
            id: 'grid-payment',
            viewConfig: {
                forceFit: true
            },
            plugins: [editor],
            columns: [{
                    header: 'Ref Number',
                    dataIndex: 'ref_number',
                    sortable: true,
                    width: 100
                }, {
                    header: 'Project Code',
                    dataIndex: 'prj_kode',
                    sortable: true,
                    width: 90
                }, {
                    header: 'Site Code',
                    dataIndex: 'sit_kode',
                    sortable: true,
                    width: 60
                }, {
                    header: 'Coa Code',
                    dataIndex: 'coa_kode',
                    sortable: true,
                    width: 60
                }, {
                    header: 'Valuta',
                    dataIndex: 'valuta',
                    sortable: true,
                    align: 'right',
                    width: 50
                }, {
                    header: 'Voucher Value',
                    dataIndex: 'total_bayar',
                    sortable: true,
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0.00') : '';
                    },
                    align: 'right'
                }, {
                    header: 'PPN',
                    dataIndex: 'statusppn',
                    sortable: true,
                    width: 40
                }, {
                    header: 'Holding Tax',
                    dataIndex: 'holding_tax_status',
                    sortable: true,
                    width: 20
                }, {
                    header: 'Holding Tax Value',
                    dataIndex: 'holding_tax',
                    sortable: true,
                    renderer: function(v, p, r) {
                        if (!isNaN(v) && v != '')
                            return (parseFloat(v) * 100).toString() + '%';
                    },
                    align: 'right',
                    width: 60
                }, {
                    header: 'Total',
                    dataIndex: 'total',
                    sortable: true,
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0.00') : '';
                    },
                    align: 'right'
                }
                , {
                    header: 'Total Paid',
                    dataIndex: 'total_paid',
                    sortable: true,
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0.00') : '';
                    },
                    align: 'right'
                },
                {
                    xtype: 'numbercolumn',
                    header: 'Total Payment',
                    dataIndex: 'total_payment',
                    align: 'right',
                    width: 100,
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0') : '';
                    },
                    sortable: true,
                    editor: {
                        xtype: 'numberfield',
                        allowBlank: false,
                        minValue: 0
                    }
                },
                {
                    xtype: 'numbercolumn',
                    header: 'Payment Equivalent',
                    dataIndex: 'total_payment_konversi',
                    align: 'right',
                    width: 130,
                    value: 0.00,
                    sortable: true,
                    editor: {
                        xtype: 'numberfield',
                        minValue: 0
                    }
                }
            ]
        })

        var fieldset_payment = new Ext.form.FieldSet({
            title: 'RPI bank payment voucher list',
            items: [grid_payment]
        })

        var panel_payment = new Ext.form.FormPanel({
            title: 'RPI voucher payment',
            renderTo: 'rpi-voucher-payment',
            id: 'rpi_voucher_payment',
            frame: true,
            layout: 'form',
            labelWidth: 130,
            items: [{
                    xtype: 'combo',
                    fieldLabel: 'Transaction ',
                    id: 'trans',
                    allowBlank: false,
                    width: 100,
                    store: new Ext.data.Store({
                        proxy: new Ext.data.HttpProxy({
                            url: '/finance/coa/gettranotype'
                        }),
                        reader: new Ext.data.JsonReader({
                            totalProperty: 'count',
                            root: 'data'
                        }, [{
                                name: 'trano'
                            }])
                    }),
                    valueField: 'trano',
                    displayField: 'trano',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'remote',
                    triggerAction: 'all',
                    selectOnFocus: true,
                    emptyText: 'Select a type ...',
                    listeners: {
                        'select': function(c, row, index)
                        {
                            cekCoaBank();
                        }
                    }
                }, {
                    xtype: 'trigger',
                    fieldLabel: 'Voucher number ',
                    triggerClass: 'teropong',
                    allowBlank: false,
                    editable: false,
                    id: 'voc-number',
                    onTriggerClick: function()
                    {
                        showrpivoucherpayment();
                    }
                }, fieldset_payment, {
                    layout: 'column',
                    items: [{
                            columnWidth: 0.5,
                            layout: 'form',
                            items: [{
                                    xtype: 'combo',
                                    fieldLabel: 'Payment Type ',
                                    id: 'pay-type',
                                    allowBlank: false,
                                    width: 100,
                                    store: new Ext.data.SimpleStore({
                                        fields: ['nilai', 'name'],
                                        data: [
                                            ['CASH', 'CASH'],
                                            ['CHEQUE', 'CHEQUE'],
                                            ['GIRO', 'GIRO'],
                                            ['TRANSFER', 'TRANSFER']
                                        ]
                                    }),
                                    valueField: 'nilai',
                                    displayField: 'name',
                                    typeAhead: true,
                                    forceSelection: true,
                                    editable: false,
                                    mode: 'local',
                                    triggerAction: 'all',
                                    selectOnFocus: true,
                                    emptyText: 'Select a type ...',
                                    listeners: {
                                        'select': function(c, n, o) {
                                            paymentType = n.data['nilai'];
                                        }
                                    }
                                },
                                {
                                    xtype: 'checkbox',
                                    id: 'payment-idr',
                                    fieldLabel: 'Payment with IDR',
                                    hidden: true,
                                    listeners: {
                                        check: function(checkbox, checked) {
                                            if (checked) {
                                                paymentIDR = true;
                                            } else {
                                                paymentIDR = false;
                                            }
                                        }
                                    }
                                }, {
                                    fieldLabel: 'Due Date ',
                                    id: 'date',
                                    xtype: 'datefield',
                                    width: 100
                                }, {
                                    fieldLabel: 'Notes ',
                                    id: 'notes',
                                    xtype: 'textarea',
                                    width: 200
                                }, {
                                    xtype: 'currencyselector',
                                    anchor: '100%',
                                    id: 'currency-select',
                                    Selectid: 'val_kode_text',
                                    Nameid: 'val_nama_text',
                                    ShowName: true,
                                    fieldLabel: 'Currency Code',
                                    allowBlank: false,
                                    selectValue: 'IDR'
                                },
                                new Ext.ux.customRendererField(
                                        {
                                            priceDelemiter: ',',
                                            fieldLabel: 'Exchange Rate',
                                            style: "text-align:right",
                                            xtype: 'textfield',
                                            width: 100,
                                            id: 'val_rate_text',
                                            enableKeyEvents: true,
                                            listeners: {
                                                'customblur': function(t, e) {

                                                    var valuta = Ext.getCmp('valuta-1').getValue();
                                                    if (valuta != 'IDR' && valuta != '')
                                                    {
                                                        if (!isNaN(Ext.getCmp('val_rate_text').getOriginalValue()))
                                                        {
                                                            var newrate = Ext.getCmp('val_rate_text').getOriginalValue().replace(/\$|\,/g, '');
                                                            store_payment.each(function(stores) {
                                                                stores.data['total_payment_konversi'] = parseFloat(stores.data['total_payment']) * parseFloat(newrate);
                                                            });
                                                            grid_payment.getView().refresh();
                                                        }
                                                    }
                                                }}
                                        })
                            ]
                        }, {
                            columnWidth: 0.5,
                            layout: 'form',
                            items: [{
                                    layout: 'column',
                                    items: [{
                                            columnWidth: 0.7,
                                            layout: 'form',
                                            items: [
                                                new Ext.ux.customRendererField({
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Voucher Total Value ',
                                                    anchor: '98%',
                                                    priceDelemiter: ',',
                                                    id: 'voc-val',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                })
                                            ]
                                        }, {
                                            columnWidth: 0.1,
                                            layout: 'form',
                                            items: [{
                                                    xtype: 'textfield',
                                                    anchor: '97%',
                                                    hideLabel: true,
                                                    id: 'valuta-1',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                }]
                                        }]
                                },
                                new Ext.ux.customRendererField({
                                    xtype: 'textfield',
                                    fieldLabel: 'Stamp Duty ',
                                    width: 120,
                                    priceDelemiter: ',',
                                    id: 'voc-materai',
                                    readOnly: true,
                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                }),
                                {
                                    layout: 'column',
                                    items: [{
                                            columnWidth: 0.7,
                                            layout: 'form',
                                            items: [
                                                new Ext.ux.customRendererField({
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Voucher Already Paid ',
                                                    priceDelemiter: ',',
                                                    id: 'voc-paid',
                                                    anchor: '98%',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                })
                                            ]
                                        }, {
                                            columnWidth: 0.1,
                                            layout: 'form',
                                            items: [{
                                                    xtype: 'textfield',
                                                    hideLabel: true,
                                                    anchor: '97%',
                                                    id: 'valuta-2',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                }]
                                        }, {
                                            columnWidth: 0.08,
                                            layout: 'form',
                                            items: [{
                                                    xtype: 'button',
                                                    cls: "x-btn-icon",
                                                    icon: "/images/icons/fam/information.png",
                                                    anchor: '98%',
                                                    handler: function() {
                                                        showpaymenthistory()
                                                    }
                                                }]
                                        }]
                                }, {
                                    layout: 'column',
                                    items: [{
                                            columnWidth: 0.7,
                                            layout: 'form',
                                            items: [
                                                new Ext.ux.customRendererField({
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Voucher Balance ',
                                                    anchor: '98%',
                                                    priceDelemiter: ',',
                                                    id: 'voc-balan',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                })
                                            ]
                                        }, {
                                            columnWidth: 0.1,
                                            layout: 'form',
                                            items: [{
                                                    xtype: 'textfield',
                                                    hideLabel: true,
                                                    anchor: '97%',
                                                    id: 'valuta-3',
                                                    readOnly: true,
                                                    style: {'font-weight': 'bold', 'text-align': 'right'}
                                                }]
                                        }]
                                }, {
                                    layout: 'column',
                                    items: [{
                                            columnWidth: 0.7,
                                            layout: 'form',
                                            items: [
                                                new Ext.ux.customRendererField({
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Payment Value ',
                                                    anchor: '98%',
                                                    priceDelemiter: ',',
                                                    style: "text-align:right",
                                                    id: 'pay-value',
                                                    vtype: 'numeric',
                                                    readOnly: true,
                                                    style: {'color': '#ff0000', 'font-weight': 'bold', 'text-align': 'right'}
                                                })
                                            ]
                                        }, {
                                            columnWidth: 0.1,
                                            layout: 'form',
                                            items: [{
                                                    xtype: 'textfield',
                                                    hideLabel: true,
                                                    style: "text-align:right",
                                                    anchor: '97%',
                                                    id: 'valuta-4',
                                                    readOnly: true
                                                }]
                                        }]
                                }]
                        }]
                }],
            buttons: [{
                    text: 'Submit',
                    iconCls: 'silk-add',
                    handler: function(btn, ev)
                    {

                        if (!Ext.getCmp('rpi_voucher_payment').getForm().isValid())
                        {
                            Ext.Msg.alert('Error', 'Form not valid');
                            return false;
                        }
                        if (Ext.getCmp('valuta-1').getValue() != 'IDR')
                        {
                            if (Ext.getCmp('val_rate_text').getOriginalValue() < 0)
                                return false;
                        }

                        if (parseFloat(Ext.getCmp('pay-value').getValue().toString().replace(/\$|\,/g, '')) <= 0)
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry payment value must be grater then 0',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }
                        var payment = parseFloat(Ext.getCmp('pay-value').getValue().toString().replace(/\$|\,/g, '')).toFixed(3);
                        var total_value = parseFloat(Ext.getCmp('voc-val').getValue().toString().replace(/\$|\,/g, '')) + parseFloat(Ext.getCmp('voc-materai').getValue().toString().replace(/\$|\,/g, ''));
                        if (moneycomp(payment, '>', total_value, 2)) {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry payment value is greater than voucher total value !',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }
                        var bal = parseFloat(Ext.getCmp('voc-balan').getValue().toString().replace(/\$|\,/g, '')).toFixed(3);
                        if (moneycomp(payment, '>', bal, 2))
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry payment value is greater than voucher balancess !',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }
                        var tot = 0;
                        var totalmaterai = parseFloat(Ext.getCmp('voc-materai').getValue().toString().replace(/\$|\,/g, ''));
                        store_payment.each(function(stores) {
                            tot += parseFloat(stores.data['total_payment']);
                        });
                        if (parseFloat(Ext.getCmp('pay-value').getValue().toString().replace(/\$|\,/g, '')).toFixed(3) > parseFloat(tot + totalmaterai).toFixed(3))
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry payment value is greater than all items payment balance !',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }

                        var diffCurrency = '';

                        if (Ext.getCmp('valuta-1').getValue() != payment_valuta)
                            diffCurrency = '<br > <b>[ This transaction using different currency, please check your Bank Code! ]</b>';

                        Ext.MessageBox.confirm('Confirm', 'Are you sure want this action ?' + diffCurrency, function(btn) {
                            if (btn == 'yes')
                            {
                                tempExchange = Ext.getCmp('val_rate_text').getOriginalValue();
                                var formfield = Ext.getCmp('rpi_voucher_payment').findByType('textfield');
                                var jsonform = '';
                                Ext.each(formfield, function(t, index) {
                                    if (t.id == 'val_rate_text')
                                        jsonform = jsonform + '"' + t.id + '"' + ":" + '"' + t.getOriginalValue() + '",';
                                    else
                                    jsonform = jsonform + '"' + t.id + '"' + ":" + '"' + t.getValue().toString().replace(/\"|\'|\n|\t|\r/g, '') + '",';
                                });
                                jsonform = jsonform.substring(0, jsonform.length - 1);
                                var form_encode = "{" + jsonform + "}";
                                var voucherlist = '';
                                store_payment.each(function(store) {
                                    voucherlist += Ext.util.JSON.encode(store.data) + ',';
                                })

                                voucherlist = '[' + voucherlist.substring(0, voucherlist.length - 1) + ']';
                                var params = {
                                    form: form_encode,
                                    list: voucherlist
                                };
                                var callbackFunc = function(coaKode)
                                {
                                    var newParams = {
                                        form: params.form,
                                        list: params.list,
                                        coaPC: coaKode,
                                        paymentIDR: paymentIDR,
                                        payment_valuta: payment_valuta
                                    };
                                    Ext.getBody().mask('Loading..','x-mask-loading',false);
                                    Ext.Ajax.request({
                                        url: '/finance/payment/doinsertrpivoucherpayment',
                                        method: 'POST',
                                        params: newParams,
                                        success: function(result)
                                        {
                                            Ext.getBody().unmask();        
                                            var returnData = Ext.util.JSON.decode(result.responseText);
                                            if (returnData.success) {
                                                Ext.Msg.alert('Message', 'Success, Data has been saved<br><br>Your Transaction number is <b><font color="#ff0000">' + returnData.trano + '</font></b>');

                                                var valPayment = Ext.getCmp('valuta-1').getValue();
                                                if (paymentType == 'TRANSFER' && valPayment == 'IDR')
                                                {
                                                    Ext.MessageBox.confirm('Confirm', 'Are you want to add this payment [ <b><font color="#ff0000">'
                                                            + returnData.trano + '</font></b> ] to EBanking transaction ?', function(btn) {

                                                                if (btn == 'yes')
                                                                {
                                                                    gridEbanking.addNewTrano({
                                                                        item_type: 'RPI',
                                                                        bpv_trano: recordBPV.get("trano"),
                                                                        trano: returnData.trano,
                                                                        ref_number: recordBPV.get("ref_number"),
                                                                        val_kode: recordBPV.get("valuta"),
                                                                        total: Ext.getCmp('pay-value').getValue().toString().replace(/\$|\,/g, '')
                                                                    });
                                                                }
                                                                else
                                                                    resetFormPayment();
                                                            });
                                                }
                                                else
                                                    resetFormPayment();
                                                paymentIDR = false;
                                            }
                                            else
                                            {
                                                Ext.Msg.alert('Error', 'Sorry, ' + returnData.message);
                                                return false;
                                            }
                                        },
                                        failure: function(action)
                                        {
                                            Ext.getBody().unmask();
                                            if (action.failureType == 'server') {
                                                obj = Ext.util.JSON.decode(action.response.responseText);
                                                Ext.Msg.alert('Error!', obj.errors.reason);
                                            } else {
                                                Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
                                            }
                                        }
                                    });
                                }
                                if (Ext.getCmp('trans').getValue() == 'PC')
                                {
                                    Ext.Ajax.request({
                                        url: '/finance/payment/checktransactiontype',
                                        method: 'POST',
                                        params: {
                                            type: Ext.getCmp('trans').getValue()
                                        },
                                        success: function(result)
                                        {
                                            var returnData = Ext.util.JSON.decode(result.responseText);
                                            selectCoaPC(returnData.data, callbackFunc);
                                        }
                                    });
                                }
                                else
                                {
                                    callbackFunc();
                                }
                            }
                        })


                    }
                }, {
                    text: 'Reset',
                    handler: function(btn, ev)
                    {
                        resetFormPayment();
                    }
                }, {
                    text: 'Cancel',
                    handler: function(btn, ev)
                    {
                        mypanel = Ext.getCmp('abs-budget-panel');
                        mypanel.body.load({
                            url: '/procurement/procurement/rpi',
                            scripts: true
                        });
                    }
                }]

        });
    })


</script>

<div id="rpi-voucher-payment"></div><br>
<div id="gridEbanking"></div>
