<script type="text/javascript">
showWorkflow = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowitem',
	        scripts : true
        });
	};

showWorkflowItemGeneric = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowitemgeneric',
	        scripts : true
        });
	};

showWorkflowProcessGeneric1 = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowprocessgenericbyone',
	        scripts : true
        });
	};
showWorkflowProcessGeneric = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowprocessgeneric',
	        scripts : true
        });
	};

showWorkflowProcess = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowprocess',
	        scripts : true
        });
	};	

showWorkflowRoute = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/addworkflowroute',
	        scripts : true
        });
	};	
showWorkflowType = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowtype',
	        scripts : true
        });
	};
showWorkflowGeneric = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/workflow/workflowgeneric',
	        scripts : true
        });
	};
	
var windowForm =  ({

    title: 'Workflow',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    loadMask: true,
    minWidth: 300,
    minHeight: 200,
    tbar: [{
		    xtype: 'tbbutton',
		    text: 'Select Action',
		    iconCls: 'menu-drop',
		    menu: {
			items: [
		            {
					    id: 'fill_button2',
					    text: 'Add Workflow Type',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/action_paste.gif",
					    handler:showWorkflowType
				    },
					{
					    id: 'fill_button',
					    text: 'Add Workflow Item',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/action_paste.gif",
					    handler:showWorkflow
					},
					
					{
					    id: 'process_button',
					    text: 'Add Workflow Process',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/icon_wand.gif",
					    handler:showWorkflowProcess
					},
					{
					    id: 'route_button',
					    text: 'Add Workflow Route',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/icon_wand.gif",
					    handler:showWorkflowRoute
					},
                    '-',
                    {
					    id: 'fill2_button',
					    text: 'Add Generic Workflow Item',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/action_paste.gif",
					    handler:showWorkflowItemGeneric
					},
                    {
					    id: 'processgeneric_button',
					    text: 'Add Workflow Generic Process (Bulk)',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/icon_wand.gif",
					    handler:showWorkflowProcessGeneric
					},
                    {
					    id: 'processgeneric2_button',
					    text: 'Add Workflow Generic Process (1 By 1)',
					    cls:"x-btn-text-icon" ,
					    icon:"/images/icons/fam/icon_wand.gif",
					    handler:showWorkflowProcessGeneric1
					}
				]
    		}
    	}
           ]

});
viewPort = Ext.getCmp('viewport');

centerRegionTab = viewPort.getComponent('content-panel');
centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
centerRegionTab.add(windowForm);
panelBaru = Ext.getCmp('abs-budget-panel');
centerRegionTab.layout.setActiveItem('abs-budget-panel');
<?php

if ($this->goto != '')
{
?>
    myPanel = Ext.getCmp('abs-budget-panel');
    myPanel.body.load({
        url: '/admin/workflow/<?php echo $this->goto ?>',
        scripts : true
    });
<?php
} else {
?>
myPanel = Ext.getCmp('abs-budget-panel');
myPanel.body.load({
    url: '/admin/workflow/workflowitem',
    scripts : true
});
<?php
}
?>
</script>
