<script type="text/javascript">
    Ext.onReady(function(){
        var panelTarget = new Ext.Panel({
            title: 'Person To Switch',
            width: 400,
            autoHeight: true,
            frame: true,
            renderTo: 'person-target',
            items: [
                {
                    xtype: 'userselector',
                    id: 'users',
                    ShowName: false,
                    UserSelectid: 'user_text',
                    width: 200
                }
            ]
        })
    });
</script>

    <div id="person-target"></div>
