<html>
<head>
<?php echo $this->printHeader(); ?>
</head>
<body>
<?php echo $this->webHeader(); ?>
<?php echo $this->specialHeader(); ?>


  
  <div id="ipcc-loading-mask" style=""></div>
  <div id="ipcc-loading">
      <div class="ipcc-loading-indicator">
        <span id="ipcc-loading-logo">QDC iPCC</span>
        <br>
        <span id="ipcc-loading-logo-text"><img src="/images/imd.gif" /></span>
        <br>
        <img src="/images/loading.gif" width="150"/>
        <br>
        <span id="ipcc-loading-msg">Loading Extjs library...</span>
      </div>
  </div>
  <script type="text/javascript">
            if (!Ext.isEmpty(Ext.get('ipcc-loading'))) {
        Ext.get('ipcc-loading').remove();
      }
</script>
<div style="width:100%;height:100%;overflow: hidden;" id="content">
    <iframe id="content_iframe" src="" style="border:0;width:100%;height:100%;overflow-y: hidden;margin:0;padding:0;" FRAMEBORDER="no"></iframe>
  </div>
    <div style="display:none;">


        <div id="tabs-nested-layouts-details">
            <h2>Another Menu</h2>
        </div>
        

        <!-- Form layouts -->
        <div id="abs-form-po-details">
            <h2>Procurement PO</h2>
            <p></p>
        </div>
    </div>
    </body>
</html>    