<script type="text/javascript">
var windowForm =  ({

    title: 'Log Print Document',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    minWidth: 300,
    minHeight: 200,
    loadMask: true,
    tbar:[
        {
            xtype: 'tbtext',
            text: 'Document Number'
        },
        {
            xtype:'tranoselector',
            fieldLabel:'Reference Number',
            id:'trano',
            Selectid: 'trano_text',
            Enableeditable: true,
            width: 150
        },
        '-',
        {
            xtype: 'button',
            text: 'Show',
            width:70,
            id: 'show_trans',
            cls:"x-btn-text-icon" ,
            icon:"/images/icons/fam/control_rewind.png",
            handler:function() {
                var myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                    url: '/default/home/show-log-print-document',
                    scripts: true,
                    params: {
                        trano: Ext.getCmp('trano_text').getValue()
                    }

                });
            }
        }
    ]
});

viewPort = Ext.getCmp('viewport');

centerRegionTab = viewPort.getComponent('content-panel');
centerRegionTab.items.each(function(c){centerRegionTab.remove(c);})
centerRegionTab.add(windowForm);
panelBaru = Ext.getCmp('abs-budget-panel');
centerRegionTab.layout.setActiveItem('abs-budget-panel');

</script>

