<?php 
/* 
	Created @ Aprl 06, 2010
 */
?>

<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<b><?php echo $this->result[0]['prj_kode']; ?> - Project <?php echo $this->result[0]['prj_nama']; ?></b><br>
Customer : <br>
Project Manager : <br>
Project Baseline : <b><?php echo $this->result[0]['tglaw']; ?> (yyyy/mm/dd)</b><br>				

<table id="rounded-corner" tablewidth = "800">
<caption><b>Sites Summary</b></caption>
    <thead>
    	<tr>
            <th align=center scope="col" class="rounded-company"><b>Site Code</b></th> 
            <th align=center scope="col" class="rounded-q3"><b>Name</b></th>             
            <th align=center scope="col" class="rounded-q3"><b>Budget Project (BoQ3)</b></th>
            <th align=center scope="col" class="rounded-q3"><b>Actual Cost (BoQ4)</b></th>
            <th align=center scope="col" class="rounded-q4"><b>Progress</b></th>        
        </tr>
    </thead>
    <tbody>
    	<?php
            
            for($i=0;$i<count($this->result);$i++)
            {
                $no = $i + 1;
                
                /*
                if (($this->result[$i]['boq3_ori'] > 0 || $this->result[$i]['boq3_ori'] !='')) 
                {
                    $d = number_format($this->result[$i]['boq3_ori']);                      
                }
                else
                {
                    $d = '';                   
                }
                if (($this->result[$i]['boq3_current'] > 0 || $this->result[$i]['boq3_current'] !=''))
                {    
                	$f =  number_format($this->result[$i]['boq3_current']); }
                else
                {    
                	$f = ''; }
               
                if (($this->result[$i]['boq3_current'] > 0 || $this->result[$i]['boq3_current'] !='') && ($this->result[$i]['boq4_current'] > 0 || $this->result[$i]['boq4_current'] != ''))
                {                    
                    //$h = $this->result[$i]['boq4_current'] / $this->result[$i]['boq3_current'];
                    $h = $this->result[$i]['boq4_current'];
                }
                else
                {
                    $h = '';                  
                }
                
                   */           
        ?>
        
        <tr>
            <td align=center><?php echo $this->result[$i]['sit_kode']; ?></td>
            <td><a href=/dashboard/project/prj_kode/<?php echo $this->result[$i]['prj_kode']; ?>/sit_kode/<?php echo $this->result[$i]['sit_kode']; ?>/><?php echo $this->result[$i]['sit_nama']; ?></a></td>         
            <td><NOBR><?php echo number_format($this->result[$i]['boq3_current1']); ?> IDR</NOBR><br> 
            	<NOBR><?php if ($this->result[$i]['boq3_current2'] > 0){echo number_format($this->result[$i]['boq3_current2'],2) . ' USD';}?></NOBR>
            </td>
            <td><NOBR><?php echo number_format($this->result[$i]['boq4_current']); ?> IDR<br></NOBR>
             	<NOBR><?php if ($this->result[$i]['boq4_current2'] >0){echo number_format($this->result[$i]['boq4_current2'],2) . ' USD';}?></NOBR>
            </td>
            <td> TODO: Progress of site in %
            </td>
       </tr>
        
        <?php        
				$boq3_site_IDR = $this->result[$i]['boq3_current1'];
				$boq3_site_USD = $this->result[$i]['boq3_current2'];
				$boq3Jumlah_IDR = $boq3Jumlah_IDR + $boq3_site_IDR;
				$boq3Jumlah_USD = $boq3Jumlah_USD + $boq3_site_USD; 			    
            }
        
        	echo "Value: <b><br>"; 
        	echo number_format($boq3Jumlah_IDR,2); echo "$nbsp IDR <br>";
        	echo number_format($boq3Jumlah_USD,2); echo "$nbsp USD </b>";  
         ?>   	
    </tbody>
</table>