<html>
<head>
<style type="text/css">

	#history {
		border: 1px solid #666666;
        width: 100%;
        padding: 5px 15px 0 15px;
	}

	#history tbody tr td {
		font-family: "lucida grande", verdana, sans-serif;
		font-size: 8pt;
		padding: 3px 8px;
        text-align: center;
	}

    #history tbody tr th {
		font-family: "lucida grande", verdana, sans-serif;
		font-size: 8pt;
		padding: 3px 8px;
        background-color: #3d80df;
        color: #fff;
        text-align: center;
	}

	#history tbody tr.selected td {
		background-color: #3d80df;
		color: #ffffff;
		font-weight: bold;
		border-left: 1px solid #346DBE;
		border-bottom: 1px solid #7DAAEA;
	}
</style>
</head>
<body style="overflow: auto;">
<table id="history">
<tr>
    <th>No.</th>
    <th>Trano</th>
    <th>Deletion Date From Workflow</th>
    <th>Reason for Deletion</th>
</tr>
<?php
        $i = 1;
        foreach ($this->result as $key => $val)
        {
            if ($i % 2 == 0)
                $style = "background-color:#eee;";
            else
                $style = "background-color:#fff;";
?>
<tr style="<?=$style?>">
    <td><?=$i?></td>
    <td><?=$val['trano']?></td>
    <td><?=date("d M Y H:i:s",strtotime($val['tgl']))?></td>
     <td><?=$val['reason']?></td>
</tr>
<?php
            $i++;
        }
?>
</table>
</body>
</html>