<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        <?php echo $this->action('index','textfield',null); ?>


        function addengineerwork ()
        {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/projectmanagement/engineerwork/addengineerwork',
                scripts : true
            });
        }

        function editengineerwork ()
        {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/projectmanagement/engineerwork/editengineerwork',
                scripts : true
            });
        }

        var windowForm = ({

            title:'Master Engineer Work',
            id:'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                    items: [
                            {
                                id: 'masterwork_add_button',
                                text: 'Add Engineer Work',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/action_paste.gif",
                                handler:addengineerwork
                            }
                            ,{
                                id: 'masterwork_edit_button',
                                text: 'Edit Existing Engineer Work',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler:editengineerwork
                            }
                            ]
                    }
                }
            ]

        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        panelBaru.body.load({
                url: '/projectmanagement/engineerwork/viewengineerwork',
                scripts: true
            });

        showSubmenu('abs-budget-panel');
    })

</script>
