<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<style type="text/css">

.parentContainer{
    margin: 5px;
    padding: 0px;
    border: none;
    width: 740px;
    height: 460px;
    overflow: auto;
    font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
        <tr>
            <th scope="col" align="center"><b>No</b></th>
            <th scope="col" align="center"><b>MDI No</b></th>
            <th scope="col" align="center"><b>Date</b></th>
            <th scope="col" align="center"><b>Prod Id</b></th>
            <th scope="col" align="center"><b>Material Name</b></th>       
            <th scope="col" align="center"><b>MDO No</b></th>
            <th scope="col" align="center"><b>Date</b></th>
            <th scope="col" align="center"><b>Qty MDI</b></th>
            <th scope="col" align="center"><b>Qty MDO</b></th>
            <th scope="col" align="center"><b>Balance</b></th>
        </tr>

    </thead>
    
    <tbody>    
    	<?php
            for($i=0; $i<count($this->result); $i++)
            {
        ?>
    	<tr>
            <td><?=$i+1;?></td>
            <td><?=$this->result[$i]['mdi_no'];?></td>
            <td><?=$this->result[$i]['tgl_mdi'];?></td>
            <td><?=$this->result[$i]['kode_brg'];?></td>
            <td><?=$this->result[$i]['nama_brg'];?></td>       
            <td><?=$this->result[$i]['mdo_no'];?></td>
            <td><?=$this->result[$i]['tgl_mdo'];?></td>
            <td align="right"><?=number_format($this->result[$i]['qty_mdi'],4);?></td>
            <td align="right"><?=number_format($this->result[$i]['qty_mdo'],4);?></td>
            <td align="right"><?=number_format($this->result[$i]['balance'],4);?></td>
        </tr>
        <?php            
            }
        ?>
    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 1
	});
})();

</script>