<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>

<style type="text/css">

.parentContainer{ 
    margin: 5px;
    padding: 0px;
    border: none;
    width: 840px; 
    height: 420px; 
    overflow: auto; 
    font-size: 14px;
}

</style>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead id="fixed">
        <tr>
            <th scope="col"><center><b>No</b></center></th>
            <th scope="col"><center><b>Trans No</b></center></th>
            <th scope="col"><center><b>Date</b></center></th>
            <th scope="col"><center><b>Work Id</b></center></th>
            <th scope="col"><center><b>Work Name</b></center></th>
            <th scope="col"><center><b>Product Id</b></center></th>
            <th scope="col"><center><b>Description</b></center></th>
            <th scope="col"><center><b>Qty</b></center></th>
            <th scope="col"><center><b>Requestor</b></center></th>
        </tr>
    </thead>
    <tbody>
        <?php
            for($i=0; $i<count($this->result); $i++)
            {
    	?>
    	<tr>
            <td><?=$i+1;?></td>
            <td><?=$this->result[$i]['trano'];?></td>
            <td><?=$this->result[$i]['tgl'];?></td>
            <td><?=$this->result[$i]['workid'];?></td>
            <td><?=$this->result[$i]['workname'];?></td>
            <td><?=$this->result[$i]['kode_brg'];?></td>
            <td><?=$this->result[$i]['nama_brg'];?></td>
            <td><?=$this->result[$i]['qty'];?></td>
            <td><?=$this->result[$i]['pc_nama'];?></td>
        </tr>

        <?php

                }
        ?>       
    			
    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 2,
		headerRows : 1
	});
})();

</script>