<?php 
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}

?>
<style type="text/css">

    .parentContainer{ 
        margin: 5px;
        padding: 0px;
        border: none;
        width: 625px; 
        height: 380px; 
        overflow: auto; 
        font-size: 14px;
    }

</style>

<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
            <tr>
                <th scope="col"><center><b>No</b></center></th>
        <th scope="col"><center><b>PR Number</b></center></th>
        <th scope="col"><center><b>Kode Barang</b></center></th>
        <th scope="col"><center><b>Qty</b></center></th>
        <th scope="col"><center><b>DOR Number</b></center></th>
        <th scope="col"><center><b>Kode Barang</b></center></th>
        <th scope="col"><center><b>Qty</b></center></th>
        </tr>
        <tr>
        </tr>
        </thead>
        <tbody>
            <?php
            $i = 0;
            $totalPRIDR = 0;
            $totalPRUSD = 0;
            $totalDORIDR = 0;
            $totalDORUSD = 0;
            $compare1='';
            $pr_no='';
            foreach ($this->result as $k => $v) 
            {
                $row = 1;
                $totalRow = count($this->result[$k]);
                $grandTotalDOR = 0;
                
                        
                foreach($v as $k2 => $v2)
                {
                    $v2['val_kode_pr'] = 'IDR';
                    $compare2=$v2['dor_no'];
                     $po_no2 =$v2['pr_no'];
               ?>
                <tr>
                    <td><?=$i+1; ?></td>
                    <?php if ($row == 1) { ?>
                    <td rowspan="<?=$totalRow?>"><?= $v2['pr_no']; ?></td>
                    <?php } ?>
                    <td align="right"><?= $v2['kode_brg_pr']; ?></td>
                    <td align="right"><?= number_format($v2['qty_pr'],2); ?></td>
                    <td><?= $v2['dor_no']; ?></td>
                    <td align="right"><?= $v2['kode_brg_dor']; ?></td>
                    <td align="right"><?= number_format($v2['qty_dor'],2); ?></td>
                </tr>

    <?php
    $i++;
                    $row++;
                    if($compare1 !=$compare2){
                       
                        $compare1=$v2['dor_no'];
                        
                    }
                }
            }
?>       
           
        </tbody>
    </table>
</div>

<script type="text/javascript">

    (function() {
        var mySt = new superTable("budgetTable", {
            cssSkin: "sSky",
            fixedCols: 2,
            headerRows: 2
        });
    })();

</script>