<script type="text/javascript">
var windowForm =  ({

    title: 'Master List',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    minWidth: 300,
    minHeight: 200,
    loadMask: true,
    tbar:[
      
    ]
});

<?php echo $this->action('index','textfield',null); ?>

var aForm =  new Ext.Window({
    id: 'a-form-panel-1',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    closable:false,
    width: 400,
    height: 400,
    items : [
        
    ]

  });

 viewPort = Ext.getCmp('viewport');

 centerRegionTab = viewPort.getComponent('content-panel');
 centerRegionTab.items.each(function(c){centerRegionTab.remove(c);})
 centerRegionTab.add(windowForm);
 panelBaru = Ext.getCmp('abs-budget-panel');
 centerRegionTab.layout.setActiveItem('abs-budget-panel');
 myPanel = Ext.getCmp('abs-budget-panel');
 myPanel.body.load({

    url: '/report/showformbarang/',
    scripts : true
});

    </script>

