<script type="text/javascript">
    Ext.onReady(function() {

        var text2encode = '<?=$this->textEncode?>';

        if (text2encode == '')
        {
            Ext.Msg.alert('Error','Text is null');
            return false;
        }

        Ext.create('Ext.ux.QrPanel', {

            renderTo : Ext.getBody(),
            margin : 20, // blank frame around
            textToEncode : text2encode,
            typeNumber : 2

        });

    });
</script>
    <div id="panel-barcode"></div>