<script type="text/javascript">
    Ext.onReady(function(){
        Ext.QuickTips.init();

        showCreateBoq2 = function (){
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/sales/sales/createboq2',
                scripts: true
            });
        };

        showAddCO = function (){
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/sales/sales/addco',
                scripts: true
            });
        };

  
        var windowForm = ({
            title: 'Customer Order Transaction',
            id:'abs-budget-panel',
            layout:'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [{
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu:{
                        items: [{
                                id:'create_praco',
                                text:'Create Customer Order',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/action_paste.gif",
                                handler:function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/sales/sales/createco',
                                        scripts: true
                                    });
                                }

                            },{
                                id:'edit_praco',
                                text:'Edit Existing Customer Order',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/page_edit.gif",
                                handler:function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/sales/sales/editco',
                                        scripts: true
                                    });
                                }

                            },
//                            {
//                                id:'esti-ori',
//                                text:'Estimate To Origin',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/action_paste.gif",
//                                handler:function()
//                                {
//                                    myPanel = Ext.getCmp('abs-budget-panel');
//                                    myPanel.body.load({
//                                        url: '/sales/sales/estimatetoorigin',
//                                        scripts: true
//                                    });
//                                }
//                            },
//                            {
//                                id:'co_add_button',
//                                text:'Input Customer Order',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/action_paste.gif",
//				                handler:showCreateBoq2
//                            },
//                            {
//                                id:'edit_co',
//                                text:'Edit Existing Customer Order',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/page_edit.gif",
//                                handler:function ()
//                                {
//                                    myPanel = Ext.getCmp('abs-budget-panel');
//                                    myPanel.body.load({
//                                        url: '/sales/sales/editboq2',
//                                        scripts: true
//                                    });
//                                }
//                            },
//                            {
//                                id:'co_additional_button',
//                                text:'Additional Customer Order',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/action_paste.gif",
//				handler:showAddCO
//                            },
                            {
                                id:'create_co_additional_button',
                                text:'Create Additional Customer Order',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/action_paste.gif",
				                handler:function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/sales/sales/createaddco',
                                        scripts: true
                                    });
                                }
                            },{
                                id:'edit_co_additional_button',
                                text:'Edit Additional Customer Order',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/action_paste.gif",
				                handler:function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/sales/sales/editaddco',
                                        scripts: true
                                    });
                                }
                            }
//                            ,{
//                                id:'create_praco',
//                                text:'Create Customer Order',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/action_paste.gif",
//                                handler:function()
//                                {
//                                    myPanel = Ext.getCmp('abs-budget-panel');
//                                    myPanel.body.load({
//                                        url: '/sales/sales/createco',
//                                        scripts: true
//                                    });
//                                }
//
//                            },{
//                                id:'edit_praco',
//                                text:'Edit Existing Customer Order',
//                                cls:'x-btn-text-icon',
//                                icon:"/images/icons/fam/page_edit.gif",
//                                handler:function()
//                                {
//                                    myPanel = Ext.getCmp('abs-budget-panel');
//                                    myPanel.body.load({
//                                        url: '/sales/sales/editco',
//                                        scripts: true
//                                    });
//                                }
//
//                            }
    						
                        ]
                    }
            }]

        });
        
//        function getExchangeRate()
//        {
//            Ext.Ajax.request({
//                url: '/default/valuta/getexchangerate/val_kode/USD',
//                method: 'POST',
//                success: function(result, request) {
//                    var returnData = Ext.util.JSON.decode(result.responseText);
//                    if (returnData.success) {
//                        if(returnData.rate == 0)
//                        {
//                            Ext.MessageBox.show({
//                                title: 'Error',
//                                msg: 'Please Call Accounting Staffs (Ext. 1101 - 1104). Ask Them to Input Current IDR Rate. Thank You.',
//                                buttons: Ext.MessageBox.OK,
//                                icon: Ext.MessageBox.ERROR,
//                                fn:function(){window.location='';}
//                            });
//                        }
//                    
//                        Ext.getCmp('rateidr').setValue(returnData.rate);
//                    }
//                },
//                failure: function(action) {
//                    if (action.failureType == 'server') {
//                        obj = Ext.util.JSON.decode(action.response.responseText);
//                        Ext.Msg.alert('Error!', obj.errors.reason);
//                    }
//                }
//            });
//        }
//        getExchangeRate();

        viewPort = Ext.getCmp('viewport');
        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        showSubmenu('abs-budget-panel');

    });
</script>