<style>
.files{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#E0ECEE;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.last-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.all-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#F6CBCA;
    color:#222222;
    padding:4px;
    text-align:left;
}
.all-approve{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    /*background:#CEE6C3;*/
    color:#222222;
    padding:4px;
    text-align:left;
    height: 200px;
    overflow: auto;
}

.body {
	/*width: 720px;*/
    overflow: auto;
}
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
	margin-bottom: 10px;
}
.etc {
	width: 100%;
	height: 50px;
}
.kanan-etc {
	float: right;
	width: 48%;
}
.kiri-etc {
	float: left;
	width: 48%;
}
.blok {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
}
.budgetTable {
	width: 100%;
	font-size: 12px;
	font-weight: normal;
}

.ketin {
    width: 100%;
    font-size: 12px;
	font-weight: bold;
    background-color:#FBF0A5;
}
.ketin fieldset p {
    padding: 5px 5px 5px 5px;
}
</style>

<script type="text/javascript">


var jsonFile = '<?php echo $this->jsonFile; ?>';
var jsonDeletedFile = '<?php echo $this->deletedFile; ?>';

function submitData(params)
{
    var addurl = '';

    if (params == "" || params == '')
        return false;
    Ext.getBody().mask('Loading..','x-mask-loading',false);
    Ext.Ajax.request({
        url: '/finance/invoice/insertinvoice' + addurl,
        method:'POST',
        success: function(resp){
                Ext.getBody().unmask();
			var returnData = Ext.util.JSON.decode(resp.responseText);
			if (returnData.success)
			{
                Ext.Msg.alert('Success', '<br>Your Invoice number is <b><font color="#ff0000">' + returnData.trano + '</font></b>');
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                    url: '/finance/invoice/invoice',
                    scripts : true
                });
			}
            else
            {
                Ext.Msg.alert('Error', returnData.msg);
            }
        },
    	failure:function( action){
        Ext.getBody().unmask();
      	if(action.failureType == 'server'){
          obj = Ext.util.JSON.decode(action.responseText);
          Ext.Msg.alert('Error!', obj.errors.reason);
      	}else{
          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
      	}
      	},
        params: params
    });
}

function submitData2(params)
{
    var addurl = '';

    if (params == "" || params == '')
        return false;
    Ext.getBody().mask('Loading..','x-mask-loading',false);
    Ext.Ajax.request({
        url: '/finance/invoice/updateinvoice' + addurl,
        method:'POST',
        success: function(resp){
                Ext.getBody().unmask();
			var returnData = Ext.util.JSON.decode(resp.responseText);
			if (returnData.success)
			{
                Ext.Msg.alert('Success', 'Invoice has been saved!');
                myPanel = Ext.getCmp('abs-budget-panel');
                myPanel.body.load({
                    url: '/finance/invoice/invoice',
                    scripts : true
                });
			}
            else
            {
                Ext.Msg.alert('Error', returnData.msg);
            }
        },
    	failure:function( action){
          Ext.getBody().unmask();
      	if(action.failureType == 'server'){
          obj = Ext.util.JSON.decode(action.responseText);
          Ext.Msg.alert('Error!', obj.errors.reason);
      	}else{
          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.responseText);
      	}
      	},
        params: params
    });
}

var okButton = new Ext.Button({
    text: 'Submit',
    iconCls: 'icon-save',
    scale: 'large',
    handler: function (){
//        this.disable()
        
        var param = <?=$this->jsonData?>;
        <?php if ($this->edit) { ?>
        submitData2(param);
        <?php } else { ?>
        submitData(param);
        <?php } ?>
    },
    renderTo: 'ok-button'
});

var backButton = new Ext.Button({
    text: 'Cancel',
    scale: 'large',
    handler: function (){
		myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '<?php echo $this->urlBack; ?>',
	        scripts : true
	    });
	},
	renderTo: 'back-button'
});

Ext.onReady(function(){

    Ext.QuickTips.init();

});

</script>


<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">
<div align="right"><img src="/images/qdc.gif" alt= "logo qdc" /></div>
<div class="title"><?php if ($this->edit) {?>Edit <?php } ?>Invoice</div>

<?php if ($this->file != '') { ?>
<div class="files">
    Attachment Files :<br />
    <ul>
    <?php foreach ($this->file as $key => $val) { ?>
    <li>- <a href="#" onclick="window.open('/default/file/download/path/files/filename/<?php echo $val['savename']; ?>','mywin','left=20,top=20,width=100,height=20,toolbar=0,resizable=0');"><?php echo $val['filename']; ?></a></li>
    <?php } ?>
    </ul>
</div>
<?php } ?>

<div class="etc">
	<div class="kiri-etc">
        <?php if ($this->edit) {?><div class="blok">Invoice Number : <?=$this->data['trano']?></div><?php } ?>
		<div class="blok">Request Invoice Number : <?=$this->data['riv_no']?></div>
        <div class="blok">Invoice Date : <?=date('d-m-Y')?></div>
	</div>
	<div class="kanan-etc">
		<div class="blok">Project : <?=$this->data['prj_kode']?> - <?=$this->data['prj_nama']?></div>
		<div class="blok">Site : <?=$this->data['sit_kode']?> - <?=$this->data['sit_nama']?></div>
		<div class="blok">Customer : <?=$this->data['cus_kode']?> - <?=$this->data['cus_nama']?></div>
	</div>
</div>
<br>
<div class="ketin">
    <fieldset>
     <legend>Payment Term</legend>
        <p>
        <?php echo $this->data['paymentterm']; ?>
        </p>
    </fieldset>
    <fieldset>
     <legend>TOP</legend>
        <p>
        <?php echo $this->data['top'].' Days'; ?>
        </p>
    </fieldset>
    <fieldset>
     <legend>Bank Account</legend>
        <p>
        <?php echo $this->bank['bnk_nama'] . " - " . $this->bank['bnk_cabang']; ?>
        </p>
        <p>
        <?php echo $this->bank['bnk_alamat'] . " - " . $this->bank['bnk_kota']; ?>
        </p>
        <p>
        A/C No : <?php echo $this->bank['bnk_norek']; ?>
        </p>
    </fieldset>
</div>
<br>

<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>Description</center></th>
            <th scope="col"><center>Remark</center></th>
            <th scope="col"><center>Total Invoice</center></th>
        </tr>
    <?php
    $i = 0;
    $gtotal = 0;
    foreach($this->invoice as $k => $v)
    {
        if ($v['ppn'] == '') $v['ppn'] = 0;
        if ($v['holdingtaxval'] == '') $v['holdingtaxval'] = 0;
//        if ($v['deduction'] == '') $v['deduction'] = 0;
        $gtotal = (floatval($v['total']) - $v['total_deduction_before']) + floatval($v['ppn']) - floatval($v['holding_tax_val']) - $v['total_deduction_after'];
        $totals += $gtotal;

        $totalRow = 4;
        $totalRow += count($v['deduction_before']);
        $totalRow += count($v['deduction_after']);
    ?>
    		<tr>
    		<th scope="row" class="spec" rowspan="<?=$totalRow?>"><?=($i+1)?></th>
    		<td><?=$v['nama_brg'] ?> </td>
            <td ><?=$v['ket']?></td>
    		<td align="right"><?=number_format($v['total'],2)?></td>
            </tr>
        <?php
            if (count($v['deduction_before']) > 0)
            {
                foreach($v['deduction_before'] as $key => $val)
                {
        ?>
            <tr>
                <td colspan="2"><?=$val['ket']?></td>
                <td align="right">(<?=number_format($val['total'],2)?>)</td>
            </tr>
        <?php
                }
            }
        ?>
            <tr>
                <td colspan="2">VAT</td>
                <td align="right"><?=number_format($v['ppn'],2)?></td>
            </tr>
            <tr>
                <td colspan="2">Holding Tax</td>
                <td align="right"><?=number_format($v['holding_tax_val'],2)?></td>
            </tr>
        <?php
        if (count($v['deduction_after']) > 0)
        {
            foreach($v['deduction_after'] as $key => $val)
            {
                ?>
                <tr>
                    <td colspan="2"><?=$val['ket']?></td>
                    <td align="right">(<?=number_format($val['total'],2)?>)</td>
                </tr>
            <?php
            }
        }
        ?>
            <tr>
                <td colspan="2">Total</td>
    		    <td align="right"><?=number_format($gtotal,2)?></td>
    		</tr>
    <?php
        $i++;
    }
    ?>
        <tr>
           <th scope="row" class="spec" colspan="3">Grand Total</th>
           <td align="right"><?=$v['val_kode']. " " . number_format($totals,2)?></td>
        </tr>
       </table>

	<div style="margin-top:15px;">
		<div id="back-button"  style="margin-left:5px;float: right;"></div>
		<div id="ok-button"  style="float: right;"></div>
	</div>
</div>

