

<script type="text/javascript">

    Ext.onReady(function() {

        Ext.QuickTips.init();

        var windowForm = ({
            title: 'Invoice',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg: {cls: 'xpanel-body-table', style: {'overflow': 'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                        items: [
                            {
                                id: 'finance_request_invoice',
                                text: 'Request Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/icons/fam/action_paste.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/requestinvoice',
                                        scripts: true
                                    });
                                }
                            },
                            {
                                id: 'finance_edit_request_invoice',
                                text: 'Edit Existing Request Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/icons/fam/page_edit.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/editrequestinvoice',
                                        scripts: true
                                    });
                                }
                            }
                            , {
                                id: 'finance_add_invoice',
                                text: 'Add New Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/icons/fam/action_paste.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/addinvoice',
                                        scripts: true
                                    });
                                }
                            }
                            , {
                                id: 'finance_invoice',
                                text: 'Edit Existing Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/icons/fam/page_edit.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/editinvoice',
                                        scripts: true
                                    });
                                }
                            },
                            {
                                id: 'invoice_payment',
                                text: 'Payment Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/money.png",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/paymentinvoice',
                                        scripts: true
                                    });
                                }
                            },
                            {
                                id: 'invoice_editpayment',
                                text: 'Edit Payment Invoice',
                                cls: "x-btn-text-icon",
                                icon: "/images/icons/fam/page_edit.gif",
                                handler: function()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/invoice/editpaymentinvoice',
                                        scripts: true
                                    });
                                }
                                }
                        ]
                    }
                }

            ]

        })
        
        function getExchangeRate()
        {
            Ext.Ajax.request({
                url: '/default/valuta/getexchangerate/val_kode/USD',
                method: 'POST',
                success: function(result, request) {
                    var returnData = Ext.util.JSON.decode(result.responseText);
                    if (returnData.success) {
                        if(returnData.rate == 0)
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Please Input Current IDR Rate. Thank You.',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR,
                                fn:function(){window.location='';}
                            });
                        }
                    
                        Ext.getCmp('rateidr').setValue(returnData.rate);
                    }
                },
                failure: function(action) {
                    if (action.failureType == 'server') {
                        obj = Ext.util.JSON.decode(action.response.responseText);
                        Ext.Msg.alert('Error!', obj.errors.reason);
                    }
                }
            });
        }
        getExchangeRate();

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c) {
            centerRegionTab.remove(c);
        });
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');


    })


</script>
<div id="aaa"></div>