<style type="text/css">
    fieldset {
        margin: 5px 10px 5px 5px;
        -moz-border-radius:15px;
        border-radius: 15px;
        -webkit-border-radius: 15px; //edit :D
    }
    h4 {
        margin: 5px 10px 5px 5px;
        font-size: 13px;
    }
</style>
<h4>Project Manager : <?=$this->pm?></h4>
<h4>Project Control : <?=$this->pc?></h4>
<h4>Activity for <?=$this->prjKode?> - <?=$this->prjNama?></h4>
<fieldset>
<table id="hor-minimalist-b">
    <thead>
        <tr>
            <td><h4>Submit New Document Activity</h4></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
    <?php
        $last = '';
        foreach($this->data['data']['totalactivity'] as $key => $val) {
    ?>
        <?php
            foreach($val as $key2 => $val2) {
        ?>
        <tr>
            <?php if ($last != $key || $last == '') { ?>
            <td><?php echo $key; ?></td>
            <?php } else { ?>
            <td>&nbsp;</td>
            <?php } ?>
            <td><a href="#" onclick="window.open('/default/projectdashboard/showtrans/item_type/<?=$key?>/uid/<?=$val2['uid']?>/prj_kode/<?=$this->prjKode?>','projectdashboard-popup','toolbar=0,scrollbars=1');"><?php echo $val2['name']; ?></a></td>
            <td align="right"><?=number_format($val2['jumlah'],2)?></td>
        </tr>
        <?php
            $last = $key;
            }
        ?>
    <?php
        }
    ?>
    </tbody>
</table>
</fieldset>
