<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var windowForm =  ({

        title: 'List Material Pulsa for Bank Payment Voucher',
        id: 'abs-budget-panel',
        layout: 'fit',
        bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
        bodyStyle: 'padding:15px;',
        loadMask: true,
        minWidth: 300,
        minHeight: 200,
        tbar: [{
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                        items: [{
                                    id: 'show_button',
                                    text: 'Insert Pulsa',
                                    cls:"x-btn-text-icon" ,
                                    icon:"/images/icons/fam/grid.png",
                                    handler:function()
                                    {
                                        myPanel = Ext.getCmp('abs-budget-panel');
                                        myPanel.body.load({
                                            url: '/admin/document/insertpulsa',
                                            scripts : true
                                        });
                                    }
                                }]
                        }
                }]

});
    viewPort = Ext.getCmp('viewport');

    centerRegionTab = viewPort.getComponent('content-panel');
    centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
    centerRegionTab.add(windowForm);
    panelBaru = Ext.getCmp('abs-budget-panel');
    centerRegionTab.layout.setActiveItem('abs-budget-panel');
    panelBaru = Ext.getCmp('abs-budget-panel');
    panelBaru.body.load({
            url: '/admin/document/viewpulsa',
            scripts: true
        });
    showSubmenu('abs-budget-panel');

    })



</script>
