<style type="text/css">
@page
{
	size: landscape;
	margin: 2cm;
}
th, td {
	border: 1px solid #cccccc;
	padding: 3px 6px 3px 4px;
	white-space: nowrap;
}
</style>
<style type="text/css" media="print">
@page
{
	size: landscape;
	margin: 2cm;
}
</style>

<h1>GENERAL REPORT <?=$this->prjKode?> - <?=$this->sitKode?></h1>

<?php if ($this->salary > 0) { ?>
<b>Total Salary : IDR <?=number_format($this->salary,2)?></b>
<?php } ?>

<table>
    <thead>
    	<tr>
            <th rowspan="2"><b>No.</b></th>
            <th scope="col" rowspan="2"><b>Product</b></th>
            <th scope="col" rowspan="2"><b>Product Code</b></th>
            <th scope="col" rowspan="2"><b>WorkID</b></th>
            <th scope="col" rowspan="2"><b>Uom</b></th>
            <th scope="col" colspan="3"><b>Budget</b></th>
            <th scope="col" colspan="3"><b>PR</b></th>
            <th scope="col" colspan="3"><b>PO</b></th>
            <th scope="col" colspan="3"><b>RPI</b></th>
            <!--<th scope="col" class="rounded-q2" colspan="3"><b>Payment For RPI</b></th>-->
            <th scope="col" colspan="3"><b>ARF</b></th>
            <th scope="col" colspan="3"><b>ASF</b></th>
            <th scope="col" colspan="3"><b>ASF Cancel</b></th>
            <!--<th scope="col" class="rounded-q2" colspan="3"><b>Payment For ASF</b></th>-->
            <th scope="col" ><b>DO</b></th>
            <th scope="col" ><b>DOR</b></th>
        </tr>
		<tr>
			<!--<th scope="col" class="rounded-q1">Qty</th>-->
			<!--<th scope="col" class="rounded-q1">IDR</th>-->
			<!--<th scope="col" class="rounded-q1">USD</th>-->
			<!--<th scope="col" class="rounded-q1">Qty</th>-->
			<!--<th scope="col" class="rounded-q1">IDR</th>-->
			<!--<th scope="col" class="rounded-q1">USD</th>-->
			<!--<th scope="col" class="rounded-q1">Qty</th>-->
			<!--<th scope="col" class="rounded-q1">IDR</th>-->
			<!--<th scope="col" class="rounded-q1">USD</th>-->
			<!--<th scope="col" class="rounded-q1">Qty</th>-->
			<!--<th scope="col" class="rounded-q1">IDR</th>-->
			<!--<th scope="col" class="rounded-q1">USD</th>-->
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
			<th scope="col" >Qty</th>
			<th scope="col" >IDR</th>
			<th scope="col" >USD</th>
            <th scope="col" >Qty</th>
            <th scope="col" >Qty</th>

		</tr>


    </thead>

    <div style="overflow-y:auto">
    <tbody>
    <?php
            $no = 1;
            foreach($this->result as $key => $val)
            {
    ?>
        <tr>
            <td align="right"><?=$no?></td>
            <td><?=$val['nama_brg']?></td>
            <td><?=$val['kode_brg']?></td>
            <td><?=$val['workid']?></td>
            <td><?=$val['sat_kode']?></td>
            <td align="right"><?=number_format($val['qty'],4)?></td>
            <td align="right"><?=number_format($val['totalHargaIDR'],2)?></td>
            <td align="right"><?=number_format($val['totalHargaUSD'],2)?></td>
            <td align="right"><?=number_format($val['pr']['qty'],4)?></td>
            <td align="right"><?=number_format($val['pr']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['pr']['USD'],2)?></td>
            <td align="right"><?=number_format($val['po']['qty'],4)?></td>
            <td align="right"><?=number_format($val['po']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['po']['USD'],2)?></td>
            <td align="right"><?=number_format($val['rpi']['qty'],4)?></td>
            <td align="right"><?=number_format($val['rpi']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['rpi']['USD'],2)?></td>
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <!--<td></td>-->
            <td align="right"><?=number_format($val['arf']['qty'],4)?></td>
            <td align="right"><?=number_format($val['arf']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['arf']['USD'],2)?></td>
            <td align="right"><?=number_format($val['asf']['qty'],4)?></td>
            <td align="right"><?=number_format($val['asf']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['asf']['USD'],2)?></td>
            <td align="right"><?=number_format($val['asfc']['qty'],4)?></td>
            <td align="right"><?=number_format($val['asfc']['IDR'],2)?></td>
            <td align="right"><?=number_format($val['asfc']['USD'],2)?></td>
            <td align="right"><?=number_format($val['dor']['qty'],4)?></td>
            <td align="right"><?=number_format($val['do']['qty'],4)?></td>
        </tr>
    <?php
            $no++;
            }
    ?>
    <!--    TOTAL -->
    <tr style="background-color: #CFDCEE">
        <td colspan="4" align="center"><b>TOTAL</b></td>
        <td colspan="2">&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['boq3']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['boq3']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['pr']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['pr']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['po']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['po']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['rpi']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['rpi']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['arf']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['arf']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['asf']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['asf']['USD'],2)?></b></td>
        <td >&nbsp;</td>
        <td align="right"><b><?=number_format($this->total['asfc']['IDR'],2)?></b></td>
        <td align="right"><b><?=number_format($this->total['asfc']['USD'],2)?></b></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    </tbody>
    <tfoot>

    </tfoot>
    </div>
</table>
<script type="text/javascript">
//window.print();
</script>