<?php 
/* 
	Created @ April 12, 2010 by Haryadi
 */
?>

<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<img src="/images/qdc.gif" />
<br>
<br>
<table border=0 tablewidth="800">
	<tr><td>Project</td><td>: <?php echo $this->result[0]['prj_kode']; ?> - <?php echo $this->result[0]['prj_nama']; ?><br></td></tr> 
	<tr><td>Site</td><td>: <?php echo $this->result[0]['sit_kode']; ?> - <?php echo $this->result[0]['sit_nama']; ?></td></tr>	 
	<tr><td>Work</td><td>: <?php echo $this->result[0]['workname']; ?></td></tr>
	<tr><td>PO</td><td>: <?php echo $this->result[0]['trano']; ?></td></tr>
	<tr><td>Supplier</td><td>: <?php echo $this->result[0]['sup_nama']; ?></td></tr>
</table>

<div align="center"> 
<table id="rounded-corner" tablewidth="800">
<caption><font size=5 face=arial><b>Purchase Order</b></font></caption>
    <thead>
    	<tr>       
            <th align=center scope="col" class="rounded-q5"><b>Material</b></th>             
            <th align=center scope="col" class="rounded-q6"><b>Qty</b></th>
            <th align=center scope="col" class="rounded-q7"><b>Curr</b></th> 
            <th align=center scope="col" class="rounded-q8"><b>Unit Price</b></th>
            <th align=center scope="col" class="rounded-q9"><b>Tax</b></th> 
            <th align=center scope="col" class="rounded-q10"><b>Total</b></th>                   
        </tr>
    </thead>
    <tbody>
    	<?php
            
            for($i=0;$i<count($this->result);$i++)
            
            {
                $no = $i + 1;               
        ?>
        
        <tr>
            <td><?php echo $this->result[$i]['nama_brg']; ?></td>       
            <td><?php echo $this->result[$i]['qty']; ?></td>
            <td><?php echo $this->result[$i]['val_kode']; ?></td>
            <td><?php echo $this->result[$i]['harga']; ?></td>
            <td><?php echo $this->result[$i]['ppn']; ?></td>
            <td><?php echo $this->result[$i]['total']; ?></td>         
       </tr>        
   	<?php 
        }
   	?>
   	
    </tbody>
</table>
</div>