<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var typesuppstore = new Ext.data.Store ({

            autoLoad:true,
            url:'/logistic/logistictypesupplier/gettypesupp',
            reader:new Ext.data.JsonReader ({
                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'id'
                },{
                    name:'jenisupplier'
                },{
                    name:'jenissupliernama'
                }]
            })


        })

        var typesuppgrid = new Ext.grid.GridPanel ({

            store:typesuppstore,
            frame:'true',
            title:'Type Supplier List',
            renderTo:'list_supplier',
            height:300,
            width:460,
            columns:[new Ext.grid.RowNumberer(),{
                header:'Supplier Type',
                dataIndex:'jenisupplier',
                sortable:true,
                width:120
            },{
                header:'Supplier Type Name',
                dataIndex:'jenissupliernama',
                sortable:true,
                width:340
            }],
            bbar:new Ext.PagingToolbar ({
                id: 'paging-typesupp',
                pageSize: 20,
                store: typesuppstore,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            })



        })


    })


</script>

    <div id="list_supplier"></div>
