 <script type="text/javascript">
    Ext.onReady(function(){
        Ext.QuickTips.init();

        <?php echo $this->action('index','textfield',null); ?>
        
        generalStockCard = function (){
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/logistic/report/gencardstock',
                scripts: true
            });
        };
        detailStockCard = function (){
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/logistic/report/detcardstock',
                scripts: true
            });
        };

        var windowForm = ({
            title: 'Stock Card Report',
            id:'abs-budget-panel',
            layout:'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [{
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu:{
                        items: [

                            {
                                id:'gs_add_button',
                                text:'General Stock Card Report',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/action_paste.gif",
				                handler:generalStockCard
                            },
                            {
                                id:'dcs_add_button',
                                text:'Detail Stock Card Report',
                                cls:'x-btn-text-icon',
                                icon:"/images/icons/fam/action_paste.gif",
				                handler:detailStockCard
                            }
                           
                        ]
                    }
            }]

        });

        viewPort = Ext.getCmp('viewport');
        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
         myPanel = Ext.getCmp('abs-budget-panel');

        showSubmenu('abs-budget-panel');
    });
</script>