<script type="text/javascript">
    showPrint = function() {
        prjKode = Ext.getCmp('prj_kode_text').getValue();
        sitKode = Ext.getCmp('sit_kode_text').getValue();

        if (prjKode == '')
        {
            Ext.MessageBox.show({
                title: 'Error',
                msg: 'Please Insert/Select Project Code!',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.ERROR
            });
            return false;

        }

        if (sitKode == '')
        {
            Ext.MessageBox.show({
                title: 'Error',
                msg: 'Please Insert/Select Site Code!',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.ERROR
            });
            return false;

        }
        window.open('/projectmanagement/report/general/print/true/prj_kode/' + prjKode + '/sit_kode/' + sitKode,'general-report','toolbar=0');
    };

    showReport = function(){
        myPanel = Ext.getCmp('abs-budget-panel');
        perKode = Ext.getCmp('periode_text').getValue();
        option = Ext.getCmp('option').getValue();
        search = Ext.getCmp('search').getValue();

        if (perKode == '')
        {
            Ext.MessageBox.show({
                title: 'Error',
                msg: 'Please Select Periode Code!',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.ERROR
            });
            return false;

        }

        myPanel.body.load({
            url: '/logistic/report/showinventory/perkode/' + perKode + '/option/' + option + '/search/' + search,
            scripts: true

        });
    };

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var windowForm = ({

            title:'Closing Inventory Report',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype: 'tbtext',
                    text: 'Periode'
                },
                {
                    xtype: 'periodefinanceselector',
                    id: 'perkode_text',
                    Selectid: 'periode_text',
                    inventory: true,
                    width: 150
                },
                '-',
                {
                    xtype: 'tbtext',
                    text: 'Search By'
                },
                {
                    id : 'option',
                    name: 'option',
                    xtype: 'combo',
                    width: 100,
                    store: new Ext.data.SimpleStore({
                        fields:['name','nilai'],
                        data:[
                            ['Product ID','kode_brg'],
                            ['Product Name','nama_brg']
                        ]
                    }),
                    valueField:'nilai',
                    displayField:'name',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'local',
                    triggerAction: 'all',
                    selectOnFocus: true,
                    value: 'kode_brg'
                },
                {
                    xtype: 'textfield',
                    name: 'search',
                    id: 'search',
                    width: 125
                },
                '-',
                {
                    xtype: 'button',
                    text: 'Show',
                    width:70,
                    id: 'show_budget',
                    cls:"x-btn-text-icon" ,
                    icon:"/images/icons/fam/control_rewind.png",
                    handler:showReport
                },
                '-',
                {
                    xtype: 'button',
                    id: 'export_button',
                    cls:"x-btn-icon" ,
                    icon:"/images/print.png",
                    handler: showPrint
                }
            ]

        });

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        showSubmenu('abs-budget-panel');


    })


</script>