<?php
if (count($this->result) == 0) {
    echo "No Data to display...";
    die();
}
?>

<link rel="stylesheet" type="text/css" href="/css/superTables.css"/>
<script type="text/javascript" src="/js/layout/base/superTables.js"></script>
<style type="text/css">

    .parentContainer{
        margin: 5px;
        padding: 0px;
        border: none;
        width: 900px;
        height: 420px;
        overflow: auto;
        font-size: 14px;
    }
</style>
<div style="border-bottom: 2px solid #99BBE8;width:900px;float:left;margin-bottom: 10px;">
    <h1 style="font-size: 18px;font-family: tahoma,verdana,arial,sans-serif;">Price History Report</h1>

</div>
<br>
<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
            <tr>
                <th scope="col"><center>No</center></th>
        <th scope="col"><center>Trans No</center></th>
        <th scope="col"><center>Date</center></th>
        <th scope="col"><center>Product ID</center></th>
        <th scope="col"><center>Description</center></th>
        <th scope="col"><center>Currency</center></th>
        <th scope="col"><center>UOM</center></th>
        <th scope="col"><center>Price</center></th>
        <th scope="col"><center>Vendor</center></th>
        <th scope="col"><center>Vendor Name</center></th>
        <th scope="col"><center>Vendor City</center></th>
        </tr>
        </thead>
        <tbody>

<?php
$nomer = 1;
foreach ($this->result as $key => $v) {
        ?>
                    <tr>
                        <td><?= $nomer; ?></td>
                        <td><?= ($v['tra_no'] != '') ? $v['tra_no'] : "&nbsp;" ?></td>
                        <td><?= ($v['tgl'] != '') ? $v['tgl'] : "&nbsp;" ?></td>
                        <td><?= ($v['brg_kode'] != '') ? $v['brg_kode'] : "&nbsp;" ?></td>
                        <td><?= ($v['brg_nama'] != '') ? $v['brg_nama'] : "&nbsp;" ?></td>
                        <td><?= ($v['val_kode'] != '') ? $v['val_kode'] : "&nbsp;" ?></td>
                        <td><?= ($v['sat_kode'] != '') ? $v['sat_kode'] : "&nbsp;" ?></td>
                        <td><?= ($v['harga'] != '') ? number_format($v['harga'],2) : "&nbsp;" ?></td>
                        <td><?= ($v['sup_kode'] != '') ? $v['sup_kode'] : "&nbsp;" ?></td>
                        <td><?= ($v['sup_nama'] != '') ? $v['sup_nama'] : "&nbsp;" ?></td>
                        <td><?= ($v['master_kota'] != '') ? $v['master_kota'] : "&nbsp;" ?></td>

                    </tr>

        <?php
    $nomer++;
}
?>

        </tbody>
    </table>
</div>
<?=$this->pagingDefault($this->pageUrl,$this->totalResult,$this->limitPerPage,$this->current,$this->currentPage,$this->pagingParam)?>


<script type="text/javascript">

    (function() {
        var mySt = new superTable("budgetTable", {
            cssSkin: "sSky",
            fixedCols: 3,
            headerRows: 1
        });
    })();

</script>