<script type="text/javascript">

    var code = '<?=$this->code?>';
    var tgl = '<?=$this->tgl?>';
    var pic = '<?=$this->pic?>';
    var status = '<?=$this->status?>';
    var sup_kode = '<?=$this->sup_kode?>';

    Ext.onReady(function(){


        var storetrans = new Ext.data.Store({

        url:'/logistic/report/getviewreportasset/code/' + code + '/tgl/' + tgl + '/pic/' + pic + '/status/' + status + '/sup_kode/' + sup_kode,
        autoLoad:true,
            reader:new Ext.data.JsonReader ({
                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'trano'
                },{
                    name:'token'
                },{
                    name:'code'
                },{
                    name:'tgl'
                },{
                    name:'uid'
                },{
                    name:'uid_pic'
                },{
                    name:'status'
                },{
                    name:'condition'
                },{
                    name:'ket'
                },{
                    name:'sup_kode'
                },{
                    name:'sup_nama'
                },{
                    name:'description'
                }]
            })

        })

        var expander = new Ext.ux.grid.RowExpander({
            tpl : new Ext.Template(
//                    '<div style="margin-left:30px;"><p><br>',
                    '<p><b>Comment :</b> {ket}</p>',
                    '<p><b>Supplier :</b> {sup_nama}</p><br></div>'
                   )
        });

        var gridtrans = new Ext.grid.GridPanel ({

            store:storetrans,
            height:300,
            renderTo:'trans-grid',
            frame:true,
            viewConfig:{
                forceFit:true
            },
            plugins:[expander],
            columns:[expander,new Ext.grid.RowNumberer(),{
                header:'Trano',
                dataIndex:'trano',
                sortable:true
            },{
                header:'Code',
                dataIndex:'code',
                sortable:true
            },{
                header:'Description',
                dataIndex:'description',
                sortable:true
            },{
                header:'Date',
                dataIndex:'tgl',
                sortable:true,
                renderer: Ext.util.Format.dateRenderer('d M Y H:i:s')
            },{
                header:'PIC',
                dataIndex:'uid_pic',
                sortable:true
            },{
                header:'Status',
                dataIndex:'status',
                sortable:true
            },{
                header:'Condition',
                dataIndex:'condition',
                sortable:true
            }],bbar:new Ext.PagingToolbar ({
                id: 'paging-asset',
                pageSize: 20,
                store: storetrans,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            })
        })


    })


</script>

    <div id="trans-grid"></div>