<script type="text/javascript">
showMenuManager = function(){
    myPanel = Ext.getCmp('abs-budget-panel');
    myPanel.body.load({
        url: '/admin/menu/menu-manager',
        scripts : true
    });
};
showMenu = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/menu/view',
	        scripts : true
        });
	};
showMenuRole = function(){
    myPanel = Ext.getCmp('abs-budget-panel');
    myPanel.body.load({
        url: '/admin/menu/add-privilege-by-role',
        scripts : true
    });
};
showSubMenu = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/admin/menu/viewsubmenu',
	        scripts : true
        });
	};
var windowForm =  ({

    title: 'Menu Management',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    loadMask: true,
    minWidth: 300,
    minHeight: 200,
    tbar: [
            {
                xtype: 'button',
                text: 'Menu Manager',
                cls:"x-btn-text-icon" ,
                icon:"/images/icons/fam/action_paste.gif",
                handler:showMenuManager
            },
            {
                text: 'Add Menu Privilege',
                icon:"/images/icons/fam/action_paste.gif",
                style: {
                    overflow: 'visible'     // For the Combo popup
                },
                menu: {
                    xtype: 'menu',
                    plain: true,
                    items: [
                        {
                            text: 'By Person',
                            handler:showMenu,
                            iconCls: 'silk-user-add'
                        },
                        {
                            text: 'By Role',
                            handler:showMenuRole,
                            iconCls: 'silk-user-comment'
                        }
                    ]
                }
            },
            {
			    xtype: 'button',
			    id: 'submenu_process_button',
			    text: 'Add Sub Menu Privilege',
			    cls:"x-btn-text-icon" ,
			    icon:"/images/icons/fam/action_paste.gif",
			    handler:showSubMenu
			}
           ]

});
viewPort = Ext.getCmp('viewport');

centerRegionTab = viewPort.getComponent('content-panel');
centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
centerRegionTab.add(windowForm);
panelBaru = Ext.getCmp('abs-budget-panel');
centerRegionTab.layout.setActiveItem('abs-budget-panel');
</script>