<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">

<b>Pra BOQ3 Number : <?php echo $this->trano; ?></b>
<br></br>
<table id="mytable" cellspacing="0">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Work</center></th>
            <th scope="col"><center>Product</center></th>
            <th scope="col"><center>UOM</center></th>
            <th scope="col"><center>Qty</center></th>
            <th scope="col"><center>Valuta</center></th>
            <th scope="col"><center>Price</center></th>
            <th scope="col"><center>Exchange Rate</center></th>
            <th scope="col"><center>Total</center></th>
        </tr>
    	<?php
    		$totals = 0;
    		for ($i=0;$i<(count($this->result));$i++)
    		{
    			foreach ($this->result[$i] as $key => $val)
    			{
    				if ($val == '')
    					$this->result[$i][$key] = "&nbsp;";
    			}

                if ($this->result[$i]['val_kode'] == 'IDR')
                {
                    $total = floatval($this->result[$i]['qty']) * floatval($this->result[$i]['harga']);
                    $totalIDR += $total;
                    $rate = '&nbsp;';
                }
                else
                {
                    $total = $this->result[$i]['qty'] * $this->result[$i]['harga'];
                    $totalUSD += $total;
                    $rate = number_format($this->result[$i]['rateidr'],2);
                }
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
    		<td><?=$this->result[$i]['workid'] . "-" . $this->result[$i]['workname']?></td>
    		<td><?=$this->result[$i]['kode_brg']?> - <?=$this->result[$i]['nama_brg']?></td>
    		<td><?=$this->result[$i]['uom']?></td>
    		<td align="right"><?=number_format(floatval($this->result[$i]['qty']),2)?></td>
            <td><?=$this->result[$i]['val_kode']?></td>
    		<td align="right"><?=number_format(floatval($this->result[$i]['harga']),2)?></td>
    		<td align="right"><?=$rate?></td>
    		<td align="right"><?=number_format($total,2)?></td>
    		</tr>
    	<?php

    		}

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="8" rowspan="2">Grand Total</th>
    		<td align="right">IDR <?=number_format($totalIDR)?></td>
    	</tr>
        <tr>
    		<td align="right">USD <?=number_format($totalUSD)?></td>
    	</tr>
</table>

</div>