<script type="text/javascript">

    var proxy = new Ext.data.HttpProxy({
       url : '/default/home/getboq3summary'

        // /default/home/getboq3summary <param prj_kode,sit_kode>
    });

    function showboq3 (prj_kode,sit_kode)
        {
            boq3store.load({
                params: {
                    prj_kode: prj_kode,
                    sit_kode: sit_kode
                }
            });
        }

    var proxy = new Ext.data.HttpProxy({
           url : '/default/home/getboq3summary'

            // /default/home/getboq3summary <param prj_kode,sit_kode>
    });

    var boq3store = new Ext.data.Store({
        id:'boq3store',
        proxy:proxy,
        reader:new Ext.data.JsonReader ({
            root:'posts',
            totalProperty:'count',
            fields:[{
                name:'workid'
            },{
                name:'workname'
            },{
                name:'cfs_kode'
            },{
                name:'cfs_nama'
            },{
                name:'kode_brg'
            },{
                name:'nama_brg'
            },{
                name:'qty'
            },{
                name:'val_kode'
            },{
                name:'tgl'
            },{
                name:'hargaIDR'
            },{
                name:'hargaUSD'
            },{
                name:'totalIDR'
            },{
                name:'totalUSD'
            },{
                name:'totalHargaIDR'
            },{
                name:'totalHargaUSD'
            },{
                name:'uom'
            },{
                name:'price'
            },{
                name:'totalPrice'
            },{
                name:'id'
            }]
        })
    })

    Ext.onReady(function(){

        Ext.QuickTips.init();

        function showWindow() {
            var forminsertnewsite = new Ext.form.FormPanel ({

                title:'Change Site Code And Site Name',
                id:'change-site',
                frame:true,
                layout:'form',
                width:346,
                items:[{
                    xtype:'textfield',
                    fieldLabel:'New Site Code ',
                    labelStyle:'width:140',
                    allowBlank: false,
                    id:'site_code',
                    maxLength:2
                },{
                    xtype:'textfield',
                    fieldLabel:'New Site Name ',
                    labelStyle:'width:140',
                    allowBlank: false,
                    id:'site_name'
                }],
                buttons:[{
                    text:'Submit',
                    handler:function(btn,ev)
                    {
                        var new_sit_kode = Ext.getCmp('site_code').getValue();
                        var new_sit_name = Ext.getCmp('site_name').getValue();

                        if (new_sit_kode == '')
                        {
                            Ext.MessageBox.show({
                            title: 'Error',
                            msg: 'Sorry , Please Insert new site code',
                            buttons: Ext.MessageBox.OK,
                            icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }

                        if (new_sit_name == '')
                        {
                            Ext.MessageBox.show({
                            title: 'Error',
                            msg: 'Sorry , Please Insert new site name',
                            buttons: Ext.MessageBox.OK,
                            icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }


                        Ext.MessageBox.confirm('Confirm','Are you sure want this action ?',function(btn){

                            if (btn == 'yes'){

                                var prj_kode = Ext.getCmp('prj_kode_text').getValue();
                                var sit_kode = Ext.getCmp('sit_kode_text').getValue();

//                                var boq3data = '';
//                                boq3store.each(function(store){
//                                    boq3data += Ext.util.JSON.encode(store.data) + ',';
//                                })
//
//                                boq3data = '[' + boq3data.substring(0, boq3data.length - 1) + ']';

                                var params = {
//                                    boq3data:boq3data,
                                    prj_kode:prj_kode,
                                    sit_kode:sit_kode,
                                    new_sit_kode:new_sit_kode,
                                    new_sit_name:new_sit_name
                                }
                                Ext.getBody().mask('Loading..','x-mask-loading',false);
                                Ext.Ajax.request({
                                    url:'/projectmanagement/budget/doupdatesiteboq3',
                                    method:'POST',
                                    params:params,
                                    success:function(result){
                                        Ext.getBody().unmask();
                                        obj = Ext.util.JSON.decode(result.responseText);

                                        if (obj.success)
                                        {
                                            windowinsert.close();
                                            Ext.Msg.alert ('Message','Success, site code dan site name has been update');
                                            myPanel = Ext.getCmp('abs-budget-panel');
                                            myPanel.body.load({
                                            url: '/projectmanagement/budget/showcreateboq3',
                                            scripts : true
                                            });
                                        }else
                                        {
                                            Ext.Msg.alert('Error', obj.msg);
                                        }
                                    },
                                    failure:function( action){
                                        Ext.getBody().unmask();
                                        if(action.failureType == 'server'){
                                          obj = Ext.util.JSON.decode(action.response.responseText);
                                          Ext.Msg.alert('Error!', obj.errors.reason);
                                        }else{
                                          Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
                                        }
                                    }

                                })

                            }


                        })
                    }
                },{
                    text:'Reset',
                    handler:function(btn,ev)
                    {
                        Ext.getCmp('site_code').setValue("");
                        Ext.getCmp('site_name').setValue("");
                    }
                },{
                    text:'Cancel',
                    handler:function(btn,ev)
                    {
                        windowinsert.close();
                    }
                }]


            })

            windowinsert = new Ext.Window ({

            //                title:'Choose Brand',
                id:'window-insert',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 360,
                height:150,
                loadMask:true,
                items:[forminsertnewsite]

            });

            windowinsert.show();
        }

        var grid = new Ext.grid.GridPanel ({

            id: 'edit-cfs-grid',
            renderTo:'edit_cfs_grid',
            store: boq3store,
            title:'Edit Site BOQ3',
            height: 400,
            frame: true,
            columns:[new Ext.grid.RowNumberer(),{
                header:'Workid',
                dataIndex:'workid',
                align:'center'
            },{
                header:'Work Name',
                dataIndex:'workname',
                align:'center'
            },{
                header:'CFS code',
                dataIndex:'cfs_kode',
                align:'center'
            },{
                header:'CFS Name',
                dataIndex:'cfs_nama',
                align:'center'
            },{
                header:'Code Barang',
                dataIndex:'kode_brg',
                align:'center'
            },{
                header:'Nama Barang',
                dataIndex:'nama_brg',
                align:'center'
            },{
                header:'Qty',
                dataIndex:'qty',
                align:'center'
            },{
                header:'UOM',
                dataIndex:'uom',
                align:'center'
            },{
                header:'Valuta',
                dataIndex:'val_kode',
                align:'center'
            },{
                header:'Price',
                dataIndex:'price',
                align:'right',
                renderer: function(v,p,r){
                    var value = Ext.util.Format.number(v,'?0,000.00');
                    return value;
                }
            },{
                header:'Total Price',
                dataIndex:'totalPrice',
                align:'right',
                renderer: function(v,p,r){
                    var value = Ext.util.Format.number(v,'?0,000.00');
                    return value;
                }
            }],
            tbar:[{
                xtype:'label',
                text:'Project Code',
                style:'margin-left:10px;'
            },'-',{
                xtype: 'projectselector',
                id: 'project-select',
                Selectid: 'prj_kode_text',
                allowBlank:false
            },'-',{
                xtype:'label',
                text:'Site Code',
                style:'margin-left:10px;'
            },'-',{
                xtype: 'siteselector',
                independent: false,
                id: 'site-select',
                SiteSelectid: 'sit_kode_text',
                ProjectSelectid: 'prj_kode_text',
                allowBlank:false
            },'-',{
                xtype: 'button',
                text: 'Show',
                width:70,
                id: 'show_ap',
                cls:"x-btn-text-icon" ,
                icon:"/images/icons/fam/control_rewind.png",
                style:'margin-left:10px;',
                handler:function(btn,ev)
                {
                    var prj_kode = Ext.getCmp('prj_kode_text').getValue();
                    var sit_kode = Ext.getCmp('sit_kode_text').getValue();

                    if (prj_kode == '')
                    {
                        Ext.MessageBox.show({
                        title: 'Error',
                        msg: 'Sorry , Please Insert Project Code',
                        buttons: Ext.MessageBox.OK,
                        icon: Ext.MessageBox.ERROR
                        });
                        return false;
                    }

                    if (sit_kode == '')
                    {
                        Ext.MessageBox.show({
                        title: 'Error',
                        msg: 'Sorry , Please Insert Site Code',
                        buttons: Ext.MessageBox.OK,
                        icon: Ext.MessageBox.ERROR
                        });
                        return false;
                    }

                    showboq3 (prj_kode,sit_kode);

                }
            }],
            buttons:[{
                iconCls:'icon-save',
                text:'Change Site',
                handler:function(btn,ev)
                {
                    if (grid.getStore().getCount() == 0)
                    return false;

                    showWindow();

//                    Ext.MessageBox.confirm('Confirm','Are you sure want this action ?',function(btn){
//
//                        if (btn == 'yes')
//                        {
//                            var prj_kode = Ext.getCmp('prj_kode_text').getValue();
//                            var sit_kode = Ext.getCmp('sit_kode_text').getValue();
//
//                            var boq3data = '';
//                            boq3store.each(function(store){
//                                boq3data += Ext.util.JSON.encode(store.data) + ',';
//                            })
//
//                            boq3data = '[' + boq3data.substring(0, boq3data.length - 1) + ']';
//
//                            var params = {
//                                boq3data:boq3data,
//                                prj_kode:prj_kode,
//                                sit_kode:sit_kode
//                            }
//
//                            Ext.Ajax.request({
//                                url:'/projectmanagement/budget/doupdatecfsboq3',
//                                method:'POST',
//                                params:params,
//                                success:function(result){
//                                    obj = Ext.util.JSON.decode(result.responseText);
//
//                                    if (obj.success)
//                                    {
//                                        Ext.Msg.alert ('Message','Success, Data cfs in boq3 has been update');
//                                        myPanel = Ext.getCmp('abs-budget-panel');
//                                        myPanel.body.load({
//                                        url: '/projectmanagement/budget/showcreateboq3',
//                                        scripts : true
//                                        });
//                                    }else
//                                    {
//                                        Ext.Msg.alert('Error', obj.msg);
//                                    }
//                                },
//                                failure:function( action){
//                                    if(action.failureType == 'server'){
//                                      obj = Ext.util.JSON.decode(action.response.responseText);
//                                      Ext.Msg.alert('Error!', obj.errors.reason);
//                                    }else{
//                                      Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
//                                    }
//                                }
//
//                            })
//                        }
//
//                    })
                }
            }]
        })


    })



</script>

<div id="edit_cfs_grid"></div>