<script type="text/javascript">

    Ext.onReady (function(){

        Ext.QuickTips.init();

        var windowForm = ({

            title:'Construction Project Closing',
            id:'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        centerRegionTab.layout.setActiveItem('abs-budget-panel');

        myPanel = Ext.getCmp('abs-budget-panel');
        myPanel.body.load({
            url: '/finance/closing/add-construction',
            scripts : true
        });

    })


</script>