<style type="text/css">
    fieldset {
        margin: 5px 10px 5px 5px;
        -moz-border-radius:15px;
        border-radius: 15px;
        -webkit-border-radius: 15px; //edit :D
    }
    h4 {
        margin: 5px 10px 5px 5px;
        font-size: 13px;
    }
</style>
<h4>Project Manager : <?=$this->pm?></h4>
<h4>Project Control : <?=$this->pc?></h4>
<h4>Progress for <?=$this->prjKode?> - <?=$this->prjNama?></h4>
<fieldset>
<table id="hor-minimalist-b">
    <thead>
        <tr>
            <td><h4>Budget (BOQ)</h4></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Current</td>
            <td align="right">IDR <?=number_format($this->data['data']['boq3']['current']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['boq3']['current']['totalUSD'],2)?></td>
        </tr>
    </tbody>
</table>
</fieldset>
<fieldset>
<table id="hor-minimalist-b">
    <thead>
        <tr>
            <td><h4>Cost</h4></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Advance Settlement (ASF)</td>
            <td align="right">IDR <?=number_format($this->data['data']['asf']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['asf']['totalHargaUSD'],2)?></td>
        </tr>
        <tr>
            <td>Payment for Invoice (RPI)</td>
            <td align="right">IDR <?=number_format($this->data['data']['rpi']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['rpi']['totalHargaUSD'],2)?></td>
        </tr>
        <tr>
            <td>Delivery Order (DO)</td>
            <td align="right">IDR <?=number_format($this->data['data']['do']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['do']['totalHargaUSD'],2)?></td>
        </tr>
        <tr>
            <td>Piece Meal</td>
            <td align="right">IDR <?=number_format($this->data['data']['piecemeal']['totalPieceMeal'],2)?></td>
            <td align="right">USD <?=number_format(0,2)?></td>
        </tr>
        <tr>
            <td>Material Return (Cancel/Left Over)</td>
            <td align="right">IDR (<?=number_format($this->data['data']['materialreturn']['totalIDR'],2)?>)</td>
            <td align="right">USD (<?=number_format($this->data['data']['materialreturn']['totalHargaUSD'],2)?>)</td>
        </tr>
        <tr style="background:#8EBAFF">
            <td>Total</td>
            <td align="right">IDR <?=number_format($this->data['data']['cost']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['cost']['totalHargaUSD'],2)?></td>
        </tr>
    </tbody>
</table>
    </fieldset>
<fieldset>
<table id="hor-minimalist-b">
    <thead>
        <tr>
            <td><h4>Cost In Process</h4></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Purchase Order (PO)</td>
            <td align="right">IDR <?=number_format($this->data['data']['po']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['po']['totalHargaUSD'],2)?></td>
        </tr>
        <tr>
            <td>Advance Request (ARF)</td>
            <td align="right">IDR <?=number_format($this->data['data']['arf']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['arf']['totalHargaUSD'],2)?></td>
        </tr>
        
        <tr style="background:#8EBAFF">
            <td>Total</td>
            <td align="right">IDR <?=number_format($this->data['data']['costinprocess']['totalIDR'],2)?></td>
            <td align="right">USD <?=number_format($this->data['data']['costinprocess']['totalHargaUSD'],2)?></td>
        </tr>
    </tbody>
</table>
    </fieldset>