<style>

.files{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#E0ECEE;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}

.l{
    float: left;
    width: 220px;
    font-weight: bold;
    font-size: 13px;
}

.l2{
    float: left;
    width: 10px;
    font-weight: bold;
    font-size: 13px;
    margin-left:5px;
    margin-right:5px;
}

.body {
	/*width: 720px;*/
    overflow: auto;
}
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
	margin-bottom: 10px;
}
.etc {
	width: 100%;
}

.mid-etc {
	width:80%;
    margin-left : 25%;
}

.blok {

	font-size: 12px;
	font-weight: bold;
	margin-bottom: 2px;
}

.bottomline{
    background-color:#FFFFFF;
    border-bottom: 1px solid #fff;
    border-top: 1px solid #fff;
    border-left: 1px solid #fff;
    border-right: 1px solid #fff;
    text-decoration: underline;
}


.last-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.all-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#F6CBCA;
    color:#222222;
    padding:4px;
    text-align:left;
}
.all-approve{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    /*background:#CEE6C3;*/
    color:#222222;
    padding:4px;
    text-align:left;
    height: 200px;
    overflow: auto;
}

.ketin {
    width: 100%;
    font-size: 12px;
	font-weight: bold;
    background-color:#FBF0A5;
}
.ketin fieldset p {
    padding: 10px 10px 10px 10px;
}

.left {
	float: left;
	width: 48%;
}
.right {
	float: right;
	width: 48%;
}

#create-info {
    font-size: 12px;
    margin-left: 10px;
    margin-bottom: 10px;
}

#create-info label{
    font-weight: bold;
}

#supplier-info{
    font-size: 14px;
    width: 100%;
    margin-bottom: 10px;
}

#supplier-info legend{
    font-weight: bold;
}

#supplier-info ol
{
    margin-left: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
}

#supplier-info label
{
    font-weight: bold;
    font-size: 12px;
}

#supplier-size{
    font-size: 14px;
    width: 100%;
    margin-bottom: 10px;
}

#supplier-size legend{
    font-weight: bold;
}

#supplier-size ol
{
    margin-left: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
}

#supplier-size label
{
    font-weight: bold;
    font-size: 12px;
}

#supplier-bank{
    font-size: 14px;
    width: 100%;
    margin-bottom: 10px;
}

#supplier-bank legend{
    font-weight: bold;
}

#supplier-bank ol
{
    margin-left: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
}

#supplier-bank label
{
    font-weight: bold;
    font-size: 12px;
}

#status-info{
    font-weight: bold;
    font-size: 12px;
}

#status-info legend{
    font-weight: bold;
}

#status-info table{
    margin-left: 10px;
}

#status thead {
    background-color: color:#333;
}

#bodytable {
    overflow: auto;
    height: 160px;
    font-size: 8px;
}

#bodytable thead{
    font-size: 12px;
    font-weight: bold;;
}

#bodytable tbody{
    font-size: 12px;
}

.notif
{
    -moz-border-radius: 15px;
    border-radius: 15px;
    -webkit-border-radius: 15px;
    background:#E0ECEE;
}

.notif legend
{
    margin-left: 6px;
}

</style>
<style type="text/css">
    .x-grid3-td-name b {
            font-family:tahoma, verdana;
            display:block;
            color:#333;
    }
    .x-grid3-td-name b i {
        font-weight:normal;
        font-style: normal;
        color:#000;
    }
    .x-grid3-td-name .personicon {
        padding-left:20px;
        background:transparent url(/images/engineer-icon.png) no-repeat 0 2px;
    }
    .x-grid3-td-name .x-grid3-cell-inner {
        white-space:normal;
    }

    .x-grid3-row-body p {
        margin:5px 20px 10px 25px !important;
        color:#555;
    }

    .rolename {
        color:#333;
    }
</style>

<script type="text/javascript">

    function showfile(trano)
        {
            var storefile = new Ext.data.Store ({
                url:'/logistic/fixedasset/getfile/trano/' + trano,
                autoLoad:true,
                id:'store_file',
                reader:new Ext.data.JsonReader ({
                    root:'data',
                    totalProperty:'total',
                    fields:[{
                        name:'id'
                    },{
                        name:"trano"
                    },{
                        name:'prj_kode'
                    },{
                        name:'uid'
                    },{
                        name:'date'
                    },{
                        name:'savename'
                    },{
                        name:'filename'
                    }]
                })
            })

            var gridfile = new Ext.grid.GridPanel ({

                store:storefile,
                height:140,
                viewConfig:{
                    forceFit:true
                },
                columns:[new Ext.grid.RowNumberer(),
                {header: "File Name",width: 130, dataIndex: 'filename'},
                {header:'Action',width:40,sortable:true,css:'text-align:center;', renderer: function (v,p,r){
                    return '<a href="#" onclick="location.href= \'/default/file/download/path/files/filename/' + r.data['savename'] + '\'"><img src="/images/icons/fam/page_find.gif"></a>&nbsp;';
                }}]

            })

            var windowviewfile = new Ext.Window ({

                title:'File List',
                id:'window-view-file',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 360,
                height:150,
                loadMask:true,
                items:[gridfile]

            })

            windowviewfile.show();


        }

</script>

<link rel="stylesheet" type="text/css" href="/css/table.css"/>

    <div class="body">

        <div align="right"><img src="/images/imd.gif" alt= "logo imd" /></div>
        <div class="title">Asset Detail</div>

        <div id="create-info">
            <ol>
                <li><label>Code : </label><?=$this->tampil['code']?></li>
                <li><label>Old Code : </label><?=$this->tampil['old_code']?></li>
                <li><label>PIC : </label><?=$this->tampil['username']?></li>
                <li><label>Input Date : </label><?=($this->tampil['input_date'] != '') ? date('d-M-Y',strtotime($this->tampil['input_date'])) : ''?></li>
            </ol>
        </div>

        <div id="supplier-info">

            <fieldset class="notif">
                <legend>Location In</tbody>formation</legend>

                <ol>
                    <li><label>Marking Date : </label><?=($this->tampil['marking_date'] != '') ? date('d-M-Y',strtotime($this->tampil['marking_date'])) : '' ?></li>
                    <li><label>Location : </label><?=$this->tampil['location']?></li>
                    <li><label>Storage : </label><?=$this->tampil['storage']?></li>
                </ol>

            </fieldset>

        </div><!-- end supplier info -->

        <div id="supplier-size">

            <fieldset class="notif">
                <legend>Asset Information</legend>

                <div class="left">
                    <ol>
                        <li><label>Description : </label><?=$this->tampil['description']?></li>
                        <li><label>Clasification : </label><?=$this->tampil['clasification']?></li>
                        <li><label>Brand : </label><?=$this->tampil['brand']?></li>
                        <li><label>Type : </label><?=$this->tampil['type']?></li>
                        <li><label>Serial Number : </label><?=$this->tampil['serial_number']?></li>
                    </ol>
                </div>

                <div class="right">
                    <ol>
                        <li><label>Accessories : </label><?=$this->tampil['accessories']?></li>
                        <li><label>Condition : </label><?=$this->tampil['condition']?></li>
                        <li><label>Status : </label><?=$this->tampil['status_aktif']?></li>
                    </ol>
                </div>

            </fieldset>

        </div><!-- end supplier size -->

        <div id="supplier-bank">

            <fieldset class="notif">
                <legend>Purchase Information</legend>

                <div class="left">
                    <ol>
                        <li><label>Purchase Status : </label><?=$this->tampil['purchase_status']?></li>
                        <li><label>Purchase Date : </label><?=($this->tampil['purchase_date'] != '' ) ? date('d-M-Y',strtotime($this->tampil['purchase_date'])) : '' ?></li>
                        <li><label>Valuta : </label><?=$this->tampil['val_kode']?></li>
                    </ol>
                </div>

                <div class="right">
                    <ol>
                        <li><label>Purchase Price : </label><?=$this->tampil['val_kode'] . " " . number_format($this->tampil['purchase_price'],2)?></li>
                        <li><label>Depr Rate : </label><?=$this->tampil['depr_rate']?> %</li>
                        <li><label>Depr Exp/Month : </label><?=$this->tampil['val_kode'] . " " .number_format($this->tampil['depr_exp'],2)?></li>
                    </ol>
                </div>

            </fieldset>

        </div>

        <div id="status-info">

            <fieldset class="notif">
                <legend>Status Information</legend>
                <div id="bodytable">
                <table id="status">
                    <thead>
                        <td width="120" align="center">Date</td>
                        <td width="120" align="center">PIC</td>
                        <td width="120" align="center">Status</td>
                        <td width="120" align="center">Condition</td>
                        <td width="240" align="center">Comment</td>
                        <td width="140" align="center">Supplier</td>
                        <td width="100" align="center">File</td>
                    </thead>
                    <tbody>
                    <?php
                        $data = $this->trans;
                        foreach($data as $key => $val)
                        {
                    ?>

                    <tr>
                        <td align="center"><?=$val['tgl']?></td>
                        <td align="center"><?=$val['uid_pic']?></td>
                        <td align="center"><?=$val['status']?></td>
                        <td align="center"><?=$val['condition']?></td>
                        <td><?=$val['ket']?></td>
                        <td><?=$val['sup_nama']?></td>
                        <td align="center"><a href="#" onclick="showfile('<?=$val['trano']?>')"><img src="/images/list.png" width="20" height="20" style="margin: 2px 2px 2px 2px"/></a></td>
                    </tr>

                    <?php
                        }
                    ?>
                    </tbody>
                </table>
                </div>

            </fieldset>

        </div>

    </div>

