<script type="text/javascript">

    function showcoalist (tipe)
    {
        var coastore = new Ext.data.Store ({
            autoLoad:true,
            url:'/finance/paymentreimbursement/getcoalist',
            reader:new Ext.data.JsonReader ({
                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'coa_kode'
                },{
                    name:'coa_nama'
                },{
                    name:'tipe'
                }]
            })

        })

        var coagrid = new Ext.grid.GridPanel ({

            store:coastore,
            viewConfig:{
                forceFit:true
            },
            height:300,
            columns:[{
                header:'COA CODE',
                dataIndex:'coa_kode',
                align:'center',
                sortable:true
            },{
                header:'COA NAME',
                dataIndex:'coa_nama',
                align:'center',
                sortable:true
            },{
                header:'Type',
                dataIndex:'tipe',
                align:'center',
                sortable:true
            }],
            bbar:new Ext.PagingToolbar ({
                id: 'paging-coa',
                pageSize: 20,
                store: coastore,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),tbar:[{
                text:'Search By',
                xtype:'label',
                style:'margin-left:5px'
            },{
                xtype: 'combo',
                width: 100,
                allowBlank: false,
                store: new Ext.data.SimpleStore({
                    fields:['name','nilai'],
                    data:[
                            ['Coa Code',1],
                            ['Coa Name',2],
                            ['Coa Type',3]
                        ]
                }),
                valueField:'nilai',
                displayField:'name',
                typeAhead: true,
                forceSelection: true,
                editable: false,
                mode: 'local',
                triggerAction: 'all',
                selectOnFocus: true,
                value:1,
                id:'option'
            },{
                xtype:'textfield',
                id:'search',
                style:'margin-left:10px',
                enableKeyEvents:true,
                width:100,
                listeners:{
                    'keyup' : function (txttext,event)
                    {
                        var txttext = txttext.getValue();
                        if (txttext != "" && txttext.toString().length >= 3)
                        {
                            var option = Ext.getCmp('option').getValue();
                            var search = Ext.getCmp('search').getValue();

                            coastore.proxy.setUrl('/finance/paymentreimbursement/getcoalist/search/' + search + '/option/' + option);
                            coastore.reload();
                            coagrid.getView().refresh();
                        }
                    }
                }
            }],
            listeners:
            {
                'rowdblclick':function(gridaktif,rowIndex,e)
                {
                    isDbClick = true;
                    var coa = gridaktif.getStore().getAt(rowIndex);
                    var coa_kode = coa.get('coa_kode');

                    if(tipe == 'debet')
                    {
                        Ext.getCmp('coa_debit').setValue(coa_kode);
                    }else if (tipe == 'credit')
                    {
                        Ext.getCmp('coa_credit').setValue(coa_kode);
                    }

                    coawindow.close();

                }
            }



        })

        var coawindow = new Ext.Window ({

            title:'COA List',
            id:'coa-list-window',
            layout:'absolute',
            minHeight: 200,
            stateful:false,
            modal: true,
            resizable: false,
            closeAction: 'close',
            width: 432,
            height: 330,
            loadMask:true,
            items:[
                coagrid
            ]

        })

        coawindow.show();
    }

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var panel = new Ext.form.FormPanel ({

            title:'Insert Kategori Fixed Asset',
            id:'insert-kategori-fixed-asset',
            renderTo:'insert_kategori_fixed_asset',
            frame:true,
            width:300,
            items:[{
                xtype:'textfield',
                fieldLabel:'Code ',
                allowBlank:false,
                id:'code'
            },{
                xtype:'textfield',
                fieldLabel:'Kategori Name ',
                allowBlank:false,
                id:'name'
            },{
                xtype:'combo',
                fieldLabel:'COA Debet ',
                id:'coa_debit',
                triggerClass: 'teropong',
                allowBlank: false,
                editable : false,
                width:100,
                onTriggerClick:function()
                {
                   showcoalist ('debet')
                }
            },{
                xtype:'combo',
                fieldLabel:'COA Credit ',
                id:'coa_credit',
                triggerClass: 'teropong',
                allowBlank: false,
                editable : false,
                width:100,
                onTriggerClick:function()
                {
                   showcoalist ('credit')
                }
            }],
            buttons:[{
                text:'Submit',
                handler:function(btn,ev)
                {
                    if (!Ext.getCmp('insert-kategori-fixed-asset').getForm().isValid())
                    {
                        Ext.Msg.alert('Error','Form not valid');
                        return false;
                    }

                    Ext.MessageBox.confirm('Confirm','Are you sure want this action ?',function(btn){

                        if (btn == 'yes')
                        {
                            Ext.getBody().mask('Loading..','x-mask-loading',false);
                            Ext.getCmp('insert-kategori-fixed-asset').getForm().submit({
                            method:'POST',
                            url:'/finance/kategoriasset/doinsertkategoriasset',
                            success:function(thisForm,response){
                                Ext.getBody().unmask();
                            if (response.result.success)
                            {
                                Ext.Msg.alert('Message','Success, Data has been saved');
                                myPanel = Ext.getCmp('abs-budget-panel');
                                myPanel.body.load({
                                url: '/finance/kategoriasset/menu',
                                scripts : true

                                });
                            }
                            },
                            failure:function(thisForm,response){
                                Ext.getBody().unmask();
                                if (response.failureType == 'server')
                                {
                                    var resp = Ext.util.JSON.decode(response.response.responseText);
                                    Ext.Msg.alert('Error',resp.msg);
                                }
                            }
                            })
                        }

                    })
                }
            },{
                text:'Reset',
                handler:function(btn,ev)
                {
                    Ext.getCmp('insert-kategori-fixed-asset').getForm().reset();
                }
            }]


        })


    })


</script>

    <div id="insert_kategori_fixed_asset"></div>