<div id="paging-teks"><?=$this->current?> of <?=$this->totalResult?> Result</div>
<div id="paging2">
	<ul>
		<?php if ($this->currentPage > 1) {?>
		<li><a href="#" onclick="gotoPage(1);">First</a></li>
		<li><a href="#" onclick="gotoPage(<?=($this->currentPage-1)?>);">&lt; Previous</a></li>
		<?php }
			  if ($this->currentPage > 2)	 
			  {
			  	for($i=$this->currentPage-2;$i<=($this->currentPage-1);$i++)
			  	{
		?>
		<li><a href="#" onclick="gotoPage(<?=$i?>);"><?=$i?></a></li>	  		
		<?php 
			  	}
			  }
			  elseif ($this->currentPage > 1)
			  {
		?>
		<li><a href="#" onclick="gotoPage(1);">1</a></li>
		<?php 	  	
			  }		
		?>
		<li><a href="#" class="current"><?=$this->currentPage?></a></li>
		<?php 
			  if ($this->totalPage >= ($this->currentPage + 2 ))	 
			  {
			  	for($i=$this->currentPage+1;$i<=($this->currentPage+2);$i++)
			  	{
		?>
				<li><a href="#" onclick="gotoPage(<?=$i?>);"><?=$i?></a></li>
		<?php 
			  	}
			  }
			  elseif ($this->totalPage >= ($this->currentPage + 1 ))
			  {
		?>
				<li><a href="#" onclick="gotoPage(<?=$this->totalPage?>);"><?=$this->totalPage?></a></li>
		<?php 	  	
			  }		
			  if ($this->currentPage < $this->totalPage)
			  {
		?>		
		<li><a href="#" onclick="gotoPage(<?=($this->currentPage+1)?>);">Next &gt;</a></li>
		<li><a href="#" onclick="gotoPage(<?=$this->totalPage?>);">Last</a></li>
		<?php 	  	
			  }		
		?>
	</ul>
</div>
<script type="text/javascript">
function gotoPage(pageNum)
{
	var limit = <?=$this->limit?>;
	var currentPage = <?=$this->currentPage?>;

	var currents = 1 + ((pageNum - 1) * limit);
	 myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
		        url: '<?=$this->pageUrl?>',
	                scripts: true,
	                params: {currentPage: pageNum, current: currents}

		});
}
</script>