<style type="text/css">
    /* Image classes */

    #preview-image {
        background:#fff;
        color:#222;
        font:normal 12px tahoma,verdana,arial,sans-serif;
    }

    .preview-image .x-panel-body p {
        line-height:18px;
        margin:8px 0;
    }

    .preview-image .x-panel-body ul {
        margin-left:18px;
    }

    .preview-image .x-panel-body ul li {
        display:list-item;
        list-style-image:none !important;
        list-style-position:outside !important;
        list-style-type:disc !important;
        margin-left:18px;
    }

    .preview-image .x-panel-body pre, #preview .x-panel-body code {
        background:#f1f1f1;
        display:block;
    }

    #preview-image div.image-data {
        background:#f1f2f4;
        padding:5px;
        border-bottom:1px solid #dadadb;
    }
    #preview-image div.image-body img {
        padding:10px;
        border: 2px solid #000; 
    }

    div.image-date {
        font-weight:normal;
        color:#555;
        font-size:13px;
    }
    div.image-title {
        font-weight:normal;
        color:#555;
        font-size:13px;
    }
    div.image-make {
        font-weight:normal;
        color:#555;
        font-size:13px;
    }
    div.image-gps {
        font-weight:normal;
        color:#555;
        font-size:13px;
    }
</style>
<div id="preview-image">
    <div class="image-data">
        <div class="image-date">Filename : <?php echo $this->fileName; ?></div>
        <div class="image-title">Original Date/Time : <?php echo $this->DateTimeOriginal; ?></div>
        <div class="image-make">Taken From : <?php echo $this->Make; ?>, Model : <?php echo $this->Model; ?></div>
        <div  class="image-gps">GPS Coordinate : (Latitude) <?php echo $this->GpsLat; ?> (Longitude) <?php echo $this->GpsLong; ?></div>
    </div>
    <div class="image-body"><img src="<?php echo $this->imageFile; ?>"></img>
</div>