<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var windowForm = ({

            title:'Depreciation Fixed Asset',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[{
                xtype: 'tbbutton',
                text: 'Select Action',
                iconCls: 'menu-drop',
                menu:{
                    items:[{
                        text:'Fixed Asset Depreciation By Items',
                        id:'deprecitaton-fixed-asset-item-report',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/report/depreciationassetitem',
                                scripts : true
                            });
                        }
                    },{
                        text:'Fixed Asset Depreciation By Periode',
                        id:'depreciation-fixed-asset-periode-report',
                        cls:"x-btn-text-icon" ,
                        icon:"/images/icons/fam/action_paste.gif",
                        handler:function()
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/report/depreciationassetperiode',
                                scripts : true
                            });
                        }
                    }]
                }
            }]

        });

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
//        panelBaru = Ext.getCmp('abs-budget-panel');
//        panelBaru.body.load({
//            url: '/logistic/fixedasset/viewfixedasset',
//            scripts: true
//        });
//        showSubmenu('abs-budget-panel');


    })



</script>