<?php
if (count($this->data) == 0)
{
    echo "No Data to display...";
    die();
}
?>


<style type="text/css">

    .parentContainer{
        margin: 5px;
        padding: 0px;
        border: none;
        /*width: 740px;*/
        /*height: 460px;*/
        overflow: auto;
        font-size: 14px;
        margin-top: 40px;
    }

    .headtext{
        text-align: center;
        font-weight:bolder;

    }

    #header_content h1{
        font-size: 18px;
        margin-top: 20px;
    }

    .budgetTable {
        font-family: Verdana, Arial, sans serif;
        font-size: 0.8em;
        border-spacing: 0px 0px !important;
        border-collapse: collapse !important;
    }

    .budgetTable th {
        background-color: #CFDCEE;
    }

    .budgetTable th, .budgetTable td {
        border: 1px solid #9EB6CE;
        padding: 3px 6px 3px 4px;
        white-space: nowrap;
    }


</style>

<div id="header_content">
    <center><h1>DETAIL REM AGING</h1></center>
</div>
<b>Customer Name : <?=$this->name?></b>
<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
        <tr>
            <th width="40" scope="col" class="headtext">No</th>
            <th width="140" scope="col" class="headtext">Trano</th>
            <th width="140" scope="col" class="headtext">Payment Date</th>
            <th width="140" scope="col" class="headtext">Age Until Now (days)</th>
            <th width="160" scope="col" class="headtext">Value to Process DN</th>
        </tr>
        </thead>

        <tbody>
        <?php
        $num = 1;
        foreach ($this->data as $key => $val)
        {
            $uid = $key;
            ?>
        <tr>
            <td align="center"><?php echo $num?></td>
            <td align="center"><?=$val['trano_rem']?></td>
            <td align="center"><?=date('d - M - Y',strtotime($val['tgl']))?></td>
            <td align="center"><?=$val['days']?></td>
            <td align="right"><?=$val['val_kode']?>&nbsp;<?=number_format($val['total'],2)?></td>
        </tr>
            <?
            $num++;
        }
        ?>
        </tbody>
    </table>
</div>
