<?php
if (count($this->data) == 0)
{
    echo "No Data to display...";
    die();
}

?>
<style type="text/css">

    .parentContainer{
        margin: 5px;
        padding: 0px;
        border: none;
        width: 840px;
        height: 420px;
        overflow: auto;
        font-size: 14px;
    }
</style>
<div style="border-bottom: 2px solid #99BBE8;width:840px;float:left;margin-bottom: 10px;">
    <h1 style="font-size: 18px;font-family: tahoma,verdana,arial,sans-serif;">BANK CHARGE <?=$this->title?></h1>
    <!--<h2 style="font-size: 16px;float: left;"><b>--><?//=$this->periode?><!--</b></h2>-->
    <h3 style="font-size: 11px;float: left;"><b><?=$this->tgl?></b></h3>
    <h3 style="font-size: 11px;float: right;"><i>Currency : IDR</i></h3>
</div>
<br>
<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Trano</center></th>
            <th scope="col"><center>Date</center></th>
            <th scope="col"><center>Ref Number</center></th>
            <th scope="col"><center>COA Code</center></th>
            <th scope="col"><center>COA Name</center></th>
            <th scope="col"><center>Debit</center></th>
            <th scope="col"><center>Credit</center></th>
        </tr>
        </thead>
        <tbody>

        <?php
        $nomer = 1;$totalDebit = 0;$totalCredit = 0;
        foreach($this->data as $k => $v )
        {
            $totalDebit += $v['debit'];
            $totalCredit += $v['credit'];
            ?>
        <tr>
            <td><?=$nomer;?></td>
            <td><?=($v['trano'] != '') ? $v['trano'] : "&nbsp;"?></td>
            <td><?=($v['tgl'] != '') ? $v['tgl'] : "&nbsp;"?></td>
            <td><?=($v['ref_number'] != '') ? $v['ref_number'] : "&nbsp;"?></td>
            <td><?=($v['coa_kode'] != '') ? $v['coa_kode'] : "&nbsp;"?></td>
            <td><?=($v['coa_nama'] != '') ? $v['coa_nama'] : $v['text']?></td>
            <td align="right"><?=number_format($v['debit'],2)?></td>
            <td align="right"><?=number_format($v['credit'],2)?></td>
        </tr>

            <?php
            $nomer++;
        }
        ?>
        <!--        TOTAL -->
        <?php
        if (bccomp($totalCredit,$totalDebit,2) != 0)
        {
            $color = "#ffea8f";
            $selisih = $totalCredit - $totalDebit;
            if ($selisih < 0)
            {
                $selisih = -1 * $selisih;
            }
            $selisih = "&nbsp;(<b>Variance : " . number_format($selisih,2) . "</b>)";
        }
        ?>
        <tr bgcolor="<?=$color?>">
            <td colspan = 6 >TOTAL <?=($selisih) ? $selisih : ''?></td>
            <td align="right"><b><?=number_format($totalDebit,2)?></b></td>
            <td align="right"><b><?=number_format($totalCredit,2)?></b></td>
        </tr>

        </tbody>
    </table>
</div>
<script type="text/javascript">

    (function() {
        var mySt = new superTable("budgetTable", {
            cssSkin : "sSky",
            fixedCols : 3,
            headerRows : 1
        });
    })();

</script>