<?php
if (count($this->data) == 0)
{
    echo "No Data to display...";
    die();
}

?>
<style type="text/css">

    .parentContainer{
        margin: 5px;
        padding: 0px;
        border: none;
        width: 840px;
        height: 420px;
        overflow: auto;
        font-size: 14px;
    }
</style>
<div style="border-bottom: 2px solid #99BBE8;width:840px;float:left;margin-bottom: 10px;">
    <h1 style="font-size: 18px;font-family: tahoma,verdana,arial,sans-serif;">GENERAL LEDGER DETAIL</h1>
    <h2 style="font-size: 18px;font-family: tahoma,verdana,arial,sans-serif;"> <?=$this->title?></h2>
    <!--<h2 style="font-size: 16px;float: left;"><b>--><?//=$this->periode?><!--</b></h2>-->
    <h3 style="font-size: 11px;float: left;"><b><?=$this->tgl?></b></h3>
    <h3 style="font-size: 11px;float: right;"><i>Currency : IDR</i></h3>
</div>
<br>
<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
        <tr>
            <th scope="col"><center>No</center></th>
            <th scope="col"><center>Transaction</center></th>
            <th scope="col"><center>Trano</center></th>
            <th scope="col"><center>Date</center></th>
            <th scope="col"><center>Ref Number</center></th>
            <th scope="col"><center>COA Code</center></th>
            <th scope="col"><center>COA Name</center></th>
            <th scope="col"><center>Debit</center></th>
            <th scope="col"><center>Credit</center></th>
            <th scope="col"><center>Debit (Conversion)</center></th>
            <th scope="col"><center>Credit (Conversion)</center></th>
            <th scope="col"><center>Job Number</center></th>
        </tr>
        </thead>
        <tbody>

        <?php
        $nomer = $this->current;$totalDebit = 0;$totalCredit = 0;
        foreach($this->data as $k => $v )
        {
        ?>
        <tr>
            <td><?=$nomer;?></td>
            <td><?=$v['transaction'];?></td>
            <td><?=$v['trano'];?></td>
            <td><?=date("d M Y",strtotime($v['tgl']))?></td>
            <td><?=$v['ref_number']?></td>
            <td><?=($v['coa_kode'] != '') ? $v['coa_kode'] : "&nbsp;"?></td>
            <td><?=($v['coa_nama'] != '') ? $v['coa_nama'] : $v['text']?></td>
            <td align="right"><?=number_format($v['debit'],2)?></td>
            <td align="right"><?=number_format($v['credit'],2)?></td>
            <td align="right"><?=number_format($v['debit_conversion'],2)?></td>
            <td align="right"><?=number_format($v['credit_conversion'],2)?></td>
             <td><?=$v['job_number']?></td>
        </tr>

        <?php
            $nomer++;
        }
        ?>
        </tbody>
        <tfoot>
            <tr style="background-color: #CFDCEE">
                <td colspan="9" class="rounded-foot-left"><b>Grand Total</b></td>
                <td align="right"><?=number_format($this->totalDebit,2)?></td>
                <td align="right"><?=number_format($this->totalCredit,2)?></td>
                <td class="rounded-foot-left">&nbsp;</td>
            </tr>
        </tfoot>

    </table>
</div>

<?=$this->paging($this->pageUrl,$this->totalResult,$this->limitPerPage,$this->current,$this->currentPage)?>
<script type="text/javascript">

    (function() {
        var mySt = new superTable("budgetTable", {
            cssSkin : "sSky",
            fixedCols : 3,
            headerRows : 1
        });
    })();

</script>