<style type="text/css">

.parentContainer{
    margin: 5px;
    padding: 0px;
    border: none;
    /*width: 740px;*/
    /*height: 460px;*/
    overflow: auto;
    font-size: 14px;
    margin-top: 40px;
}

.headtext{
    text-align: center;
    font-weight:bolder;

}

#header_content h1{
    font-size: 18px;
    margin-top: 20px;
}

.budgetTable {
    font-family: Verdana, Arial, sans serif;
    font-size: 0.8em;
    border-spacing: 0px 0px !important;
    border-collapse: collapse !important;
}

.budgetTable th {
    background-color: #CFDCEE;
}

.budgetTable th, .budgetTable td {
    border: 1px solid #9EB6CE;
    padding: 3px 6px 3px 4px;
    white-space: nowrap;
}


</style>

<div id="header_content">
    <center><h1>AP AGING</h1></center>
</div>

<div class="parentContainer">
    <table id="budgetTable" class="budgetTable">
        <thead id="fixed">
            <tr>
            <th width="40" scope="col" class="headtext">No</th>
            <th width="240" scope="col" class="headtext">Supplier Name</th>
            <th width="140" scope="col" class="headtext">Total Due</th>
            <th width="140" scope="col" class="headtext">Current</th>
            <th width="140" scope="col" class="headtext">1 - 30</th>
            <th width="140" scope="col" class="headtext">31 - 60</th>
            <th width="140" scope="col" class="headtext">61 - 90</th>
            <th width="140" scope="col" class="headtext">90 +</th>
            </tr>
        </thead>

        <tbody>
            <?php
                $num = 1;
                $tgl = $this->tgl;  
                foreach ($this->data as $key => $val)
                {
                    $name = $val['name'];
                    $uid = $key;
            ?>
            <tr>
            <td align="center"><?php echo $num?></td>
            <td align="left"><?=$name?></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>')">&nbsp;<?=number_format($val['total'],2)?></a></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>/start/current')">&nbsp;<?=number_format($val['current'],2)?></a></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>/start/0')">&nbsp;<?=number_format($val['0'],2)?></a></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>/start/30')">&nbsp;<?=number_format($val['30'],2)?></a></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>/start/60')">&nbsp;<?=number_format($val['60'],2)?></a></td>
            <td align="right"><a href="#" onclick="popup('/finance/report/detail-rpi-aging/tgl/<?=$tgl?>/sup_kode/<?= $key?>/start/90')">&nbsp;<?=number_format($val['90'],2)?></a></td>
            </tr>
            <?
                    $num++;
                }
            ?>
            <tr style="background-color: #CFDCEE">
                <td colspan="2" align="center"><b>Total</b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_all'],2)?></b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_current'],2)?></b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_0'],2)?></b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_30'],2)?></b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_60'],2)?></b></td>
                <td align="right"><b><?=number_format($this->total['grandTotal_90'],2)?></b></td>
            </tr>
        </tbody>
    </table>
</div>
