<script type="text/javascript">

   Ext.onReady(function(){

       Ext.QuickTips.init();

       function showliststypesupp()
       {
            var typesuppstore = new Ext.data.Store ({

                autoLoad:true,
                url:'/logistic/logistictypesupplier/gettypesupp',
                reader:new Ext.data.JsonReader ({
                    root:'data',
                    totalProperty:'total',
                    fields:[{
                        name:'id'
                    },{
                        name:'jenisupplier'
                    },{
                        name:'jenissupliernama'
                    }]
                })


            })

            var typesuppgrid = new Ext.grid.GridPanel ({

                store:typesuppstore,
                height:300,
                width:488,
                columns:[{
                    header:'ID',
                    dataIndex:'id',
                    width:40
                },{
                    header:'Supplier Type',
                    dataIndex:'jenisupplier',
                    sortable:true,
                    width:120
                },{
                    header:'Supplier Type Name',
                    dataIndex:'jenissupliernama',
                    sortable:true,
                    width:340
                }],
                bbar:new Ext.PagingToolbar ({
                    id: 'paging-typesupp',
                    pageSize: 20,
                    store: typesuppstore,
                    displayInfo: true,
                    displayMsg: 'Displaying data {0} - {1} of {2}',
                    emptyMsg: "No data to display"
                }),
                listeners:{
                    'rowdblclick':function (gridaktif,rowIndex,e)
                    {
                        isDbClick = true;

                        var typesupp = gridaktif.getStore().getAt(rowIndex);

                        Ext.getCmp('supp-id').setValue(typesupp.get('id'));
                        Ext.getCmp('supp-type').setValue(typesupp.get('jenisupplier'));
                        Ext.getCmp('supp-type-name').setValue(typesupp.get('jenissupliernama'));

                        typesuppwindow.close();
                    }
                }



            })

           var typesuppwindow = new Ext.Window ({

                title:'Supplier Type List',
                id:'supp-type-list',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 500,
                height: 330,
                loadMask:true,
                items:[typesuppgrid]

           })

           typesuppwindow.show();
       }

       var edittypesupp = new Ext.form.FormPanel ({

            title:'Edit Existing Type Supplier',
            id:'edit-type-supplier',
            renderTo:'edit_type_supp',
            iconCls: 'silk-user',
            frame: true,
            width:360,
            labelWidth:140,
            items:[{
                xtype:'hidden',
                id:'supp-id'
            },{
                xtype:'trigger',
                fieldLabel:'Supplier Type ',
                id:'supp-type',
                msgTarget:'side',
                width:180,
                allowBlank:false,
                triggerClass: 'teropong',
                onTriggerClick:function()
                {
                    showliststypesupp();
                }
            },{
                xtype:'textfield',
                fieldLabel:'Supplier Type Name ',
                id:'supp-type-name',
                msgTarget:'side',
                width:180,
                allowBlank:false
            }],
           buttons:[{
               text:'Update',
               handler:function(btn,ev)
               {
                    if(!Ext.getCmp('edit-type-supplier').getForm().isValid())
                    {
                        Ext.Msg.alert('Error','Please fill in all required fields');
                        return false;
                    }

                    var id = Ext.getCmp('supp-id').getValue();

                    Ext.getCmp('edit-type-supplier').getForm().submit({

                        method:'POST',
                        url:'/logistic/logistictypesupplier/doupdatetypesupp/id/' + id,
                        success:function(thisForm,response)
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/logistic/logistictypesupplier/typesupplier',
                                scripts : true
                            });
                        },
                        failure:function(thisForm,response){
                            if (response.failureType == 'server')
                            {
                                var resp = Ext.util.JSON.decode(response.response.responseText);
                                Ext.Msg.alert('Error',resp.pesan);
                            }
                        }

                    })
               }
           },{
               text:'Cancel',
               handler:function(btn,ev)
               {
                    myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                        url: '/logistic/logistictypesupplier/typesupplier',
                        scripts : true
                    });
               }
           }]

       })



   })


</script>

    <div id="edit_type_supp"></div>
