<style>


.last-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.all-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#F6CBCA;
    color:#222222;
    padding:4px;
    text-align:left;
}
.all-approve{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    /*background:#CEE6C3;*/
    color:#222222;
    padding:4px;
    text-align:left;
    height: 200px;
    overflow: auto;
}

.body {
	/*width: 720px;*/
    overflow: auto;
}
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
	margin-bottom: 10px;
}
.etc {
	width: 100%;
	height: 50px;
}
.kanan-etc {
	float: right;
	width: 48%;
}
.kiri-etc {
	float: left;
	width: 48%;
}
.blok {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
}
.budgetTable {
	width: 100%;
	font-size: 12px;
	font-weight: normal;
}

</style>
<style type="text/css">
    .x-grid3-td-name b {
            font-family:tahoma, verdana;
            display:block;
            color:#333;
    }
    .x-grid3-td-name b i {
        font-weight:normal;
        font-style: normal;
        color:#000;
    }
    .x-grid3-td-name .personicon {
        padding-left:20px;
        background:transparent url(/images/engineer-icon.png) no-repeat 0 2px;
    }
    .x-grid3-td-name .x-grid3-cell-inner {
        white-space:normal;
    }

    .x-grid3-row-body p {
        margin:5px 20px 10px 25px !important;
        color:#555;
    }

    .rolename {
        color:#333;
    }
.ketin {
    width: 100%;
    font-size: 12px;
	font-weight: bold;
}
.ketin fieldset p {
    padding: 5px 5px 5px 5px;
}
</style>

<script type="text/javascript">

Ext.onReady(function(){
    <?php if (!$this->preview && !$this->show) { ?>
    <?php if ($this->approve) { ?>
    //Variabel yg dikirim, approve / reject sama variabelna...
    var trano = '<?=$this->docsID?>';
    var uid = '<?=$this->uid?>';
    var user_id = '<?=$this->userID?>';

    <?php if (!$this->reject) { ?>
    var wButt = new Ext.ux.workflowButton({
        renderTo: 'wButton',
        showApproveButton: true,
        showRejectButton: true,
        showAskButton: true,
        showCancelButton: true,
        trano: '<?=$this->trano?>',
        itemType: 'ARFO',
        approveParams: {trans:trano, user: uid, user_id:user_id},
        rejectParams: {trans:trano, user: uid, user_id:user_id},
        beforeApproveCallback: function(theWButton) {
            var cb = function(bypass) {
                if (bypass == undefined)
                    bypass = false;
                theWButton.approveParams.bypass_next = bypass;
                var cbcomment = function(comment) {
                    theWButton.approveParams.comment = comment;
                    theWButton.doApprove(theWButton.approveParams);
                };
                theWButton.showComment(cbcomment);
            };
            checkNominalWorkflow(uid,'<?=$this->docsID?>','<?=$this->trano?>', cb);
        },
        approveSuccessCallback: function() {
            getDocs();
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/default/home/showprocessdocument',
                scripts : true
            });
        },
        rejectSuccessCallback: function() {
            getDocs();
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/default/home/showprocessdocument',
                scripts : true
            });
        },
        cancelSuccessCallback: function() {
            getDocs();
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/default/home/showprocessdocument',
                scripts : true
            });
        }
    });

    wButt.on('beforeworkflowapprove',function(t){

    });
    <?php } else { ?>

    var wButt = new Ext.ux.workflowButton({
        renderTo: 'wButton',
        showEditButton: true,
        itemType: 'ARF',
        editSuccessCallback: function() {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/procurement/procurement/editnewarfsales',
                params: {
                    trano: '<?php echo $this->trano; ?>'
                },
                scripts : true
            });
        }
    });
    <?php } ?>
    <?php } else { ?>
    // variabel yg dikirim untuk submit ke workflow
    var json = '<?php echo $this->jsonResult; ?>';
    var jsonFile = '<?php echo $this->jsonFile; ?>';
    var jsonDeletedFile = '<?php echo $this->jsonDeletedFile; ?>';
    var parameter = '<?=Zend_Json::encode($this->etc)?>';

    var params = {
        posts:json,
        etc:parameter,
        file: jsonFile,
        item_type: 'ARFO'
    };

    <?php if (!$this->edit) { ?>
    var url = '/procurement/procurement/insertarfbudget/sales/true',
        urlCancel = '/procurement/procurement/addnewarfbudget/returnback/true',
        edit = false;
    <?php } else { ?>
    var url = '/procurement/procurement/updatearfbudget/sales/true',
        edit = true;
    <?php } ?>

    var wButt = new Ext.ux.workflowButton({
        renderTo: 'wButton',
        itemType: 'ARFO',
        showSubmitButton: true,
        showCancelButton: true,
        urlSubmit: url,
        isEdit: edit,
        submitParams: params,
        submitSuccessCallback: function() {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/procurement/procurement/arf',
                scripts : true
            });
        },
        cancelSuccessCallback: function() {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: urlCancel,
                params: params,
                scripts : true
            });
        }
    });
    <?php } ?>
    <?php } ?>
});

</script>


<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">
<div align="right"><img src="/images/imd.gif" alt= "logo imd" /></div>
<div class="title">Advance Request Form for Sales</div>

<?php if ($this->reject) { ?>
<div class="last-reject">
    This Document was Rejected by <?php echo $this->lastReject[0]['name']; ?> at <?php echo date('d-m-Y H:i:s',strtotime($this->lastReject[0]['date'])); ?>
    <br />
    Comment : <?php echo $this->lastReject[0]['comment']; ?>
</div>
<?php } ?>

<div class="etc">
	<div class="kiri-etc">
        <?php if ($this->edit || $this->approve) {?><div class="blok">ARF Number : <?=$this->etc[0]['trano']?></div><?php } ?>
		<div class="blok">ARF Date : <?=date('d-m-Y')?></div>
<!--        <div class="blok">Requester Name : --><?//=$this->etc[0]['requester']?><!--</div>-->
        <div class="blok">Currency : <?=$this->etc[0]['valuta']?></div>
        <div class="blok">Origin of Budget : <?=$this->etc[0]['budgettype']?></div>

	</div>
	<div class="kanan-etc">
		<div class="blok">Project : <?=$this->etc[0]['prj_kode']?> - <?=$this->etc[0]['prj_nama']?></div>
		<div class="blok">Site : <?=$this->etc[0]['sit_kode']?> - <?=$this->etc[0]['sit_nama']?></div>
        <div class="blok">Manager : <?=QDC_User_Ldap::factory(array("uid" => $this->etc[0]['mgr_kode']))->getName()?></div>
        <div class="blok">PIC : <?=QDC_User_Ldap::factory(array("uid" =>$this->etc[0]['pic_kode']))->getName()?></div>
    </div>
</div>


<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>Requester Name</center></th>
            <th scope="col"><center>Budget ID</center></th>
            <th scope="col"><center>Budget Name</center></th>
            <th scope="col"><center>Description</center></th>
<!--            <th scope="col"><center>Remark</center></th>-->
            <th scope="col"><center>UOM</center></th>
            <th scope="col"><center>Qty</center></th>
            <th scope="col"><center>Unit Price</center></th>
            <th scope="col"><center>Total</center></th>
        </tr>
    	<?php

    		$totals = 0;
    		$pajak=0;
    		$grandtotals=0;

    		$tax = $this->result[0]['tax'];
       		for ($i=0;$i<(count($this->result));$i++)
    		{

   				foreach ($this->result[$i] as $key => $val)
    			{
    				if ($val == '')
    					$this->result[$i][$key] = "&nbsp;";
    			}

                $harga = $this->result[$i]['priceArf'];
                $total = $this->result[$i]['qty'] * $this->result[$i]['priceArf'];


    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
            <td><?=$this->result[$i]['requesterName'] ?> </td>
    		<td><?=$this->result[$i]['budgetid'] ?> </td>
            <td><?=$this->result[$i]['budgetname'] ?> </td>
    		<td>
                <?=$this->result[$i]['kode_brg']?> - <?=$this->result[$i]['nama_brg']?>
                <?php if ($this->result[$i]['ket'] != '&nbsp;') { ?>
                <p>
                    <font color="red"><b>Ket: <?=$this->result[$i]['ket']?></b></font>
                </p>
                <?php } ?>
            </td>
<!--            <td >--><?//=$this->result[$i]['ket']?><!--</td>-->
    		<td ><?=$this->result[$i]['uom']?></td>
    		<td align="right"><?=number_format($this->result[$i]['qty'],4)?></td>
            <td align="right"><?=number_format($this->result[$i]['priceArf'],2)?></td>

            <td align="right"><?=number_format($total,2)?></td>
    		</tr>

                   <?php
                                   $totals += $total;
                               }

                           ?>
                           <tr>
                               <th scope="row" class="spec" colspan="9">Grand Total</th>
                               <td align="right"><?=number_format($totals,2)?></td>
                               </tr>
                   </table>

     <?php
    if ( $this->etc[0]['user_approval'] != '')
    {
    ?>
    <div class="all-approve">
    <b>Approval History</b></br>
    <ul>
    <?php
        foreach ($this->etc[0]['user_approval'] as $key => $val)
        {
    ?>
            <li><?php echo "<b>" . $val['approve'] . "</b> " . date('d-m-Y H:i:s',strtotime($val['date'])) . " : " . $val['displayname'] . " (" . $val['display_name'] . ")<br />Sign : " . $val['signature'] . "<br />Comment : " . $val['comment']; ?></li>
    <?
        }
    ?>
    </ul>
    </div>
    <?php
    }
    ?>
<!--
    <?php
    if ($this->allReject != '')
    {
    ?>
    <div class="all-reject">
    <b>Rejection History</b></br>
    <ul>
    <?php
        foreach ($this->allReject as $key => $val)
        {
    ?>
            <li><?php echo date('d-m-Y H:i:s',strtotime($val['date'])) . " : " . $val['displayname'] . " (" . $val['display_name'] . ")"; ?><br />Comment : <?php echo $val['comment']; ?></li>
    <?
        }
    ?>
    </ul>
    </div>
    <?php
    }
    ?>
-->

    <div style="margin-top:15px; float:right;" id="wButton">

</div>
