<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        <?php echo $this->action('index','textfield',null); ?>

//	function showBarangChoose(num)
//	{
//		var bForm =  new Ext.Window({
//		    id: 'b-form-panel-trano_button',
//		    layout:'fit',
//		    width: 350,
//		    height: 100,
//		    style: 'margin-top: 10px',
//		    labelAlign: 'right',
//		    stateful: false,
//	        modal: true,
//	        resizable: false,
//		    items: [
//					new Ext.form.FormPanel({
//						frame: true,
//                        labelWidth : 150,
////                        labelPad : 7,
//						items: [{
//								    fieldLabel : 'Product ID',
//								    id : 'kode_brg_text',
//								    xtype: 'trigger',
//			                        allowBlank: false,
//			                        editable : false,
//			                        value: num,
//								    onTriggerClick:
//			                            function ()
//			                            {
//                            				bForm.close();
//											showBarangList();
//			                            },
//			                    	scope: this,
//			                    	width: 150
//						    	}]
//						})
//
//				    ],
//		    buttons: [
//		              {
//	 			         text: 'Edit',
//	 			         id: 'save',
//	 			         iconCls: 'silk-upd',
//	 			         handler: function(btn, ev) {
//		 			        var kodeBrg = Ext.getCmp('kode_brg_text').getValue();
//		 			        if (kodeBrg != undefined)
//		 			        {
//				          	    myPanel = Ext.getCmp('abs-budget-panel');
//				          	    myPanel.body.load({
//				          	        url: '/logistic/logistic/editmaterial/kode_brg/' + kodeBrg,
//				          	        scripts : true
//				                  });
//		 			        }
//		 			        bForm.close();
//			              }
//
//		              },
//		              {
//	 			         text: 'Cancel',
//	 			         id: 'cancel',
//	 			         handler: function(btn, ev) {
//		 			         bForm.close();
//			              }
//
//		              }
//
//
//			  		    ]
//		});
//
//		bForm.show();
//	}

//    function showBarangList()
//    {
//        var columns = [ {header:'Product ID',width:120,sortable:true,dataIndex:'kode_brg'},
//                        {header:'Product Name',width:170,sortable:true,dataIndex:'nama_brg'},
//                        {header:'Uom',width:60,sortable:true,dataIndex:'sat_kode'}
//                        ]
//
//        urlJson = CFG_CLIENT_SERVER_NAME +'/barang/list';
//        data =  [
//                {name: 'kode_brg', mapping: 'kode_brg'},
//                {name: 'nama_brg', mapping: 'nama_brg'},
//                {name: 'sat_kode', mapping: 'sat_kode'}
//                ];
//        primaryKey = 'kode_brg';
//        Pk = primaryKey;
//        widthGrid = 380;
//        heightGrid = 250;
//
//        var stores = new Ext.data.Store({
//            proxy:new Ext.data.HttpProxy({
//            url: urlJson
//             }),
//            reader: new Ext.data.JsonReader({
//            root: 'posts',
//            totalProperty: 'count'
//        },data)
//            });
//
//        yAxis=100;
//        grids = function()
//        {
//            grids.superclass.constructor.call(this, {
//            store: stores,
//            columns: columns,
//            x:0,
//            y:yAxis,
//            id:primaryKey+'_grid',
//            loadMask: true,
//            bbar:[ new Ext.PagingToolbar({
//                pageSize: 100,
//                store: stores,
//                displayInfo: true,
//                displayMsg: 'Displaying data {0} - {1} of {2}',
//                emptyMsg: "No data to display"
//            })],
//            height:heightGrid,
//            width:widthGrid,
//            listeners: {
//                'rowdblclick': function(g, rowIndex, e){
//                                closeForm = false;
//                                isDblClick = true;
//                                objectName = 'kode_brg';
//                                txtBoxChange = 'kode_brg_text';
//                                closeForm = true;
//                                formId = 'a-form-panel-kode_brg_button';
//                                prox = 'trano_proxy';
//                                gri = 'trano_grid';
//                                var trano = g.getStore().getAt(rowIndex).get(objectName);
//                                showBarangChoose(trano);
//                                Ext.getCmp('kode_brg_text').setValue(trano);
//                                aForm.close();
//								window.setTimeout(function(){
//                                        isDblClick = false;
//                                }, 0);
//                        }
//                }
//        });
//        }
//        stores.load();
//
//        Ext.extend(grids, Ext.grid.GridPanel);
//        Ext.extend(txtboks,Ext.form.TextField);//PR
//        searchKodeBrg = function(field,e){
//            newUrl = '/barang/listByParams/name/kode_brg/data/' + field.getValue(); prox = Pk+'_proxy';
//            gri = Pk+'_grid';
//            proxies = Ext.getCmp(gri).getStore();
//            proxies.proxy = new Ext.data.HttpProxy( {
//                url: newUrl
//                 });
//            Ext.getCmp(gri).getStore().reload();
//        };
//        searchNamaBrg = function(field,e){
//            newUrl = '/barang/listByParams/name/nama_brg/data/' + field.getValue(); prox = Pk+'_proxy';
//            gri = Pk+'_grid';
//            proxies = Ext.getCmp(gri).getStore();
//            proxies.proxy = new Ext.data.HttpProxy( {
//                url: newUrl
//                 });
//            Ext.getCmp(gri).getStore().reload();
//    };
//
//
//        var aForm =  new Ext.Window({
//        id: 'a-form-panel-kode_brg_button',
//        layout: 'absolute',
//        minWidth: 300,
//        minHeight: 200,
//        stateful:false,
//        modal: true,
//        resizable: false,
//        width: 400,
//        height: 400,
//        items : [
//            {
//            x: 6,
//            y: 12,
//            xtype: 'label',
//            text: 'Product ID'
//            },
//           new txtboks(80,10,80,'kode_brg',searchKodeBrg),
//           {
//               x : 6,
//               y: 52,
//               xtype: 'label',
//               text: 'Product Name'
//               },
//              new txtboks(80,50,80,'nama_brg',searchNamaBrg)
//
//            ,new grids('barang_list')
//        ]
//
//      });
//      aForm.title = 'Choose Material';
//      aForm.show();
//
//
//    }




    function showSatuanChoose (num)
    {
        var searchSatuan = new Ext.Window({

            id: 'searchSatuan',
		    layout:'absolute',
		    width: 350,
		    height: 100,
		    style: 'margin-top: 10px',
		    labelAlign: 'right',
		    stateful: false,
	        modal: true,
	        resizable: false,
            items:[
                    new Ext.form.FormPanel({
						frame: true,
                        labelWidth : 150,
//                        labelPad : 7,
						items: [{
								    fieldLabel : 'UOM Kode',
								    id : 'sat_kode',
								    xtype: 'trigger',
			                        allowBlank: false,
			                        editable : false,
			                        value: num,
								    onTriggerClick:
			                            function ()
			                            {
                            				searchSatuan.close();
											showSatuanList();
			                            },
			                    	scope: this,
			                    	width: 150
						    	}]
						})

	                ],
            buttons: [
		              {
	 			         text: 'Edit',
	 			         id: 'save',
	 			         iconCls: 'silk-upd',
	 			         handler: function(btn, ev) {
		 			        var satkode = Ext.getCmp('sat_kode').getValue();
                            if (satkode == null || satkode == "")
                            {
                                Ext.Msg.alert('Error','Please choose UOM kode');
                                return false;
                            }
		 			        if (satkode != undefined)
		 			        {
				          	    myPanel = Ext.getCmp('abs-budget-panel');
				          	    myPanel.body.load({
				          	        url: '/logistic/logisticsatuan/editsatuan/satkode/' + satkode,
				          	        scripts : true
				                  });
		 			        }
		 			        searchSatuan.close();
			              }

		              },
		              {
	 			         text: 'Cancel',
	 			         id: 'cancel',
	 			         handler: function(btn, ev) {
		 			         searchSatuan.close();
			              }

		              }
	                ]
        })

        searchSatuan.show();

    }


    function showSatuanList()
    {
        var satuanstore = new Ext.data.Store ({

            url:'/logistic/logisticsatuan/getsatuan',
            autoLoad:true,

            reader: new Ext.data.JsonReader({
                root:'data',
                totalProperty:'total'
                },[
                {name:'sat_kode',type:'String'},
                {name:'sat_nama',type:'String'},
                {name:'ket',type:'String'}

            ])


        })

        searchData = function()
        {
            var docs = Ext.getCmp('document-text').getValue();
            satuanstore.proxy.setUrl('/logistic/logisticsatuan/getsatuan/search/' + docs);
            satuanstore.reload();

            grid.getView().refresh();
        }

        refreshData = function()
        {
            satuanstore.clearFilter();
            Ext.getCmp('document-text').setValue('');
            Ext.getCmp('pagingShowSatuan').doRefresh();
        }

        var grid = new Ext.grid.GridPanel({

            store:satuanstore,

            viewConfig:{
                forceFit:true
                },
            layout: 'fit',
            width:400,
            height: 290,
            listeners: {
                'rowdblclick': function(gridYangAktif, rowIndex, e){
                                isDblClick = true;
                                txtBoxChange = 'satuanlist';
                                var satuan = gridYangAktif.getStore().getAt(rowIndex).get('sat_kode');
                                showSatuanChoose(satuan);
                                //Ext.getCmp('sat_name').setValue(trano);
                                Ext.getCmp('satuanlist').close();
								window.setTimeout(function(){
                                        isDblClick = false;
                                }, 0);
                        }
                },
            columns:[
                {
                    header:'UOM Code',
                    dataIndex:'sat_kode',
                    width:80,
                    align:'center',
                    sortable:true
                },{
                    header:'UOM Name',
                    dataIndex:'sat_nama',
                    width:120,
                    align:'center',
                    sortable:true
                },{
                    header:'UOM Description',
                    dataIndex:'ket',
                    width:160,
                    align:'center',
                    sortable:true
                }
            ],
            bbar: new Ext.PagingToolbar({
            id: 'pagingShowSatuan',
            pageSize: 10,
            store: satuanstore,
            displayInfo: true,
            displayMsg: 'Displaying data {0} - {1} of {2}',
            emptyMsg: "No data to display"
            }),
            tbar: [
				{
					text: 'UOM Name',
					xtype:'label',
				    style: 'margin-right: 5px'
				},
				{
					xtype: 'textfield',
					id: 'document-text'
				},
				{
				    text: 'Search',
				    iconCls: 'search-icon',
				    handler: searchData,
				    scope: this
				},
                '-',
                {
				    text: 'refresh',
				    iconCls: 'icon-refresh',
				    handler: refreshData,
				    scope: this
				},
                '-',
                {
					text: '',
					xtype:'label',
				    style: 'margin-right: 5px',
                    id:'label-last-upd'
				}
               ]


        })
        var satuanlist = new Ext.Window ({
            id: 'satuanlist',
            layout: 'absolute',
            minWidth: 300,
            minHeight: 200,
            stateful:false,
            modal: true,
            resizable: false,
            closeAction: 'close',
            width: 420,
            height: 320,
            loadMask:true,
            items:[
                    grid
            ]
        })

        satuanlist.title = 'Choose UOM';
        satuanlist.show();
    }



    showAddBarang = function(){
	    myPanel = Ext.getCmp('abs-budget-panel');
	    myPanel.body.load({
	        url: '/logistic/logisticsatuan/addsatuan',
	        scripts : true
        });
	};

	showEditSatuan= function(){
			showSatuanChoose();
	};

//	showAppBarang = function(){
//	    myPanel = Ext.getCmp('abs-budget-panel');
//	    myPanel.body.load({
//	        url: '*',
//	        scripts : true
//        });
//	};


    var windowForm =  ({

    title: 'Master Unit Of Measurement',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    loadMask: true,
    minWidth: 300,
    minHeight: 200,
    tbar: [
			{
			    xtype: 'tbbutton',
			    text: 'Select Action',
			    iconCls: 'menu-drop',
			    menu: {

			    items: [
						{
						    id: 'satuan_add_button',
						    text: 'Add UOM',
						    cls:"x-btn-text-icon" ,
						    icon:"/images/icons/fam/action_paste.gif",
						    handler:showAddBarang
						}
						,{
						    id: 'satuan_edit_button',
						    text: 'Edit Existing UOM',
						    cls:"x-btn-text-icon" ,
						    icon:"/images/icons/fam/page_edit.gif",
						    handler:showEditSatuan
						}
//                        {
//						    id: 'app_button',
//						    text: 'Verify & Approval',
//						    cls:"x-btn-text-icon" ,
//						    icon:"/images/icons/fam/page_script.gif",
//						    handler:showAppSupp
//						}
						]
				}
			}
         ]
    });


viewPort = Ext.getCmp('viewport');

centerRegionTab = viewPort.getComponent('content-panel');
centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
centerRegionTab.add(windowForm);
panelBaru = Ext.getCmp('abs-budget-panel');
centerRegionTab.layout.setActiveItem('abs-budget-panel');
//myPanel = Ext.getCmp('abs-budget-panel');
            panelBaru.body.load({
                url: '/logistic/logisticsatuan/allsatuan',
                scripts: true
            });
        showSubmenu('abs-budget-panel');

    })




</script>

