<?php
if (count($this->result) == 0)
{
	echo "No Data to display...";
	die();
}
?>
<style type="text/css">
		.tooltip {
			border-bottom: 1px dotted #000000; color: #000000; outline: none;
			cursor: help; text-decoration: none;
			position: relative;
		}
		.tooltip span {
			margin-left: -999em;
			position: absolute;
		}
		.tooltip:hover span {
			border-radius: 5px 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px;
			box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1); -webkit-box-shadow: 5px 5px rgba(0, 0, 0, 0.1); -moz-box-shadow: 5px 5px rgba(0, 0, 0, 0.1);
			font-family: Calibri, Tahoma, Geneva, sans-serif;
			position: absolute; left: 1em; top: 2em; z-index: 99;
			margin-left: 0; 
		}
		.tooltip:hover img {
			border: 0; margin: -10px 0 0 -55px;
			float: left; position: absolute;
		}
		.tooltip:hover em {
			font-family: Candara, Tahoma, Geneva, sans-serif; font-size: 1.2em; font-weight: bold;
			display: block; padding: 0.2em 0 0.6em 0;
		}
		.info { padding: 0.8em 1em; }
		.custom { padding: 0.5em 0.8em 0.8em 2em; }
		* html a:hover { background: transparent; }
		.info {background: #FFFFAA; border: 1px solid #FFAD33; }
		</style>
<style type="text/css">
.cache{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.parentContainer { /* The parent container */
    margin: 5px;
    padding: 0px;
    border: none;
    width: 840px; /* Required to set */
    height: 430px; /* Required to set */
    overflow: hidden; /* Required to set */
	font-size: 14px;
}

</style>

<?php
if ($this->time != '') {
?>
<div class="cache">
<b>This Report is generated from cache, If there any changes to the data beetween <?=$this->time['generate']?> and <?=$this->time['expire']?> will not shown here.<br>
Cache will expire at <?=$this->time['expire']?></b>
</div>
<?php } ?>

<?php if ($this->salary > 0) { ?>
    <b>Total Salary : IDR <?=number_format($this->salary,2)?></b>
<?php } ?>

<div class="parentContainer">
<table id="budgetTable" class="budgetTable">
    <thead>
    	<tr>
            <th rowspan="2"><b>No.</b></th>
            <th scope="col" class="rounded-q1" colspan="3" style="text-align: center;"><b>Items</b></th>
            <th scope="col" class="rounded-q2" colspan="5" style="text-align: center;"><b>Actual</b></th>
        </tr>
		<tr>
            <th scope="col" class="rounded-q1" style="text-align: center;">Work ID</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Product ID</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Product Name</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Qty</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">UOM</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Price</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Total</th>
            <th scope="col" class="rounded-q1" style="text-align: center;">Currency</th>
            

		</tr>


    </thead>

    <div style="overflow-y:auto">
    <tbody>
    <?php
            $no = 1;
            foreach($this->result as $key => $val)
            {
    ?>
        <tr>
            <td align="right"><?=$no?></td>
            <td><a class="tooltip" href="#"><?=$val['workid']?><span class="info"><?=$val['workname']?></span></a></td>
            <td><?=$val['kode_brg']?></td>
            <td><a class="tooltip" href="#"><?=substr($val['nama_brg'],0,40)?><span class="info"><?=$val['nama_brg']?></span></a></td>
            <td align="right"><?=number_format($val['qty'],0)?></td>
            <td><?=$val['sat_kode']?></td>
            <td align="right"><?=number_format($val['harga'],2)?></td>
            <td align="right"><?=number_format($val['total'],2)?></td>
            <td align="right"><?=$val['val_kode']?></td>
        </tr>
    <?php
            $no++;
            }
    ?>

<!--    TOTAL -->
    <tr style="background-color: #CFDCEE">
        <td colspan="4" align="center"><b>TOTAL</b></td>
        <td >&nbsp;</td>
        <td >&nbsp;</td>
        <td >&nbsp;</td>  
        <td align="right"><b><?=number_format($this->total['total'],2)?></b></td>
        <td >&nbsp;</td>
    </tr>
    </tbody>
    <tfoot>

    </tfoot>
    </div>
</table>
</div>
<? //$this->paging($this->pageUrl,$this->totalResult,$this->limitPerPage,$this->current,$this->currentPage)?>
<script type="text/javascript">
//<![CDATA[

(function() {
	var mySt = new superTable("budgetTable", {
		cssSkin : "sSky",
		fixedCols : 4,
		headerRows : 2
	});
})();

//]]>
</script>