<style>
    .menu-title{
        background: #D6E3F2;
        border-style: solid;
        border-color:#DAE6F4 #99bbe8 #99bbe8 #DAE6F4;
        border-width: 1px;
        margin:-2px -2px 0;
        color:#15428b;
        font:bold 10px tahoma,arial,verdana,sans-serif;
        display:block;
        padding:3px;
    }
</style>

<script type="text/javascript">

showCFS = function(){
    myPanel = Ext.getCmp('abs-budget-panel');
    prjKode = Ext.getCmp('prj_kode_text').getValue();
    sitKode = Ext.getCmp('sit_kode_text').getValue();

	if (prjKode == '')
	{
		Ext.MessageBox.show({
	           title: 'Error',
	           msg: 'Please Insert/Select Project Code!',
	           buttons: Ext.MessageBox.OK,
	           icon: Ext.MessageBox.ERROR
	       });
		 return false;

	}

//    if (sitKode == '')
//    {
//        Ext.MessageBox.show({
//               title: 'Error',
//               msg: 'Please Insert/Select Site Code!',
//               buttons: Ext.MessageBox.OK,
//               icon: Ext.MessageBox.ERROR
//           });
//         return false;
//
//    }


    myPanel.body.load({
        url: '/projectmanagement/report/scurvecost/prj_kode/' + prjKode + '/sit_kode/' + sitKode,
        scripts: true
    });
}

var windowForm =  ({

    title: 'S-Curve Report',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    minWidth: 300,
    minHeight: 200,
    loadMask: true,
    tbar:[
        {
            xtype: 'tbtext',
            text: 'Project Code'
        },
        /*{
            xtype: 'projectselector',
            fieldLabel: 'Project Code',
            anchor: '100%',
            id: 'project-select',
            Selectid: 'prj_kode_text',
            Nameid: 'prj_nama_text',
            ShowName: true,
            urlProject: '/extjs4/gantt/getscurveprojectlist/userole/false',
            urlSearchProject: '/extjs4/gantt/getscurveprojectlist/userole/false'
        }*/
        {
            xtype: 'projectselectorreport',
            fieldLabel: 'Project Code',
            anchor: '100%',
            id: 'project-select',
            Selectid: 'prj_kode_text',
            Nameid: 'prj_nama_text',
            ShowName: false
        }
        ,'-',
        {
            xtype: 'tbtext',
            text: 'Site Code'
        },
        /*{
            xtype: 'siteselector',
            fieldLabel: 'Site Code',
            anchor: '100%',
            independent: false,
            id: 'site-select',
            SiteSelectid: 'sit_kode_text',
            SiteNameid: 'sit_nama_text',
            ProjectSelectid: 'prj_kode_text',
            ShowName: true,
            urlSite: '/extjs4/gantt/getscurvesitelist/userole/false',
            urlSearchSite: '/extjs4/gantt/getscurvesitelist/userole/false'
        }*/
        {
            xtype: 'siteselector',
            fieldLabel: 'Site Code',
            anchor: '100%',
            id: 'site-select',
            SiteSelectid: 'sit_kode_text',
            SiteNameid: 'sit_nama_text',
            ProjectSelectid: 'prj_kode_text',
            ShowName: false
        }
        ,'-',
        {
            xtype: 'button',
            text: 'Show',
            width:70,
            id: 'show_budget',
            cls:"x-btn-text-icon" ,
            icon:"/images/icons/fam/control_rewind.png",
            handler:showCFS
        }
    ]
});


  viewPort = Ext.getCmp('viewport');

 centerRegionTab = viewPort.getComponent('content-panel');
 centerRegionTab.items.each(function(c){centerRegionTab.remove(c);})
 centerRegionTab.add(windowForm);
 panelBaru = Ext.getCmp('abs-budget-panel');
 centerRegionTab.layout.setActiveItem('abs-budget-panel');
</script>