<script type="text/javascript">

    Ext.onReady(function() {

        Ext.QuickTips.init();


        var callbackFunc = function()
        {
            Ext.getCmp('user_text').setValue('');
        };

        var windowForm = ({
            title: 'AR Aging Report',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg: {cls: 'xpanel-body-table', style: {'overflow': 'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [
                {
                    xtype: 'label',
                    text: 'Customer Name'
                }, '-',
                {
                    xtype: 'customerselector',
                    id: 'customer',
                    ShowName: false,
                    Selectid: 'customer_text',
                    width: 120
                },
                {
                    xtype: 'tbtext',
                    text: 'Date',
                    style: 'margin-left:-25;margin-right:5'

                },
                {
                    xtype: 'datefield',
                    name: 'tgl',
                    id: 'tgl',
                    msgTarget: 'side',
                    format: 'd-m-Y'
                },
                {
                    xtype: 'button',
                    text: 'Show',
                    width: 70,
                    id: 'show_report',
                    cls: "x-btn-text-icon",
                    icon: "/images/icons/fam/control_rewind.png",
                    handler: function(btn, ev)
                    {

                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/finance/report/view-invoice-aging',
                            params: {
                                cus_kode: Ext.getCmp('customer_text').getValue(),
                                tgl: Ext.getCmp('tgl').getValue()
                            },
                            scripts: true
                        });
                    }
                }, '-',
                /*{
                    xtype: 'button',
                    text: 'Show All',
                    width: 70,
                    id: 'show_report_all',
                    cls: "x-btn-text-icon",
                    icon: "/images/icons/fam/control_rewind.png",
                    handler: function(btn, ev)
                    {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/finance/report/view-invoice-aging',
                            scripts: true
                        });
                    }
                }, */
                
                {
                    xtype: 'button',
                    id: 'export_button',
                    cls: "x-btn-icon",
                    icon: "/images/print.png",
                    handler: function()
                    {
                        location.href = '/finance/report/view-invoice-aging/export/true';

                    }
                }
            ]
        });

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c) {
            centerRegionTab.remove(c);
        });
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
        panelBaru.body.load({
            url: '/finance/report/view-invoice-aging',
            scripts: true
        });
    })


</script>
