<script type="text/javascript">
var windowForm =  ({

    title: 'Notification Manager',
    id: 'abs-budget-panel',
    layout: 'fit',
    bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
    bodyStyle: 'padding:15px;',
    loadMask: true,
    minWidth: 300,
    minHeight: 200
});
viewPort = Ext.getCmp('viewport');

centerRegionTab = viewPort.getComponent('content-panel');
centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
centerRegionTab.add(windowForm);
centerRegionTab.layout.setActiveItem('abs-budget-panel');


myPanel = Ext.getCmp('abs-budget-panel');
myPanel.body.load({
    url: '/admin/notification/manager',
    scripts : true
});
</script>