
<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        function insertpaymentreimbursement ()
        {
            myPanel = Ext.getCmp('abs-budget-panel');
            myPanel.body.load({
                url: '/finance/paymentreimbursement/insertpaymentreimbursement',
                scripts : true
            });
        }

        var windowForm = ({

            title: 'Payment Reimbursement',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype: 'tbbutton',
                    text: 'Select Action',
                    iconCls: 'menu-drop',
                    menu: {
                    items: [
                            {
                                id: 'add_button',
                                text: 'Add Payment Reimbursement',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/action_paste.gif",
                                handler:insertpaymentreimbursement
                            }
                            ,{
                                id: 'edit_button',
                                text: 'Edit Existing Payment Reimbursement',
                                cls:"x-btn-text-icon" ,
                                icon:"/images/icons/fam/page_edit.gif",
                                handler:function ()
                                {
                                    myPanel = Ext.getCmp('abs-budget-panel');
                                    myPanel.body.load({
                                        url: '/finance/paymentreimbursement/editpaymentreimbursement',
                                        scripts : true
                                    });
                                }
                            }
                            ]
                    }
                }

            ]

        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');


    })


</script>
 
