<script type="text/javascript">


    var datas = [
        ['CNY','CNY'],
        ['EUR','EUR'],
        ['USD','USD'],
        ['KRW','KRW']
        
    ];

    var store = new Ext.data.ArrayStore({
        fields: ['name', 'nilai'],
        data : datas
    });
        
    var combo = new Ext.form.ComboBox({
        store: store,
        displayField:'name',
        valueField: 'nilai',
        typeAhead: true,
        mode: 'local',
        triggerAction: 'all',
        selectOnFocus:true,
        name:'val_kode',
        width:100,
        value:'USD',
        style: 'margin-left: 5px',
        id:'val_kode'
    });
        
    var ratestore = new Ext.data.Store({

        url:'/finance/rateidr/getviewfinancerate',
        autoLoad:true,
        reader: new Ext.data.JsonReader({
            root:'data',
            totalProperty:'total'
        },[
            {name:'tgl',type:'String'},
            {name:'rateidr',type:'String'},
            {name:'val_kode',type:'String'},
            {name:'source',type:'String'}
        ])

    });
       
        
    Ext.onReady(function(){

        Ext.QuickTips.init();

        var addrate = new Ext.form.FormPanel ({

            id:'add-new-rate',
            title:'Add New Rate',
            renderTo:'rateform',
            frame:true,
            iconCls: 'silk-user',
            width:400,
            height:150,
            items:[
                
                {
                    xtype:'datefield',
                    fieldLabel:'Date',
                    name:'rate_date',
                    id:'rate_date',
                    format: 'Y-m-d',
                    msgTarget:'side',
                    width:100,
                    allowBlank:false,
                    
                },
                
                {
                    fieldLabel: 'Currency',
                    xtype: 'combo',
                    width: 100,
                    allowBlank: false,
                    store: new Ext.data.SimpleStore({
                        fields: ['name', 'nilai'],
                        data: [
                            ['CNY','CNY'],
                            ['EUR','EUR'],
                            ['USD','USD'],
                            ['KRW','KRW']
                        ]
                    }),
                    valueField: 'nilai',
                    displayField: 'name',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'local',
                    triggerAction: 'all',
                    value:'USD',
                    selectOnFocus: true,
                    id: 'val-kode'
                },
                
                {
                    xtype:'textfield',
                    fieldLabel:'IDR Rate',
                    name:'rate_idr',
                    id:'rate_idr',
                    msgTarget:'side',
                    width:100,
                    allowBlank:false,
                    editable:false
                  
                }
            ],
            buttons:[
                {
                    text:'Submit',
                    handler:function(btn,ev)
                    {
                        if (!Ext.getCmp('add-new-rate').getForm().isValid())
                        {
                            Ext.Msg.alert('Error','Please fill in all required fields');
                            return false;
                        }else
                        {
                            Ext.MessageBox.confirm(
                                    'Confirm',
                                    'Are you sure you want to create a new rate ?',
                                    function(btn)
                                    {
                                        if (btn == 'yes')
                                        {
                                            Ext.getBody().mask('Loading..','x-mask-loading',false);
                                            Ext.getCmp('add-new-rate').getForm().submit({
                                                method:'POST',
                                                url:'/finance/rateidr/getaddrate',
                                                success:function(thisform,response){
                                                    Ext.getBody().unmask();
                                                    Ext.Msg.alert('success','New rate has been saved');
                                                    Panel = Ext.getCmp('rate-panel');
                                                    Panel.body.load ({
                                                        url:'/finance/rateidr/create',
                                                        scripts:true
                                                    })
  
                                                },failure:function(thisform, response)
                                                {
                                                    Ext.getBody().unmask();
                                                    if (response.failureType == 'server')
                                                    {
                                                        var resp = Ext.util.JSON.decode(response.response.responseText);
                                                        Ext.Msg.alert('Error',resp.pesan);
                                                    }
                                                }
                                            })
                                        }
                                    });
                        }
                    }
                },{
                    text:'Reset',
                    handler:function (btn,ev)
                    {
                        addcfs.form.reset();
                    }
                }
            ]

        });
        
        var grid = new Ext.grid.GridPanel ({

            store:ratestore,

            viewConfig:{
              forceFit:true  
            },

            title:'Rate List By Finance & Accounting Staff',
            renderTo:'viewfinancerate',
            id:'financerate',
            width:520,
            height:400,
            frame:true,
            columns:[
                new Ext.grid.RowNumberer(),
                {
                    header:'Date',
                    dataIndex:'tgl',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'IDR Rate',
                    dataIndex:'rateidr',
                    align:'center',
                    width:20,
                    sortable:true,
                    renderer: function(v, p, r) {
                        return CommaFormatted(v);
                    },
                }
                ,
                {
                    header:'Currency',
                    dataIndex:'val_kode',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'Staff',
                    dataIndex:'source',
                    align:'center',
                    width:20,
                    sortable:true
                }
            ],
            bbar: new Ext.PagingToolbar ({
                id:'paging',
                pagesize:20,
                store:ratestore,
                displayInfo:true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),
            tbar:[
                {
                    xtype:'tbtext',
                    text:'Currency',
                    style: 'margin-left: 5px'
                },'-',
                combo
                ,'-',
                {
                    xtype:'tbtext',
                    text:'From',
                    style: 'margin-left: 5px'
                },
                '-',
                {
                    xtype:'datefield',
                    name: 'startdate',
                    id: 'startdate',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype:'tbtext',
                    text:'to',
                    style: 'margin-left: 5px'
                }
                ,'-',
                {
                    xtype:'datefield',
                    name: 'enddate',
                    id: 'enddate',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype: 'button',
                    text: 'Show',
                    width:70,
                    id: 'show_finance_rate',
                    cls:"x-btn-text-icon" ,
                    icon:"/images/icons/fam/control_rewind.png",
                    handler:showfinancerate
                }
            ]

        });
        
        
    })

</script>


<div id="rateform"></div>
<br/>
<div id="viewfinancerate"></div>

 
