<script type="text/javascript">
    
    var grid;
    var grid2;
    
    function showsystemrate()
    {
        var d2 = new Date(Ext.getCmp('startdate2').getValue());
        var from2 = d2.getFullYear()+'-'+(d2.getMonth()+1)+'-'+d2.getDate();
        
        var e2 = new Date(Ext.getCmp('enddate2').getValue());
        var to2 = e2.getFullYear()+'-'+(e2.getMonth()+1)+'-'+e2.getDate();
        
        var val_kode2 = Ext.getCmp('val_kode2').getValue();
        
        ratestore2.proxy.setUrl('/finance/rateidr/getviewsystemrate/val_kode/' + val_kode2 + '/from/' + from2 + '/to/' + to2);
        ratestore2.reload();
        grid2.getView().refresh();
        
        
    }
    
    
    
    function showfinancerate()
    {
        var d = new Date(Ext.getCmp('startdate').getValue());
        var from = d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate();
        
        var e = new Date(Ext.getCmp('enddate').getValue());
        var to = e.getFullYear()+'-'+(e.getMonth()+1)+'-'+e.getDate();
        
        var val_kode = Ext.getCmp('val_kode').getValue();
        ratestore.proxy.setUrl('/finance/rateidr/getviewfinancerate/val_kode/' + val_kode + '/from/' + from+ '/to/' + to);
        ratestore.reload();
        grid.getView().refresh();
        
        
    }
    
    var datas = [
        ['CNY','CNY'],
        ['EUR','EUR'],
        ['USD','USD'],
        ['KRW','KRW']
    ];

    var store = new Ext.data.ArrayStore({
        fields: ['name', 'nilai'],
        data : datas
    });
        
    var combo = new Ext.form.ComboBox({
        store: store,
        displayField:'name',
        valueField: 'nilai',
        typeAhead: true,
        mode: 'local',
        triggerAction: 'all',
        selectOnFocus:true,
        name:'val_kode',
        width:100,
        value:'USD',
        style: 'margin-left: 5px',
        id:'val_kode'
    });
        
    var ratestore = new Ext.data.Store({

        url:'/finance/rateidr/getviewfinancerate',
        autoLoad:true,
        reader: new Ext.data.JsonReader({
            root:'data',
            totalProperty:'total'
        },[
            {name:'tgl',type:'String'},
            {name:'rateidr',type:'String'},
            {name:'val_kode',type:'String'},
            {name:'source',type:'String'}
        ])

    });
    
    var datas2 = [
        ['CNY','CNY'],
        ['EUR','EUR'],
        ['USD','USD']
    ];

    var store2 = new Ext.data.ArrayStore({
        fields: ['name', 'nilai'],
        data : datas
    });
        
    var combo2 = new Ext.form.ComboBox({
        store: store2,
        displayField:'name',
        valueField: 'nilai',
        typeAhead: true,
        mode: 'local',
        triggerAction: 'all',
        selectOnFocus:true,
        name:'val_kode2',
        width:100,
        value:'USD',
        style: 'margin-left: 5px',
        id:'val_kode2'
    });
        
    var ratestore2 = new Ext.data.Store({

        url:'/finance/rateidr/getviewsystemrate',
        autoLoad:true,
        reader: new Ext.data.JsonReader({
            root:'data',
            totalProperty:'total'
        },[
            {name:'tgl',type:'String'},
            {name:'rateidr',type:'String'},
            {name:'val_kode',type:'String'},
            {name:'source',type:'String'}
        ])

    });
        
    Ext.onReady(function(){

        Ext.QuickTips.init();

        grid = new Ext.grid.GridPanel ({

            store:ratestore,

            viewConfig:{
              forceFit:true  
            },

            title:'Rate List By Finance & Accounting Staff',
            renderTo:'viewfinancerate',
            id:'financerate',
            width:520,
            height:400,
            frame:true,
            columns:[
                new Ext.grid.RowNumberer(),
                {
                    header:'Date',
                    dataIndex:'tgl',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'IDR Rate',
                    dataIndex:'rateidr',
                    align:'center',
                    width:20,
                    sortable:true,
                    renderer: function(v, p, r) {
                        return CommaFormatted(v);
                    },
                }
                ,
                {
                    header:'Currency',
                    dataIndex:'val_kode',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'Staff',
                    dataIndex:'source',
                    align:'center',
                    width:20,
                    sortable:true
                }
            ],
            bbar: new Ext.PagingToolbar ({
                id:'paging',
                pagesize:20,
                store:ratestore,
                displayInfo:true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),
            tbar:[
                {
                    xtype:'tbtext',
                    text:'Currency',
                    style: 'margin-left: 5px'
                },'-',
                combo
                ,'-',
                {
                    xtype:'tbtext',
                    text:'From',
                    style: 'margin-left: 5px'
                },
                '-',
                {
                    xtype:'datefield',
                    name: 'startdate',
                    id: 'startdate',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype:'tbtext',
                    text:'to',
                    style: 'margin-left: 5px'
                }
                ,'-',
                {
                    xtype:'datefield',
                    name: 'enddate',
                    id: 'enddate',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype: 'button',
                    text: 'Show',
                    width:70,
                    id: 'show_finance_rate',
                    cls:"x-btn-text-icon" ,
                    icon:"/images/icons/fam/control_rewind.png",
                    handler:showfinancerate
                }
            ]

        });
        
        grid2 = new Ext.grid.GridPanel ({

            store:ratestore2,

            viewConfig:{
              forceFit:true  
            },

            title:'Rate List By System',
            renderTo:'viewfinancerate',
            id:'financerate2',
            width:520,
            height:400,
            frame:true,
            columns:[
                new Ext.grid.RowNumberer(),
                {
                    header:'Date',
                    dataIndex:'tgl',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'IDR Rate',
                    dataIndex:'rateidr',
                    align:'center',
                    width:20,
                    sortable:true,
                    renderer: function(v, p, r) {
                        return CommaFormatted(v);
                    },
                }
                ,
                {
                    header:'Currency',
                    dataIndex:'val_kode',
                    align:'center',
                    width:20,
                    sortable:true
                }
                ,
                {
                    header:'Staff',
                    dataIndex:'source',
                    align:'center',
                    width:20,
                    sortable:true
                }
            ],
            bbar: new Ext.PagingToolbar ({
                id:'paging2',
                pagesize:20,
                store:ratestore2,
                displayInfo:true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),
            tbar:[
                {
                    xtype:'tbtext',
                    text:'Currency',
                    style: 'margin-left: 5px'
                },'-',
                combo2
                ,'-',
                {
                    xtype:'tbtext',
                    text:'From',
                    style: 'margin-left: 5px'
                },
                '-',
                {
                    xtype:'datefield',
                    name: 'startdate2',
                    id: 'startdate2',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype:'tbtext',
                    text:'to',
                    style: 'margin-left: 5px'
                }
                ,'-',
                {
                    xtype:'datefield',
                    name: 'enddate2',
                    id: 'enddate2',
                    format: 'Y-m-d',
                },'-',
                {
                    xtype: 'button',
                    text: 'Show',
                    width:70,
                    id: 'show_system_rate',
                    cls:"x-btn-text-icon" ,
                    icon:"/images/icons/fam/control_rewind.png",
                    handler:showsystemrate
                }
            ]

        });
    })

</script>
<div id="viewfinancerate"></div>
<br/>
<div id="viewsystemrate"></div>

    

