<script type="text/javascript">

	var logoutHandler = function() {
            var redirect = '/mobile/logout';
            window.location = redirect; 
	};

	var erp = new Ext.Application({
	    launch: function() {
		this.tabs = new Ext.TabPanel({
		    fullscreen: true,
		    cardAnimation: 'slide',
		    dockedItems: [{
			    xtype:'toolbar', 
			    title:'Mobile ERP',    
			    items: [
					{xtype: 'spacer'},
					{
		            text: 'Logout',
		            ui: 'plain',
		            handler: logoutHandler			        
				    }]
		    }],
		    tabBar: {
                ui: 'light',
                dock: 'bottom',
		        layout: {
			        pack: 'center'
				    }
		    	},
                items: [{
	                        title: 'Main', 
	                        iconCls: 'user',
	                        cls: 'maintab',    
	                        scroll: 'vertical',
	                        html: '<tpl>' +
	                        	  'Welcome <?php echo $this->account[name];?>' +
	                        	  '</tpl>'
                        },{
                        	iconCls: 'time',
                        	cls: 'workflow',
                            title:'Workflow' 
                        }]
			});
	    }
	});

	</script>

<style>
.maintab {
	background: #ffffff;
}

.workflow {
	background: #ffffff;
	background-image:
		url(http://i.tinysrc.mobi/320/http://www.unc.edu/world/College_Updates_2009/world-globe.jpg);
	background-repeat: no-repeat;
}
</style>
