<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<style type="text/css">

#parents {
    width: 840px;
    float: left;
}

.info{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}

#child {
    float: left;
    margin-right: 10px;
    border: solid 2px #DEDEDE;
    padding: 3px 3px 3px 3px;
}

.parentContainer{
    margin: 5px;
    padding: 0px;
    border: none;
    width: 360px;
    height: 200px;
    overflow: auto;
    font-size: 14px;
}

</style>

<div class="info">
<table>
<tr>
    <td>Transaction Number</td><td>:</td><td><?php echo $this->trano; ?></td>
</tr>
<tr>
    <td>Username</td><td>:</td><td><?php echo $this->userEdit; ?></td>
</tr>
<tr>
    <td>Date</td><td>:</td><td><?php echo $this->date; ?></td>
</tr>
<tr>
    <td>Action</td><td>:</td><td><?php echo $this->action; ?></td>
</tr>
</table>
</div>
<br>
<div id="parents">
<div id="child">
    <h1>Data Before</h1>
<?php
        $i = 1;
        foreach ($this->before as $k => $v)
        {
        $no = 1;
?>
<h1><?php echo $k; ?></h1>
<div class="parentContainer">
<table id="budgetTable<?php echo $i; ?>" class="budgetTable<?php echo $i; ?>">
    <thead id="fixed">
        <tr>
            <th scope="col" align="left"><b>No</b></th>
            <?php
                //ambil nama column....
                if ($v[0] != '')
                {
                    foreach ($v[0] as $k2 => $v2)
                    {
            ?>
                <th scope="col" align="center"><b><?php echo $k2; ?></b></th>
            <?php
                    }
            ?>
        </tr>

    </thead>

    <tbody>
    	<?php
                    foreach($v as $k3 => $v3)
                    {
         ?>
                <tr>
                    <td><?php echo $no; ?></td>
        <?php
                        foreach($v3 as $k4 => $v4)
                        {
                            if (is_numeric($v4))
                            {
                                $align = 'align="right"';
                            }
                            else
                                $align = '';
        ?>
                    <td <?php echo $align; ?>><?php echo $v4; ?></td>
        <?php
                        }
        ?>
                </tr>
        <?php
                    $no++;
                    }
                }
        ?>
    </tbody>
</table>
</div>
        
<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable<?php echo $i; ?>", {
		cssSkin : "sSky",
		fixedCols : 1,
		headerRows : 1
	});
})();

</script>
<?php
            $i++;
        }
?>

</div>
<div id="child">
    <h1>Data After</h1>
<?php
        $i++;
        foreach ($this->after as $k => $v)
        {
            $no = 1;
?>
<h1><?php echo $k; ?></h1>
<div class="parentContainer">
<table id="budgetTable<?php echo $i; ?>" class="budgetTable<?php echo $i; ?>">
    <thead id="fixed">
        <tr>
            <th scope="col" align="left"><b>No</b></th>
            <?php
                //ambil nama column....
                if ($v[0] != '')
                {
                    foreach ($v[0] as $k2 => $v2)
                    {
            ?>
                <th scope="col" align="center"><b><?php echo $k2; ?></b></th>
            <?php
                    }
            ?>
        </tr>

    </thead>

    <tbody>
    	<?php
                    foreach($v as $k3 => $v3)
                    {
         ?>
                <tr>
                    <td><?php echo $no; ?></td>
        <?php
                        foreach($v3 as $k4 => $v4)
                        {
                            if (is_numeric($v4))
                            {
                                $align = 'align="right"';
                            }
                            else
                                $align = '';
        ?>
                    <td <?php echo $align; ?>><?php echo $v4; ?></td>
        <?php
                        }
        ?>
                </tr>
        <?php
                    $no++;
                    }
                }
        ?>
    </tbody>
</table>
</div>

<script type="text/javascript">

(function() {
	var mySt = new superTable("budgetTable<?php echo $i; ?>", {
		cssSkin : "sSky",
		fixedCols : 1,
		headerRows : 1
	});
})();

</script>
<?php
            $i++;
        }
?>
</div>
</div>
