<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var periodeStore = new Ext.data.Store ({

            autoLoad:true,
            url:'/finance/periode/getviewperiode',
            reader: new Ext.data.JsonReader ({
                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'tahun',type:'String'
                },{
                    name:'perkode'
                },{
                    name:'tgl_awal'
                },{
                    name:'tgl_akhir'
                },{
                    name:'bulan'
                },{
                    name:'aktif'
                }]
            })

        })

        var periodeGrid = new Ext.grid.GridPanel({

            store:periodeStore,
            renderTo:'view_periode',
            frame:true,
            height:300,
            width:620,
            viewConfig:{

                forceFit:true
            },
            columns:[{
                header:'Periode Code',
                dataIndex:'perkode',
                sortable:true,
                align:'center'
            },{
                header:'Year',
                dataIndex:'tahun',
                sortable:true,
                align:'center'
            },{
                header:'Month',
                dataIndex:'bulan',
                sortable:true,
                align:'center'
            },{
                header:'Start Date',
                dataIndex:'tgl_awal',
                sortable:true,
                align:'center'
            },{
                header:'End Date',
                dataIndex:'tgl_akhir',
                sortable:true,
                align:'center'
            },{
                header:'Active',
                dataIndex:'aktif',
                sortable:true,
                align:'center'
            }],
            bbar:new Ext.PagingToolbar ({
                pageSize:20,
                store:periodeStore,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            })


        })



    })

</script>

    <div id="view_periode"></div>


 
