<script type="text/javascript">

    Ext.onReady(function() {

        Ext.QuickTips.init();
        showReport = function() {

            var kodebrg = Ext.getCmp('kode_brg_text').getValue();
            var periode = Ext.getCmp('periode_txt').getValue();
            var gudang = Ext.getCmp('warehouse_text').getValue();

            var errorMsg = '';

            if (kodebrg == '')
                errorMsg += '- Product ID field is required <br />';
            if (periode == '')
                errorMsg += '- Periode field is required <br />';
            if (gudang == '')
                errorMsg += '- Warehouse field is required';

            if (errorMsg != '') {
                Ext.MessageBox.show({
                    title: 'Error',
                    msg: errorMsg,
                    buttons: Ext.MessageBox.OK,
                    icon: Ext.MessageBox.ERROR
                });
                return false;
            }


            var myPanel = Ext.getCmp('abs-budget-panel'),
                    kode_brg = Ext.getCmp('kode_brg_text').getValue(),
                    periode = Ext.getCmp('periode_txt').getValue(),
                    warehouse = Ext.getCmp('warehouse_selector_id').getWarehouse();

//            if (Ext.getCmp('all-warehouse').getValue())
//                warehouse = '';


            myPanel.body.load({
                url: '/logistic/report/det-stock-card',
                params: {
                    periode: periode,
                    kode_brg: kode_brg,
                    gdg_kode: warehouse
                },
                scripts: true
            });


        };

        exportReport = function() {
            myPanel = Ext.getCmp('abs-budget-panel');
            var kode_brg = Ext.getCmp('kode_brg_text').getValue();
            var periode = Ext.getCmp('periode_txt').getValue();
            var gudang = Ext.getCmp('warehouse_text').getValue();
            var warehouse = Ext.getCmp('warehouse_selector_id').getWarehouse();
//            var option = Ext.getCmp('option').getValue();
//            var search = Ext.getCmp('search').getValue();
//            var optionParam = '';
//            if (warehouse == undefined)
//                warehouse = '';

//            if (Ext.getCmp('all-warehouse').getValue())
//                warehouse = '';

//            if (search !== '')
//                optionParam = '/' + option + '/' + search;

            if (kode_brg == '' || periode == '' || gudang =='')
            {
                Ext.MessageBox.show({
                    title: 'Error',
                    msg: 'Please fill all required fields (Product ID , Periode, & Warehouse)!',
                    buttons: Ext.MessageBox.OK,
                    icon: Ext.MessageBox.ERROR
                });
                return false;
            }
            if (combo.getRawValue() == '')
            {
                Ext.MessageBox.show({
                    title: 'Error',
                    msg: 'Please Select Format!',
                    buttons: Ext.MessageBox.OK,
                    icon: Ext.MessageBox.ERROR
                });
                return false;
            }
            else
            {
                periode = Ext.getCmp('periode_txt').getValue();
                urlLoad = '/jasper/detcardstock/periode/' + periode + '/gdg_kode/' + warehouse + '/kode_brg/' + kode_brg + '/type/' + combo.getValue();

            }


            window.open(urlLoad, 'mywin',
                    'left=20,top=20,width=100,height=20,toolbar=0,resizable=0');
        };



        Ext.apply(Ext.form.VTypes, {
            daterange: function(val, field) {
                var date = field.parseDate(val);

                if (!date) {
                    return false;
                }
                if (field.startDateField && (!this.dateRangeMax || (date.getTime() != this.dateRangeMax.getTime()))) {
                    var start = Ext.getCmp(field.startDateField);
                    start.setMaxValue(date);
                    start.validate();
                    this.dateRangeMax = date;
                }
                else if (field.endDateField && (!this.dateRangeMin || (date.getTime() != this.dateRangeMin.getTime()))) {
                    var end = Ext.getCmp(field.endDateField);
                    end.setMinValue(date);
                    end.validate();
                    this.dateRangeMin = date;
                }
                /*
                 * Always return true since we're only using this vtype to set the
                 * min/max allowed values (these are tested for after the vtype test)
                 */
                return true;
            }
        });

        var callbackFunc = function()
        {
            //Ext.getCmp('periode_txt').setValue('');

        };

        var datas = new Ext.data.SimpleStore({
            fields: ['type', 'name']
            , data: [['pdf', 'PDF'], ['xls', 'Excel']]
        });

        var combo = new Ext.form.ComboBox({
            fieldLabel: 'Export'
            , name: 'showReport'
            , store: datas
            , valueField: 'type'
            , displayField: 'name'
            , typeAhead: true
            , mode: 'local'
            , triggerAction: 'all'
            , value: 'pdf'
            , selectOnFocus: true
            , anchor: '95%'
            , hiddenName: 'type'
            , width: 70
            , editable: false

        });

        var windowForm = ({
            title: 'Detail Stock Card Report',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg: {cls: 'xpanel-body-table', style: {'overflow': 'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar: [
                {
                    xtype: 'tbtext',
                    text: 'Product ID'
                },
                {
                    xtype: 'itemselector',
                    id: 'kode_brg',
                    Selectid: 'kode_brg_text',
                    width: 100,
                    callbackFunc: callbackFunc,
                    showAll: true,
                    nopmeal: true
                },
                '-',
                {
                    xtype: 'tbtext',
                    text: 'Periode'
                },
                {
                    xtype: 'periodefinanceselector',
                    id: 'perkode_text',
                    Selectid: 'periode_txt',
                    inventory: true,
                    width: 150
                },
                '-',
                {
                    xtype: 'tbtext',
                    text: 'Warehouse'
                },
                {
                    xtype: 'warehouseselector',
                    Selectid: 'warehouse_text',
                    width: 150,
                    id: 'warehouse_selector_id'
                }, '-',
                {
                    xtype: 'checkbox',
                    id: 'all-warehouse',
                    hidden: true,
                    listeners: {
                        check: function(checkbox, checked) {
                            if (checked) {
                                Ext.getCmp('warehouse_selector_id').disable();
                            } else {
                                Ext.getCmp('warehouse_selector_id').enable();
                            }
                        }
                    }
                },
                {
                    xtype: 'tbtext',
                    text: 'All Warehouse',
                    hidden: true

                },
                '-', '-',
                {
                    xtype: 'button',
                    text: 'Show',
                    width: 70,
                    id: 'show_report',
                    cls: "x-btn-text-icon",
                    icon: "/images/icons/fam/control_rewind.png",
                    handler: showReport
                }, '-', combo,
                {
                    xtype: 'button',
                    id: 'export_button',
                    cls: "x-btn-icon",
                    icon: "/images/print.png",
                    handler: exportReport
                }
            ]

        });

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c) {
            centerRegionTab.remove(c);
        });
        centerRegionTab.add(windowForm);
        centerRegionTab.layout.setActiveItem('abs-budget-panel');
//        showSubmenu('the=window');


    })
</script>