<style type="text/css">
        .tooltip {
            border-bottom: 1px dotted #000000; color: #000000; outline: none;
            cursor: help; text-decoration: none;
            position: relative;
        }
        .tooltip span {
            margin-left: -999em;
            position: absolute;
        }
        .tooltip:hover span {
            border-radius: 5px 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px;
            box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1); -webkit-box-shadow: 5px 5px rgba(0, 0, 0, 0.1); -moz-box-shadow: 5px 5px rgba(0, 0, 0, 0.1);
            font-family: Calibri, Tahoma, Geneva, sans-serif;
            position: absolute; left: 1em; top: 2em; z-index: 99;
            margin-left: 0;
        }
        .tooltip:hover img {
            border: 0; margin: -10px 0 0 -55px;
            float: left; position: absolute;
        }
        .tooltip:hover em {
            font-family: Candara, Tahoma, Geneva, sans-serif; font-size: 1.2em; font-weight: bold;
            display: block; padding: 0.2em 0 0.6em 0;
        }
        .info { padding: 0.8em 1em;background: #FFFFAA; border: 1px solid #FFAD33;width:370px; }
        .custom { padding: 0.5em 0.8em 0.8em 2em; }
        * html a:hover { background: transparent;}

</style> 

<style>

.files{
    margin-top: 30px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#E0ECEE;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}


.last-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#EFEFEF;
    /*color:#222222;*/
    color: #C15119;
    padding:4px;
    text-align:left;
}
.all-reject{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    background:#F6CBCA;
    color:#222222;
    padding:4px;
    text-align:left;
}
.all-approve{
    margin-top: 10px;
    margin-bottom: 10px;
    border:solid 1px #DEDEDE;
    /*background:#CEE6C3;*/
    color:#222222;
    padding:4px;
    text-align:left;
    height: 200px;
    overflow: auto;
}    
.body {
	/*width: 720px;*/
    /*overflow: auto;*/
}
.title {
	width: 100%;
	text-align: center;
	font-size: 18px;
	font-weight: bold;
    margin-bottom: 10px;
}
.title2 {
	width: 100%;
    float: left;
	text-align: center;
	font-size: 14px;
	font-weight: bold;
    margin-top: 10px;
	margin-bottom: 10px;
}
.etc {
	width: 100%;
	height: 50px;
}
.kanan-etc {
	float: right;
	width: 48%;
}
.kiri-etc {
	float: left;
	width: 48%;
}
.blok {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
}
.blokoverhead {
	font-size: 12px;
	font-weight: bold;
	margin-bottom: 5px;
    color: #ff0000;
}
.budgetTable {
	width: 100%;
	font-size: 12px;
	font-weight: normal;
}

/*css for afe &boq3 table*/
table.afe
{ width: 700px;
background-color: #fafafa;
border: 1px #000000 solid;
border-collapse: collapse;
border-spacing: 0px; }


td.afeheader
{ background-color: #99CCCC;
border: 1px #000000 solid;
font-weight: bold;
font-size: 14px;
text-align: center;
color: #404040; }


td.afeisi
{ border-bottom: 1px #6699CC dotted;
font-weight: normal;
font-size: .7em;
color: #404040;
background-color: #fafafa;
padding-top: 4px;
padding-bottom: 4px;
padding-left: 8px;
padding-right: 8px; }

#afe_info {
    margin-bottom: 30px;
}

td.total
{
    font-weight: bold;
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    border-bottom: 1px #000000 solid;
    border-top: 1px #000000 solid;
}

td.margin
{
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    font-weight: bold;
    color: red;
}

td.movement
{
    font-size: .7em;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 8px;
    padding-right: 8px;
    font-weight: bold;
    color: red;
    background-color: #ffff00;
}

/*end here*/
    
</style>

<style type="text/css">
    .x-grid3-td-name b {
            font-family:tahoma, verdana;
            display:block;
            color:#333;
    }
    .x-grid3-td-name b i {
        font-weight:normal;
        font-style: normal;
        color:#000;
    }
    .x-grid3-td-name .personicon {
        padding-left:20px;
        background:transparent url(/images/engineer-icon.png) no-repeat 0 2px;
    }
    .x-grid3-td-name .x-grid3-cell-inner {
        white-space:normal;
    }

    .x-grid3-row-body p {
        margin:5px 20px 10px 25px !important;
        color:#555;
    }

    .rolename {
        color:#333;
    }

</style>


<script type="text/javascript">
    Ext.onReady(function(){
        <?php if (!$this->preview && !$this->show) { ?>
            <?php if ($this->approve) { ?>
                //Variabel yg dikirim, approve / reject sama variabelna...
                var trano = '<?=$this->docsID?>';
                var uid = '<?=$this->uid?>';
                var user_id = '<?=$this->userID?>';

                <?php if (!$this->reject) { ?>
                    var wButt = new Ext.ux.workflowButton({
                        renderTo: 'wButton',
                        showApproveButton: true,
                        showRejectButton: true,
                        showAskButton: true,
                        showCancelButton: true,
                        trano: '<?=$this->trano?>',
                        itemType: 'AFE',
                        approveParams: {trans:trano, user: uid, user_id:user_id},
                        rejectParams: {trans:trano, user: uid, user_id:user_id},
                        beforeApproveCallback: function(theWButton) {
                            var cb = function(bypass) {
                                if (bypass == undefined)
                                    bypass = false;
                                theWButton.approveParams.bypass_next = bypass;
                                var cbcomment = function(comment) {
                                    theWButton.approveParams.comment = comment;
                                    theWButton.doApprove(theWButton.approveParams);
                                };
                                theWButton.showComment(cbcomment);
                            };
                            checkNominalWorkflow(uid, trano,'<?=$this->trano?>', cb);
                        },
                        approveSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts : true
                            });
                        },
                        rejectSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts : true
                            });
                        },
                        cancelSuccessCallback: function() {
                            getDocs();
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/default/home/showprocessdocument',
                                scripts : true
                            });
                        }
                    });

                    wButt.on('beforeworkflowapprove',function(t){

                    });
                <?php } else { ?>
                    var wButt = new Ext.ux.workflowButton({
                        renderTo: 'wButton',
                        showEditButton: true,
                        itemType: 'AFE',
                        editSuccessCallback: function() {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/projectmanagement/afe/editafe',
                                params: {
                                    trano: '<?php echo $this->trano; ?>'
                                },
                                scripts : true
                            });
                        }
                    });
                <?php } ?>
            <?php } else { ?>
                // variabel yg dikirim untuk submit ke workflow
                var json = '<?php echo $this->jsonResult; ?>';
                var json2 = '<?php echo $this->jsonResult2; ?>';
                var jsonFile = '<?php echo $this->jsonFile; ?>';

                <?php if (!$this->edit) { ?>
                    var url = '/projectmanagement/afe/insertafe',
                        urlCancel = '/projectmanagement/afe/addafe/returnback/true',
                        edit = false;
                
                    var parameter = '[{"prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($marginAFEToOri)?>", "margin2": "<?=number_format($marginAFEToCurrent)?>"}]';
                    
                <?php } else { ?>
                    var url = '/projectmanagement/afe/updateafe',
                        urlCancel = '/projectmanagement/afe/editafe/trano/'+'<?=$this->etc[0]['trano']?>',
                        edit = true;
                
                    var parameter = '[{"trano":"<?=$this->etc[0]['trano']?>","prj_kode":"<?=$this->etc[0]['prj_kode']?>","prj_nama":"<?=$this->etc[0]['prj_nama']?>", "sit_kode":"<?=$this->etc[0]['sit_kode']?>", "sit_nama":"<?=$this->etc[0]['sit_nama']?>" ,"ket" : "<?=$this->etc[0]['ket']?>","add_rev" : "<?=$this->etc[0]['add_rev']?>","pocustomer" : "<?=$this->etc[0]['pocustomer']?>","totalpocustomer" : "<?=$this->etc[0]['totalpocustomer']?>","val_kode" : "<?=$this->etc[0]['val_kode']?>","rateidr" : "<?=$this->etc[0]['rateidr']?>","margin" : "<?=number_format($marginAFEToOri)?>", "margin2": "<?=number_format($marginAFEToCurrent)?>"}]';
                    
                <?php } ?>
                    
                
                var params = {
                    posts:json, 
                    etc:parameter, 
                    posts2:json2, 
                    file: jsonFile,
                    item_type: 'AFE'
                };
                    
                var wButt = new Ext.ux.workflowButton({
                    renderTo: 'wButton',
                    itemType: 'AFE',
                    showSubmitButton: true,
                    showCancelButton: true,
                    urlSubmit: url,
                    isEdit: edit,
                    submitParams: params,
                    submitSuccessCallback: function() {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: '/projectmanagement/afe/afe',
                            scripts : true
                        });
                    },
                    cancelSuccessCallback: function() {
                        myPanel = Ext.getCmp('abs-budget-panel');
                        myPanel.body.load({
                            url: urlCancel,
                            params: params,
                            scripts : true
                        });
                    }
                });

            <?php } ?>
        <?php } ?>
    });

</script>


<link rel="stylesheet" type="text/css" href="/css/table.css"/>

<div class="body">

<div class="title">APPROVAL FOR EXPENDITURE</div>

<?php if ($this->reject) { ?>
<div class="last-reject">
        This Document was Rejected by <?php echo $this->lastReject[0]['name']; ?> at <?php echo date('d-m-Y H:i:s',strtotime($this->lastReject[0]['date'])); ?>
        <br />
        Comment : <?php echo $this->lastReject[0]['comment']; ?>
</div>
<?php } 
?>

<div class="etc">
	<div class="kiri-etc">
        <div class="blok">Submitted Date : <?=date("d M Y",strtotime($this->tglAfe));?></div>
        <div class="blok">Final Approved Date : <?=date("d M Y",strtotime($this->finalDate));?></div>
	<?php if ($this->edit || $this->approve) {?><div class="blok">AFE Number : <?=$this->etc[0]['trano']?></div><?php } ?>
        <?php if ($this->edit || $this->approve) {?><div class="blok">PIC : <?=$this->etc[0]['user']?></div><?php } ?>
        <div class="blok">Project : <?=$this->etc[0]['prj_kode']?> - <?=$this->etc[0]['prj_nama']?></div>
	</div>

    <div class="kanan-etc">

         <div class="blok">Currency : <?=$this->etc[0]['val_kode']?></div>
         <div class="blok">Exchange Rate : <?=number_format($this->etc[0]['rateidr'])?></div>
	 <div class="blok">Site : <?=  ($this->etc[0]['sit_kode'] == 999) ? $this->etc[0]['sit_nama'] : $this->etc[0]['sit_kode']." - ".$this->etc[0]['sit_nama'];?></div>
         <div class="blok">Reason  : <?=$this->etc[0]['ket']?></div>
    </div>

   
</div>

<?php if ($this->file != '') { ?>
    <br>
<div class="files">
    <div class="blok">Attachment Files For Additional Revenue :</div>
    <ul>
    <?php foreach ($this->file as $key => $val) { ?>
    <li>- <a href="#" onclick="window.open('/default/file/download/path/files/filename/<?php echo $val['savename']; ?>','mywin','left=20,top=20,width=100,height=20,toolbar=0,resizable=0');"><?php echo $val['filename']; ?></a></li>
    <?php } ?>
    </ul>
</div><br />
<?php } ?>

<?php
    $boq2_oriTotal = $this->etc[0]['boq2_oriIDR'] + ($this->etc[0]['boq2_oriUSDinIDR']);
    $boq2_currentTotal = $this->etc[0]['boq2_currentIDR']+($this->etc[0]['boq2_currentUSD']*$this->etc[0]['rateidr']);

?>

<div id = 'afe_info'>

    <center>

        <?php
            $afeValIDR = floatval($this->etc[0]['afeValIDR']);
            $afeValUSD = floatval($this->etc[0]['afeValUSD']);
            
            $val = $this->etc[0]['val_kode'];
            if ($val == 'IDR')
            {
                $add_rev_idr = $this->etc[0]['add_rev'];
                $add_rev_usd = 0;
                $total_rev = $add_rev_idr+($add_rev_usd*$this->etc[0]['rateidr']);
                $afeValTotal = $afeValIDR+($afeValUSD*$this->etc[0]['rateidr']);

                $addRevIDR = floatval($this->etc[0]['add_rev']);
                $addRevUSD = 0;
                $addRevTotal = $addRevIDR;

            }else
            {
                $add_rev_idr = 0;
                $add_rev_usd = $this->etc[0]['add_rev'];
                $total_rev = $add_rev_idr+($add_rev_usd*$this->etc[0]['rateidr']);
                $afeValTotal = $afeValIDR+($afeValUSD*$this->etc[0]['rateidr']);
               
                $addRevUSD = floatval($this->etc[0]['add_rev']);
                $addRevIDR = 0;
                $addRevTotal = $addRevUSD*$this->etc[0]['rateidr'];
            }
            
            $mip = $this->etc[0]['mip'];
            $mipIDR = $mip['mip_currentIDR'];
            $mipUSD = $mip['mip_currentHargaUSD'];
            $mipUSDRate = $mip['mip_currentHargaUSDRate'];
            $mip_total_IDR = $mip['mip_currentIDR'] + $mip['mip_currentHargaUSDRate'];
            
//            $salary_IDR = $mip['salary_IDR'];
//            $salary_USD = $mip['salary_USD'];
//            $rpi_approved_IDR = $mip['rpi_approved_IDR'];
//            $rpi_approved_USD = $mip['rpi_approved_USD'];
//            $asf_IDR = $mip['asf_IDR'];
//            $asf_USD = $mip['asf_USD'];
//            $pmeal_IDR = $mip['pmeal_IDR'];
//            $pmeal_USD = $mip['pmeal_USD'];
//            $fdopoIDR = $mip['fdopoIDR'];
//            $fdopoUSD = $mip['fdopoUSD'];
//            $material_return_IDR = $mip['material_return_IDR'];
//            $material_return_USD = $mip['material_return_USD'];

            //Balance Budget dalam IDR
            $balance_budget = floatval((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD))*$this->etc[0]['rateidr']);

            //Balance Budget dalam USD
            $balance_budget_in_USD = (floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD));
           

            $boq3_oriInIDR = floatval($this->etc[0]['boq3_oriUSD'])*$this->etc[0]['rateidr'];
//            $boq3_currentInIDR = floatval($this->etc[0]['boq3_currentUSD'])*$this->etc[0]['rateidr'];
            $boq3_currentInIDR = floatval($mip['mip_currentUSD'])+ $balance_budget;

            $boq3_oriTotal = $this->etc[0]['boq3_oriIDR']+$this->etc[0]['boq3_oriUSDRate'];//($this->etc[0]['boq3_oriUSD']*$this->etc[0]['rateidr']);
            $boq3_currentTotal = $this->etc[0]['current_budget'];//$this->etc[0]['boq3_currentIDR']+$mipUSDRate+($this->etc[0]['boq3_currentUSD']-$mipUSD)*$this->etc[0]['rateidr'];

            $totalCurrentBoq3 = $afeValTotal + $boq3_currentTotal;

            $percentage = $totalCurrentBoq3==0 ? 0 : ($afeValTotal/$totalCurrentBoq3)*100;
            

            $total_co_idr = (floatval($this->etc[0]['boq2_currentIDR']) + floatval($add_rev_idr));
            $total_co_usd = (floatval($this->etc[0]['boq2_currentUSD']) + floatval($add_rev_usd));
            $total_current_co = $total_co_idr+($total_co_usd*$this->etc[0]['rateidr']);

            $total_add_cost_idr = (floatval($this->etc[0]['boq3_currentIDR']) + floatval($afeValIDR));
            $total_add_cost_usd = (floatval($this->etc[0]['boq3_currentUSD']) + floatval($afeValUSD));
//            $total_current_add_cost = $total_add_cost_idr + ($total_add_cost_usd * $this->etc[0]['rateidr']);
            $total_current_add_cost = $boq3_currentTotal+floatval($afeValIDR)+floatval($afeValUSD*$this->etc[0]['rateidr']);
                                      

            $val_grossmargin_origin_idr = $this->etc[0]['boq2_oriIDR']-$this->etc[0]['boq3_oriIDR'];
            $val_grossmargin_origin_usd = $this->etc[0]['boq2_oriUSD']-$this->etc[0]['boq3_oriUSD'];

            $val_grossmargin_prev_idr = $this->etc[0]['boq2_currentIDR']-$this->etc[0]['boq3_currentIDR'];
            $val_grossmargin_prev_usd = $this->etc[0]['boq2_currentUSD']-$this->etc[0]['boq3_currentUSD'];

            $val_grossmargin_addcost_idr = $add_rev_idr-$afeValIDR;
            $val_grossmargin_addcost_usd = $add_rev_usd-$afeValUSD;

            $val_grossmargin_totalcurr_idr = $total_co_idr-$total_add_cost_idr;
            $val_grossmargin_totalcurr_usd = $total_co_usd-$total_add_cost_usd;

            //$total_grossmargin_origin = $val_grossmargin_origin_idr+($val_grossmargin_origin_usd*$this->etc[0]['rateidr']);
            $total_grossmargin_origin = floatval($val_grossmargin_origin_idr) + floatval($val_grossmargin_origin_usd)*floatval($this->etc[0]['boq3_rateidr']);
//            $total_grossmargin_prev = floatval($val_grossmargin_prev_idr) + (floatval($val_grossmargin_prev_usd) * $this->etc[0]['rateidr']);
            $total_grossmargin_prev = $boq2_currentTotal-$boq3_currentTotal;
            //$total_grossmargin_add = $val_grossmargin_addcost_idr+($val_grossmargin_addcost_usd*$this->etc[0]['rateidr']);
            $total_grossmargin_add = floatval($total_rev)- floatval($afeValTotal);
//            $total_grossmargin_current = floatval($val_grossmargin_totalcurr_idr) + ($val_grossmargin_totalcurr_usd * $this->etc[0]['rateidr']);
            $total_grossmargin_current = $total_current_co-$total_current_add_cost;//$val_grossmargin_totalcurr_idr+($val_grossmargin_totalcurr_usd*$this->etc[0]['rateidr']);

            $percen_grossmargin_origin = $boq2_oriTotal==0 ? 0 : ($total_grossmargin_origin/$boq2_oriTotal)*100;
            $percen_grossmargin_prev = $boq2_currentTotal==0 ? 0 : ($total_grossmargin_prev/$boq2_currentTotal)*100;

            $percen_grossmargin_totalcurrent = $total_current_co==0 ? 0 : ($total_grossmargin_current/$total_current_co)*100;
           
            //$percen_grossmargin_actual_current = (1 - (floatval($mip_total_IDR)/floatval($total_current_co))) * 100;
            $percen_grossmargin_actual_current = $this->progress==0 ? 0: floatval((($total_current_co*$this->progress - $mip_total_IDR)/$total_current_co*$this->progress) * 100);
            $percen_grossmargin_add = $total_rev == 0 ? 'N/A' : ($total_grossmargin_add/$total_rev)*100;
           

            $gm_mov_origin = $percen_grossmargin_totalcurrent - $percen_grossmargin_origin;
            $gm_mov_prev = $percen_grossmargin_totalcurrent - $percen_grossmargin_prev;

        ?>

        <table class="afe" cellspacing="0">

            <tr>
                <td class="afeheader">Description</td>
                <td class="afeheader">Valuta</td>
                <td class="afeheader">Origin</td>
                <td class="afeheader">Previous</td>
                <td class="afeheader">Add(subt)</td>
                <td class="afeheader">Total Current</td>
            </tr>

            <tr>
                <td class="afeisi">Customer Order (CO)</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_oriIDR']))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_currentIDR']))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($add_rev_idr))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_co_idr))?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_oriUSD']),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq2_currentUSD']),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($add_rev_usd),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_co_usd),2)?></td>
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq2_oriTotal))?><span class="info" style="text-align:left">
                 Origin CO IDR + Origin CO USD <br>
                 Origin CO IDR : <?=number_format(floatval($this->etc[0]['boq2_oriIDR']));?><br>
                 Origin CO USD : <?=number_format(floatval($this->etc[0]['boq2_oriUSD']),2);?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq2_rateidr']));?>)<br>
                </span></a></td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq2_currentTotal))?><span class="info" style="text-align:left">
                 Previous CO IDR + Previous CO USD <br>
                 Previous CO IDR : <?=number_format(floatval($this->etc[0]['boq2_currentIDR']));?><br>
                 Previous CO USD : <?=number_format(floatval($this->etc[0]['boq2_currentUSD']),2);?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>         
                </span></a></td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_rev))?><span class="info" style="text-align:left">
                  Add(subt) CO IDR + Add(subt) CO USD <br>
                  Add(subt) CO IDR : <?=number_format(floatval($add_rev_idr));?><br>
                  Add(subt) CO  USD : <?=number_format(floatval($add_rev_usd),2);?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>           
                </span></a></td>

                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_current_co))?><span class="info" style="text-align:left">
                   Total Current CO IDR + Total Current CO USD <br>
                   Total Current CO IDR : <?=number_format(floatval($total_co_idr));?><br>
                   Total Current CO USD : <?=number_format(floatval($total_co_usd),2);?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>         
                </span></a></td> 

            </tr>

            <tr>
                <td class="afeisi">Add(Subt) Cost</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_oriIDR']))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_currentIDR']))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($afeValIDR))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_add_cost_idr))?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_oriUSD']),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($this->etc[0]['boq3_currentUSD']),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($afeValUSD),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($total_add_cost_usd),2)?></td>
            </tr>
            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">&nbsp;</td>
                <td class="afeisi" align="right"><a class="tooltip" href="#" >Recorded Cost<span class="info" style="text-align:left">ASF Claim + BSF Claim + Piecemeal + OCA + RPI(to site) + DO - (Material Return + Material Cancel) - Cancel RPI</span></a></td></td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipUSD))?></td>
                    
                <td class="afeisi" align="right">&nbsp;</td>
                <td class="afeisi" align="right">&nbsp;</td>
            </tr>
            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">&nbsp;</td>
                <td class="afeisi" align="right">Balance Budget</td>
                <td class="afeisi" align="right"><?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)))?></td>
                 <td class="afeisi" align="right">&nbsp;</td>
                <td class="afeisi" align="right">&nbsp;</td>
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq3_oriTotal))?><span class="info" style="text-align:left">
                Origin Add(Subt) Cost IDR + Origin Add(Subt) Cost USD <br>
                Origin Add(Subt) Cost IDR : <?=number_format(floatval($this->etc[0]['boq3_oriIDR']))?><br>
                Origin Add(Subt) Cost USD : <?=number_format(floatval($this->etc[0]['boq3_oriUSD']),2)?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq3_rateidr']));?>)
                </span></a></td>     
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($boq3_currentTotal))?><span class="info" style="text-align:left">
                Previous Add(Subt) Cost IDR + Recorded Cost USD + Balance Budget USD <br>
                Previous Add(Subt) Cost IDR : <?=number_format(floatval($this->etc[0]['boq3_currentIDR']))?><br>
                Recorded Cost USD : <?=number_format(floatval($mipUSDRate),2)?> (<?=number_format(floatval($mipUSD),2)?> * Transaction's exchange rate) <br>
               
                Balance Budget USD : <?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)),2)?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>
                </span></a></td>     
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format($afeValTotal)?><span class="info" style="text-align:left">
                Add(Subt) Cost IDR + Add(Subt) Cost USD <br>
                Add(Subt) Cost IDR : <?=number_format(floatval($afeValIDR));?><br>
                Add(Subt) Cost USD : <?=number_format(floatval($afeValUSD),2)?> * <?=number_format(floatval($this->etc[0]['rateidr']))?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format($total_current_add_cost)?><span class="info" style="text-align:left">
                Total Current Add(Subt) Cost IDR  + Recorded Cost USD + Balance Budget USD + Add(Subt) Cost USD <br>
                Total Current Add(Subt) Cost IDR : <?=number_format(floatval($total_add_cost_idr));?><br>
                Recorded Cost USD : <?=number_format(floatval($mipUSDRate),2)?> (<?=number_format(floatval($mipUSD),2)?> * Transaction's exchange rate) <br>
                
                Balance Budget USD : <?=number_format((floatval($this->etc[0]['boq3_currentUSD'])-floatval($mipUSD)),2)?> * <?=number_format(floatval($this->etc[0]['rateidr']));?><br>
                Add(Subt) Cost USD : <?=number_format(floatval($afeValUSD),2)?> * <?=number_format(floatval($this->etc[0]['rateidr']))?>
                </span></a></td> 
           
            </tr>

            <tr>
                <td class="afeisi">Gross Margin</td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_origin_idr))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_prev_idr))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_addcost_idr))?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_totalcurr_idr))?></td>
              
            </tr>

             <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_origin_usd),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_prev_usd),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_addcost_usd),2)?></td>
                <td class="afeisi" align="right"><?=number_format(floatval($val_grossmargin_totalcurr_usd),2)?></td>
          
            </tr>

            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_origin))?><span class="info" style="text-align:left">
                Origin Gross Margin IDR + Origin Gross Margin USD<br>
                Origin Gross Margin IDR : <?=number_format(floatval($val_grossmargin_origin_idr))?> <br>
                Origin Gross Margin USD : <?=number_format(floatval($val_grossmargin_origin_usd),2)?> * Transaction's rate (<?=number_format(floatval($this->etc[0]['boq3_rateidr']))?>)
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_prev))?><span class="info" style="text-align:left">
                Previous CO Total - Previous Add(Subt) Cost Total<br>
                Previous CO Total : <?=number_format(floatval($boq2_currentTotal))?><br>
                Previous Add(Subt) Cost Total : <?=number_format(floatval($boq3_currentTotal))?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_add))?><span class="info" style="text-align:left">
                Add(Subt) CO Total - Add(Subt) Add(Subt) Cost Total <br>
                Add(Subt) CO Total : <?=number_format(floatval($total_rev))?><br>
                Add(Subt) Add(Subt) Cost Total : <?=number_format($afeValTotal)?>
                </span></a></td> 
                <td class="total" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($total_grossmargin_current))?><span class="info" style="text-align:left">
                Total Current CO Total - Total Current Add(Subt) Cost Total <br>
                Total Current CO Total : <?=number_format(floatval($total_current_co))?><br> 
                Total Current Add(Subt) Cost Total : <?=number_format($total_current_add_cost)?>
                </span></a></td> 
               
            </tr>

            <tr>
                <td class="margin">Gross Margin</td>
                <td class="margin" align="center">%</td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_origin),2)?> % <span class="info" style="text-align:left">
                (Origin Gross Margin Total / Origin CO Total) * 100% <br>
                Origin Gross Margin Total : <?=number_format(floatval($total_grossmargin_origin),2)?><br>
                Origin CO Total : <?=number_format(floatval($boq2_oriTotal),2)?> 
                </span></a></td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_prev),2)?> % <span class="info" style="text-align:left">
                (Previous Gross Margin Total / Previous CO Total) * 100% <br>
                Previous Gross Margin Total : <?=number_format(floatval($total_grossmargin_prev),2)?><br>
                Previous CO Total : <?=number_format(floatval($boq2_currentTotal),2)?>
                </span></a></td>
<!--                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_add),2)?> % <span class="info" style="text-align:left">
                (Add(Subt) Gross Margin Total / Add(Subt) CO Total) * 100% <br>
                Add(Subt) Gross Margin Total : <?=number_format(floatval($total_grossmargin_add),2)?><br>
                Add(Subt) CO Total : <?=number_format(floatval($total_rev),2)?>
                </span></a></td>-->
                <td class="margin" align="right"></td>
                <td class="margin" align="right"><a class="tooltip" href="#" ><?=number_format(floatval($percen_grossmargin_totalcurrent),2)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin Total / Total Current CO Total) * 100%<br>
                Total Current Gross Margin Total : <?=number_format(floatval($total_grossmargin_current),2)?><br>
                Total Current CO Total : <?=number_format(floatval($total_current_co),2)?>
                </span></a></td>

            </tr>

            <tr>
                <td class="movement">Gross Margin Movement</td>
                <td class="movement" align="center">%</td> <?php if($gm_mov_origin<0) $red='style="color:red"'; ?>
                <td class="movement" align="right"><a class="tooltip" href="#" <?=$red?> ><?=number_format(floatval($gm_mov_origin),2)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin % - Origin Gross Margin %)<br>
                Total Current Gross Margin % : <?=number_format(floatval($percen_grossmargin_totalcurrent),2)?> %  <br>
                Origin Gross Margin % : <?=number_format(floatval($percen_grossmargin_origin),2)?> % 
                </span></a></td>
                <?php if($gm_mov_prev<0) $red2='style="color:red"'; ?>
                <td class="movement" align="right"><a class="tooltip" href="#" <?=$red2?> ><?=number_format(floatval($gm_mov_prev),2)?> %<span class="info" style="text-align:left">
                (Total Current Gross Margin % - Previous Gross Margin %)  <br>
                Total Current Gross Margin % : <?=number_format(floatval($percen_grossmargin_totalcurrent),2)?> %  <br>
                Previous Gross Margin % : <?=number_format(floatval($percen_grossmargin_prev),2)?> % 
                </span></a></td>
                <td class="movement">&nbsp;</td>
                <td class="movement">&nbsp;</td>
            </tr>


            <tr  style="border-top: 1px #000000 solid;">
                <td class="afeisi"><a class="tooltip" href="#" >Recorded Cost<span class="info" style="text-align:left">ASF Claim + BSF Claim + Piecemeal + OCA + RPI(to site) + DO - (Material Return + Material Cancel) - Cancel RPI</span></a></td>
                <td class="afeisi" align="center">IDR</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipIDR))?></td>
            </tr>

            <tr>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="center">USD</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi">&nbsp;</td>
                <td class="afeisi" align="right"><?=number_format(floatval($mipUSD),2)?></td>
            </tr>
            <tr>
                <td class="total">Total</td>
                <td class="total" align="center">IDR</td>
                <td class="total">&nbsp;</td>
                <td class="total">&nbsp;</td>
                <td class="total">&nbsp;</td>
                <td class="total" align="right"><a class="tooltip" href="#" align="left" ><?=number_format(floatval($mip_total_IDR))?><span class="info" style="text-align:left">
                 Recorded Cost IDR + Recorded Cost USD <br>
                 Recorded Cost IDR : <?=number_format(floatval($mipIDR))?><br>   
                 Recorded Cost USD : <?=number_format(floatval($mipUSDRate))?> (<?=number_format(floatval($mipUSD),2)?> * Transaction's exchange rate) <br>
                 
                </span></a></td>
            </tr>

            <tr>
                <td class="margin">Actual Gross Margin</td>
                <td class="margin" align="center">%</td>
                <td class="margin" align="right">&nbsp;</td>
                <td class="margin" align="right">&nbsp;</td>
                <td class="margin" align="right">&nbsp;</td><?php if($percen_grossmargin_actual_current<0) $red3='style="color:red"'; ?>
                <td class="margin" align="right"><a class="tooltip" href="#" <?=$red3 ?>><?=number_format(floatval($percen_grossmargin_actual_current),2)?> %<span class="info" style="text-align:left">
                 ([Total Current CO * % Progress - Total Recorded Cost]/Total Current CO * % Progress)*100%   
                 Total Current CO : <?=number_format(floatval($total_current_co))?><br>
                 % Progress : <?=number_format(floatval($this->progress*100),2)?> %<br>
                 Total Recorded Cost : <?=number_format(floatval($mip_total_IDR))?><br>
                 
                   
                </span></a></td>
            </tr>

        </table>

    </center>

</div>


<?php   $rateidr = $this->etc[0]['rateidr'];
        if ($this->result) { ?>

<div class="title2">AFE Additional Table</div>

<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>Site Code</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Name Material</center></th>
             <th scope="col"><center>UoM</center></th>
             <th scope="col"><center>Qty (BOQ3)</center></th>
            <th scope="col"><center>Unit Price (BOQ3)</center></th>
            <th scope="col"><center>Total (BOQ3)</center></th>
            <th scope="col"><center>Qty (Request)</center></th>
            <th scope="col"><center>Unit Price (Request)</center></th>
            <th scope="col"><center>Total (Request)</center></th>
        </tr>
    	<?php

    		$totals = 0;
            $totals2 = 0;
        
       		for ($i=0;$i<(count($this->result));$i++)
    		{
    			$total = floatval($this->result[$i]['qty']) * floatval($this->result[$i]['price']);
                $total2 = floatval($this->result[$i]['qtyori']) * floatval($this->result[$i]['priceori']);


   				foreach ($this->result[$i] as $key => $val)
    			{
    				if ($val === '')
    					$this->result[$i][$key] = "&nbsp;";
    			}
    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
            <td ><?=$this->result[$i]['sit_kode']?></td>
            <td ><?=$this->result[$i]['cfs_kode']?></td>
            <td ><?=$this->result[$i]['workid']?></td>
            <td><?=$this->result[$i]['kode_brg']?> - <?=$this->result[$i]['nama_brg']?></td>
    		<td ><?=$this->result[$i]['uom']?></td>
    		<td align="right"><?=number_format(floatval($this->result[$i]['qtyori']),2)?></td>

            <td align="right"><?=(($this->result[$i]['val_kode'] != 'USD') ? number_format(floatval($this->result[$i]['priceori'])) : number_format(floatval($this->result[$i]['priceori']),2))?></td>

    		<td align="right"><?=(($this->result[$i]['val_kode'] != 'USD') ? number_format($total2) : number_format($total2,2))?></td>
            <td align="right"><?=number_format(floatval($this->result[$i]['qty']),2)?></td>

             <td align="right"><?=(($this->result[$i]['val_kode'] != 'USD') ? number_format(floatval($this->result[$i]['price'])) : number_format(floatval($this->result[$i]['price']),2))?></td>

    		<td align="right"><?=(($this->result[$i]['val_kode'] != 'USD') ? number_format($total) : number_format($total,2))?></td>
    		</tr>

        <?php
            if ($this->result[$i]['invalid'] === true)
            {
        ?>
            <tr bgcolor="#C15119">
                <td colspan="10"><b><?=$this->result[$i]['invalid_msg']?></b></td>
            </tr>

        <?php } ?>
    	<?php
    		$totals += $total;
            $totals2 += $total2;

    		}

            $totalAdd = $totals - $totals2;

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="8">Total</th>
    		<td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totals2) : number_format($totals2,2))?></td>
            <td colspan="2">&nbsp;</td>
            <td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totals) : number_format($totals,2))?></td>
    		</tr>
        <tr>
    		<th scope="row" class="spec" colspan="11">Total Additional Costs</th>
    		<td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totalAdd) : number_format($totalAdd,2))?></td>
        </tr>

</table>
<?php }

        if($this->result2) {?>

<div class="title2">AFE Saving Table</div>

<table id="mytable" cellspacing="0">
        <tr>
        	<th scope="col"><center>No.</center></th>
            <th scope="col"><center>Site Code</center></th>
            <th scope="col"><center>CFS Code</center></th>
            <th scope="col"><center>Work ID</center></th>
            <th scope="col"><center>Name Material</center></th>
             <th scope="col"><center>UoM</center></th>
             <th scope="col"><center>Qty (BOQ3)</center></th>
            <th scope="col"><center>Unit Price (BOQ3)</center></th>
            <th scope="col"><center>Total (BOQ3)</center></th>
            <th scope="col"><center>Qty (Request)</center></th>
            <th scope="col"><center>Unit Price (Request)</center></th>
            <th scope="col"><center>Total (Request)</center></th>
        </tr>
    	<?php

    		$totals3 = 0;
            $totals4 = 0;

       		for ($i=0;$i<(count($this->result2));$i++)
    		{
                $total3 = floatval($this->result2[$i]['qty']) * floatval($this->result2[$i]['price']);

                $total4 = floatval($this->result2[$i]['qtyori']) * floatval($this->result2[$i]['priceori']);

   				foreach ($this->result2[$i] as $key => $val)
    			{
    				if ($val == '')
    					$this->result2[$i][$key] = "&nbsp;";
    			}

    	?>
    		<tr>
    		<th scope="row" class="spec"><?=($i+1)?></th>
                <td ><?=$this->result2[$i]['sit_kode']?></td>
            <td ><?=$this->result2[$i]['cfs_kode']?></td>
            <td ><?=$this->result2[$i]['workid']?></td>
    		<td><?=$this->result2[$i]['kode_brg']?> - <?=$this->result2[$i]['nama_brg']?></td>
    		<td ><?=$this->result2[$i]['uom']?></td>
            <td align="right"><?=number_format(floatval($this->result2[$i]['qtyori']),2)?></td>

                <td align="right"><?=(($this->result2[$i]['val_kode'] != 'USD') ? number_format(floatval($this->result2[$i]['priceori'])) : number_format(floatval($this->result2[$i]['priceori']),2))?></td>

    		<td align="right"><?=(($this->result2[$i]['val_kode'] != 'USD') ? number_format($total4) : number_format($total4,2))?></td>
    		<td align="right"><?=number_format(floatval($this->result2[$i]['qty']),2)?></td>

                <td align="right"><?=(($this->result2[$i]['val_kode'] != 'USD') ? number_format(floatval($this->result2[$i]['price'])) : number_format(floatval($this->result2[$i]['price']),2))?></td>

    		<td align="right"><?=(($this->result2[$i]['val_kode'] != 'USD') ? number_format($total3) : number_format($total3,2))?></td>
    		</tr>

        <?php
            if ($this->result2[$i]['invalid'] === true)
            {
        ?>
            <tr>
                <th style="background-color: #ffff00; color: red; font-size: 10px;" colspan="10" class="spec"><?=$this->result2[$i]['invalid_msg']?></th>
            </tr>

        <?php } ?>
    	<?php
    		$totals3 += $total3;
            $totals4 += $total4;

    		}
            $totalSaving = $totals4 - $totals3;

    	?>
    	<tr>
    		<th scope="row" class="spec" colspan="8">Total</th>
    		<td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totals4) : number_format($totals4,2))?></td>
            <td colspan="2">&nbsp;</td>
            <td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totals3) : number_format($totals3,2))?></td>
    		</tr>
        <tr>
    		<th scope="row" class="spec" colspan="11">Total Saving to Compensate</th>
    		<td align="right"><?=(($this->result[0]['val_kode'] != 'USD') ? number_format($totalSaving) : number_format($totalSaving,2))?></td>

    		</tr>

</table>
<?php } ?>

<?php

    if($this->etc[0]['val_kode'] == IDR)
    {
      $afeValIDR = floatval($totalAdd) - floatval($totalSaving);
      $afeValUSD = 0;
      $afeValTotal = $afeValIDR;

      $addRevIDR = floatval($this->etc[0]['add_rev']);
      $addRevUSD = 0;
      $addRevTotal = $addRevIDR;

    }
    else
    {
      $afeValUSD = floatval($totalAdd) - floatval($totalSaving);
      $afeValIDR = 0;
      $afeValTotal = $afeValUSD*$this->etc[0]['rateidr'];

      $addRevUSD = floatval($this->etc[0]['add_rev']);
      $addRevIDR = 0;
      $addRevTotal = $addRevUSD*$this->etc[0]['rateidr'];
      
    }

    $boq3_oriInIDR = floatval($this->etc[0]['boq3_oriUSD'])*$this->etc[0]['rateidr'];
    $boq3_currentInIDR = floatval($this->etc[0]['boq3_currentUSD'])*$this->etc[0]['rateidr'];

    $boq3_oriTotal = $boq3_oriInIDR + $this->etc[0]['boq3_oriIDR'];
    $boq3_currentTotal = $boq3_currentInIDR + $this->etc[0]['boq3_currentIDR'];

    $totalCurrentBoq3 = $afeValTotal + $boq3_currentTotal;
            
    $percentage = $afeValTotal/$totalCurrentBoq3*100;

    if(floatval($boq2_oriTotal) == 0)
    {
        $mbpohOri = 0;
    }
    else
    {
        $mbpohOri = (1- floatval($boq3_oriTotal)/floatval($boq2_oriTotal))*100;
    }

    if(floatval($boq2_currentTotal) == 0)
    {
        $lastMbpoh = 0;
    }
    else
    {
        $lastMbpoh = (1- floatval($boq3_currentTotal)/floatval($boq2_currentTotal))*100;
    }


    if(floatval($boq2_currentTotal)+floatval($addRevTotal) == 0)
    {
        $mbpohCurrent = 0;
    }
    else
    {
        $mbpohCurrent = (1- ($totalCurrentBoq3)/(floatval($boq2_currentTotal)+floatval($addRevTotal)))*100;
    }
    $mbpohMoved = $mbpohCurrent- $mbpohOri;
    $mbpohLastCurrent = $lastMbpoh - $mbpohCurrent;

    $marginAFEToOri = floatval($percen_grossmargin_totalcurrent) - floatval($percen_grossmargin_origin);
    $marginAFEToCurrent = floatval($percen_grossmargin_totalcurrent) - floatval($percen_grossmargin_prev);


?>



 <?php
    if ( $this->etc[0]['user_approval'] != '')
    {
    ?>
    <div class="all-approve">
    <b>Approval History</b></br>
    <ul>
    <?php
        foreach ($this->etc[0]['user_approval'] as $key => $val)
        {
    ?>
            <li><?php echo "<b>" . $val['approve'] . "</b> " . date('d-m-Y H:i:s',strtotime($val['date'])) . " : " . $val['displayname'] . " (" . $val['display_name'] . ")<br />Sign : " . $val['signature'] . "<br />Comment : " . $val['comment']; ?></li>
    <?php
        }
    ?>
    </ul>
    </div>
    <?php
    }
    ?>

<?php if (!$this->show) { ?>
	<div style="margin-top:15px;">
		<div id="back-button"  style="margin-left:5px;float: right;"></div>
		<div id="cancel-button"  style="margin-left:5px;float: right;"></div>
		<div id="ok-button"  style="float: right;"></div>
	</div>
<?php } ?>

<div style="margin-top:15px; float:right;" id="wButton">

</div>