<script type="text/javascript">


    Ext.onReady(function(){

        Ext.QuickTips.init ();

        var windowForm = ({

            title: 'Open/Close Existing Project/Site',
            id: 'close-existing project',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[
                {
                    xtype:'tbbutton',
                    text:'Select Action',
                    iconCls:'menu-drop',
                    menu:{
                        items:[{
                            text:'Open Project',
                            cls:"x-btn-text-icon" ,
                            icon:"/images/icons/fam/action_paste.gif",
                            id:'open-project',
                            handler:function ()
                            {
                                panel = Ext.getCmp('close-existing project');
                                panel.body.load({
                                    url:'/projectmanagement/projectclose/openproject',
                                    scripts:true
                                })
                            }
                        },{
                            text:'Close Project',
                            cls:"x-btn-text-icon" ,
                            icon:"/images/icons/fam/action_paste.gif",
                            id:'close-project',
                            handler:function ()
                            {
                                panel = Ext.getCmp('close-existing project');
                                panel.body.load({
                                    url:'/projectmanagement/projectclose/viewproject',
                                    scripts:true
                                })
                            }
                        }]
                    }
                }
            ]

        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('close-existing project');
        centerRegionTab.layout.setActiveItem('close-existing project');
//        panelBaru.body.load({
//                url: '/projectmanagement/projectclose/viewproject',
//                scripts: true
//            });

    })

</script>