<script type="text/javascript">

    var posted;

    Ext.apply(Ext.form.VTypes, {
        numericText: "Only numbers are allowed.",
        numericMask: /[0-9]/,
        numericRe: /(^-?dd*.d*$)|(^-?dd*$)|(^-?.dd*$)/,
        numeric: function(v) {
            return function() {
                return this.numericRe.test(v)
            };
        }
    });

    var transCode = '';

    var bankchargeslist = Ext.data.Record.create([
        {name: 'trano'},
        {name: 'ref_number'},
        {name: 'tgl'},
        {name: 'uid'},
        {name: 'prj_kode'},
        {name: 'sit_kode'},
        {name: 'job_number'},
        {name: 'coa_kode'},
        {name: 'coa_nama'},
        {name: 'val_kode'},
        {name: 'debit'},
        {name: 'credit'},
        {name: 'trans'},
        {name: 'rateidr'}
    ])

    var storebankcharges = new Ext.data.GroupingStore({
        id: 'store-bankcharges',
        reader: new Ext.data.JsonReader({fields: bankchargeslist}),
        listeners: {
            'load': function(record) {
                hitungTotal();
            }
        }
    });
    var storebankchargesTrano = new Ext.data.GroupingStore({
        id: 'store-bankchargestrano',
        reader: new Ext.data.JsonReader({fields: bankchargeslist}),
        listeners: {
            'load': function(record) {
//                hitungTotal();
            }
        }
    });


    var totDebit = 0;
    var totCredit = 0;
    function hitungTotal()
    {
        totDebit = 0;
        totCredit = 0;
        storebankcharges.each(function(items) {
            totDebit += (parseFloat(items.data['debit']));
            totCredit += (parseFloat(items.data['credit']));
        });
        Ext.getCmp('debittotal').setText('Total Debit : ' + Ext.util.Format.number(totDebit, '0,0.00'));
        Ext.getCmp('credittotal').setText('Total Credit : ' + Ext.util.Format.number(totCredit, '0,0.00'));
    }

    function edit(r)
    {

        var dat = storebankcharges.getAt(r);
        Ext.getCmp('acc-number').setValue(dat.data['ref_number']);
        Ext.getCmp('coa_kode').setValue(dat.data['coa_kode']);
        Ext.getCmp('coa_nama').setValue(dat.data['coa_nama']);
        //Ext.getCmp('val-kode').setValue(dat.data['val_kode']);
        Ext.getCmp('val_kode_text').setValue(dat.data['val_kode']);
        Ext.getCmp('debit').setValue(dat.data['debit']);
        Ext.getCmp('credit').setValue(dat.data['credit']);
        Ext.getCmp('trans').setValue(dat.data['trans']);
        Ext.getCmp('job_number').setValue(dat.data['job_number']);


        Ext.getCmp('form-insert-bank-charges').stat = 'edit';
        Ext.getCmp('form-insert-bank-charges').idEdit = dat.id;
    }

    function deleterowgrid(idItem)
    {
        Ext.MessageBox.confirm('Confirm', 'Are you sure want to delete this?', function(btn) {
            if (btn == 'yes')
            {
                var store = storebankcharges;
                var dat = store.getById(idItem);
                if (dat)
                {
                    store.remove(dat);
                    Ext.getCmp('form-insert-bank-charges').stat = 'new';
                    Ext.getCmp('form-insert-bank-charges').idEdit = '';
                    Ext.getCmp('grid-bankcharges').getView().refresh();
                    hitungTotal();
                }
            }
        });
    }

    exportReport = function() {

        if (posted)
        {
            Ext.MessageBox.show({
                title: 'Error',
                msg: 'This Transaction has been validated!<br /> Please Select another Transaction',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.ERROR
            });
            return false;
        }

        myPanel = Ext.getCmp('abs-budget-panel');


        var tranoprint = Ext.getCmp('trano_id').getValue();
        if (tranoprint == '' || tranoprint == undefined)
        {
            Ext.MessageBox.show({
                title: 'Error',
                msg: 'Please Select Transaction Number!',
                buttons: Ext.MessageBox.OK,
                icon: Ext.MessageBox.ERROR
            });
            return false;
        }

        tranoprint = tranoprint.replace("/", "_");
        urlLoad = '/jasper/bankcharges/trano/' + tranoprint;

        location.href = urlLoad;
    };

    resetAll = function() {
        Ext.getCmp('form-insert-bank-charges').getForm().reset();
        Ext.getCmp('coa_kode').setValue('');
        Ext.getCmp('coa_nama').setValue('');
        Ext.getCmp('grid-bankcharges').getStore().removeAll();
        Ext.getCmp('grid-bankcharges').getView().refresh();
        hitungTotal();
    }

    Ext.onReady(function() {

        Ext.QuickTips.init();

        Ext.form.Field.prototype.msgTarget = 'side';

        var formpanel = new Ext.form.FormPanel({
            title: 'Bank Charges',
            id: 'form-insert-bank-charges',
            renderTo: 'insert_bank_charges',
            frame: true,
            labelAlign: 'top',
            style: 'margin:10 10 10 10',
            width: 400,
            stat: 'new',
            items: [{
                    xtype: 'textfield',
                    fieldLabel: 'Referrence ',
                    id: 'acc-number',
                    allowBlank: false
                },
                {
                    xtype: 'tranodatechanger',
                    anchor: '100%',
                    id: 'trano_tgl',
                    Selectid: 'tgl',
                    fieldLabel: 'Transaction Date',
                    selectValue: '<?= date("d M Y") ?>'
                },
                {
                    xtype: 'combo',
                    fieldLabel: 'Transaction ',
                    id: 'trans',
                    allowBlank: false,
                    width: 100,
                    store: new Ext.data.Store({
                        proxy: new Ext.data.HttpProxy({
                            url: '/finance/coa/gettranotype'
                        }),
                        reader: new Ext.data.JsonReader({
                            totalProperty: 'count',
                            root: 'data'
                        }, [{
                                name: 'trano'
                            }])
                    }),
                    valueField: 'trano',
                    displayField: 'trano',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'remote',
                    triggerAction: 'all',
                    selectOnFocus: true,
                    emptyText: 'Select a type ...'
                },
                {
                    xtype: 'coaselector',
                    fieldLabel: 'Chart Of Account',
                    id: 'coa_kodes',
                    Selectid: 'coa_kode',
                    Nameid: 'coa_nama',
                    width: 180,
                    ShowName: true,
                    allowBlank: false
                }, 
                {
                    xtype: 'currencyselector',
                    anchor: '100%',
                    id: 'currency-select',
                    Selectid: 'val_kode_text',
                    Nameid: 'val_nama_text',
                    ShowName: true,
                    fieldLabel: 'Currency Code',
                    allowBlank: false,
                    selectValue: 'IDR'
                },
                new Ext.ux.customRendererField({
                    xtype:'textfield',
                    fieldLabel:'IDR Rate',
                    id:'val_rate_text',
                    name: 'val_rate_text',
                    vtype:'numeric',
                    style:'text-align:right',
                    priceDelemiter:','
                }),
                /*        {
                    fieldLabel: 'Valuta ',
                    xtype: 'combo',
                    width: 100,
                    allowBlank: false,
                    store: new Ext.data.SimpleStore({
                        fields: ['name', 'nilai'],
                        data: [
                            ['IDR', 'IDR'],
                            ['USD', 'USD']
                        ]
                    }),
                    valueField: 'nilai',
                    displayField: 'name',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'local',
                    triggerAction: 'all',
                    selectOnFocus: true,
                    id: 'val-kode',
                    listeners: {
                        'select': function(c, store, index) {
                            var data = store.data['nilai'];
                            if (data != 'IDR')
                                Ext.getCmp('rateidr').setVisible(true);
                            else
                                Ext.getCmp('rateidr').setVisible(false);
                        }
                    }
                }, {
                    xtype: 'textfield',
                    id: 'rateidr',
                    width: 104,
                    fieldLabel: 'Exchange Rate',
                    value: '<?= $this->rateidr ?>',
//                    readOnly: false,
                    hidden: true
                },*/
                new Ext.ux.customRendererField(
                        {
                            xtype: 'textfield',
                            id: 'debit',
                            style: 'text-align:right',
                            priceDelemiter: ',',
                            fieldLabel: 'Debit ',
                            value: '0.00',
                            listeners: {
                                'customfocus': function(t) {
                                    Ext.getCmp('credit').setValue('');
                                }
                            }
                        }),
                new Ext.ux.customRendererField(
                        {
                            xtype: 'textfield',
                            id: 'credit',
                            style: 'text-align:right',
                            priceDelemiter: ',',
                            fieldLabel: 'Credit ',
                            value: '0.00',
                            listeners: {
                                'customfocus': function(t) {
                                    Ext.getCmp('debit').setValue('');
                                }
                            }
                        }), {
                    xtype: 'textfield',
                    id: 'job_number',
                    fieldLabel: 'Job Number ',
                    vtype: 'alphanumericonly'
                }
            ],
            buttons: [{
                    text: 'Add to Grid',
                    iconCls: 'silk-add',
                    handler: function(btn, ev)
                    {
                        if (!Ext.getCmp('form-insert-bank-charges').getForm().isValid())
                        {
                            Ext.Msg.alert('Error', 'Form not valid');
                            return false;
                        }

                        if (Ext.getCmp('debit').getValue().toString().replace(/\$|\,/g, '') == 0 && Ext.getCmp('credit').getValue().toString().replace(/\$|\,/g, '') == 0)
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry , please insert field debit or credit',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }

//                        if (storebankcharges.getCount() > 0)
//                        {
//                            var row = storebankcharges.getAt(storebankcharges.findExact('val_kode', Ext.getCmp('val-kode').getValue()));
//
//                            if (row == null)
//                            {
//                                Ext.MessageBox.show({
//                                    title: 'Error',
//                                    msg: 'Sorry this document different valuta',
//                                    buttons: Ext.MessageBox.OK,
//                                    icon: Ext.MessageBox.ERROR
//                                });
//                                return false;
//                            }
//                        }
                        //var rateidr = Ext.getCmp('rateidr').getValue();
                        //var valkode = Ext.getCmp('val-kode').getValue();
                        var rateidr = Ext.getCmp('val_rate_text').getOriginalValue();
                        var valkode = Ext.getCmp('val_kode_text').getValue();

                        if (valkode != 'IDR' && rateidr == 0) {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Exchange Rate is empty!',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }
                        //Cek job number sesuai dengan patter Qxxx.yyy (xxx == kode project, yyy == cfs kode)
                        var testJob = Ext.getCmp('job_number').getValue();


                        if (Ext.getCmp('form-insert-bank-charges').stat == 'new')
                        {
                            var e = new bankchargeslist({
                                ref_number: Ext.getCmp('acc-number').getValue(),
                                coa_kode: Ext.getCmp('coa_kode').getValue(),
                                coa_nama: Ext.getCmp('coa_nama').getValue(),
                                //val_kode: Ext.getCmp('val-kode').getValue(),
                                val_kode: Ext.getCmp('val_kode_text').getValue(),
                                trans: Ext.getCmp('trans').getValue(),
                                job_number: Ext.getCmp('job_number').getValue(),
                                debit: Ext.getCmp('debit').getValue().toString().replace(/\$|\,/g, ''),
                                credit: Ext.getCmp('credit').getValue().toString().replace(/\$|\,/g, ''),
                                //rateidr: Ext.getCmp('rateidr').getValue().toString().replace(/\$|\,/g, '')
                                rateidr: Ext.getCmp('val_rate_text').getOriginalValue().toString().replace(/\$|\,/g, '')
                            })

                            storebankcharges.add(e);
                            transCode = Ext.getCmp('trans').getValue();
//                        Ext.MessageBox.alert('Status', 'Changes saved successfully.');

                        } else
                        {
                            if (Ext.getCmp('form-insert-bank-charges').stat == 'edit')
                            {
                                var row = storebankcharges.getById(Ext.getCmp('form-insert-bank-charges').idEdit);

                                row.data['ref_number'] = Ext.getCmp('acc-number').getValue(),
                                        row.data['coa_kode'] = Ext.getCmp('coa_kode').getValue(),
                                        row.data['coa_nama'] = Ext.getCmp('coa_nama').getValue(),
                                        //row.data['val_kode'] = Ext.getCmp('val-kode').getValue(),
                                        row.data['val_kode'] = Ext.getCmp('val_kode_text').getValue(),
                                        row.data['job_number'] = Ext.getCmp('job_number').getValue(),
                                        row.data['trans'] = Ext.getCmp('trans').getValue(),
                                        row.data['debit'] = Ext.getCmp('debit').getValue().toString().replace(/\$|\,/g, ''),
                                        row.data['credit'] = Ext.getCmp('credit').getValue().toString().replace(/\$|\,/g, ''),
                                        //row.data['rateidr'] = Ext.getCmp('rateidr').getValue().toString().replace(/\$|\,/g, '')
                                        row.data['rateidr'] = Ext.getCmp('val_rate_text').getOriginalValue().toString().replace(/\$|\,/g, '')

                                transCode = Ext.getCmp('trans').getValue();
                            }
                        }

                        Ext.getCmp('form-insert-bank-charges').stat = 'new';
                        Ext.getCmp('form-insert-bank-charges').idEdit = '';
                        Ext.getCmp('grid-bankcharges').getView().refresh();

                        var ref_number = Ext.getCmp('acc-number').getValue();
                        //var valuta = Ext.getCmp('val-kode').getValue();
                        //var rateidr = Ext.getCmp('rateidr').getValue();
                        var valuta = Ext.getCmp('val_kode_text').getValue();
                        var rateidr = Ext.getCmp('val_rate_text').getOriginalValue();

//                        Ext.getCmp('form-insert-bank-charges').getForm().reset();

                        Ext.getCmp('acc-number').setValue(ref_number);
                        //Ext.getCmp('val-kode').setValue(valuta);
                        Ext.getCmp('val_kode_text').setValue(valuta);
                        Ext.getCmp('debit').setValue('');
                        //Ext.getCmp('rateidr').setValue(rateidr);
                        Ext.getCmp('val_rate_text').setValue(rateidr);

                        hitungTotal();
                    }
                }, {
                    text: 'Reset',
                    style: 'margin-right:26px;',
                    handler: function(btn, ev)
                    {
                        Ext.getCmp('form-insert-bank-charges').getForm().reset();
                        Ext.getCmp('coa_kode').setValue('');
                        Ext.getCmp('coa_nama').setValue('');
                    }
                }]

        })

        var printpanel = new Ext.form.FormPanel({
            title: 'Print Bank Charges',
            id: 'print-bank-charges',
            renderTo: 'print_bank_charges',
            frame: true,
            labelAlign: 'top',
            style: 'margin:10 10 10 10',
            width: 400,
            stat: 'new',
            items: [{labelWidth: 120,
                    layout: 'column',
                    items: [{
                            xtype: 'tbtext',
                            text: 'Transaction : ',
                            style: 'margin-right: 20'
                        },
                        {
                            xtype: 'tranoalljurnalselector',
                            width: 120,
                            id: 'trano_jurnal',
                            Selectid: 'trano_id',
                            labelWidth: 50,
                            style: 'margin-right: 20',
                            jurnalType: ["bank_out"],
                            callbackFunc: function(trano) {
                                Ext.Ajax.request({
                                    url: '/finance/banktransaction/checkpostbank',
                                    method: 'POST',
                                    params: {
                                        trano: trano,
                                    },
                                    success: function(result) {
                                        obj = Ext.util.JSON.decode(result.responseText);

                                        if (obj.success)
                                        {
                                            posted = true;
                                        } else
                                            posted = false;
                                    },
                                    failure: function(action) {
                                        if (action.failureType == 'server') {
                                            obj = Ext.util.JSON.decode(action.response.responseText);
                                            Ext.Msg.alert('Error!', obj.errors.reason);
                                        } else {
                                            Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
                                        }
                                    }

                                });
                            }
                        }, {
                            xtype: 'button',
                            text: 'Print',
                            width: 70,
                            id: 'show_report',
                            cls: "x-btn-text-icon",
                            icon: "/images/print.png",
                            handler: exportReport
                        }
                    ]}]


        })

        var gridpanel = new Ext.grid.GridPanel({
            store: storebankcharges,
            renderTo: 'grid_bankcharges',
            id: 'grid-bankcharges',
            frame: true,
            width: 800,
            height: 200,
            style: 'margin:10 10 10 10',
            viewConfig: {
                forceFit: true
            },
            columns: [new Ext.grid.RowNumberer(), {
                    header: "Action",
                    width: 60,
                    dataIndex: 'id',
                    css: 'text-align:center;',
                    renderer: function(v, p, r) {
                        return '<a href="#" onclick="deleterowgrid(\'' + r.id + '\')"><img src="/images/g_rec_del.png"></a>';
                    }
                }, {
                    header: 'Referrence',
                    dataIndex: 'ref_number',
                    sortable: true
                }, {
                    header: 'Transaction',
                    dataIndex: 'trans',
                    sortable: true
                }, {
                    header: 'COA Code',
                    dataIndex: 'coa_kode',
                    sortable: true
                }, {
                    header: 'COA Name',
                    dataIndex: 'coa_nama',
                    sortable: true
                }, {
                    header: 'Valuta',
                    dataIndex: 'val_kode'
                }, {
                    header: 'Debit',
                    dataIndex: 'debit',
                    sortable: true,
                    align: 'right',
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0.00') : '';
                    }
                }, {
                    header: 'Credit',
                    dataIndex: 'credit',
                    sortable: true,
                    align: 'right',
                    renderer: function(v) {
                        return v ? Ext.util.Format.number(v, '0,0.00') : '';
                    }
                }],
            buttons: [{
                    text: 'Submit',
                    iconCls: 'icon-save',
                    handler: function(btn, ev)
                    {
                        var totdebit = parseFloat(totDebit.toString().replace(/\$|\,/g, ''));
                        var totcredit = parseFloat(totCredit.toString().replace(/\$|\,/g, ''));

                        if (!moneycomp(totdebit, '==', totcredit))
                        {
                            Ext.MessageBox.show({
                                title: 'Error',
                                msg: 'Sorry, Debit and Credit Total Must be Balance',
                                buttons: Ext.MessageBox.OK,
                                icon: Ext.MessageBox.ERROR
                            });
                            return false;
                        }

                        var count = storebankcharges.getCount();
                        if (count == 0)
                        {
                            return false;
                        }

                        Ext.MessageBox.confirm('Confirm', 'Are you sure want this action ?', function(btn) {

                            if (btn == 'yes')
                            {
                                var bankchargesdata = '';
                                var totaldata = 0;
                                storebankcharges.each(function(store) {
                                    bankchargesdata += Ext.util.JSON.encode(store.data) + ',';
                                })

                                bankchargesdata = '[' + bankchargesdata.substring(0, bankchargesdata.length - 1) + ']';
                                var tgl = '';
                                if (Ext.getCmp('tgl').getValue() != '')
                                    tgl = Ext.util.Format.date(Ext.getCmp('tgl').getValue(), 'Y-m-d');
                                var params = {
                                    bankchargesdata: bankchargesdata,
                                    tgl: tgl,
                                    trans: transCode
                                }
                                Ext.getBody().mask('Loading..','x-mask-loading',false);
                                Ext.Ajax.request({
                                    url: '/finance/banktransaction/doinsertbankcharges',
                                    method: 'POST',
                                    params: params,
                                    success: function(result) {
                                        Ext.getBody().unmask();
                                        obj = Ext.util.JSON.decode(result.responseText);

                                        if (obj.success)
                                        {
                                            Ext.MessageBox.confirm(
                                                    'Success',
                                                    'Data has been saved' +
                                                    '<br><br>Your Transaction number is <b><font color="#ff0000">' +
                                                    obj.trano +
                                                    '</font></b>' +
                                                    '<br>Do You want to Print the Journal?',
                                                    function(btn) {
                                                        if (btn == 'yes')
                                                        {
                                                            var tranoprint = obj.trano.replace("/", "_");
                                                            location.href = '/jasper/bankcharges/trano/' + tranoprint;
                                                        }
                                                    }
                                            );
//                                           
                                            Ext.getCmp('form-insert-bank-charges').getForm().reset();
                                            Ext.getCmp('coa_kodes').setValue('');
                                            Ext.getCmp('coa_kode').setValue('');
                                            Ext.getCmp('coa_nama').setValue('');

//                                             Ext.getCmp('acc-number').focus(false, 100);
                                        } else
                                        {
                                            Ext.Msg.alert('Error', obj.msg);
                                        }
                                    },
                                    failure: function(action) {
                                        Ext.getBody().unmask();
                                        if (action.failureType == 'server') {
                                            obj = Ext.util.JSON.decode(action.response.responseText);
                                            Ext.Msg.alert('Error!', obj.errors.reason);
                                        } else {
                                            Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
                                        }
                                    }

                                })
                            }

                        })

                    }
                }, {
                    text: 'Reset All',
                    style: 'margin-right:26px;',
                    handler: function(btn, ev)
                    {
                        resetAll();
                        Ext.getCmp('acc-number').focus(false, 100);
                    }
                }], bbar: new Ext.Toolbar({
                id: 'total-bbar',
                style: "text-align:right",
                items: [{
                        xtype: 'label',
                        id: 'debittotal',
                        style: 'color:red;font-weight:bold;margin-right:20px;font-size:12'
                    },
                    {
                        xtype: 'label',
                        id: 'credittotal',
                        style: 'color:red;font-weight:bold;font-size:12;margin-right:10px'
                    }],
                layout: 'fit'
            }),
            listeners: {
                'rowdblclick': function(g, r, e)
                {
                    edit(r);
                },
                'afterrender': function(t)
                {
                    hitungTotal();
                }
            }

        })




    })

</script>


<div id="print_bank_charges" style="float:right;padding-right:250px;"></div>
<div id="insert_bank_charges"></div>
<div id="grid_bankcharges"></div>
