<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        var periodeStore = new Ext.data.Store ({

            autoLoad:true,
            url:'/humanresource/timesheet/getviewperiode',
            reader: new Ext.data.JsonReader ({
                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'tahun',type:'String'
                },{
                    name:'periode'
                },{
                    name:'tgl_aw'
                },{
                    name:'tglak'
                },{
                    name:'periode_act'
                },{
                    name:'jumlah_jam_bulan'
                }]
            })

        })

        var periodeGrid = new Ext.grid.GridPanel({

            store:periodeStore,
            renderTo:'view_periode',
            frame:true,
            height:170,
            width:620,
            viewConfig:{

                forceFit:true
            },
            columns:[{
                header:'Year',
                dataIndex:'tahun',
                sortable:true,
                align:'center'
            },{
                header:'Periode',
                dataIndex:'periode',
                sortable:true,
                align:'center'
            },{
                header:'Start Date',
                dataIndex:'tgl_aw',
                sortable:true,
                align:'center'
            },{
                header:'End Date',
                dataIndex:'tglak',
                sortable:true,
                align:'center'
            },{
                header:'Action',
                dataIndex:'periode_act',
                sortable:true,
                align:'center'
            },{
                header:'Hour per month',
                dataIndex:'jumlah_jam_bulan',
                sortable:true,
                align:'center'
            }],
            bbar:new Ext.PagingToolbar ({
                pageSize:5,
                store:periodeStore,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            })


        })



    })

</script>

    <div id="view_periode"></div>


 
