
//Grid Data
 SampleGrid = function(gridType,yAxis,param){
    //View column header from grid/columnHeaader
    var yAxis = yAxis;
    if (gridType == 'pr_list2')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "pr_list2")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "pr_list2")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "pr_list2")); ?>];
        primaryKey = 'trano';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'pr_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "pr_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "pr_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "pr_list")); ?>];
        primaryKey = 'trano';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
if (gridType == 'arf_list')
{
    <?php echo $this->action('columnHeader','grid',null,array("type" => "pr_list")); ?>

    urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "pr_list")); ?>';
    data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "pr_list")); ?>];
    primaryKey = 'trano';
    Pk = primaryKey;
    widthGrid = 380;
    heightGrid = 250;
}

    if (gridType == 'suplier_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "suplier_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "suplier_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "suplier_list")); ?>];
        primaryKey = 'sup_kode';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'valuta_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "valuta_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "valuta_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "valuta_list")); ?>];
        primaryKey = 'val_kode';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'satuan_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "satuan_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "satuan_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "satuan_list")); ?>];
        primaryKey = 'sat_kode';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'barang_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "barang_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "barang_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "barang_list")); ?>];
        primaryKey = 'kode_brg';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'customer_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "customer_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "customer_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "customer_list")); ?>];
        primaryKey = 'cus_kode';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    if (gridType == 'project_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "project_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "project_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "project_list")); ?>];
        primaryKey = '<?php echo $this->action('getPrimaryKey','grid',null,array("type" => "project")); ?>';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
    else if (gridType == 'site_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "site_list")); ?>
        if ( Ext.getCmp('prj_kode_text').getValue() == '')
            {urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "site_list")); ?>';}
        else
            {urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "site_list_param",'noParam' => '1','columnName'=>'prj_kode')); ?>' + Ext.getCmp('prj_kode_text').getValue();}
            data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "site_list")); ?>];
            primaryKey = '<?php echo $this->action('getPrimaryKey','grid',null,array("type" => "site")); ?>';
            Pk = primaryKey;
            widthGrid = 380;
            heightGrid = 250;
    }
    if (gridType == 'work_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "work_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "work_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "work_list")); ?>];
        primaryKey = 'workid';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }
   if (gridType == 'workpr_list')
    {
        <?php echo $this->action('columnHeader','grid',null,array("type" => "workpr_list")); ?>

        urlJson = CFG_CLIENT_SERVER_NAME +'<?php echo $this->action('getUrlJson','grid',null,array("type" => "workpr_list")); ?>';
        data =  [<?php echo $this->action('mappingField','grid',null,array("type" => "workpr_list")); ?>];
        primaryKey = 'workid';
        Pk = primaryKey;
        widthGrid = 380;
        heightGrid = 250;
    }


    var stores = new Ext.data.Store({
        proxy:new Ext.data.HttpProxy({
        url: urlJson
         }),
        reader: new Ext.data.JsonReader({
        root: 'posts',
        totalProperty: 'count'
    },data)
        });

if (yAxis == undefined)
    yAxis=100;
    SampleGrid.superclass.constructor.call(this, {
        store: stores,
        columns: columns,
        x:0,
        y:yAxis,
        id:primaryKey+'_grid',
        loadMask: true,
        bbar:[ new Ext.PagingToolbar({
            pageSize: 100,
            store: stores,
            displayInfo: true,
            displayMsg: 'Displaying data {0} - {1} of {2}',
            emptyMsg: "No data to display"
        })],
        height:heightGrid,
        width:widthGrid,
        listeners: {
                    'rowdblclick': function(g, rowIndex, e){
                            closeForm = false;
                            isDblClick = true;
                            if (gridType == 'pr_list2')
                            {   objectName = 'trano';
                                txtBoxChange = 'trano_text';
                                closeForm = true;
                                formId = 'a-form-panel-trano2_button';
                                var supKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/prd/listByParams/name/trano/data/' + supKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                Ext.getCmp('trano_text').setValue(record);
                            }
                            if (gridType == 'pr_list')
                            {   objectName = 'trano';
                                txtBoxChange = 'trano_text';
                                closeForm = true;
                                formId = 'a-form-panel-trano_button';
                                var supKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/prh/listByParams/name/trano/data/' + supKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);                       
                                Ext.getCmp('trano_text').setValue(record);
                            }
                            if (gridType == 'barang_list')
                            {
                                objectName = 'kode_brg';
                                txtBoxChange = 'kode_brg_text';
                                closeForm = true;
                                formId = 'a-form-panel-kode_brg_button';
                                var supKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/barang/listByParams/name/kode_brg/data/' + supKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("nama_brg");
                                Ext.getCmp('kode_brg_text').setValue(record);
                                Ext.getCmp('nama_brg_text').setValue(record2);
                            }
                            if (gridType == 'suplier_list')
                            {
                                objectName = 'sup_kode';
                                txtBoxChange = 'sup_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-sup_kode_button';
                                var supKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/suplier/listByParams/name/supl_kode/data/' + supKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("sup_nama");
                                Ext.getCmp('sup_kode_text').setValue(record);
                                if (Ext.getCmp('sup_nama_text') != undefined)
                                    Ext.getCmp('sup_nama_text').setValue(record2);
                            }
                            if (gridType == 'valuta_list')
                            {
                                objectName = 'val_kode';
                                txtBoxChange = 'val_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-val_kode_button';
                                var valKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/valuta/listByParams/name/val_kode/data/' + valKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                Ext.getCmp('val_kode_text').setValue(record);
                                if (Ext.getCmp('curr_text') != undefined)
                                {
                                    if (Ext.getCmp('val_kode_text').getValue() == 'IDR' )
                                    {

                                            Ext.getCmp('curr_text').setValue(0);
                                     }
                                    else
                                    {
                                	        getExchangeRate();
                                    }
                                }

                                	
                                if (Ext.getCmp('val_nama_text') != undefined)
                                {
                                var record2 = g.getStore().getAt(rowIndex).get("val_nama");
                                Ext.getCmp('val_nama_text').setValue(record2);
                                }
                            }
                            if (gridType == 'satuan_list')
                            {
                                objectName = 'sat_kode';
                                txtBoxChange = 'sat_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-sat_kode_button';
                                var satKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/satuan/listByParams/name/sat_kode/data/' + satKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("sat_nama");
                                Ext.getCmp('sat_kode_text').setValue(record);
                                Ext.getCmp('sat_nama_text').setValue(record2);
                            }
                            if (gridType == 'barang_list')
                            {
                                objectName = 'kode_brg';
                                txtBoxChange = 'kode_brg_text';
                                closeForm = true;
                                formId = 'a-form-panel-productid_button';
                                var brgKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/barang/listByParams/name/kode_brg/data/' + brgKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("nama_brg");
                                Ext.getCmp('kode_brg_text').setValue(record);
                                Ext.getCmp('nama_brg_text').setValue(record2);
                                //if (Ext.getCmp('price_text') != undefined)
                                //{
                                //	var price = g.getStore().getAt(rowIndex).get("harga_beli");
                                //	Ext.getCmp('price_text').setValue(price);
                                //}
                                if (Ext.getCmp('uom_text') != undefined)
                                {
                                	var uom = g.getStore().getAt(rowIndex).get("sat_kode");
                                	Ext.getCmp('uom_text').setValue(uom);
                                }
                            }
                            if (gridType == 'customer_list')
                            {
                                objectName = 'cus_kode';
                                txtBoxChange = 'cus_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-cus_kode_button';
                                var cusKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/customer/listByParams/name/cus_kode/data/' + cusKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("cus_nama");
                                Ext.getCmp('cus_kode_text').setValue(record);
                                Ext.getCmp('cus_nama_text').setValue(record2);
                            }
                            if (gridType == 'work_list')
                            {
                                objectName = 'workid';
                                txtBoxChange = 'workid_text';
                                closeForm = true;
                                formId = 'a-form-panel-workid_button';
                                var cusKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/work/listByParams/name/workid/data/' + cusKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("workname");
                                Ext.getCmp('workid_text').setValue(record);
                                Ext.getCmp('workname_text').setValue(record2);
                            }
                            if (gridType == 'workpr_list')
                            {
                                objectName = 'workid';
                                txtBoxChange = 'workid_text';
                                closeForm = true;
                                formId = 'a-form-panel-workid_button';
                                var cusKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/work/listByParams/name/workid/data/' + cusKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("workname");
                                Ext.getCmp('workid_text').setValue(record);
                                Ext.getCmp('workname_text').setValue(record2);
                            }
                            if (gridType == 'project_list')
                            {
                                objectName = 'Prj_Kode';
                                txtBoxChange = 'prj_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-pjr_kode_button';
                                var prjKode = g.getStore().getAt(rowIndex).get(objectName);
                               newUrl = '/procurement/listByParams/name/prj_kode/data/' + prjKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("Prj_Nama");
                                Ext.getCmp('prj_kode_text').setValue(record);

                                if (Ext.getCmp('site-detail-grid') != undefined)
                                {
                                    if (!Ext.getCmp('site-detail-grid').isVisible())
                                    {
                                        Ext.getCmp('site-detail-grid').visible(true);
                                    }
                                    Ext.getCmp('site-detail-grid').getStore().proxy.setApi('read','/default/site/list/byPrj_Kode/' + record);
                                    Ext.getCmp('site-detail-grid').getStore().reload();
                                }

                                if (Ext.getCmp('prj_nama_text') != undefined)
                                {
                                	Ext.getCmp('prj_nama_text').setValue(record2);
                                }
                                if (Ext.getCmp('sit_kode_text') != undefined)
                                {
                                	Ext.getCmp('sit_kode_text').setValue('');
                                }
                                if (Ext.getCmp('sit_nama_text') != undefined)
                                {
                                	Ext.getCmp('sit_nama_text').setValue('');
                                }
                                if (Ext.getCmp('cus_kode_text') != undefined)
                                {
                                	Ext.Ajax.request({
							            url: '/default/customer/getcustomerbyproject/prj_kode/' + prjKode,
							            method:'POST',
							            success: function(result, request){
		         			        	   var returnData = Ext.util.JSON.decode(result.responseText);
		         			        	   if (returnData.posts.cus_kode != undefined)
		         			        	   {
		         			        	   		Ext.getCmp('cus_kode_text').setValue(returnData.posts.cus_kode);
		         			        	   		Ext.getCmp('cus_nama_text').setValue(returnData.posts.cus_nama);
		         			        	   }
							            },
							        	failure:function( action){
							          	if(action.failureType == 'server'){
							              obj = Ext.util.JSON.decode(action.response.responseText);
							              Ext.Msg.alert('Error!', obj.errors.reason);
							          	}else{
							              Ext.Msg.alert('Warning!', 'Server is unreachable : ' + action.response.responseText);
							          	}
							          	}
							        });
                                }
                            }
                            else if (gridType == 'site_list')
                            {
                                objectName = 'sit_kode';
                                txtBoxChange = 'sit_kode_text';
                                closeForm = true;
                                formId = 'a-form-panel-site_kode_button';
                                var prjNama = g.getStore().getAt(rowIndex).get('sit_nama');
                                var prjKode = g.getStore().getAt(rowIndex).get('prj_kode');
                                var sitKode = g.getStore().getAt(rowIndex).get(objectName);
                                newUrl = '/procurement/listByParams/name/sit_kode/joinToPod/true/data/' + sitKode + '/Prj_Kode/' + prjKode;
                                prox = 'trano_proxy';
                                gri = 'trano_grid';
                                var record = g.getStore().getAt(rowIndex).get(objectName);
                                var record2 = g.getStore().getAt(rowIndex).get("sit_nama");
                                Ext.getCmp('sit_kode_text').setValue(record);
                                if (Ext.getCmp('sit_nama_text') != undefined)
                                {
                                	Ext.getCmp('sit_nama_text').setValue(record2);
                                }
                            }

                            if (closeForm)
                                {
                                    Ext.getCmp(formId).close();
                                }

                            window.setTimeout(function(){
                                    isDblClick = false;
                            }, 0);
                    }
            }
    });

    stores.load();

}

Ext.extend(SampleGrid, Ext.grid.GridPanel);

//Searching
<?php echo $this->action('index','textfield',null); ?>
//PR
searchTrano = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/prh/listByParams/name/trano/data/' + field.getValue(); prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy( {
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//PR2
searchTrano2 = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/prd/listByParams/name/trano/data/' + field.getValue(); prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy( {
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//Master Suplier
searchSupCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/suplier/listByParams/filter/true/name/sup_kode/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchSupName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/suplier/listByParams/filter/true/name/sup_nama/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
//Master Satuan
searchSatCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/satuan/listByParams/name/sat_kode/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchSatName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/satuan/listByParams/name/sat_nama/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//Master Valuta
searchValCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/valuta/listByParams/name/val_kode/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchValName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/valuta/listByParams/name/val_nama/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//Master Barang
searchProdCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/barang/listByParams/name/kode_brg/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchProdName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/barang/listByParams/name/nama_brg/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//Master Customer
searchCusCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/customer/listByParams/name/cus_kode/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchCusName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/customer/listByParams/name/cus_nama/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}

//Master Project
searchPrjKode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/project/listByParams/name/Prj_Kode/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchPrjName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/project/listByParams/name/Prj_Nama/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }

}

// Master Site
searchSiteName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        var prj = Ext.getCmp('prj_kode_text').getValue();
        if (prj != undefined && prj != '')
        {
            newUrl = '/site/listByParams/name/sit_nama/byPjr_Kode/' + prj + '/data/' + field.getValue();    prox = Pk+'_proxy';
            gri = Pk+'_grid';
            proxies = Ext.getCmp(gri).getStore();
            proxies.proxy = new Ext.data.HttpProxy({
                url: newUrl
                 });
            Ext.getCmp(gri).getStore().reload();
        }
    }
}
searchSiteKode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        var prj = Ext.getCmp('prj_kode_text').getValue();
        if (prj != undefined && prj != '')
        {
            newUrl = '/site/listByParams/name/sit_kode/byPjr_Kode/' + prj + '/data/' + field.getValue();    prox = Pk+'_proxy';
            gri = Pk+'_grid';
            proxies = Ext.getCmp(gri).getStore();
            proxies.proxy = new Ext.data.HttpProxy({
                url: newUrl
                 });
            Ext.getCmp(gri).getStore().reload();
        }
    }
}

// Master Work
searchWorkCode = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/work/listByParams/name/workid/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}
searchWorkName = function(field,e){
    if (field.getValue().toString().length >= 2)
    {
        newUrl = '/work/listByParams/name/workname/data/' + field.getValue();    prox = Pk+'_proxy';
        gri = Pk+'_grid';
        proxies = Ext.getCmp(gri).getStore();
        proxies.proxy = new Ext.data.HttpProxy({
            url: newUrl
             });
        Ext.getCmp(gri).getStore().reload();
    }
}


//PopUp Handler
 var projectPopUphandler = function(button,event) {
    var aForm =  new Ext.Window({
    id: 'a-form-panel-pjr_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 10,
        y: 12,
        xtype: 'label',
        text: 'Project Code:'
        },
       new txtboks(80,10,80,'project_code',searchPrjKode),
         {
        x: 170,
        y: 12,
        xtype: 'label',
        text: 'Project Name:'
        },
        new txtboks(240,10,80,'project_name',searchPrjName),
        new SampleGrid('project_list')
    ]

  });
  aForm.title = 'Choose Project';
  aForm.show();
 };

var sitePopUphandler = function(button,event) {

    var aForm =  new Ext.Window({
    id: 'a-form-panel-site_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 10,
        y: 12,
        xtype: 'label',
        text: 'Site Code:'
        },
        new txtboks(80,10,80,'site_code',searchSiteKode),
        {
        x: 170,
        y: 12,
        xtype: 'label',
        text: 'Site Name:'
        },
        new txtboks(240,10,80,'site_name',searchSiteName),
        new SampleGrid('site_list')
    ]

  });
  aForm.title = 'Choose Site';
  aForm.show();
 };

 var workPopUphandler = function(button,event) {
    var aForm =  new Ext.Window({
    id: 'a-form-panel-workid_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 10,
        y: 12,
        xtype: 'label',
        text: 'Work Id:'
        },
        new txtboks(80,10,80,'workid',searchWorkCode),
        {
        x: 170,
        y: 12,
        xtype: 'label',
        text: 'Work Name:'
        },
        new txtboks(240,10,80,'workname',searchWorkName),
        new SampleGrid('work_list')
    ]

  });
  aForm.title = 'Choose Work';
  aForm.show();
 };

 var workprPopUphandler = function(button,event) {
    var aForm =  new Ext.Window({
    id: 'a-form-panel-workidpr_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 10,
        y: 12,
        xtype: 'label',
        text: 'Work Id:'
        },
        new txtboks(80,10,80,'workid',searchWorkCode),
        {
        x: 170,
        y: 12,
        xtype: 'label',
        text: 'Work Name:'
        },
        new txtboks(240,10,80,'workname',searchWorkName),
        new SampleGrid('workpr_list')
    ]

  });
  aForm.title = 'Pop Up Window';
  aForm.show();
 };

  var productPopUphandler = function(button,event) {
  var aForm =  new Ext.Window({
    id: 'a-form-panel-productid_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 10,
        y: 12,
        xtype: 'label',
        text: 'Product Id:'
        },
        new txtboks(80,10,80,'product_id',searchProdCode),
        {
        x: 170,
        y: 12,
        xtype: 'label',
        text: 'Product Name:'
        },
        new txtboks(240,10,80,'product_name',searchProdName),
        new SampleGrid('barang_list')
    ]

  });
  aForm.title = 'Choose Material';
  aForm.show();
 };

 var customerPopUphandler = function(button,event) {
 var aForm =  new Ext.Window({
    id: 'a-form-panel-cus_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',    totalProperty: 'count',
    idProperty: 'trano',
    root: 'posts'
}, 
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'Customer Code'
        },
       new txtboks(80,10,80,'customer_code',searchCusCode),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: 'Customer Name'
        },
        new txtboks(260,10,80,'customer_name',searchCusName),
        new SampleGrid('customer_list')
    ]

  });
  aForm.title = 'Choose Customer';
  aForm.show();
 };

  var satuanPopUphandler = function(button,event) {
  var aForm =  new Ext.Window({
    id: 'a-form-panel-sat_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'UOM Code'
        },
       new txtboks(80,10,80,'customer_code',searchSatCode),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: 'UOM Name'
        },
        new txtboks(260,10,80,'satuan_name',searchSatName),
        new SampleGrid('satuan_list')
    ]

  });
  aForm.title = 'Choose UOM';
  aForm.show();
 };

  var valutaPopUphandler = function(button,event) {
  var aForm =  new Ext.Window({
    id: 'a-form-panel-val_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'Currency Code'
        },
       new txtboks(80,10,80,'valuta_code',searchValCode),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: 'Currency Name'
        },
        new txtboks(260,10,80,'valuta_name',searchValName),
        new SampleGrid('valuta_list')
    ]

  });
  aForm.title = 'Choose Currency';
  aForm.show();
 };

 var suplierPopUphandler = function(button,event) {
 var aForm =  new Ext.Window({
    id: 'a-form-panel-sup_kode_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'Supplier Code'
        },
       new txtboks(80,10,80,'suplier_code',searchSupCode),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: 'Supplier Name'
        },
        new txtboks(260,10,80,'suplier_name',searchSupName),
        new SampleGrid('suplier_list')
    ]

  });
  aForm.title = 'Choose Supplier';
  aForm.show();
 };

 var prPopUphandler = function(button,event) {
 var aForm =  new Ext.Window({
    id: 'a-form-panel-trano_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'No Trans'
        },
       new txtboks(80,10,80,'trans_no',searchTrano),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: ''
        }
        ,new SampleGrid('pr_list')
    ]

  });
  aForm.title = 'Choose No Trans';
  aForm.show();
 };
 
 var browsePopUphandler = function(button,event) {
 var aForm =  new Ext.Window({
    id: 'a-form-panel-trano2_button',
    layout: 'absolute',
    minWidth: 300,
    minHeight: 200,
    stateful:false,
    modal: true,
    resizable: false,
    width: 400,
    height: 400,
    items : [
        {
        x: 6,
        y: 12,
        xtype: 'label',
        text: 'No Trans'
        },
       new txtboks(80,10,80,'trans_no',searchTrano2),
         {
        x: 184,
        y: 12,
        xtype: 'label',
        text: ''
        }
        ,new SampleGrid('pr_list2')
    ]

  });
  aForm.title = 'Choose No Trans';
  aForm.show();
 };