<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        function showreportco ()
        {
            var prj_kode = Ext.getCmp('prj_kode_text').getValue();
            var sit_kode = Ext.getCmp('sit_kode_text').getValue();

            if (prj_kode == '' || prj_kode == null)
            {
                Ext.Msg.alert('<font color="RED">Error</font> ','<b>Please Select Project Code</b>');
            }else if (sit_kode == '' || sit_kode == null)
            {
                Ext.Msg.alert('<font color="RED">Error</font> ','<b>Please Select Site Code</b>');
            }else
            {
                myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                    url: '/sales/report/viewreportco/prj_kode/' + prj_kode + '/sit_kode/' + sit_kode,
                    scripts : true
                });
            }

            
        }

        var windowForm = ({

            title:'Customer Order Report',
            id: 'abs-budget-panel',
            layout: 'fit',
            bodyCfg : { cls:'xpanel-body-table' , style: {'overflow':'auto'}},
            bodyStyle: 'padding:15px;',
            loadMask: true,
            minWidth: 300,
            minHeight: 200,
            tbar:[{
                xtype:'tbtext',
                text: 'Project Code',
                style:'font-weight:bold;margin-left:10px;'
            },'-',{
                xtype: 'projectselector',
                anchor: '100%',
                id: 'project-select',
                Selectid: 'prj_kode_text',
                Nameid: 'prj_nama_text',
                ShowName: false
            },'-',{
                xtype:'tbtext',
                text: 'Site Code',
                style:'font-weight:bold;margin-left:10px;'
            },'-',{
                xtype: 'siteselector',
                anchor: '100%',
                independent: false,
                id: 'site-select',
                SiteSelectid: 'sit_kode_text',
                SiteNameid: 'sit_nama_text',
                ProjectSelectid: 'prj_kode_text',
                ShowName: false
            },'-',{
                xtype: 'button',
                text: 'Show',
                width:70,
                id: 'show_report',
                cls:"x-btn-text-icon" ,
                icon:"/images/icons/fam/control_rewind.png",
                handler:function(btn,ev)
                {
                    showreportco ();
                }
            }]

        })

        viewPort = Ext.getCmp('viewport');

        centerRegionTab = viewPort.getComponent('content-panel');
        centerRegionTab.items.each(function(c){centerRegionTab.remove(c);});
        centerRegionTab.add(windowForm);
        panelBaru = Ext.getCmp('abs-budget-panel');
        centerRegionTab.layout.setActiveItem('abs-budget-panel');

    })


</script>
