<script type="text/javascript">

    Ext.onReady(function(){

        Ext.QuickTips.init();

        function showbanklist ()
        {

            var storebank = new Ext.data.Store ({

            autoLoad:true,
            url:'/finance/bank/getviewbanklist',
            reader:new Ext.data.JsonReader ({

                root:'data',
                totalProperty:'total',
                fields:[{
                    name:'id'
                },{
                    name:'bnk_nama'
                },{
                    name:'bnk_norek'
                },{
                    name:'bnk_noreknama'
                },{
                    name:'bnk_cabang'
                },{
                    name:'bnk_alamat'
                },{
                    name:'val_kode'
                },{
                    name:'cabang'
                },{
                    name:'bnk_kota'
                }]

            })

        })

            var gridbank = new Ext.grid.GridPanel ({

            id:'bank_list',
            title:'Bank Account List',
            store:storebank,
//            viewConfig:{
//                forceFit:true
//            },
            height:300,
            width:840,
            columns:[{
                header:'Bank Name',
                dataIndex:'bnk_nama',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Account Number',
                dataIndex:'bnk_norek',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Account Name',
                dataIndex:'bnk_noreknama',
                sortable:true,
                align:'center',
                width:120
            },{
                header:'Bank Valuta',
                dataIndex:'val_kode',
                sortable:true,
                align:'center',
                width:100
            },{
                header:'Bank Branch',
                dataIndex:'bnk_cabang',
                sortable:true,
                align:'center',
                width:140
            },{
                header:'Bank Address',
                dataIndex:'bnk_alamat',
                sortable:true,
                align:'center',
                width:180
            },{
                header:'Bank City Address',
                dataIndex:'bnk_kota',
                sortable:true,
                align:'center',
                width:120
            }],bbar: new Ext.PagingToolbar ({
                id: 'paging',
                pageSize: 10,
                store: storebank,
                displayInfo: true,
                displayMsg: 'Displaying data {0} - {1} of {2}',
                emptyMsg: "No data to display"
            }),listeners:
                {
                    'rowdblclick':function(gridaktif,rowindex,e)
                    {
                        isDbClick = true;
                        var bank = gridaktif.getStore().getAt(rowindex);
                        Ext.getCmp('bank_nama').setValue(bank.data['bnk_nama']);
                        Ext.getCmp('banknoreknama').setValue(bank.data['bnk_noreknama']);
                        Ext.getCmp('banknorek').setValue(bank.data['bnk_norek']);
                        Ext.getCmp('bank_nama').id_bank = bank.data['id'];
                        bankwindow.close();

                    }
                }


        })


            var bankwindow = new Ext.Window ({

                title:'Choose Bank to Edit',
                id:'choose-bank',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 854,
                height: 330,
                loadMask:true,
                items:[gridbank]


            })

            bankwindow.show();
        }

        Ext.form.Field.prototype.msgTarget = 'side';

        function showeditcoalist ()
        {
            var coastore = new Ext.data.Store ({
                autoLoad:true,
                url:'/finance/coa/getcoabank',
                reader:new Ext.data.JsonReader ({
                    root:'data',
                    totalProperty:'total',
                    fields:[{
                        name:'id'
                    },{
                        name:'coa_kode'
                    },{
                        name:'coa_nama'
                    },{
                        name:'trano_type'
                    },{
                        name:'bank_id'
                    },{
                        name:'bank_nama'
                    },{
                        name:'bank_noreknama'
                    },{
                        name:'bank_norek'
                    }]
                })

            })

            var coagrid = new Ext.grid.GridPanel ({

                store:coastore,
                viewConfig:{
                    forceFit:true
                },
                height:300,
                columns:[
                {
                    header:'Trano Type',
                    dataIndex:'trano_type',
                    align:'center',
                    sortable:true
                },
                {
                    header:'COA CODE',
                    dataIndex:'coa_kode',
                    align:'center',
                    sortable:true
                },{
                    header:'COA NAME',
                    dataIndex:'coa_nama',
                    align:'center',
                    sortable:true
                },{
                    header:'Bank Name',
                    dataIndex:'bank_nama',
                    align:'center',
                    sortable:true
                },{
                    header:'Account No',
                    dataIndex:'bank_norek',
                    align:'center',
                    sortable:true
                }],
                bbar:new Ext.PagingToolbar ({
                    id: 'paging-coa',
                    pageSize: 20,
                    store: coastore,
                    displayInfo: true,
                    displayMsg: 'Displaying data {0} - {1} of {2}',
                    emptyMsg: "No data to display"
                }),tbar:[{
                    text:'Search By',
                    xtype:'label',
                    style:'margin-left:5px'
                },{
                    xtype: 'combo',
                    width: 100,
                    allowBlank: false,
                    store: new Ext.data.SimpleStore({
                        fields:['name','nilai'],
                        data:[
                                ['Coa Code','coa_kode'],
                                ['Coa Name','coa_nama'],
                                ['Trano Type','trano_type']
                            ]
                    }),
                    valueField:'nilai',
                    displayField:'name',
                    typeAhead: true,
                    forceSelection: true,
                    editable: false,
                    mode: 'local',
                    triggerAction: 'all',
                    selectOnFocus: true,
                    value:1,
                    id:'option'
                },{
                    xtype:'textfield',
                    id:'search',
                    style:'margin-left:10px',
                    enableKeyEvents:true,
                    width:100,
                    listeners:{
                        'keyup' : function (txttext,event)
                        {
                            var txttext = txttext.getValue();
                            if (txttext != "" && txttext.toString().length >= 3)
                            {
                                var option = Ext.getCmp('option').getValue();
                                var search = Ext.getCmp('search').getValue();

                                coastore.proxy.setUrl('/finance/coa/getcoabank/search/' + search + '/option/' + option);
                                coastore.reload();
                                coagrid.getView().refresh();
                            }
                        }
                    }
                }],
                listeners:
                {
                    'rowdblclick':function(gridaktif,rowIndex,e)
                    {
                        isDbClick = true;
                        var coa = gridaktif.getStore().getAt(rowIndex);
                        Ext.getCmp('bank_nama').id_bank = coa.get('bank_id');
                        Ext.getCmp('coa_kode').id_edit = coa.get('id');
                        Ext.getCmp('coa_kode').setValue(coa.get('coa_kode'));
                        Ext.getCmp('coa_nama').setValue(coa.get('coa_nama'));
                        Ext.getCmp('trano_type').setValue(coa.get('trano_type'));
                        Ext.getCmp('banknorek').setValue(coa.get('bank_norek'));
                        Ext.getCmp('bank_nama').setValue(coa.get('bank_nama'));
                        Ext.getCmp('banknoreknama').setValue(coa.get('bank_noreknama'));

                        coawindow.close();

                    }
                }



            })

            var coawindow = new Ext.Window ({

                title:'COA List',
                id:'coa-list-window',
                layout:'absolute',
                minHeight: 200,
                stateful:false,
                modal: true,
                resizable: false,
                closeAction: 'close',
                width: 432,
                height: 330,
                loadMask:true,
                items:[
                    coagrid
                ]

            })

            coawindow.show();
        }

        var addcoa = new Ext.form.FormPanel({

            title:'Create COA - Bank',
            id:'add-new-coa',
            renderTo:'add_new_coa',
            iconCls: 'silk-user',
            frame: true,
            width:450,
            labelWidth:100,
            items:[
                {
                    xtype:'trigger',
                    fieldLabel:'COA Code ',
                    id:'coa_kode',
                    msgTarget:'side',
                    width:180,
                    allowBlank:false,
                    editable: false,
                    id_edit: '',
                    triggerClass: 'teropong',
                    onTriggerClick:function()
                    {
                        showeditcoalist ();
                    }
                },
                {
                    xtype: 'textfield',
                    id: 'coa_nama',
                    fieldLabel: 'COA Name',
                    readOnly: true
                },{
                fieldLabel : 'Trano Type',
                id:'trano_type',
                xtype:'combo',
                store: new Ext.data.Store({
                    proxy: new Ext.data.HttpProxy({
                        url: '/finance/coa/gettranotype'
                    }),
                    reader: new Ext.data.JsonReader({
                        totalProperty: 'count',
                        root: 'data'
                    }, [{
                            name: 'trano'
                        }])
                }),
                valueField:'trano',
                displayField:'trano',
                typeAhead: true,
                forceSelection: true,
                editable: false,
                mode: 'remote',
                triggerAction: 'all',
                allowBlank: false,
                editable: false,
                selectOnFocus:true,
                width:100
            },
            {
                xtype:'trigger',
                fieldLabel:'Bank Name',
                triggerClass:'teropong',
                allowBlank:false,
                editable:false,
                id_bank: '',
                id:'bank_nama',
                width:157,
                onTriggerClick:function()
                {
                    showbanklist();
                }
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Account Name',
                id: 'banknoreknama',
                readOnly: true
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Account No',
                id: 'banknorek',
                readOnly: true
            }
            ],
            buttons:[{
                text:'Submit',
                handler:function(btn,ev)
                {
                    if(!Ext.getCmp('add-new-coa').getForm().isValid())
                    {
                        Ext.Msg.alert('Error','Please fill in all required fields');
                        return false;
                    }

                    Ext.getCmp('add-new-coa').getForm().submit({
                        params: {
                            id_edit: Ext.getCmp('coa_kode').id_edit,
                            bank_id: Ext.getCmp('bank_nama').id_bank,
                            coa_kode: Ext.getCmp('coa_kode_text').getValue(),
                            coa_nama: Ext.getCmp('coa_nama_text').getValue(),
                            trano_type: Ext.getCmp('trano_type').getValue()
                        },
                        method:'POST',
                        url:'/finance/coa/doupdatecoabank',
                        success:function(thisForm,response)
                        {
                            myPanel = Ext.getCmp('abs-budget-panel');
                            myPanel.body.load({
                                url: '/finance/coa/coabanklist',
                                scripts : true
                            });
                        },
                        failure:function(thisForm,response){
                            if (response.failureType == 'server')
                            {
                                var resp = Ext.util.JSON.decode(response.response.responseText);
                                Ext.Msg.alert('Error',resp.pesan);
                            }
                        }

                    })
                }
            },{
                text:'Cancel',
                handler:function(btn,ev)
                {
                    myPanel = Ext.getCmp('abs-budget-panel');
                    myPanel.body.load({
                        url: '/finance/coa/coamenu',
                        scripts : true
                    });
                }
            }]


        })



    })


</script>

    <div id="add_new_coa"></div>